import { aiToolsConfig } from "@/components/lesson/AIToolSelector";

export interface MasteryTrailModule {
  title: string;
  summary: string;
  outcome: string;
}

export interface MasteryTrail {
  slug: string;
  name: string;
  headline: string;
  summary: string;
  category: string;
  intensity: string;
  durationLabel: string;
  lessonCount: number;
  deliverable: string;
  signature: string;
  audience: string;
  modules: MasteryTrailModule[];
  vibe: [string, string, string];
  accent: string;
  logo?: string;
}

const withToolVisual = (slug: string, trail: Omit<MasteryTrail, "accent" | "logo">): MasteryTrail => ({
  ...trail,
  accent: aiToolsConfig[slug]?.color || "#f97316",
  logo: aiToolsConfig[slug]?.logo,
});

export const aiMasteryTrails: MasteryTrail[] = [
  withToolVisual("chatgpt", {
    slug: "chatgpt",
    name: "ChatGPT",
    headline: "Trilha Especialista em ChatGPT",
    summary: "Uma trilha independente para construir sistemas de prompts, operacoes e entregas com ChatGPT em contexto real de negocio.",
    category: "Texto, prompts e operacoes",
    intensity: "Execucao pratica",
    durationLabel: "6 modulos",
    lessonCount: 18,
    deliverable: "Prompt operating system para conteudo e produtividade",
    signature: "Do prompt solto ao sistema replicavel.",
    audience: "Para quem quer transformar ChatGPT em um motor diario de criacao, decisao e velocidade.",
    vibe: ["prompting", "workflow", "operacao"],
    modules: [
      { title: "Arquitetura de prompts", summary: "Como escrever comandos com contexto, restricoes e saida previsivel.", outcome: "Biblioteca base de prompts essenciais." },
      { title: "Rotinas de trabalho", summary: "Fluxos para pesquisa, escrita, revisao e organizacao de tarefas.", outcome: "Stack de produtividade com ChatGPT." },
      { title: "Conteudo e distribuicao", summary: "Sprints para posts, emails, paginas e roteiros com consistencia.", outcome: "Calendario de conteudo assistido por IA." },
      { title: "Sistema pessoal", summary: "Como transformar tudo em um playbook repetivel para seu negocio ou carreira.", outcome: "Playbook final pronto para uso real." },
    ],
  }),
  withToolVisual("claude", {
    slug: "claude",
    name: "Claude",
    headline: "Trilha Analitica com Claude",
    summary: "Uma jornada desenhada para analise profunda, leitura de documentos extensos e sintese estrategica.",
    category: "Analise e raciocinio",
    intensity: "Pensamento estrategico",
    durationLabel: "5 modulos",
    lessonCount: 16,
    deliverable: "Sala de decisao com prompts e frameworks para Claude",
    signature: "Pensar melhor antes de executar.",
    audience: "Ideal para quem precisa estudar, resumir, diagnosticar e tomar decisoes com mais clareza.",
    vibe: ["estrategia", "leitura", "sintese"],
    modules: [
      { title: "Leitura de contexto", summary: "Importando materiais densos e organizando o raciocinio da IA.", outcome: "Mapa mental do problema." },
      { title: "Sintese de alto nivel", summary: "Resumos executivos, comparativos e visoes em camadas.", outcome: "Briefings claros e acionaveis." },
      { title: "Diagnostico e debate", summary: "Prompts para argumentos, riscos, contradicoes e cenarios.", outcome: "Quadro de decisao com pros e contras." },
      { title: "Operacao editorial", summary: "Relatorios, notas e entregas bem estruturadas para times.", outcome: "Template editorial com Claude." },
    ],
  }),
  withToolVisual("deepseek", {
    slug: "deepseek",
    name: "DeepSeek",
    headline: "Trilha Tecnica DeepSeek",
    summary: "Uma trilha independente para raciocinio logico, codigo, debugging e construcao de sistemas tecnicos com IA.",
    category: "Codigo e logica",
    intensity: "Hands on tecnico",
    durationLabel: "5 modulos",
    lessonCount: 15,
    deliverable: "Kit tecnico para analise, refatoracao e automacao",
    signature: "Pensamento tecnico com mais profundidade.",
    audience: "Para devs, analistas e perfis tecnicos que querem uma IA para pensar junto em nivel alto.",
    vibe: ["debug", "refatoracao", "sistemas"],
    modules: [
      { title: "Raciocinio estruturado", summary: "Quebrando problemas complexos em blocos solucionaveis.", outcome: "Metodo de decomposicao com IA." },
      { title: "Debug orientado", summary: "Investigacao de bugs, logs, causas raiz e validacao.", outcome: "Checklist tecnico de troubleshooting." },
      { title: "Refatoracao guiada", summary: "Como pedir melhorias de arquitetura, legibilidade e performance.", outcome: "Pipeline de refatoracao assistida." },
      { title: "Build de utilitarios", summary: "Crie pequenas ferramentas, scripts e estruturas com clareza.", outcome: "Mini projeto tecnico final." },
    ],
  }),
  withToolVisual("gemini", {
    slug: "gemini",
    name: "Gemini",
    headline: "Trilha Multimodal Gemini",
    summary: "Uma trilha para usar texto, arquivos, imagens e contexto do ecossistema Google em um unico fluxo de trabalho.",
    category: "Google e multimodal",
    intensity: "Workspace conectado",
    durationLabel: "5 modulos",
    lessonCount: 14,
    deliverable: "Sistema de analise multimodal para trabalho e estudo",
    signature: "Tudo conversa com tudo.",
    audience: "Para quem quer trabalhar com Drive, Docs, imagens e pesquisa integrada sem perder contexto.",
    vibe: ["arquivos", "multimodal", "workspace"],
    modules: [
      { title: "Contexto em camadas", summary: "Como combinar pergunta, documento e objetivo no mesmo briefing.", outcome: "Modelo de briefing multimodal." },
      { title: "Arquivos e leitura", summary: "Uso de documentos longos para analise e reducao de tempo.", outcome: "Rotina de estudo assistida." },
      { title: "Imagem e interpretacao", summary: "Transformando imagens e screenshots em insight operacional.", outcome: "Fluxo visual de apoio a decisoes." },
      { title: "Workspace final", summary: "Montagem de um processo integrado para execucao diaria.", outcome: "Painel pessoal com Gemini." },
    ],
  }),
  withToolVisual("copilot", {
    slug: "copilot",
    name: "Copilot",
    headline: "Trilha Copilot para Trabalho Real",
    summary: "Uma tela pensada para mostrar como o Copilot pode entrar no cotidiano corporativo e reduzir o peso operacional.",
    category: "Produtividade corporativa",
    intensity: "Ritmo de equipe",
    durationLabel: "5 modulos",
    lessonCount: 15,
    deliverable: "Playbook de produtividade com Copilot no escritorio",
    signature: "Menos friccao, mais entrega.",
    audience: "Perfeita para quem vive entre reunioes, planilhas, relatorios e demandas recorrentes.",
    vibe: ["office", "equipes", "ritmo"],
    modules: [
      { title: "Emails e briefing", summary: "Prompts para respostas, alinhamentos e contextualizacao rapida.", outcome: "Biblioteca de comunicacao profissional." },
      { title: "Documentos e resumos", summary: "Como sintetizar materiais e transformar caos em decisao.", outcome: "Template de resumo executivo." },
      { title: "Planilhas e leitura", summary: "Interpretacao de dados e apoio para analise em ambiente corporativo.", outcome: "Fluxo para dados e apresentacoes." },
      { title: "Operacao recorrente", summary: "Montagem de processos repetiveis com menos desgaste humano.", outcome: "Playbook final de rotina com Copilot." },
    ],
  }),
  withToolVisual("grok", {
    slug: "grok",
    name: "Grok",
    headline: "Trilha Radar com Grok",
    summary: "Uma trilha para usar Grok como radar de sinais, tendencias, debates e contexto de mercado em tempo real.",
    category: "Tempo real e leitura de cenario",
    intensity: "Radar de sinais",
    durationLabel: "4 modulos",
    lessonCount: 12,
    deliverable: "Rotina de inteligencia em tempo real",
    signature: "Contexto vivo para agir mais rapido.",
    audience: "Para quem trabalha com audiencia, mercado, noticias e precisao no timing.",
    vibe: ["sinais", "tendencias", "mercado"],
    modules: [
      { title: "Leitura de movimento", summary: "Como extrair sinais relevantes do barulho informacional.", outcome: "Painel de monitoramento rapido." },
      { title: "Contexto e narrativa", summary: "Interpretando debates e posicionamentos com mais clareza.", outcome: "Mapa narrativo do tema." },
      { title: "Sprints de atualizacao", summary: "Resumos instantaneos para decisao e conteudo.", outcome: "Ritual diario de atualizacao." },
      { title: "Aplicacao em negocio", summary: "Transformando tendencia em insight acionavel.", outcome: "Template de resposta rapida ao mercado." },
    ],
  }),
  withToolVisual("perplexity", {
    slug: "perplexity",
    name: "Perplexity",
    headline: "Trilha de Pesquisa com Perplexity",
    summary: "Uma estrutura de pesquisa com fontes, contexto e confianca para estudo, conteudo e inteligencia competitiva.",
    category: "Pesquisa com fontes",
    intensity: "Investigacao guiada",
    durationLabel: "4 modulos",
    lessonCount: 12,
    deliverable: "Metodo de pesquisa validada com IA",
    signature: "Buscar melhor antes de concluir.",
    audience: "Para quem precisa pesquisar com velocidade sem abrir mao de criterio.",
    vibe: ["fontes", "pesquisa", "validacao"],
    modules: [
      { title: "Perguntas que guiam", summary: "Como formular consultas que trazem respostas mais uteis.", outcome: "Framework de pesquisa inicial." },
      { title: "Leitura com fontes", summary: "Separando evidencias, ruido e referencias fracas.", outcome: "Checklist de confianca." },
      { title: "Sintese documentada", summary: "Criando briefs, comparativos e relatorios citaveis.", outcome: "Modelo de briefing com fontes." },
      { title: "Monitoramento continuo", summary: "Mantendo temas criticos sempre atualizados.", outcome: "Workflow de vigilancia inteligente." },
    ],
  }),
  withToolVisual("manus", {
    slug: "manus",
    name: "Manus",
    headline: "Trilha de Agentes com Manus",
    summary: "Uma experiencia desenhada para delegacao, automacao e desenho de tarefas mais autonomas com IA agente.",
    category: "Agentes autonomos",
    intensity: "Delegacao e controle",
    durationLabel: "4 modulos",
    lessonCount: 13,
    deliverable: "Blueprint operacional de tarefas delegaveis",
    signature: "Delegar bem muda o jogo.",
    audience: "Para quem quer sair do microgerenciamento e aprender a orquestrar agentes com clareza.",
    vibe: ["delegacao", "agentes", "controle"],
    modules: [
      { title: "Escopo de agente", summary: "Definindo tarefa, limite e criterio de sucesso.", outcome: "Ficha de delegacao objetiva." },
      { title: "Supervisao inteligente", summary: "Como revisar sem matar a autonomia do processo.", outcome: "Checklist de supervisao." },
      { title: "Tarefas encadeadas", summary: "Transformando uma demanda grande em um fluxo de execucao.", outcome: "Fluxo multi-etapas com agente." },
      { title: "Operacao final", summary: "Montagem de um sistema pronto para rotina de trabalho.", outcome: "Blueprint de agente operacional." },
    ],
  }),
  withToolVisual("lovable", {
    slug: "lovable",
    name: "Lovable",
    headline: "Trilha de Produto com Lovable",
    summary: "Uma trilha independente para transformar ideias em produtos navegaveis, com narrativa, interface e senso de direcao.",
    category: "Apps e produtos",
    intensity: "Produto em movimento",
    durationLabel: "5 modulos",
    lessonCount: 16,
    deliverable: "Blueprint de produto com IA pronto para validacao",
    signature: "Da ideia ao prototipo navegavel.",
    audience: "Para criadores, founders e profissionais que querem dar forma rapida a um produto.",
    vibe: ["produto", "ux", "shipping"],
    modules: [
      { title: "Tese de produto", summary: "Definicao do problema, usuario e promessa central.", outcome: "Documento de tese do produto." },
      { title: "Arquitetura da experiencia", summary: "Fluxo de telas, estados e hierarquia de informacao.", outcome: "Mapa navegavel da experiencia." },
      { title: "Prompting para construcao", summary: "Como pedir componentes, paginas e ajustes com precisao.", outcome: "Prompt stack de criacao no Lovable." },
      { title: "Polimento e narrativa", summary: "Acabamento visual, copy e coesao do produto.", outcome: "Versao pronta para demo." },
    ],
  }),
  withToolVisual("nanobanana", {
    slug: "nanobanana",
    name: "NanoBanana",
    headline: "Trilha Visual NanoBanana",
    summary: "Uma trilha leve e ousada para exploracao visual, referencias, variacoes e direcao criativa com IA.",
    category: "Criacao visual",
    intensity: "Exploracao rapida",
    durationLabel: "4 modulos",
    lessonCount: 10,
    deliverable: "Kit visual com variacoes e referencias de estilo",
    signature: "Criar rapido sem perder identidade.",
    audience: "Para quem quer experimentar visualmente e descobrir linguagens com velocidade.",
    vibe: ["estilo", "visual", "variacoes"],
    modules: [
      { title: "Exploracao de referencias", summary: "Definindo mood, textura, cor e direcao visual.", outcome: "Mapa de referencias visuais." },
      { title: "Variacoes com controle", summary: "Gerando alternativas sem virar bagunca visual.", outcome: "Lote de variacoes curadas." },
      { title: "Consistencia de linguagem", summary: "Mantendo identidade em uma serie de imagens.", outcome: "Mini sistema visual repetivel." },
      { title: "Aplicacao em marca", summary: "Usando os outputs em pecas, posts e paginas.", outcome: "Pacote visual de campanha." },
    ],
  }),
  withToolVisual("leonardo", {
    slug: "leonardo",
    name: "LeonardoAI",
    headline: "Trilha Criativa com Leonardo",
    summary: "Uma jornada para design de imagens, composicao consistente e producao visual pronta para produto e marketing.",
    category: "Design de imagens",
    intensity: "Direcao de design",
    durationLabel: "4 modulos",
    lessonCount: 12,
    deliverable: "Pacote visual para marca, produto ou campanha",
    signature: "Imagem util, nao so bonita.",
    audience: "Para quem precisa transformar ideia visual em ativo de negocio com consistencia.",
    vibe: ["design", "branding", "campanha"],
    modules: [
      { title: "Base visual", summary: "Cores, materiais, enquadramento e intencao de cena.", outcome: "Guia de estilo inicial." },
      { title: "Produto e composicao", summary: "Cenas para mockups, vitrines e apresentacoes visuais.", outcome: "Biblioteca de cenas de produto." },
      { title: "Campanhas consistentes", summary: "Criando colecoes com coerencia para lancamentos.", outcome: "Conjunto de pecas alinhadas." },
      { title: "Entrega final", summary: "Preparacao para uso em marca, anuncio ou landing page.", outcome: "Pacote final pronto para publicacao." },
    ],
  }),
  withToolVisual("midjourney", {
    slug: "midjourney",
    name: "MidJourney",
    headline: "Trilha de Direcao com MidJourney",
    summary: "Uma trilha para quem quer imagens mais cinematograficas, autorais e com direcao visual consciente.",
    category: "Arte e direcao visual",
    intensity: "Cinematografia visual",
    durationLabel: "4 modulos",
    lessonCount: 12,
    deliverable: "Serie visual autoral com direcao refinada",
    signature: "Imagem com intencao e assinatura.",
    audience: "Para criativos que querem sair do prompt generico e construir identidade visual forte.",
    vibe: ["cinema", "arte", "assinatura"],
    modules: [
      { title: "Linguagem visual", summary: "Composicao, atmosfera e referencias de direcao.", outcome: "Guia de direcao visual." },
      { title: "Prompting cinematografico", summary: "Clima, camera, luz e textura a favor da narrativa.", outcome: "Biblioteca de prompts de cena." },
      { title: "Iteracao fina", summary: "Como lapidar imagens sem perder a alma do conceito.", outcome: "Serie refinada de exploracoes." },
      { title: "Hero assets", summary: "Criacao de imagens de impacto para campanha ou portfolio.", outcome: "Colecao hero pronta para uso." },
    ],
  }),
  withToolVisual("captions", {
    slug: "captions",
    name: "Captions",
    headline: "Trilha de Videos com Captions",
    summary: "Uma tela focada em videos curtos, ritmo, hook e estrutura de conteudo para redes com apoio de IA.",
    category: "Video curto",
    intensity: "Conteudo com ritmo",
    durationLabel: "4 modulos",
    lessonCount: 11,
    deliverable: "Sistema de videos curtos pronto para publicar",
    signature: "Velocidade com retenção.",
    audience: "Para criadores e marcas que dependem de video para alcance e conversao.",
    vibe: ["roteiro", "corte", "retencao"],
    modules: [
      { title: "Hook e promessa", summary: "Como abrir um video de forma que segure a atencao.", outcome: "Banco de hooks por objetivo." },
      { title: "Estrutura e cortes", summary: "Ritmo, blocos e montagem para consumo rapido.", outcome: "Template de video curto." },
      { title: "Legenda e reforco", summary: "Legendas que guiam o olhar e amplificam a mensagem.", outcome: "Padrao visual de legenda." },
      { title: "Distribuicao final", summary: "Variacoes, repost e escalada de conteudo.", outcome: "Sistema de distribuicao multiplataforma." },
    ],
  }),
  withToolVisual("elevenlabs", {
    slug: "elevenlabs",
    name: "ElevenLabs",
    headline: "Trilha de Voz com ElevenLabs",
    summary: "Uma trilha para narracao, identidade de voz, roteiros e ativos sonoros com acabamento profissional.",
    category: "Voz e narracao",
    intensity: "Som e presenca",
    durationLabel: "4 modulos",
    lessonCount: 11,
    deliverable: "Kit de voz para videos, anuncios e aulas",
    signature: "Sua mensagem com timbre e presenca.",
    audience: "Para quem quer som profissional em conteudo, produto ou educacao sem depender de estudio tradicional.",
    vibe: ["voz", "narracao", "audio"],
    modules: [
      { title: "Identidade vocal", summary: "Escolha de tom, cadencia e persona de voz.", outcome: "Mapa de identidade sonora." },
      { title: "Roteiro para voz", summary: "Textos pensados para soar bem, nao so ler bem.", outcome: "Modelo de roteiro narrado." },
      { title: "Producao de audio", summary: "Variacoes, testes e limpeza para qualidade consistente.", outcome: "Pacote base de narracoes." },
      { title: "Aplicacao final", summary: "Uso em aulas, anuncios, reels e conteudo de marca.", outcome: "Kit final de audio pronto." },
    ],
  }),
  withToolVisual("veo", {
    slug: "veo",
    name: "VEO",
    headline: "Trilha Cinematica com VEO",
    summary: "Uma trilha voltada para prompts de video, direcao de cena, storyboard e construcao de pecas audiovisuais com IA.",
    category: "Video com IA",
    intensity: "Storyboard a tela",
    durationLabel: "4 modulos",
    lessonCount: 12,
    deliverable: "Storyboard audiovisual com prompts e cenas coerentes",
    signature: "Da cena imaginada ao frame dirigido.",
    audience: "Para criativos e times que querem dominar video com IA de forma mais sofisticada.",
    vibe: ["cenas", "storyboard", "impacto"],
    modules: [
      { title: "Narrativa de cena", summary: "Como desenhar sequencias que tenham ritmo e funcao.", outcome: "Estrutura de storyboard inicial." },
      { title: "Prompting audiovisual", summary: "Movimento, lente, enquadramento e atmosfera nos comandos.", outcome: "Biblioteca de prompts de video." },
      { title: "Direcao e continuidade", summary: "Mantendo coesao entre tomadas e momentos.", outcome: "Mapa de continuidade visual." },
      { title: "Peca final", summary: "Montagem de uma peca de alto impacto para campanha ou portfolio.", outcome: "Video conceito pronto para refinamento." },
    ],
  }),
];

export const aiMasteryTrailsBySlug = Object.fromEntries(
  aiMasteryTrails.map((trail) => [trail.slug, trail]),
) as Record<string, MasteryTrail>;
