const textStep = (title: string, content: string, promptBox?: string) => ({
  type: "text" as const,
  title,
  content,
  ...(promptBox ? { promptBox } : {}),
});

const quizStep = (
  title: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
) => ({
  type: "quiz" as const,
  title,
  question,
  options,
  correctIndex,
  explanation,
});

const fillStep = (
  title: string,
  instruction: string,
  sentence: string,
  answers: string[],
  options: string[],
  explanation: string,
) => ({
  type: "fill_blanks" as const,
  title,
  instruction,
  sentence,
  answers,
  options,
  explanation,
});

export const MIDJOURNEY_MODULE_2_STEPS_PT = [
  textStep(
    "Como a iluminacao pode transformar suas imagens",
    "Bem-vindo de volta! Nesta licao, voce vai descobrir como a iluminacao e o elemento mais poderoso e transformador de uma imagem no MidJourney. A mesma cena, o mesmo personagem e o mesmo ambiente podem gerar resultados completamente diferentes em emocao, atmosfera e impacto visual quando a luz muda.\n\nFotografos profissionais dizem que fotografar e escrever com luz. No MidJourney, isso tambem e verdade: a palavra que descreve a iluminacao pode mudar o tom emocional da imagem mesmo que todo o resto do prompt permaneca igual.",
  ),
  quizStep(
    "Por que a iluminacao importa tanto",
    "Por que a iluminacao tem tanto impacto em uma imagem gerada pelo MidJourney?",
    [
      "Porque a luz define sombras, temperatura de cor, contraste e profundidade, e o cerebro usa tudo isso para interpretar o clima emocional da cena.",
      "Porque o MidJourney prioriza a iluminacao acima de todos os outros elementos do prompt.",
      "Porque a iluminacao so importa em imagens de retratos humanos.",
      "Porque iluminacao e estilo tem o mesmo peso e podem ser usados de forma intercambiavel.",
    ],
    0,
    "A luz organiza a forma como lemos profundidade, contraste e temperatura emocional. Por isso ela muda a sensacao da cena tao rapido.",
  ),
  fillStep(
    "Preencha a lacuna - Use o Golden Hour",
    "Complete o prompt com os elementos corretos.",
    "/imagine ___, luz golden hour, estilo ___, tons ___, ___",
    [
      "um casal caminhando na praia",
      "fotografia cinematografica",
      "dourados e ambar quentes",
      "--ar 16:9",
    ],
    [
      "um casal caminhando na praia",
      "fotografia cinematografica",
      "dourados e ambar quentes",
      "--ar 16:9",
    ],
    "Golden Hour funciona muito bem quando voce quer calor, memoria afetiva e beleza natural instantanea.",
  ),
  quizStep(
    "Emocao do Golden Hour",
    "Qual sensacao emocional o Golden Hour transmite em uma imagem?",
    [
      "Tensao e urgencia, ideal para cenas de acao.",
      "Frieza e distancia, ideal para retratos formais.",
      "Calor, nostalgia, romantismo e beleza natural, como se a cena fosse um momento especial.",
      "Golden Hour so funciona bem em imagens de paisagens sem pessoas.",
    ],
    2,
    "Golden Hour faz a cena parecer memoravel e afetiva. E uma luz que aproxima emocionalmente o espectador.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Blue Hour",
    "Monte o prompt com a atmosfera correta.",
    "/imagine ___, luz blue hour, estilo ___, atmosfera melancolica, tons ___, ___",
    [
      "uma figura solitaria parada em uma ponte da cidade",
      "fotografia cinematografica",
      "azul profundo e roxo",
      "--ar 16:9",
    ],
    [
      "uma figura solitaria parada em uma ponte da cidade",
      "fotografia cinematografica",
      "azul profundo e roxo",
      "--ar 16:9",
    ],
    "Blue Hour cria uma atmosfera sofisticada, elegante e levemente melancolica, com cara de cinema.",
  ),
  quizStep(
    "Quando usar Blue Hour",
    "Em qual tipo de projeto o Blue Hour seria a escolha mais estrategica?",
    [
      "Uma campanha alegre e colorida para um produto infantil.",
      "Imagens de culinaria que precisam parecer apetitosas e acolhedoras.",
      "Um editorial de moda sofisticado, um poster de suspense ou qualquer projeto que precise de misterio e profundidade emocional.",
      "Blue Hour so funciona para paisagens urbanas noturnas.",
    ],
    2,
    "Blue Hour brilha em projetos que pedem misterio, sofisticacao e uma atmosfera emocional mais profunda.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Dramatic Lighting",
    "Complete o prompt com os elementos que reforcam tensao e poder.",
    "/imagine ___, iluminacao dramatica, estilo ___, ___, sombras profundas, ___",
    [
      "um guerreiro poderoso segurando uma espada",
      "arte conceitual de fantasia sombria",
      "fonte unica de luz direcional",
      "--ar 9:16",
    ],
    [
      "um guerreiro poderoso segurando uma espada",
      "arte conceitual de fantasia sombria",
      "fonte unica de luz direcional",
      "--ar 9:16",
    ],
    "Dramatic Lighting cresce quando existe uma fonte de luz forte e bem definida contra grandes areas de sombra.",
  ),
  quizStep(
    "O que define o Dramatic Lighting",
    "Qual e o elemento visual que define o Dramatic Lighting?",
    [
      "Muitas fontes de luz distribuidas uniformemente pela cena.",
      "Cores vibrantes e saturadas em toda a composicao.",
      "O alto contraste entre areas iluminadas e sombras profundas, criando tensao visual.",
      "Dramatic Lighting e sinonimo de imagens escuras sem fonte de luz aparente.",
    ],
    2,
    "O coracao do Dramatic Lighting e o contraste forte, que direciona o olhar e aumenta a sensacao de poder e intensidade.",
  ),
  fillStep(
    "Preencha a lacuna - Use o Soft Box",
    "Preencha o prompt para uma fotografia de produto limpa e profissional.",
    "/imagine ___, iluminacao soft box, fundo ___, estilo de fotografia ___, ___, ___",
    [
      "um frasco de perfume de luxo com gotas de agua",
      "branco limpo",
      "produto comercial",
      "ultra detalhado",
      "--ar 1:1",
    ],
    [
      "um frasco de perfume de luxo com gotas de agua",
      "branco limpo",
      "produto comercial",
      "ultra detalhado",
      "--ar 1:1",
    ],
    "Soft Box elimina sombras duras e deixa o produto limpo, elegante e pronto para comunicacao de marca.",
  ),
  quizStep(
    "Soft Box para produtos",
    "Por que o Soft Box Lighting e a escolha ideal para fotografia de produtos?",
    [
      "Porque cria sombras dramaticas que valorizam a forma do produto.",
      "Porque deixa o produto mais artistico e menos comercial.",
      "Porque ilumina de forma uniforme, valoriza detalhes e texturas e cria uma aparencia limpa e profissional.",
      "Porque so funciona em produtos brancos ou neutros.",
    ],
    2,
    "Em produto, clareza e uniformidade contam muito. Soft Box organiza a cena para valorizar detalhes sem distorcao.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Chiaroscuro",
    "Monte o prompt com profundidade artistica historica.",
    "/imagine ___, iluminacao chiaroscuro, estilo ___, ___, inspirado em ___, ___",
    [
      "um velho estudioso lendo a luz de velas",
      "pintura a oleo",
      "sombras profundas e luz quente de vela",
      "Rembrandt",
      "--ar 9:16",
    ],
    [
      "um velho estudioso lendo a luz de velas",
      "pintura a oleo",
      "sombras profundas e luz quente de vela",
      "Rembrandt",
      "--ar 9:16",
    ],
    "Chiaroscuro puxa a imagem para uma linguagem classica de pintura, com peso historico e profundidade temporal.",
  ),
  quizStep(
    "Chiaroscuro x Dramatic",
    "O que diferencia o Chiaroscuro do Dramatic Lighting comum?",
    [
      "O Chiaroscuro usa varias fontes de luz enquanto o Dramatic usa apenas uma.",
      "Sao tecnicas identicas com nomes diferentes.",
      "O Chiaroscuro carrega uma raiz artistica historica e evoca a pintura classica com luz de vela ou tocha.",
      "Chiaroscuro so funciona em imagens em preto e branco.",
    ],
    2,
    "Os dois usam contraste, mas Chiaroscuro carrega uma memoria artistica historica que vai alem do contraste fotografico puro.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Neon Lighting",
    "Complete o prompt para uma cena urbana vibrante.",
    "/imagine ___, iluminacao neon, estilo ___, ___, reflexos de chuva nas ruas molhadas, cores ___, ___",
    [
      "uma hacker em um beco futurista",
      "arte digital cyberpunk",
      "ambiente urbano noturno",
      "roxo e ciano vivos",
      "--ar 9:16",
    ],
    [
      "uma hacker em um beco futurista",
      "arte digital cyberpunk",
      "ambiente urbano noturno",
      "roxo e ciano vivos",
      "--ar 9:16",
    ],
    "Neon Lighting funciona quando voce quer energia urbana, artificialidade, cultura pop e clima futurista.",
  ),
  quizStep(
    "Quando Neon nao combina",
    "Em qual projeto o Neon Lighting seria a escolha mais inadequada?",
    [
      "Um poster de evento de musica eletronica.",
      "A capa de um livro de ficcao cientifica urbana.",
      "Uma campanha para uma marca de produtos organicos e naturais, onde o neon contradiz a ideia de naturalidade.",
      "Neon Lighting nao funciona em imagens com personagens femininos.",
    ],
    2,
    "A luz precisa reforcar o posicionamento da marca. Neon comunica sintese urbana, nao naturalidade organica.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Volumetric Lighting",
    "Complete o prompt para uma cena com profundidade epica.",
    "/imagine ___, iluminacao volumetrica, estilo ___, ___, raios de luz ___, ___",
    [
      "o interior de uma catedral antiga com particulas de poeira",
      "arte conceitual de fantasia",
      "vitrais altos",
      "dourados e divinos",
      "--ar 9:16",
    ],
    [
      "o interior de uma catedral antiga com particulas de poeira",
      "arte conceitual de fantasia",
      "vitrais altos",
      "dourados e divinos",
      "--ar 9:16",
    ],
    "Volumetric Lighting deixa a luz visivel no espaco e adiciona profundidade, escala e sensacao quase sagrada.",
  ),
  quizStep(
    "O que o Volumetric adiciona",
    "O que o Volumetric Lighting adiciona a uma imagem que outros tipos de iluminacao nao conseguem replicar?",
    [
      "Sombras mais profundas e dramaticas na cena.",
      "Cores mais saturadas e vibrantes em todos os elementos.",
      "A materializacao visivel da luz no espaco, criando profundidade tridimensional e escala epica.",
      "Volumetric Lighting so funciona em ambientes internos fechados.",
    ],
    2,
    "O diferencial do volumetric esta em transformar a luz em presenca fisica visivel dentro da cena.",
  ),
  fillStep(
    "Preencha a lacuna - Use o Rim Lighting",
    "Monte o prompt para destacar a silhueta do personagem.",
    "/imagine ___, iluminacao de contorno, fundo ___, estilo ___, silhueta ___, ___",
    [
      "um detetive misterioso com sobretudo",
      "escuro e melancolico",
      "fotografia noir cinematografica",
      "com contorno brilhante",
      "--ar 9:16",
    ],
    [
      "um detetive misterioso com sobretudo",
      "escuro e melancolico",
      "fotografia noir cinematografica",
      "com contorno brilhante",
      "--ar 9:16",
    ],
    "Rim Lighting separa o personagem do fundo e aumenta imediatamente a presenca cinematografica.",
  ),
  quizStep(
    "Por que o Rim funciona",
    "Por que o Rim Lighting e especialmente eficaz em retratos de personagens?",
    [
      "Porque ilumina o rosto com mais clareza do que qualquer outra luz.",
      "Porque cria sombras no rosto que adicionam profundidade facial.",
      "Porque o contorno luminoso separa o personagem do fundo e transforma a silhueta em presenca de protagonista.",
      "Porque so funciona com fundos completamente pretos.",
    ],
    2,
    "Rim Lighting cria destaque, separacao e presenca. Ele faz a silhueta parecer mais forte e memoravel.",
  ),
  fillStep(
    "Preencha a lacuna - Combine iluminacoes",
    "Complete o prompt usando duas iluminacoes no mesmo resultado.",
    "/imagine ___, iluminacao ___ e ___, estilo ___, atmosfera ___, ___",
    [
      "um samurai em uma floresta de bambu ao entardecer",
      "golden hour",
      "volumetric",
      "fotografia cinematografica",
      "mistica e epica",
      "--ar 16:9",
    ],
    [
      "um samurai em uma floresta de bambu ao entardecer",
      "golden hour",
      "volumetric",
      "fotografia cinematografica",
      "mistica e epica",
      "--ar 16:9",
    ],
    "Quando duas iluminacoes se reforcam, a imagem ganha camadas de atmosfera que uma unica luz nao entregaria sozinha.",
  ),
  quizStep(
    "Golden Hour + Volumetric",
    "Qual e o resultado de combinar Golden Hour com Volumetric Lighting no mesmo prompt?",
    [
      "Os dois tipos de luz se cancelam e o resultado fica neutro.",
      "O MidJourney ignora uma delas e aplica apenas a mais comum.",
      "A luz dourada do Golden Hour fica visivel em feixes no ar, criando beleza epica e profundidade cinematografica ao mesmo tempo.",
      "Combinar iluminacoes sempre gera imagens confusas e mal resolvidas.",
    ],
    2,
    "Golden Hour aquece a cena e Volumetric materializa essa luz no espaco. Juntos, eles ampliam atmosfera e escala.",
  ),
  fillStep(
    "Preencha a lacuna - Escolha a luz certa",
    "Complete o guia rapido de iluminacao por objetivo.",
    "Para imagens ___ e acolhedoras use ___. Para atmosfera ___ e sofisticada use ___. Para impacto e ___ use Dramatic Lighting. Para produtos e retratos ___ use Soft Box. Para arte com profundidade ___ use Chiaroscuro. Para cenas ___ noturnas use Neon Lighting. Para escala ___ e magia use Volumetric Lighting.",
    [
      "quentes",
      "Golden Hour",
      "misteriosa",
      "Blue Hour",
      "poder",
      "profissionais",
      "historica",
      "urbanas",
      "epica",
    ],
    [
      "quentes",
      "Golden Hour",
      "misteriosa",
      "Blue Hour",
      "poder",
      "profissionais",
      "historica",
      "urbanas",
      "epica",
    ],
    "Escolher a luz certa e alinhar emocao, objetivo e aplicacao real da imagem.",
  ),
  quizStep(
    "Erro comum na escolha de luz",
    "Qual e o erro mais comum ao escolher iluminacao no MidJourney?",
    [
      "Usar o mesmo tipo de iluminacao em projetos diferentes.",
      "Combinar dois tipos de iluminacao no mesmo prompt.",
      "Escolher a iluminacao pela aparencia visual sem considerar a emocao que ela transmite.",
      "Especificar iluminacao em prompts curtos com poucos elementos.",
    ],
    2,
    "Uma imagem pode ficar bonita e ainda assim errada para o objetivo se a luz contradizer a emocao que o projeto precisa comunicar.",
  ),
  textStep(
    "Conclusao",
    "A iluminacao e a alma de qualquer imagem no MidJourney. Golden Hour para calor e nostalgia, Blue Hour para misterio e sofisticacao, Dramatic para poder e tensao, Soft Box para limpeza profissional, Chiaroscuro para profundidade artistica, Neon para energia urbana, Volumetric para escala epica e Rim para presenca e destaque.\n\nAgora que voce entende a linguagem da luz, seus prompts nunca mais serao os mesmos. Escolha a luz certa. Conte a historia certa.",
  ),
] as const;

export const MIDJOURNEY_MODULE_2_STEPS_EN = [
  textStep(
    "How lighting transforms your images",
    "Welcome back! In this lesson, you will see how lighting becomes the most powerful and transformative element in a MidJourney image. The same scene, the same character, and the same environment can create completely different emotions, atmospheres, and visual impact when the light changes.\n\nProfessional photographers often say photography is writing with light. In MidJourney, that is also true: the lighting phrase alone can shift the emotional tone of the image even when every other part of the prompt stays the same.",
  ),
  quizStep(
    "Why lighting matters so much",
    "Why does lighting have such a strong impact in a MidJourney image?",
    [
      "Because light defines shadows, color temperature, contrast, and depth, and the brain uses all of that to read emotional tone.",
      "Because MidJourney prioritizes lighting above every other prompt element.",
      "Because lighting only matters in human portrait images.",
      "Because lighting and style have the same role and can be used interchangeably.",
    ],
    0,
    "Light shapes how we read depth, contrast, and emotional temperature. That is why it changes the feeling of the scene so quickly.",
  ),
  fillStep(
    "Fill in the blanks - Use Golden Hour",
    "Complete the prompt with the correct elements.",
    "/imagine ___, golden hour lighting, ___ style, ___ tones, ___",
    [
      "a couple walking on a beach",
      "cinematic photography",
      "warm golden and amber",
      "--ar 16:9",
    ],
    [
      "a couple walking on a beach",
      "cinematic photography",
      "warm golden and amber",
      "--ar 16:9",
    ],
    "Golden Hour works best when you want warmth, memory, romance, and immediate natural beauty.",
  ),
  quizStep(
    "Golden Hour emotion",
    "What emotional feeling does Golden Hour transmit in an image?",
    [
      "Tension and urgency, ideal for action scenes.",
      "Coldness and distance, ideal for formal portraits.",
      "Warmth, nostalgia, romance, and natural beauty, making the scene feel memorable.",
      "Golden Hour only works well for landscapes without people.",
    ],
    2,
    "Golden Hour makes a scene feel emotionally close and worth remembering.",
  ),
  fillStep(
    "Fill in the blanks - Create with Blue Hour",
    "Build the prompt with the right atmosphere.",
    "/imagine ___, blue hour lighting, ___ style, moody atmosphere, ___ tones, ___",
    [
      "a lonely figure standing on a city bridge",
      "cinematic photography",
      "deep blue and purple",
      "--ar 16:9",
    ],
    [
      "a lonely figure standing on a city bridge",
      "cinematic photography",
      "deep blue and purple",
      "--ar 16:9",
    ],
    "Blue Hour creates a cinematic, sophisticated, and slightly melancholic mood.",
  ),
  quizStep(
    "When to use Blue Hour",
    "In which kind of project would Blue Hour be the most strategic choice?",
    [
      "A cheerful and colorful campaign for a children's product.",
      "Food images that need to feel cozy and appetizing.",
      "A sophisticated fashion editorial, a thriller poster, or any project that needs mystery and emotional depth.",
      "Blue Hour only works for urban night landscapes.",
    ],
    2,
    "Blue Hour shines in work that needs mystery, elegance, and emotional depth.",
  ),
  fillStep(
    "Fill in the blanks - Create with Dramatic Lighting",
    "Complete the prompt with elements that reinforce tension and power.",
    "/imagine ___, dramatic lighting, ___ style, ___, deep shadows, ___",
    [
      "a powerful warrior holding a sword",
      "dark fantasy concept art",
      "single directional light source",
      "--ar 9:16",
    ],
    [
      "a powerful warrior holding a sword",
      "dark fantasy concept art",
      "single directional light source",
      "--ar 9:16",
    ],
    "Dramatic Lighting becomes stronger when one clear light source fights against large shadow areas.",
  ),
  quizStep(
    "What defines Dramatic Lighting",
    "What visual element defines Dramatic Lighting?",
    [
      "Many light sources spread evenly across the scene.",
      "Vibrant and saturated colors across the whole composition.",
      "Strong contrast between lit areas and deep shadows, creating tension.",
      "Dramatic Lighting simply means dark images with no visible light source.",
    ],
    2,
    "The core of Dramatic Lighting is contrast. It directs the eye and increases power and intensity.",
  ),
  fillStep(
    "Fill in the blanks - Use Soft Box",
    "Complete the prompt for a clean, professional product image.",
    "/imagine ___, soft box lighting, ___ background, ___ photography style, ___, ___",
    [
      "a luxury perfume bottle with water drops",
      "clean white",
      "commercial product",
      "ultra detailed",
      "--ar 1:1",
    ],
    [
      "a luxury perfume bottle with water drops",
      "clean white",
      "commercial product",
      "ultra detailed",
      "--ar 1:1",
    ],
    "Soft Box removes harsh shadows and makes the product feel clean, elegant, and ready for brand communication.",
  ),
  quizStep(
    "Soft Box for products",
    "Why is Soft Box Lighting the ideal choice for product photography?",
    [
      "Because it creates dramatic shadows that define the product shape.",
      "Because it makes the product look more artistic and less commercial.",
      "Because it lights the product evenly, values detail and texture, and creates a clean professional look.",
      "Because it only works on white or neutral products.",
    ],
    2,
    "In product visuals, clarity and uniformity matter. Soft Box makes details visible without distortion.",
  ),
  fillStep(
    "Fill in the blanks - Create with Chiaroscuro",
    "Build the prompt with historical artistic depth.",
    "/imagine ___, chiaroscuro lighting, ___ style, ___, ___ inspired, ___",
    [
      "an old scholar reading by candlelight",
      "oil painting",
      "deep shadows and warm candlelight",
      "Rembrandt",
      "--ar 9:16",
    ],
    [
      "an old scholar reading by candlelight",
      "oil painting",
      "deep shadows and warm candlelight",
      "Rembrandt",
      "--ar 9:16",
    ],
    "Chiaroscuro pulls the image toward classic painting language, with historical weight and temporal depth.",
  ),
  quizStep(
    "Chiaroscuro vs Dramatic",
    "What makes Chiaroscuro different from regular Dramatic Lighting?",
    [
      "Chiaroscuro uses multiple light sources while Dramatic uses only one.",
      "They are identical techniques with different names.",
      "Chiaroscuro carries a historical artistic root and evokes classical painting with candle or torch light.",
      "Chiaroscuro only works in black and white images.",
    ],
    2,
    "Both use contrast, but Chiaroscuro also carries historical painting references that go beyond simple photographic contrast.",
  ),
  fillStep(
    "Fill in the blanks - Create with Neon Lighting",
    "Complete the prompt for a vibrant urban scene.",
    "/imagine ___, neon lighting, ___ style, ___, rain reflections on wet streets, ___ colors, ___",
    [
      "a female hacker in a futuristic alley",
      "cyberpunk digital art",
      "nighttime urban environment",
      "vivid purple and cyan",
      "--ar 9:16",
    ],
    [
      "a female hacker in a futuristic alley",
      "cyberpunk digital art",
      "nighttime urban environment",
      "vivid purple and cyan",
      "--ar 9:16",
    ],
    "Neon Lighting works when you want urban energy, artificiality, pop culture, and futuristic atmosphere.",
  ),
  quizStep(
    "When Neon does not fit",
    "In which project would Neon Lighting be the most inappropriate choice?",
    [
      "A poster for an electronic music event.",
      "The cover of an urban science fiction book.",
      "An ad campaign for an organic and natural products brand, where neon contradicts natural values.",
      "Neon Lighting does not work with female characters.",
    ],
    2,
    "Lighting should reinforce brand positioning. Neon communicates synthetic urban energy, not organic naturalness.",
  ),
  fillStep(
    "Fill in the blanks - Create with Volumetric Lighting",
    "Complete the prompt for epic depth.",
    "/imagine ___, volumetric lighting, ___ style, ___, ___ rays of light, ___",
    [
      "an ancient cathedral interior with dust particles",
      "fantasy concept art",
      "tall stained glass windows",
      "golden divine",
      "--ar 9:16",
    ],
    [
      "an ancient cathedral interior with dust particles",
      "fantasy concept art",
      "tall stained glass windows",
      "golden divine",
      "--ar 9:16",
    ],
    "Volumetric Lighting makes light visible in space and adds depth, scale, and a nearly sacred feeling.",
  ),
  quizStep(
    "What Volumetric adds",
    "What does Volumetric Lighting add that other lighting types cannot replicate?",
    [
      "Deeper and more dramatic shadows.",
      "More saturated and vibrant colors across the image.",
      "Visible materialized light in space, creating three-dimensional depth and epic scale.",
      "Volumetric Lighting only works indoors.",
    ],
    2,
    "Its real power is turning light into a visible physical presence inside the scene.",
  ),
  fillStep(
    "Fill in the blanks - Use Rim Lighting",
    "Build the prompt to highlight the character silhouette.",
    "/imagine ___, rim lighting, ___ background, ___ style, ___ silhouette, ___",
    [
      "a mysterious detective in a long coat",
      "dark moody",
      "cinematic noir photography",
      "glowing edge",
      "--ar 9:16",
    ],
    [
      "a mysterious detective in a long coat",
      "dark moody",
      "cinematic noir photography",
      "glowing edge",
      "--ar 9:16",
    ],
    "Rim Lighting separates the character from the background and increases cinematic presence immediately.",
  ),
  quizStep(
    "Why Rim works",
    "Why is Rim Lighting especially effective in character portraits?",
    [
      "Because it lights the face more clearly than any other light.",
      "Because it creates facial shadows that add detail.",
      "Because the luminous edge separates the character from the background and gives the silhouette protagonist energy.",
      "Because it only works on fully black backgrounds.",
    ],
    2,
    "Rim Lighting creates highlight, separation, and presence. It makes a silhouette feel stronger and more memorable.",
  ),
  fillStep(
    "Fill in the blanks - Combine lighting",
    "Complete the prompt using two lighting styles together.",
    "/imagine ___, ___ and ___ lighting, ___ style, ___ atmosphere, ___",
    [
      "a samurai standing in a bamboo forest at dusk",
      "golden hour",
      "volumetric",
      "cinematic photography",
      "mystical and epic",
      "--ar 16:9",
    ],
    [
      "a samurai standing in a bamboo forest at dusk",
      "golden hour",
      "volumetric",
      "cinematic photography",
      "mystical and epic",
      "--ar 16:9",
    ],
    "When two lighting approaches reinforce each other, the image gains atmospheric layers that one light alone could not create.",
  ),
  quizStep(
    "Golden Hour + Volumetric",
    "What happens when you combine Golden Hour with Volumetric Lighting in the same prompt?",
    [
      "The two lights cancel each other out and create a neutral image.",
      "MidJourney ignores one of them and applies only the most common one.",
      "The warm golden light becomes visible as beams in the air, creating epic beauty and cinematic depth at the same time.",
      "Combining lighting always creates confused and badly generated images.",
    ],
    2,
    "Golden Hour warms the scene, and Volumetric makes that light visible in space. Together they amplify atmosphere and scale.",
  ),
  fillStep(
    "Fill in the blanks - Choose the right light",
    "Complete the quick guide for lighting by objective.",
    "For ___ and cozy images use ___. For a ___ and sophisticated atmosphere use ___. For impact and ___ use Dramatic Lighting. For ___ products and portraits use Soft Box. For art with ___ depth use Chiaroscuro. For ___ night scenes use Neon Lighting. For ___ scale and magic use Volumetric Lighting.",
    [
      "warm",
      "Golden Hour",
      "mysterious",
      "Blue Hour",
      "power",
      "professional",
      "historical",
      "urban",
      "epic",
    ],
    [
      "warm",
      "Golden Hour",
      "mysterious",
      "Blue Hour",
      "power",
      "professional",
      "historical",
      "urban",
      "epic",
    ],
    "Choosing the right light means aligning emotion, objective, and the real use case of the image.",
  ),
  quizStep(
    "Common lighting mistake",
    "What is the most common mistake when choosing lighting in MidJourney?",
    [
      "Using the same lighting style in different projects.",
      "Combining two lighting styles in one prompt.",
      "Choosing lighting by visual appearance without considering the emotion it communicates.",
      "Specifying lighting in short prompts with few elements.",
    ],
    2,
    "An image can look beautiful and still be wrong for the objective if the lighting contradicts the feeling the project needs.",
  ),
  textStep(
    "Conclusion",
    "Lighting is the soul of any MidJourney image. Golden Hour for warmth and nostalgia, Blue Hour for mystery and sophistication, Dramatic for power and tension, Soft Box for professional clarity, Chiaroscuro for artistic depth, Neon for urban energy, Volumetric for epic scale, and Rim for presence and separation.\n\nNow that you understand the language of light, your prompts will never feel the same again. Choose the right light. Tell the right story.",
  ),
] as const;

export const MIDJOURNEY_MODULE_2_STEPS_ES = [
  textStep(
    "Como la iluminacion transforma tus imagenes",
    "Bienvenido de nuevo. En esta leccion vas a descubrir como la iluminacion es el elemento mas poderoso y transformador de una imagen en MidJourney. La misma escena, el mismo personaje y el mismo entorno pueden generar emociones, atmosferas e impacto visual completamente distintos cuando cambia la luz.\n\nLos fotografos profesionales dicen que fotografiar es escribir con luz. En MidJourney eso tambien es cierto: una sola expresion de iluminacion puede cambiar por completo el tono emocional de la imagen aunque el resto del prompt siga igual.",
  ),
  quizStep(
    "Por que la iluminacion importa tanto",
    "Por que la iluminacion tiene tanto impacto en una imagen generada con MidJourney?",
    [
      "Porque la luz define sombras, temperatura de color, contraste y profundidad, y el cerebro usa eso para interpretar el clima emocional.",
      "Porque MidJourney prioriza la iluminacion por encima de todos los demas elementos del prompt.",
      "Porque la iluminacion solo importa en retratos humanos.",
      "Porque iluminacion y estilo tienen el mismo peso y se pueden usar indistintamente.",
    ],
    0,
    "La luz organiza como percibimos profundidad, contraste y temperatura emocional. Por eso cambia tan rapido la sensacion de una escena.",
  ),
  fillStep(
    "Rellena el espacio - Usa Golden Hour",
    "Completa el prompt con los elementos correctos.",
    "/imagine ___, golden hour lighting, estilo ___, tonos ___, ___",
    [
      "una pareja caminando por la playa",
      "fotografia cinematografica",
      "dorados y ambar calidos",
      "--ar 16:9",
    ],
    [
      "una pareja caminando por la playa",
      "fotografia cinematografica",
      "dorados y ambar calidos",
      "--ar 16:9",
    ],
    "Golden Hour funciona muy bien cuando buscas calidez, recuerdo emocional, romance y belleza natural inmediata.",
  ),
  quizStep(
    "Emocion de Golden Hour",
    "Que sensacion emocional transmite Golden Hour en una imagen?",
    [
      "Tension y urgencia, ideal para escenas de accion.",
      "Frialdad y distancia, ideal para retratos formales.",
      "Calidez, nostalgia, romanticismo y belleza natural, como si la escena fuera un momento para recordar.",
      "Golden Hour solo funciona en paisajes sin personas.",
    ],
    2,
    "Golden Hour hace que la escena se sienta cercana y memorable.",
  ),
  fillStep(
    "Rellena el espacio - Crea con Blue Hour",
    "Arma el prompt con la atmosfera adecuada.",
    "/imagine ___, blue hour lighting, estilo ___, atmosfera melancolica, tonos ___, ___",
    [
      "una figura solitaria en un puente de la ciudad",
      "fotografia cinematografica",
      "azul profundo y morado",
      "--ar 16:9",
    ],
    [
      "una figura solitaria en un puente de la ciudad",
      "fotografia cinematografica",
      "azul profundo y morado",
      "--ar 16:9",
    ],
    "Blue Hour crea una atmosfera cinematografica, sofisticada y ligeramente melancolica.",
  ),
  quizStep(
    "Cuando usar Blue Hour",
    "En que tipo de proyecto seria mas estrategico usar Blue Hour?",
    [
      "Una campana alegre y colorida para un producto infantil.",
      "Imagenes de comida que deben verse acogedoras y apetitosas.",
      "Un editorial de moda sofisticado, un poster de suspense o cualquier proyecto que necesite misterio y profundidad emocional.",
      "Blue Hour solo funciona para paisajes urbanos nocturnos.",
    ],
    2,
    "Blue Hour destaca cuando necesitas misterio, elegancia y una atmosfera emocional profunda.",
  ),
  fillStep(
    "Rellena el espacio - Crea con Dramatic Lighting",
    "Completa el prompt con elementos que refuercen tension y poder.",
    "/imagine ___, dramatic lighting, estilo ___, ___, sombras profundas, ___",
    [
      "un guerrero poderoso sosteniendo una espada",
      "arte conceptual de fantasia oscura",
      "una unica fuente de luz direccional",
      "--ar 9:16",
    ],
    [
      "un guerrero poderoso sosteniendo una espada",
      "arte conceptual de fantasia oscura",
      "una unica fuente de luz direccional",
      "--ar 9:16",
    ],
    "Dramatic Lighting gana fuerza cuando una luz clara compite contra grandes zonas de sombra.",
  ),
  quizStep(
    "Que define el Dramatic Lighting",
    "Cual es el elemento visual que define el Dramatic Lighting?",
    [
      "Muchas fuentes de luz distribuidas de forma uniforme por la escena.",
      "Colores vibrantes y saturados en toda la composicion.",
      "El contraste fuerte entre zonas iluminadas y sombras profundas, creando tension visual.",
      "Dramatic Lighting significa simplemente imagenes oscuras sin fuente de luz visible.",
    ],
    2,
    "La base del Dramatic Lighting es el contraste, que dirige la mirada y aumenta la intensidad de la escena.",
  ),
  fillStep(
    "Rellena el espacio - Usa Soft Box",
    "Completa el prompt para una foto de producto limpia y profesional.",
    "/imagine ___, soft box lighting, fondo ___, estilo fotografico ___, ___, ___",
    [
      "un frasco de perfume de lujo con gotas de agua",
      "blanco limpio",
      "producto comercial",
      "ultra detallado",
      "--ar 1:1",
    ],
    [
      "un frasco de perfume de lujo con gotas de agua",
      "blanco limpio",
      "producto comercial",
      "ultra detallado",
      "--ar 1:1",
    ],
    "Soft Box elimina sombras duras y deja el producto limpio, elegante y listo para comunicacion de marca.",
  ),
  quizStep(
    "Soft Box para productos",
    "Por que Soft Box Lighting es la mejor opcion para fotografia de producto?",
    [
      "Porque crea sombras dramaticas que resaltan la forma del producto.",
      "Porque hace que el producto se vea mas artistico y menos comercial.",
      "Porque ilumina de forma uniforme, realza detalles y texturas y crea un aspecto limpio y profesional.",
      "Porque solo funciona con productos blancos o neutros.",
    ],
    2,
    "En producto, la claridad y la uniformidad importan mucho. Soft Box ayuda a mostrar detalle sin distorsion.",
  ),
  fillStep(
    "Rellena el espacio - Crea con Chiaroscuro",
    "Construye el prompt con profundidad artistica historica.",
    "/imagine ___, chiaroscuro lighting, estilo ___, ___, inspirado en ___, ___",
    [
      "un viejo erudito leyendo a la luz de las velas",
      "pintura al oleo",
      "sombras profundas y luz calida de vela",
      "Rembrandt",
      "--ar 9:16",
    ],
    [
      "un viejo erudito leyendo a la luz de las velas",
      "pintura al oleo",
      "sombras profundas y luz calida de vela",
      "Rembrandt",
      "--ar 9:16",
    ],
    "Chiaroscuro lleva la imagen hacia un lenguaje de pintura clasica, con peso historico y profundidad temporal.",
  ),
  quizStep(
    "Chiaroscuro vs Dramatic",
    "Que diferencia al Chiaroscuro del Dramatic Lighting comun?",
    [
      "Chiaroscuro usa multiples fuentes de luz mientras Dramatic usa solo una.",
      "Son tecnicas identicas con nombres distintos.",
      "Chiaroscuro tiene una raiz artistica historica y evoca la pintura clasica con luz de vela o antorcha.",
      "Chiaroscuro solo funciona en blanco y negro.",
    ],
    2,
    "Ambos usan contraste, pero Chiaroscuro tambien arrastra una memoria artistica historica que va mas alla del contraste fotografico.",
  ),
  fillStep(
    "Rellena el espacio - Crea con Neon Lighting",
    "Completa el prompt para una escena urbana vibrante.",
    "/imagine ___, neon lighting, estilo ___, ___, reflejos de lluvia en calles mojadas, colores ___, ___",
    [
      "una hacker en un callejon futurista",
      "arte digital cyberpunk",
      "entorno urbano nocturno",
      "morado y cian intensos",
      "--ar 9:16",
    ],
    [
      "una hacker en un callejon futurista",
      "arte digital cyberpunk",
      "entorno urbano nocturno",
      "morado y cian intensos",
      "--ar 9:16",
    ],
    "Neon Lighting funciona cuando quieres energia urbana, artificialidad, cultura pop y una atmosfera futurista.",
  ),
  quizStep(
    "Cuando Neon no encaja",
    "En que proyecto seria mas inadecuado usar Neon Lighting?",
    [
      "Un poster para un evento de musica electronica.",
      "La portada de un libro de ciencia ficcion urbana.",
      "Una campana para una marca de productos organicos y naturales, donde el neon contradice la idea de naturalidad.",
      "Neon Lighting no funciona con personajes femeninos.",
    ],
    2,
    "La luz debe reforzar el posicionamiento de la marca. Neon comunica energia urbana sintetica, no naturalidad organica.",
  ),
  fillStep(
    "Rellena el espacio - Crea con Volumetric Lighting",
    "Completa el prompt para una escena con profundidad epica.",
    "/imagine ___, volumetric lighting, estilo ___, ___, rayos de luz ___, ___",
    [
      "el interior de una catedral antigua con particulas de polvo",
      "arte conceptual de fantasia",
      "vitrales altos",
      "dorados y divinos",
      "--ar 9:16",
    ],
    [
      "el interior de una catedral antigua con particulas de polvo",
      "arte conceptual de fantasia",
      "vitrales altos",
      "dorados y divinos",
      "--ar 9:16",
    ],
    "Volumetric Lighting vuelve visible la luz en el espacio y agrega profundidad, escala y una sensacion casi sagrada.",
  ),
  quizStep(
    "Lo que aporta Volumetric",
    "Que agrega Volumetric Lighting que otros tipos de iluminacion no pueden replicar?",
    [
      "Sombras mas profundas y dramaticas.",
      "Colores mas saturados y vibrantes en toda la imagen.",
      "La materializacion visible de la luz en el espacio, creando profundidad tridimensional y escala epica.",
      "Volumetric Lighting solo funciona en interiores.",
    ],
    2,
    "Su poder real esta en convertir la luz en una presencia visible dentro de la escena.",
  ),
  fillStep(
    "Rellena el espacio - Usa Rim Lighting",
    "Arma el prompt para destacar la silueta del personaje.",
    "/imagine ___, rim lighting, fondo ___, estilo ___, silueta ___, ___",
    [
      "un detective misterioso con abrigo largo",
      "oscuro y melancolico",
      "fotografia noir cinematografica",
      "con borde brillante",
      "--ar 9:16",
    ],
    [
      "un detective misterioso con abrigo largo",
      "oscuro y melancolico",
      "fotografia noir cinematografica",
      "con borde brillante",
      "--ar 9:16",
    ],
    "Rim Lighting separa al personaje del fondo y aumenta su presencia cinematografica de inmediato.",
  ),
  quizStep(
    "Por que Rim funciona",
    "Por que Rim Lighting es especialmente eficaz en retratos de personajes?",
    [
      "Porque ilumina la cara con mas claridad que cualquier otra luz.",
      "Porque crea sombras faciales que agregan detalle.",
      "Porque el borde luminoso separa al personaje del fondo y convierte la silueta en presencia de protagonista.",
      "Porque solo funciona con fondos completamente negros.",
    ],
    2,
    "Rim Lighting crea destaque, separacion y presencia. Hace que la silueta se sienta mas fuerte y memorable.",
  ),
  fillStep(
    "Rellena el espacio - Combina iluminaciones",
    "Completa el prompt usando dos iluminaciones al mismo tiempo.",
    "/imagine ___, iluminacion ___ and ___, estilo ___, atmosfera ___, ___",
    [
      "un samurai de pie en un bosque de bambu al atardecer",
      "golden hour",
      "volumetric",
      "fotografia cinematografica",
      "mistica y epica",
      "--ar 16:9",
    ],
    [
      "un samurai de pie en un bosque de bambu al atardecer",
      "golden hour",
      "volumetric",
      "fotografia cinematografica",
      "mistica y epica",
      "--ar 16:9",
    ],
    "Cuando dos iluminaciones se refuerzan, la imagen gana capas atmosfericas que una sola luz no podria crear por si misma.",
  ),
  quizStep(
    "Golden Hour + Volumetric",
    "Que ocurre al combinar Golden Hour con Volumetric Lighting en el mismo prompt?",
    [
      "Las dos luces se cancelan y el resultado queda neutro.",
      "MidJourney ignora una de ellas y aplica solo la mas comun.",
      "La luz dorada se vuelve visible en haces en el aire, creando belleza epica y profundidad cinematografica al mismo tiempo.",
      "Combinar iluminaciones siempre genera imagenes confusas y mal resueltas.",
    ],
    2,
    "Golden Hour calienta la escena y Volumetric hace visible esa luz en el espacio. Juntas amplifican atmosfera y escala.",
  ),
  fillStep(
    "Rellena el espacio - Elige la luz correcta",
    "Completa la guia rapida de iluminacion por objetivo.",
    "Para imagenes ___ y acogedoras usa ___. Para una atmosfera ___ y sofisticada usa ___. Para impacto y ___ usa Dramatic Lighting. Para productos y retratos ___ usa Soft Box. Para arte con profundidad ___ usa Chiaroscuro. Para escenas ___ nocturnas usa Neon Lighting. Para escala ___ y magia usa Volumetric Lighting.",
    [
      "calidas",
      "Golden Hour",
      "misteriosa",
      "Blue Hour",
      "poder",
      "profesionales",
      "historica",
      "urbanas",
      "epica",
    ],
    [
      "calidas",
      "Golden Hour",
      "misteriosa",
      "Blue Hour",
      "poder",
      "profesionales",
      "historica",
      "urbanas",
      "epica",
    ],
    "Elegir la luz correcta significa alinear emocion, objetivo y uso real de la imagen.",
  ),
  quizStep(
    "Error comun al elegir luz",
    "Cual es el error mas comun al elegir iluminacion en MidJourney?",
    [
      "Usar el mismo tipo de iluminacion en proyectos diferentes.",
      "Combinar dos iluminaciones en un mismo prompt.",
      "Elegir la iluminacion por la apariencia visual sin considerar la emocion que transmite.",
      "Especificar iluminacion en prompts cortos con pocos elementos.",
    ],
    2,
    "Una imagen puede verse bonita y aun asi ser incorrecta para el objetivo si la luz contradice la emocion que el proyecto necesita comunicar.",
  ),
  textStep(
    "Conclusion",
    "La iluminacion es el alma de cualquier imagen en MidJourney. Golden Hour para calidez y nostalgia, Blue Hour para misterio y sofisticacion, Dramatic para poder y tension, Soft Box para limpieza profesional, Chiaroscuro para profundidad artistica, Neon para energia urbana, Volumetric para escala epica y Rim para presencia y separacion.\n\nAhora que entiendes el lenguaje de la luz, tus prompts ya no volveran a ser los mismos. Elige la luz correcta. Cuenta la historia correcta.",
  ),
] as const;
export const MIDJOURNEY_MODULE_2_STEPS_FR = [
  textStep(
    "Comment la lumiere transforme vos images",
    "Bienvenue a nouveau. Dans cette lecon, vous allez comprendre pourquoi la lumiere est l'element le plus puissant et le plus transformateur d'une image MidJourney. La meme scene, le meme personnage et le meme decor peuvent produire des emotions, des atmospheres et un impact visuel totalement differents lorsque la lumiere change.\n\nLes photographes professionnels disent souvent que photographier, c'est ecrire avec la lumiere. Dans MidJourney, c'est egalement vrai: une seule expression de lumiere peut changer tout le ton emotionnel de l'image meme si le reste du prompt reste identique.",
  ),
  quizStep(
    "Pourquoi la lumiere compte autant",
    "Pourquoi la lumiere a-t-elle un impact si fort dans une image generee avec MidJourney?",
    [
      "Parce que la lumiere definit les ombres, la temperature de couleur, le contraste et la profondeur, et le cerveau s'appuie sur cela pour lire l'emotion d'une scene.",
      "Parce que MidJourney donne toujours la priorite a la lumiere par rapport aux autres elements du prompt.",
      "Parce que la lumiere ne compte que dans les portraits humains.",
      "Parce que la lumiere et le style ont exactement le meme role et peuvent etre utilises de la meme facon.",
    ],
    0,
    "La lumiere organise notre lecture de la profondeur, du contraste et de la temperature emotionnelle. C'est pour cela qu'elle change si vite la sensation d'une scene.",
  ),
  fillStep(
    "Completez les blancs - Utilisez Golden Hour",
    "Completez le prompt avec les bons elements.",
    "/imagine ___, golden hour lighting, style ___, tons ___, ___",
    [
      "un couple marchant sur une plage",
      "photographie cinematographique",
      "dores et ambre chaleureux",
      "--ar 16:9",
    ],
    [
      "un couple marchant sur une plage",
      "photographie cinematographique",
      "dores et ambre chaleureux",
      "--ar 16:9",
    ],
    "Golden Hour fonctionne tres bien quand vous cherchez la chaleur, la nostalgie, le romantisme et une beaute naturelle immediate.",
  ),
  quizStep(
    "Emotion du Golden Hour",
    "Quelle sensation emotionnelle le Golden Hour transmet-il dans une image?",
    [
      "La tension et l'urgence, ideales pour les scenes d'action.",
      "La froideur et la distance, ideales pour les portraits formels.",
      "La chaleur, la nostalgie, le romantisme et une beaute naturelle qui rendent la scene memorable.",
      "Golden Hour ne fonctionne bien que pour les paysages sans personnes.",
    ],
    2,
    "Golden Hour rapproche emotionnellement le spectateur et donne a la scene une valeur de souvenir.",
  ),
  fillStep(
    "Completez les blancs - Creez avec Blue Hour",
    "Construisez le prompt avec la bonne atmosphere.",
    "/imagine ___, blue hour lighting, style ___, atmosphere melancolique, tons ___, ___",
    [
      "une silhouette solitaire sur un pont urbain",
      "photographie cinematographique",
      "bleu profond et violet",
      "--ar 16:9",
    ],
    [
      "une silhouette solitaire sur un pont urbain",
      "photographie cinematographique",
      "bleu profond et violet",
      "--ar 16:9",
    ],
    "Blue Hour cree une atmosphere cinematographique, elegante et legerement melancolique.",
  ),
  quizStep(
    "Quand utiliser Blue Hour",
    "Dans quel type de projet Blue Hour serait-il le choix le plus strategique?",
    [
      "Une campagne joyeuse et coloree pour un produit pour enfants.",
      "Des images culinaires qui doivent sembler chaleureuses et appetissantes.",
      "Un editorial de mode sophistique, une affiche de thriller ou tout projet qui a besoin de mystere et de profondeur emotionnelle.",
      "Blue Hour ne fonctionne que pour les paysages urbains nocturnes.",
    ],
    2,
    "Blue Hour est ideal quand le projet a besoin de mystere, d'elegance et de profondeur emotionnelle.",
  ),
  fillStep(
    "Completez les blancs - Creez avec Dramatic Lighting",
    "Completez le prompt avec des elements qui renforcent tension et puissance.",
    "/imagine ___, dramatic lighting, style ___, ___, ombres profondes, ___",
    [
      "un guerrier puissant tenant une epee",
      "concept art de fantasy sombre",
      "une source unique de lumiere directionnelle",
      "--ar 9:16",
    ],
    [
      "un guerrier puissant tenant une epee",
      "concept art de fantasy sombre",
      "une source unique de lumiere directionnelle",
      "--ar 9:16",
    ],
    "Dramatic Lighting devient plus fort lorsqu'une source lumineuse claire lutte contre de grandes zones d'ombre.",
  ),
  quizStep(
    "Ce qui definit Dramatic Lighting",
    "Quel element visuel definit le Dramatic Lighting?",
    [
      "De nombreuses sources de lumiere reparties uniformement dans la scene.",
      "Des couleurs tres vives et saturees dans toute la composition.",
      "Un contraste fort entre les zones eclairees et les ombres profondes, qui cree une tension visuelle.",
      "Dramatic Lighting signifie simplement une image sombre sans source lumineuse visible.",
    ],
    2,
    "Le coeur du Dramatic Lighting, c'est le contraste. Il dirige le regard et renforce la puissance de la scene.",
  ),
  fillStep(
    "Completez les blancs - Utilisez Soft Box",
    "Completez le prompt pour une image produit propre et professionnelle.",
    "/imagine ___, soft box lighting, fond ___, style photo ___, ___, ___",
    [
      "un flacon de parfum de luxe avec des gouttes d'eau",
      "blanc propre",
      "produit commercial",
      "ultra detaille",
      "--ar 1:1",
    ],
    [
      "un flacon de parfum de luxe avec des gouttes d'eau",
      "blanc propre",
      "produit commercial",
      "ultra detaille",
      "--ar 1:1",
    ],
    "Soft Box supprime les ombres dures et donne au produit une apparence propre, elegante et prete pour la communication de marque.",
  ),
  quizStep(
    "Soft Box pour les produits",
    "Pourquoi Soft Box Lighting est-il ideal pour la photographie de produit?",
    [
      "Parce qu'il cree des ombres dramatiques qui mettent en valeur la forme du produit.",
      "Parce qu'il rend le produit plus artistique et moins commercial.",
      "Parce qu'il eclaire de maniere uniforme, valorise les details et les textures et donne un rendu propre et professionnel.",
      "Parce qu'il ne fonctionne qu'avec des produits blancs ou neutres.",
    ],
    2,
    "En photo produit, la clarte et l'uniformite comptent beaucoup. Soft Box aide a montrer les details sans distorsion.",
  ),
  fillStep(
    "Completez les blancs - Creez avec Chiaroscuro",
    "Construisez le prompt avec une profondeur artistique historique.",
    "/imagine ___, chiaroscuro lighting, style ___, ___, inspire par ___, ___",
    [
      "un vieux savant lisant a la bougie",
      "peinture a l'huile",
      "ombres profondes et lumiere chaude de bougie",
      "Rembrandt",
      "--ar 9:16",
    ],
    [
      "un vieux savant lisant a la bougie",
      "peinture a l'huile",
      "ombres profondes et lumiere chaude de bougie",
      "Rembrandt",
      "--ar 9:16",
    ],
    "Le chiaroscuro rapproche l'image d'un langage pictural classique, avec du poids historique et de la profondeur temporelle.",
  ),
  quizStep(
    "Chiaroscuro vs Dramatic",
    "Qu'est-ce qui distingue le Chiaroscuro du Dramatic Lighting classique?",
    [
      "Le Chiaroscuro utilise plusieurs sources de lumiere alors que Dramatic n'en utilise qu'une.",
      "Ce sont exactement les memes techniques avec deux noms differents.",
      "Le Chiaroscuro porte une racine artistique historique et evoque la peinture classique a la bougie ou a la torche.",
      "Le Chiaroscuro ne fonctionne qu'en noir et blanc.",
    ],
    2,
    "Les deux jouent avec le contraste, mais le Chiaroscuro ajoute une memoire artistique historique qui va au-dela du simple contraste photographique.",
  ),
  fillStep(
    "Completez les blancs - Creez avec Neon Lighting",
    "Completez le prompt pour une scene urbaine vibrante.",
    "/imagine ___, neon lighting, style ___, ___, reflets de pluie sur les rues mouillees, couleurs ___, ___",
    [
      "une hackeuse dans une ruelle futuriste",
      "art digital cyberpunk",
      "environnement urbain nocturne",
      "violet et cyan vifs",
      "--ar 9:16",
    ],
    [
      "une hackeuse dans une ruelle futuriste",
      "art digital cyberpunk",
      "environnement urbain nocturne",
      "violet et cyan vifs",
      "--ar 9:16",
    ],
    "Neon Lighting fonctionne quand vous cherchez de l'energie urbaine, de l'artificialite, de la culture pop et une atmosphere futuriste.",
  ),
  quizStep(
    "Quand Neon ne convient pas",
    "Dans quel projet Neon Lighting serait-il le choix le plus inadapte?",
    [
      "Une affiche pour un evenement de musique electronique.",
      "La couverture d'un livre de science-fiction urbaine.",
      "Une campagne pour une marque de produits organiques et naturels, ou l'esthetique neon contredit la naturalite.",
      "Neon Lighting ne fonctionne pas avec des personnages feminins.",
    ],
    2,
    "La lumiere doit renforcer le positionnement de la marque. Le neon communique une energie urbaine synthetique, pas une naturalite organique.",
  ),
  fillStep(
    "Completez les blancs - Creez avec Volumetric Lighting",
    "Completez le prompt pour une scene a profondeur epique.",
    "/imagine ___, volumetric lighting, style ___, ___, rayons de lumiere ___, ___",
    [
      "l'interieur d'une cathedrale ancienne avec des particules de poussiere",
      "concept art fantasy",
      "grands vitraux",
      "dores et divins",
      "--ar 9:16",
    ],
    [
      "l'interieur d'une cathedrale ancienne avec des particules de poussiere",
      "concept art fantasy",
      "grands vitraux",
      "dores et divins",
      "--ar 9:16",
    ],
    "Volumetric Lighting rend la lumiere visible dans l'espace et ajoute profondeur, echelle et sensation presque sacree.",
  ),
  quizStep(
    "Ce que Volumetric ajoute",
    "Qu'apporte Volumetric Lighting qu'aucun autre type de lumiere ne reproduit vraiment?",
    [
      "Des ombres plus profondes et plus dramatiques.",
      "Des couleurs plus saturees et plus vives dans toute l'image.",
      "La materialisation visible de la lumiere dans l'espace, creant profondeur tridimensionnelle et echelle epique.",
      "Volumetric Lighting ne fonctionne qu'en interieur.",
    ],
    2,
    "Sa force, c'est de transformer la lumiere en presence visible a l'interieur de la scene.",
  ),
  fillStep(
    "Completez les blancs - Utilisez Rim Lighting",
    "Construisez le prompt pour mettre en valeur la silhouette du personnage.",
    "/imagine ___, rim lighting, fond ___, style ___, silhouette ___, ___",
    [
      "un detective mysterieux en long manteau",
      "sombre et melancolique",
      "photographie noir cinematographique",
      "avec bord lumineux",
      "--ar 9:16",
    ],
    [
      "un detective mysterieux en long manteau",
      "sombre et melancolique",
      "photographie noir cinematographique",
      "avec bord lumineux",
      "--ar 9:16",
    ],
    "Rim Lighting separe le personnage du fond et augmente immediatement sa presence cinematographique.",
  ),
  quizStep(
    "Pourquoi Rim fonctionne",
    "Pourquoi Rim Lighting est-il particulierement efficace dans les portraits de personnages?",
    [
      "Parce qu'il eclaire le visage plus clairement que n'importe quelle autre lumiere.",
      "Parce qu'il cree des ombres faciales qui ajoutent du relief.",
      "Parce que le contour lumineux separe le personnage du fond et donne a la silhouette une energie de protagoniste.",
      "Parce qu'il ne fonctionne qu'avec des fonds noirs complets.",
    ],
    2,
    "Rim Lighting cree du relief, de la separation et de la presence. Il rend la silhouette plus forte et plus memorable.",
  ),
  fillStep(
    "Completez les blancs - Combinez les lumieres",
    "Completez le prompt en utilisant deux types de lumiere ensemble.",
    "/imagine ___, lumiere ___ and ___, style ___, atmosphere ___, ___",
    [
      "un samourai dans une foret de bambous au crepuscule",
      "golden hour",
      "volumetric",
      "photographie cinematographique",
      "mystique et epique",
      "--ar 16:9",
    ],
    [
      "un samourai dans une foret de bambous au crepuscule",
      "golden hour",
      "volumetric",
      "photographie cinematographique",
      "mystique et epique",
      "--ar 16:9",
    ],
    "Quand deux approches de lumiere se renforcent, l'image gagne des couches d'atmosphere qu'une seule lumiere ne peut pas produire seule.",
  ),
  quizStep(
    "Golden Hour + Volumetric",
    "Quel est le resultat de la combinaison Golden Hour + Volumetric Lighting dans un meme prompt?",
    [
      "Les deux lumieres s'annulent et donnent une image neutre.",
      "MidJourney ignore l'une d'elles et garde seulement la plus commune.",
      "La lumiere doree devient visible sous forme de faisceaux dans l'air, creant beaute epique et profondeur cinematographique en meme temps.",
      "Combiner plusieurs lumieres produit toujours des images confuses et ratees.",
    ],
    2,
    "Golden Hour rechauffe la scene et Volumetric rend cette lumiere visible dans l'espace. Ensemble, elles amplifient atmosphere et echelle.",
  ),
  fillStep(
    "Completez les blancs - Choisissez la bonne lumiere",
    "Completez le guide rapide de la lumiere selon l'objectif.",
    "Pour des images ___ et chaleureuses utilisez ___. Pour une atmosphere ___ et sophistiquee utilisez ___. Pour l'impact et la ___ utilisez Dramatic Lighting. Pour des produits et portraits ___ utilisez Soft Box. Pour un art a profondeur ___ utilisez Chiaroscuro. Pour des scenes ___ nocturnes utilisez Neon Lighting. Pour une echelle ___ et de la magie utilisez Volumetric Lighting.",
    [
      "chaudes",
      "Golden Hour",
      "mysterieuse",
      "Blue Hour",
      "puissance",
      "professionnels",
      "historique",
      "urbaines",
      "epique",
    ],
    [
      "chaudes",
      "Golden Hour",
      "mysterieuse",
      "Blue Hour",
      "puissance",
      "professionnels",
      "historique",
      "urbaines",
      "epique",
    ],
    "Choisir la bonne lumiere, c'est aligner l'emotion, l'objectif et l'usage reel de l'image.",
  ),
  quizStep(
    "Erreur courante dans le choix de la lumiere",
    "Quelle est l'erreur la plus courante quand on choisit une lumiere dans MidJourney?",
    [
      "Utiliser le meme type de lumiere dans des projets differents.",
      "Combiner deux types de lumiere dans le meme prompt.",
      "Choisir la lumiere pour son apparence visuelle sans tenir compte de l'emotion qu'elle transmet.",
      "Preciser la lumiere dans des prompts courts avec peu d'elements.",
    ],
    2,
    "Une image peut etre belle et pourtant mauvaise pour l'objectif si la lumiere contredit l'emotion que le projet doit transmettre.",
  ),
  textStep(
    "Conclusion",
    "La lumiere est l'ame de toute image MidJourney. Golden Hour pour la chaleur et la nostalgie, Blue Hour pour le mystere et la sophistication, Dramatic pour la puissance et la tension, Soft Box pour la clarte professionnelle, Chiaroscuro pour la profondeur artistique, Neon pour l'energie urbaine, Volumetric pour l'echelle epique et Rim pour la presence et la separation.\n\nMaintenant que vous comprenez le langage de la lumiere, vos prompts ne seront plus jamais les memes. Choisissez la bonne lumiere. Racontez la bonne histoire.",
  ),
] as const;
