const textStep = (title: string, content: string, promptBox?: string) => ({
  type: "text" as const,
  title,
  content,
  ...(promptBox ? { promptBox } : {}),
});

const quizStep = (
  title: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
) => ({
  type: "quiz" as const,
  title,
  question,
  options,
  correctIndex,
  explanation,
});

const fillStep = (
  title: string,
  instruction: string,
  sentence: string,
  answers: string[],
  options: string[],
  explanation: string,
) => ({
  type: "fill_blanks" as const,
  title,
  instruction,
  sentence,
  answers,
  options,
  explanation,
});

export const MIDJOURNEY_MODULE_2_STEPS_PT = [
  textStep(
    "Como a iluminacao pode transformar suas imagens",
    "Bem-vindo de volta! Nesta licao, voce vai descobrir como a iluminacao e o elemento mais poderoso e transformador de uma imagem no MidJourney. A mesma cena, o mesmo personagem e o mesmo ambiente podem gerar resultados completamente diferentes em emocao, atmosfera e impacto visual quando a luz muda.\n\nFotografos profissionais dizem que fotografar e escrever com luz. No MidJourney, isso tambem e verdade: a palavra que descreve a iluminacao pode mudar o tom emocional da imagem mesmo que todo o resto do prompt permaneca igual.",
  ),
  fillStep(
    "Preencha a lacuna - Use o Golden Hour",
    "Complete o prompt com os elementos corretos.",
    "/imagine ___, luz golden hour, estilo ___, tons ___, ___",
    [
      "um casal caminhando na praia",
      "fotografia cinematografica",
      "dourados e ambar quentes",
      "--ar 16:9",
    ],
    [
      "um casal caminhando na praia",
      "fotografia cinematografica",
      "dourados e ambar quentes",
      "--ar 16:9",
    ],
    "Golden Hour funciona muito bem quando voce quer calor, memoria afetiva e beleza natural instantanea.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Blue Hour",
    "Monte o prompt com a atmosfera correta.",
    "/imagine ___, luz blue hour, estilo ___, atmosfera melancolica, tons ___, ___",
    [
      "uma figura solitaria parada em uma ponte da cidade",
      "fotografia cinematografica",
      "azul profundo e roxo",
      "--ar 16:9",
    ],
    [
      "uma figura solitaria parada em uma ponte da cidade",
      "fotografia cinematografica",
      "azul profundo e roxo",
      "--ar 16:9",
    ],
    "Blue Hour cria uma atmosfera sofisticada, elegante e levemente melancolica, com cara de cinema.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Dramatic Lighting",
    "Complete o prompt com os elementos que reforcam tensao e poder.",
    "/imagine ___, iluminacao dramatica, estilo ___, ___, sombras profundas, ___",
    [
      "um guerreiro poderoso segurando uma espada",
      "arte conceitual de fantasia sombria",
      "fonte unica de luz direcional",
      "--ar 9:16",
    ],
    [
      "um guerreiro poderoso segurando uma espada",
      "arte conceitual de fantasia sombria",
      "fonte unica de luz direcional",
      "--ar 9:16",
    ],
    "Dramatic Lighting cresce quando existe uma fonte de luz forte e bem definida contra grandes areas de sombra.",
  ),
  quizStep(
    "O que define o Dramatic Lighting",
    "Qual e o elemento visual que define o Dramatic Lighting?",
    [
      "Muitas fontes de luz distribuidas uniformemente pela cena.",
      "Cores vibrantes e saturadas em toda a composicao.",
      "O alto contraste entre areas iluminadas e sombras profundas, criando tensao visual.",
      "Dramatic Lighting e sinonimo de imagens escuras sem fonte de luz aparente.",
    ],
    2,
    "O coracao do Dramatic Lighting e o contraste forte, que direciona o olhar e aumenta a sensacao de poder e intensidade.",
  ),
  fillStep(
    "Preencha a lacuna - Use o Soft Box",
    "Preencha o prompt para uma fotografia de produto limpa e profissional.",
    "/imagine ___, iluminacao soft box, fundo ___, estilo de fotografia ___, ___, ___",
    [
      "um frasco de perfume de luxo com gotas de agua",
      "branco limpo",
      "produto comercial",
      "ultra detalhado",
      "--ar 1:1",
    ],
    [
      "um frasco de perfume de luxo com gotas de agua",
      "branco limpo",
      "produto comercial",
      "ultra detalhado",
      "--ar 1:1",
    ],
    "Soft Box elimina sombras duras e deixa o produto limpo, elegante e pronto para comunicacao de marca.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Chiaroscuro",
    "Monte o prompt com profundidade artistica historica.",
    "/imagine ___, iluminacao chiaroscuro, estilo ___, ___, inspirado em ___, ___",
    [
      "um velho estudioso lendo a luz de velas",
      "pintura a oleo",
      "sombras profundas e luz quente de vela",
      "Rembrandt",
      "--ar 9:16",
    ],
    [
      "um velho estudioso lendo a luz de velas",
      "pintura a oleo",
      "sombras profundas e luz quente de vela",
      "Rembrandt",
      "--ar 9:16",
    ],
    "Chiaroscuro puxa a imagem para uma linguagem classica de pintura, com peso historico e profundidade temporal.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Neon Lighting",
    "Complete o prompt para uma cena urbana vibrante.",
    "/imagine ___, iluminacao neon, estilo ___, ___, reflexos de chuva nas ruas molhadas, cores ___, ___",
    [
      "uma hacker em um beco futurista",
      "arte digital cyberpunk",
      "ambiente urbano noturno",
      "roxo e ciano vivos",
      "--ar 9:16",
    ],
    [
      "uma hacker em um beco futurista",
      "arte digital cyberpunk",
      "ambiente urbano noturno",
      "roxo e ciano vivos",
      "--ar 9:16",
    ],
    "Neon Lighting funciona quando voce quer energia urbana, artificialidade, cultura pop e clima futurista.",
  ),
  fillStep(
    "Preencha a lacuna - Combine iluminacoes",
    "Complete o prompt usando duas iluminacoes no mesmo resultado.",
    "/imagine ___, iluminacao ___ e ___, estilo ___, atmosfera ___, ___",
    [
      "um samurai em uma floresta de bambu ao entardecer",
      "golden hour",
      "volumetric",
      "fotografia cinematografica",
      "mistica e epica",
      "--ar 16:9",
    ],
    [
      "um samurai em uma floresta de bambu ao entardecer",
      "golden hour",
      "volumetric",
      "fotografia cinematografica",
      "mistica e epica",
      "--ar 16:9",
    ],
    "Quando duas iluminacoes se reforcam, a imagem ganha camadas de atmosfera que uma unica luz nao entregaria sozinha.",
  ),
  textStep(
    "Conclusao",
    "A iluminacao e a alma de qualquer imagem no MidJourney. Golden Hour para calor e nostalgia, Blue Hour para misterio e sofisticacao, Dramatic para poder e tensao, Soft Box para limpeza profissional, Chiaroscuro para profundidade artistica, Neon para energia urbana, Volumetric para escala epica e Rim para presenca e destaque.\n\nAgora que voce entende a linguagem da luz, seus prompts nunca mais serao os mesmos. Escolha a luz certa. Conte a historia certa.",
  ),
] as const;

export const MIDJOURNEY_MODULE_2_STEPS_EN = [
  textStep(
    "How lighting transforms your images",
    "Welcome back! In this lesson, you will see how lighting becomes the most powerful and transformative element in a MidJourney image. The same scene, the same character, and the same environment can create completely different emotions, atmospheres, and visual impact when the light changes.\n\nProfessional photographers often say photography is writing with light. In MidJourney, that is also true: the lighting phrase alone can shift the emotional tone of the image even when every other part of the prompt stays the same.",
  ),
  fillStep(
    "Fill in the blanks - Use Golden Hour",
    "Complete the prompt with the correct elements.",
    "/imagine ___, golden hour lighting, ___ style, ___ tones, ___",
    [
      "a couple walking on a beach",
      "cinematic photography",
      "warm golden and amber",
      "--ar 16:9",
    ],
    [
      "a couple walking on a beach",
      "cinematic photography",
      "warm golden and amber",
      "--ar 16:9",
    ],
    "Golden Hour works best when you want warmth, memory, romance, and immediate natural beauty.",
  ),
  fillStep(
    "Fill in the blanks - Create with Blue Hour",
    "Build the prompt with the right atmosphere.",
    "/imagine ___, blue hour lighting, ___ style, moody atmosphere, ___ tones, ___",
    [
      "a lonely figure standing on a city bridge",
      "cinematic photography",
      "deep blue and purple",
      "--ar 16:9",
    ],
    [
      "a lonely figure standing on a city bridge",
      "cinematic photography",
      "deep blue and purple",
      "--ar 16:9",
    ],
    "Blue Hour creates a cinematic, sophisticated, and slightly melancholic mood.",
  ),
  fillStep(
    "Fill in the blanks - Create with Dramatic Lighting",
    "Complete the prompt with elements that reinforce tension and power.",
    "/imagine ___, dramatic lighting, ___ style, ___, deep shadows, ___",
    [
      "a powerful warrior holding a sword",
      "dark fantasy concept art",
      "single directional light source",
      "--ar 9:16",
    ],
    [
      "a powerful warrior holding a sword",
      "dark fantasy concept art",
      "single directional light source",
      "--ar 9:16",
    ],
    "Dramatic Lighting becomes stronger when one clear light source fights against large shadow areas.",
  ),
  quizStep(
    "What defines Dramatic Lighting",
    "What visual element defines Dramatic Lighting?",
    [
      "Many light sources spread evenly across the scene.",
      "Vibrant and saturated colors across the whole composition.",
      "Strong contrast between lit areas and deep shadows, creating tension.",
      "Dramatic Lighting simply means dark images with no visible light source.",
    ],
    2,
    "The core of Dramatic Lighting is contrast. It directs the eye and increases power and intensity.",
  ),
  fillStep(
    "Fill in the blanks - Use Soft Box",
    "Complete the prompt for a clean, professional product image.",
    "/imagine ___, soft box lighting, ___ background, ___ photography style, ___, ___",
    [
      "a luxury perfume bottle with water drops",
      "clean white",
      "commercial product",
      "ultra detailed",
      "--ar 1:1",
    ],
    [
      "a luxury perfume bottle with water drops",
      "clean white",
      "commercial product",
      "ultra detailed",
      "--ar 1:1",
    ],
    "Soft Box removes harsh shadows and makes the product feel clean, elegant, and ready for brand communication.",
  ),
  fillStep(
    "Fill in the blanks - Create with Chiaroscuro",
    "Build the prompt with historical artistic depth.",
    "/imagine ___, chiaroscuro lighting, ___ style, ___, ___ inspired, ___",
    [
      "an old scholar reading by candlelight",
      "oil painting",
      "deep shadows and warm candlelight",
      "Rembrandt",
      "--ar 9:16",
    ],
    [
      "an old scholar reading by candlelight",
      "oil painting",
      "deep shadows and warm candlelight",
      "Rembrandt",
      "--ar 9:16",
    ],
    "Chiaroscuro pulls the image toward classic painting language, with historical weight and temporal depth.",
  ),
  fillStep(
    "Fill in the blanks - Create with Neon Lighting",
    "Complete the prompt for a vibrant urban scene.",
    "/imagine ___, neon lighting, ___ style, ___, rain reflections on wet streets, ___ colors, ___",
    [
      "a female hacker in a futuristic alley",
      "cyberpunk digital art",
      "nighttime urban environment",
      "vivid purple and cyan",
      "--ar 9:16",
    ],
    [
      "a female hacker in a futuristic alley",
      "cyberpunk digital art",
      "nighttime urban environment",
      "vivid purple and cyan",
      "--ar 9:16",
    ],
    "Neon Lighting works when you want urban energy, artificiality, pop culture, and futuristic atmosphere.",
  ),
  fillStep(
    "Fill in the blanks - Combine lighting",
    "Complete the prompt using two lighting styles together.",
    "/imagine ___, ___ and ___ lighting, ___ style, ___ atmosphere, ___",
    [
      "a samurai standing in a bamboo forest at dusk",
      "golden hour",
      "volumetric",
      "cinematic photography",
      "mystical and epic",
      "--ar 16:9",
    ],
    [
      "a samurai standing in a bamboo forest at dusk",
      "golden hour",
      "volumetric",
      "cinematic photography",
      "mystical and epic",
      "--ar 16:9",
    ],
    "When two lighting approaches reinforce each other, the image gains atmospheric layers that one light alone could not create.",
  ),
  textStep(
    "Conclusion",
    "Lighting is the soul of any MidJourney image. Golden Hour for warmth and nostalgia, Blue Hour for mystery and sophistication, Dramatic for power and tension, Soft Box for professional clarity, Chiaroscuro for artistic depth, Neon for urban energy, Volumetric for epic scale, and Rim for presence and separation.\n\nNow that you understand the language of light, your prompts will never feel the same again. Choose the right light. Tell the right story.",
  ),
] as const;

export const MIDJOURNEY_MODULE_2_STEPS_ES = [
  textStep(
    "Como la iluminacion transforma tus imagenes",
    "Bienvenido de nuevo. En esta leccion vas a descubrir como la iluminacion es el elemento mas poderoso y transformador de una imagen en MidJourney. La misma escena, el mismo personaje y el mismo entorno pueden generar emociones, atmosferas e impacto visual completamente distintos cuando cambia la luz.\n\nLos fotografos profesionales dicen que fotografiar es escribir con luz. En MidJourney eso tambien es cierto: una sola expresion de iluminacion puede cambiar por completo el tono emocional de la imagen aunque el resto del prompt siga igual.",
  ),
  fillStep(
    "Rellena el espacio - Usa Golden Hour",
    "Completa el prompt con los elementos correctos.",
    "/imagine ___, golden hour lighting, estilo ___, tonos ___, ___",
    [
      "una pareja caminando por la playa",
      "fotografia cinematografica",
      "dorados y ambar calidos",
      "--ar 16:9",
    ],
    [
      "una pareja caminando por la playa",
      "fotografia cinematografica",
      "dorados y ambar calidos",
      "--ar 16:9",
    ],
    "Golden Hour funciona muy bien cuando buscas calidez, recuerdo emocional, romance y belleza natural inmediata.",
  ),
  fillStep(
    "Rellena el espacio - Crea con Blue Hour",
    "Arma el prompt con la atmosfera adecuada.",
    "/imagine ___, blue hour lighting, estilo ___, atmosfera melancolica, tonos ___, ___",
    [
      "una figura solitaria en un puente de la ciudad",
      "fotografia cinematografica",
      "azul profundo y morado",
      "--ar 16:9",
    ],
    [
      "una figura solitaria en un puente de la ciudad",
      "fotografia cinematografica",
      "azul profundo y morado",
      "--ar 16:9",
    ],
    "Blue Hour crea una atmosfera cinematografica, sofisticada y ligeramente melancolica.",
  ),
  fillStep(
    "Rellena el espacio - Crea con Dramatic Lighting",
    "Completa el prompt con elementos que refuercen tension y poder.",
    "/imagine ___, dramatic lighting, estilo ___, ___, sombras profundas, ___",
    [
      "un guerrero poderoso sosteniendo una espada",
      "arte conceptual de fantasia oscura",
      "una unica fuente de luz direccional",
      "--ar 9:16",
    ],
    [
      "un guerrero poderoso sosteniendo una espada",
      "arte conceptual de fantasia oscura",
      "una unica fuente de luz direccional",
      "--ar 9:16",
    ],
    "Dramatic Lighting gana fuerza cuando una luz clara compite contra grandes zonas de sombra.",
  ),
  quizStep(
    "Que define el Dramatic Lighting",
    "Cual es el elemento visual que define el Dramatic Lighting?",
    [
      "Muchas fuentes de luz distribuidas de forma uniforme por la escena.",
      "Colores vibrantes y saturados en toda la composicion.",
      "El contraste fuerte entre zonas iluminadas y sombras profundas, creando tension visual.",
      "Dramatic Lighting significa simplemente imagenes oscuras sin fuente de luz visible.",
    ],
    2,
    "La base del Dramatic Lighting es el contraste, que dirige la mirada y aumenta la intensidad de la escena.",
  ),
  fillStep(
    "Rellena el espacio - Usa Soft Box",
    "Completa el prompt para una foto de producto limpia y profesional.",
    "/imagine ___, soft box lighting, fondo ___, estilo fotografico ___, ___, ___",
    [
      "un frasco de perfume de lujo con gotas de agua",
      "blanco limpio",
      "producto comercial",
      "ultra detallado",
      "--ar 1:1",
    ],
    [
      "un frasco de perfume de lujo con gotas de agua",
      "blanco limpio",
      "producto comercial",
      "ultra detallado",
      "--ar 1:1",
    ],
    "Soft Box elimina sombras duras y deja el producto limpio, elegante y listo para comunicacion de marca.",
  ),
  fillStep(
    "Rellena el espacio - Crea con Chiaroscuro",
    "Construye el prompt con profundidad artistica historica.",
    "/imagine ___, chiaroscuro lighting, estilo ___, ___, inspirado en ___, ___",
    [
      "un viejo erudito leyendo a la luz de las velas",
      "pintura al oleo",
      "sombras profundas y luz calida de vela",
      "Rembrandt",
      "--ar 9:16",
    ],
    [
      "un viejo erudito leyendo a la luz de las velas",
      "pintura al oleo",
      "sombras profundas y luz calida de vela",
      "Rembrandt",
      "--ar 9:16",
    ],
    "Chiaroscuro lleva la imagen hacia un lenguaje de pintura clasica, con peso historico y profundidad temporal.",
  ),
  fillStep(
    "Rellena el espacio - Crea con Neon Lighting",
    "Completa el prompt para una escena urbana vibrante.",
    "/imagine ___, neon lighting, estilo ___, ___, reflejos de lluvia en calles mojadas, colores ___, ___",
    [
      "una hacker en un callejon futurista",
      "arte digital cyberpunk",
      "entorno urbano nocturno",
      "morado y cian intensos",
      "--ar 9:16",
    ],
    [
      "una hacker en un callejon futurista",
      "arte digital cyberpunk",
      "entorno urbano nocturno",
      "morado y cian intensos",
      "--ar 9:16",
    ],
    "Neon Lighting funciona cuando quieres energia urbana, artificialidad, cultura pop y una atmosfera futurista.",
  ),
  fillStep(
    "Rellena el espacio - Combina iluminaciones",
    "Completa el prompt usando dos iluminaciones al mismo tiempo.",
    "/imagine ___, iluminacion ___ and ___, estilo ___, atmosfera ___, ___",
    [
      "un samurai de pie en un bosque de bambu al atardecer",
      "golden hour",
      "volumetric",
      "fotografia cinematografica",
      "mistica y epica",
      "--ar 16:9",
    ],
    [
      "un samurai de pie en un bosque de bambu al atardecer",
      "golden hour",
      "volumetric",
      "fotografia cinematografica",
      "mistica y epica",
      "--ar 16:9",
    ],
    "Cuando dos iluminaciones se refuerzan, la imagen gana capas atmosfericas que una sola luz no podria crear por si misma.",
  ),
  textStep(
    "Conclusion",
    "La iluminacion es el alma de cualquier imagen en MidJourney. Golden Hour para calidez y nostalgia, Blue Hour para misterio y sofisticacion, Dramatic para poder y tension, Soft Box para limpieza profesional, Chiaroscuro para profundidad artistica, Neon para energia urbana, Volumetric para escala epica y Rim para presencia y separacion.\n\nAhora que entiendes el lenguaje de la luz, tus prompts ya no volveran a ser los mismos. Elige la luz correcta. Cuenta la historia correcta.",
  ),
] as const;
export const MIDJOURNEY_MODULE_2_STEPS_FR = [
  textStep(
    "Comment la lumiere transforme vos images",
    "Bienvenue a nouveau. Dans cette lecon, vous allez comprendre pourquoi la lumiere est l'element le plus puissant et le plus transformateur d'une image MidJourney. La meme scene, le meme personnage et le meme decor peuvent produire des emotions, des atmospheres et un impact visuel totalement differents lorsque la lumiere change.\n\nLes photographes professionnels disent souvent que photographier, c'est ecrire avec la lumiere. Dans MidJourney, c'est egalement vrai: une seule expression de lumiere peut changer tout le ton emotionnel de l'image meme si le reste du prompt reste identique.",
  ),
  fillStep(
    "Completez les blancs - Utilisez Golden Hour",
    "Completez le prompt avec les bons elements.",
    "/imagine ___, golden hour lighting, style ___, tons ___, ___",
    [
      "un couple marchant sur une plage",
      "photographie cinematographique",
      "dores et ambre chaleureux",
      "--ar 16:9",
    ],
    [
      "un couple marchant sur une plage",
      "photographie cinematographique",
      "dores et ambre chaleureux",
      "--ar 16:9",
    ],
    "Golden Hour fonctionne tres bien quand vous cherchez la chaleur, la nostalgie, le romantisme et une beaute naturelle immediate.",
  ),
  fillStep(
    "Completez les blancs - Creez avec Blue Hour",
    "Construisez le prompt avec la bonne atmosphere.",
    "/imagine ___, blue hour lighting, style ___, atmosphere melancolique, tons ___, ___",
    [
      "une silhouette solitaire sur un pont urbain",
      "photographie cinematographique",
      "bleu profond et violet",
      "--ar 16:9",
    ],
    [
      "une silhouette solitaire sur un pont urbain",
      "photographie cinematographique",
      "bleu profond et violet",
      "--ar 16:9",
    ],
    "Blue Hour cree une atmosphere cinematographique, elegante et legerement melancolique.",
  ),
  fillStep(
    "Completez les blancs - Creez avec Dramatic Lighting",
    "Completez le prompt avec des elements qui renforcent tension et puissance.",
    "/imagine ___, dramatic lighting, style ___, ___, ombres profondes, ___",
    [
      "un guerrier puissant tenant une epee",
      "concept art de fantasy sombre",
      "une source unique de lumiere directionnelle",
      "--ar 9:16",
    ],
    [
      "un guerrier puissant tenant une epee",
      "concept art de fantasy sombre",
      "une source unique de lumiere directionnelle",
      "--ar 9:16",
    ],
    "Dramatic Lighting devient plus fort lorsqu'une source lumineuse claire lutte contre de grandes zones d'ombre.",
  ),
  quizStep(
    "Ce qui definit Dramatic Lighting",
    "Quel element visuel definit le Dramatic Lighting?",
    [
      "De nombreuses sources de lumiere reparties uniformement dans la scene.",
      "Des couleurs tres vives et saturees dans toute la composition.",
      "Un contraste fort entre les zones eclairees et les ombres profondes, qui cree une tension visuelle.",
      "Dramatic Lighting signifie simplement une image sombre sans source lumineuse visible.",
    ],
    2,
    "Le coeur du Dramatic Lighting, c'est le contraste. Il dirige le regard et renforce la puissance de la scene.",
  ),
  fillStep(
    "Completez les blancs - Utilisez Soft Box",
    "Completez le prompt pour une image produit propre et professionnelle.",
    "/imagine ___, soft box lighting, fond ___, style photo ___, ___, ___",
    [
      "un flacon de parfum de luxe avec des gouttes d'eau",
      "blanc propre",
      "produit commercial",
      "ultra detaille",
      "--ar 1:1",
    ],
    [
      "un flacon de parfum de luxe avec des gouttes d'eau",
      "blanc propre",
      "produit commercial",
      "ultra detaille",
      "--ar 1:1",
    ],
    "Soft Box supprime les ombres dures et donne au produit une apparence propre, elegante et prete pour la communication de marque.",
  ),
  fillStep(
    "Completez les blancs - Creez avec Chiaroscuro",
    "Construisez le prompt avec une profondeur artistique historique.",
    "/imagine ___, chiaroscuro lighting, style ___, ___, inspire par ___, ___",
    [
      "un vieux savant lisant a la bougie",
      "peinture a l'huile",
      "ombres profondes et lumiere chaude de bougie",
      "Rembrandt",
      "--ar 9:16",
    ],
    [
      "un vieux savant lisant a la bougie",
      "peinture a l'huile",
      "ombres profondes et lumiere chaude de bougie",
      "Rembrandt",
      "--ar 9:16",
    ],
    "Le chiaroscuro rapproche l'image d'un langage pictural classique, avec du poids historique et de la profondeur temporelle.",
  ),
  fillStep(
    "Completez les blancs - Creez avec Neon Lighting",
    "Completez le prompt pour une scene urbaine vibrante.",
    "/imagine ___, neon lighting, style ___, ___, reflets de pluie sur les rues mouillees, couleurs ___, ___",
    [
      "une hackeuse dans une ruelle futuriste",
      "art digital cyberpunk",
      "environnement urbain nocturne",
      "violet et cyan vifs",
      "--ar 9:16",
    ],
    [
      "une hackeuse dans une ruelle futuriste",
      "art digital cyberpunk",
      "environnement urbain nocturne",
      "violet et cyan vifs",
      "--ar 9:16",
    ],
    "Neon Lighting fonctionne quand vous cherchez de l'energie urbaine, de l'artificialite, de la culture pop et une atmosphere futuriste.",
  ),
  fillStep(
    "Completez les blancs - Combinez les lumieres",
    "Completez le prompt en utilisant deux types de lumiere ensemble.",
    "/imagine ___, lumiere ___ and ___, style ___, atmosphere ___, ___",
    [
      "un samourai dans une foret de bambous au crepuscule",
      "golden hour",
      "volumetric",
      "photographie cinematographique",
      "mystique et epique",
      "--ar 16:9",
    ],
    [
      "un samourai dans une foret de bambous au crepuscule",
      "golden hour",
      "volumetric",
      "photographie cinematographique",
      "mystique et epique",
      "--ar 16:9",
    ],
    "Quand deux approches de lumiere se renforcent, l'image gagne des couches d'atmosphere qu'une seule lumiere ne peut pas produire seule.",
  ),
  textStep(
    "Conclusion",
    "La lumiere est l'ame de toute image MidJourney. Golden Hour pour la chaleur et la nostalgie, Blue Hour pour le mystere et la sophistication, Dramatic pour la puissance et la tension, Soft Box pour la clarte professionnelle, Chiaroscuro pour la profondeur artistique, Neon pour l'energie urbaine, Volumetric pour l'echelle epique et Rim pour la presence et la separation.\n\nMaintenant que vous comprenez le langage de la lumiere, vos prompts ne seront plus jamais les memes. Choisissez la bonne lumiere. Racontez la bonne histoire.",
  ),
] as const;
