const textStep = (title: string, content: string, promptBox?: string) => ({
  type: "text" as const,
  title,
  content,
  ...(promptBox ? { promptBox } : {}),
});

const quizStep = (
  title: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
) => ({
  type: "quiz" as const,
  title,
  question,
  options,
  correctIndex,
  explanation,
});

const fillStep = (
  title: string,
  instruction: string,
  sentence: string,
  answers: string[],
  options: string[],
  explanation: string,
) => ({
  type: "fill_blanks" as const,
  title,
  instruction,
  sentence,
  answers,
  options,
  explanation,
});

export const MIDJOURNEY_MODULE_5_STEPS_PT = [
  textStep(
    "Combinando modos no MidJourney - Camadas de intencao no mesmo prompt",
    "Bem-vindo de volta. Nesta licao, voce vai aprender a combinar modos, estilos, iluminacoes, pontos de vista, paletas e parametros no mesmo prompt. A ideia aqui nao e empilhar termos bonitos. E construir uma imagem em camadas, em que cada decisao reforca a anterior e empurra o MidJourney para uma visao muito mais precisa.\n\nIniciantes descrevem o sujeito. Intermediarios adicionam estilo e luz. Avancados combinam multiplas camadas com intencao, criando um resultado que parece pensado por uma direcao criativa inteira, nao por um prompt generico.",
  ),
  fillStep(
    "Preencha a lacuna - Entenda a estrutura",
    "Organize a estrutura logica de um prompt combinado do mais essencial ao mais refinado.",
    "A estrutura ideal de um prompt combinado e: ___ + ___ + ___ + ___ + ___ + ___ + ___.",
    [
      "sujeito e acao",
      "ambiente e contexto",
      "estilo artistico",
      "ponto de vista",
      "iluminacao",
      "paleta de cores",
      "parametros tecnicos",
    ],
    [
      "sujeito e acao",
      "ambiente e contexto",
      "estilo artistico",
      "ponto de vista",
      "iluminacao",
      "paleta de cores",
      "parametros tecnicos",
    ],
    "Cada camada responde a uma pergunta diferente: o que, onde, como, de qual angulo, com qual luz, em quais cores e em qual formato.",
  ),
  textStep(
    "Estilo + iluminacao",
    "A primeira combinacao poderosa e unir um estilo artistico com a iluminacao que melhor amplifica sua estetica. Quando estilo e luz apontam para a mesma atmosfera, o resultado fica muito mais coeso.\n\nPense assim: algumas combinacoes parecem naturais porque compartilham o mesmo universo emocional.",
    "Combinacoes naturais:\ncinematografico + golden hour = epico e cinematografico\npintura a oleo + chiaroscuro = artistico e historico\ncyberpunk + neon = urbano e futurista",
  ),
  fillStep(
    "Preencha a lacuna - Una estilo e iluminacao",
    "Complete o prompt com uma combinacao natural entre estilo, luz, atmosfera e cor.",
    "/imagine ___, estilo ___, iluminacao ___, atmosfera ___, cores ___, ___.",
    [
      "um cavaleiro solitario a cavalo cruzando um campo de batalha enevoado",
      "arte conceitual dark fantasy",
      "volumetrica dourada",
      "epica e dramatica",
      "tons terrosos profundos",
      "--ar 16:9",
    ],
    [
      "um cavaleiro solitario a cavalo cruzando um campo de batalha enevoado",
      "arte conceitual dark fantasy",
      "volumetrica dourada",
      "epica e dramatica",
      "tons terrosos profundos",
      "--ar 16:9",
    ],
    "Quando estilo, luz, atmosfera e cor falam a mesma lingua emocional, a imagem parece muito mais intencional.",
  ),
  fillStep(
    "Preencha a lacuna - Adicione ponto de vista",
    "Complete o prompt combinando ponto de vista, estilo e luz na mesma cena.",
    "/imagine ___, enquadramento ___, estilo ___, iluminacao ___, clima ___, cores ___, ___.",
    [
      "uma astronauta flutuando perto de uma estacao espacial com a Terra visivel ao fundo",
      "low angle worm's eye view",
      "fotografia cinematografica sci-fi",
      "rim light dramatica com fundo de espaco profundo",
      "inspirador e meditativo",
      "azul frio e prata",
      "--ar 9:16",
    ],
    [
      "uma astronauta flutuando perto de uma estacao espacial com a Terra visivel ao fundo",
      "low angle worm's eye view",
      "fotografia cinematografica sci-fi",
      "rim light dramatica com fundo de espaco profundo",
      "inspirador e meditativo",
      "azul frio e prata",
      "--ar 9:16",
    ],
    "Aqui voce ja nao esta so descrevendo um sujeito. Esta dizendo como ele deve ser visto, sentido e enquadrado.",
  ),
  textStep(
    "Referencias artisticas hibridas",
    "Uma das tecnicas mais sofisticadas e combinar duas referencias artisticas diferentes para criar um estilo hibrido. O objetivo nao e parecer estranho. E parecer unico.\n\nA forca dessa abordagem esta em pegar o que cada universo tem de mais reconhecivel e unir isso de forma coerente.",
    "Hibridos fortes:\nfotografia moderna + pintura renascentista\nanime japones + noir ocidental\naquarela classica + flat design moderno",
  ),
  fillStep(
    "Preencha a lacuna - Crie um estilo hibrido",
    "Complete o prompt com duas referencias artisticas que se complementam.",
    "/imagine ___, estilo ___ encontra ___, iluminacao ___, paleta ___, composicao ___, ___.",
    [
      "uma imperatriz poderosa em seu trono",
      "pintura barroca",
      "fotografia editorial moderna",
      "chiaroscuro",
      "ouro intenso e vermelho carmim",
      "simetrica e imponente",
      "--ar 2:3",
    ],
    [
      "uma imperatriz poderosa em seu trono",
      "pintura barroca",
      "fotografia editorial moderna",
      "chiaroscuro",
      "ouro intenso e vermelho carmim",
      "simetrica e imponente",
      "--ar 2:3",
    ],
    "As referencias se tornam originais quando cada uma entrega um valor claro: uma traz heranca visual, a outra traz leitura contemporanea.",
  ),
  textStep(
    "Paleta + mood",
    "Paleta de cores e mood sao dois dos elementos mais importantes para decidir como o espectador vai se sentir diante da imagem. Quando eles estao alinhados, a emocao chega rapido. Quando entram em conflito, a mensagem perde forca.",
    "Combinacoes de paleta e mood:\nazul frio e cinza + melancolico = melancolia sofisticada\namarelo quente e laranja + alegre = energia e otimismo\nroxo profundo e preto + ominoso = misterio e tensao",
  ),
  fillStep(
    "Preencha a lacuna - Una cores e emocao",
    "Complete o prompt alinhando paleta, clima e atmosfera emocional.",
    "/imagine ___, estilo ___, iluminacao ___, paleta ___, clima ___, atmosfera ___, ___.",
    [
      "uma bailarina dancando sozinha em um palco vazio",
      "fotografia fine art",
      "luar azul suave",
      "azul dessaturado e prata",
      "melancolico e etereo",
      "onirica e poetica",
      "--ar 9:16",
    ],
    [
      "uma bailarina dancando sozinha em um palco vazio",
      "fotografia fine art",
      "luar azul suave",
      "azul dessaturado e prata",
      "melancolico e etereo",
      "onirica e poetica",
      "--ar 9:16",
    ],
    "Quando paleta, clima e atmosfera contam a mesma historia, a emocao da imagem chega de forma muito mais imediata.",
  ),
  fillStep(
    "Preencha a lacuna - Crie produto avancado",
    "Complete o prompt de fotografia de produto premium.",
    "/imagine ___, angulo ___, fundo ___, iluminacao ___, estilo ___, detalhe ___, sensacao ___, ___.",
    [
      "um frasco de perfume preto de luxo com detalhes dourados e fumaca ao redor",
      "low angle",
      "superficie de marmore escuro com reflexos sutis",
      "luz dramatica direcional unica com rim light",
      "fotografia editorial comercial",
      "ultra alto 8K",
      "cara, premium e sedutora",
      "--ar 4:5",
    ],
    [
      "um frasco de perfume preto de luxo com detalhes dourados e fumaca ao redor",
      "low angle",
      "superficie de marmore escuro com reflexos sutis",
      "luz dramatica direcional unica com rim light",
      "fotografia editorial comercial",
      "ultra alto 8K",
      "cara, premium e sedutora",
      "--ar 4:5",
    ],
    "Produto premium nasce de contexto visual. Angulo, luz, fundo e estilo criam valor antes mesmo da pessoa saber o preco.",
  ),
  fillStep(
    "Preencha a lacuna - Crie retrato cinematografico",
    "Complete o prompt de retrato com profundidade emocional.",
    "/imagine ___, enquadramento ___, estilo ___, iluminacao ___, fundo ___, expressao ___, clima ___, ___.",
    [
      "um velho pescador de rosto marcado com olhos bondosos",
      "close up eye level",
      "fotografia documental cinematografica",
      "chiaroscuro suave com luz lateral quente",
      "oceano desfocado ao por do sol",
      "digna e contemplativa",
      "profundamente humano e atemporal",
      "--ar 4:5",
    ],
    [
      "um velho pescador de rosto marcado com olhos bondosos",
      "close up eye level",
      "fotografia documental cinematografica",
      "chiaroscuro suave com luz lateral quente",
      "oceano desfocado ao por do sol",
      "digna e contemplativa",
      "profundamente humano e atemporal",
      "--ar 4:5",
    ],
    "Aqui as camadas funcionam juntas para fazer a imagem parecer um retrato vivido, nao apenas bonito.",
  ),
  fillStep(
    "Preencha a lacuna - Crie paisagem epica",
    "Complete o prompt de paisagem com escala e atmosfera.",
    "/imagine ___, enquadramento ___, estilo ___, iluminacao ___, atmosfera ___, cores ___, figura humana ___ para escala, ___.",
    [
      "um glaciar colossal encontrando um oceano artico tempestuoso",
      "wide establishing",
      "fotografia epica de paisagem",
      "blue hour com neblina volumetrica",
      "dramatica e primordial",
      "azul petroleo profundo e branco",
      "em silhueta",
      "--ar 16:9",
    ],
    [
      "um glaciar colossal encontrando um oceano artico tempestuoso",
      "wide establishing",
      "fotografia epica de paisagem",
      "blue hour com neblina volumetrica",
      "dramatica e primordial",
      "azul petroleo profundo e branco",
      "em silhueta",
      "--ar 16:9",
    ],
    "Paisagem epica nao depende so de tamanho. Depende de contraste de escala, atmosfera e leitura emocional.",
  ),
  fillStep(
    "Preencha a lacuna - Monte o prompt definitivo",
    "Complete o prompt que alinha sujeito, ambiente, estilo, luz, paleta, clima e atmosfera.",
    "/imagine ___, em ___, enquadramento ___, estilo ___, iluminacao ___, paleta ___, clima ___, atmosfera ___, ___.",
    [
      "um samurai solitario meditando",
      "uma antiga floresta de bambu ao amanhecer com neblina matinal",
      "low angle",
      "fotografia dark fantasy cinematografica com ukiyo-e",
      "volumetrica dourada com rim light",
      "verde suave, dourado e preto",
      "profundamente espiritual e poderoso",
      "atemporal e epica",
      "--ar 9:16",
    ],
    [
      "um samurai solitario meditando",
      "uma antiga floresta de bambu ao amanhecer com neblina matinal",
      "low angle",
      "fotografia dark fantasy cinematografica com ukiyo-e",
      "volumetrica dourada com rim light",
      "verde suave, dourado e preto",
      "profundamente espiritual e poderoso",
      "atemporal e epica",
      "--ar 9:16",
    ],
    "Esse tipo de prompt funciona porque todas as camadas estao alinhadas. Nada esta sobrando. Nada esta competindo.",
  ),
  fillStep(
    "Preencha a lacuna - Evite os erros",
    "Complete a frase com os erros mais comuns ao combinar modos.",
    "Os erros mais comuns ao combinar modos sao: misturar estilos ___ que se contradizem, usar iluminacao ___ com o estilo escolhido, combinar paleta e clima ___, adicionar elementos ___ sem proposito claro e ___ elementos ate criar ambiguidade visual.",
    [
      "incompativeis",
      "incoerente",
      "conflitantes",
      "desnecessarios",
      "acumular",
    ],
    [
      "incompativeis",
      "incoerente",
      "conflitantes",
      "desnecessarios",
      "acumular",
    ],
    "O problema nao e ter varias camadas. O problema e ter varias camadas puxando para direcoes diferentes.",
  ),
  textStep(
    "Conclusao",
    "Combinar modos e a habilidade que transforma o MidJourney de um gerador de imagens em um estudio criativo. Estilo com iluminacao, ponto de vista com mood, paleta com atmosfera, referencias artisticas hibridas e todas as camadas unidas em um unico prompt com intencao clara criam possibilidades que nenhum elemento isolado conseguiria produzir.\n\nO segredo nao e usar mais elementos. E usar os elementos certos, na ordem certa, reforcando a mesma ideia visual do inicio ao fim.",
  ),
] as const;

export const MIDJOURNEY_MODULE_5_STEPS_EN = [
  textStep(
    "Combining modes in MidJourney - Building images with layered intent",
    "Welcome back. In this lesson, you will learn how to combine modes, styles, lighting, point of view, palettes, and parameters inside the same prompt. The goal is not to stack impressive words. The goal is to build an image in layers, where each choice reinforces the previous one and pushes MidJourney toward a much more precise vision.\n\nBeginners describe the subject. Intermediate users add style and light. Advanced users combine multiple layers with intent, creating results that feel directed instead of generic.",
  ),
  fillStep(
    "Fill in the blanks - Understand the structure",
    "Organize the logical structure of a layered prompt from essential to refined.",
    "The ideal structure of a combined prompt is: ___ + ___ + ___ + ___ + ___ + ___ + ___.",
    [
      "subject and action",
      "environment and context",
      "artistic style",
      "point of view",
      "lighting",
      "color palette",
      "technical parameters",
    ],
    [
      "subject and action",
      "environment and context",
      "artistic style",
      "point of view",
      "lighting",
      "color palette",
      "technical parameters",
    ],
    "Each layer answers a different question: what, where, how, from which angle, with what light, in which colors, and in what format.",
  ),
  textStep(
    "Style + lighting",
    "The first powerful combination is pairing an artistic style with the type of lighting that best amplifies its aesthetic. When style and light point toward the same atmosphere, the result becomes much more cohesive.\n\nSome combinations feel natural because they share the same emotional universe.",
    "Natural combinations:\ncinematic + golden hour = epic and cinematic\noil painting + chiaroscuro = artistic and historical\ncyberpunk + neon = urban and futuristic",
  ),
  fillStep(
    "Fill in the blanks - Match style and lighting",
    "Complete the prompt with a natural combination of style, light, atmosphere, and color.",
    "/imagine ___, ___ style, ___ lighting, ___ atmosphere, ___ colors, ___.",
    [
      "a lone knight on a horse crossing a misty battlefield",
      "dark fantasy concept art",
      "volumetric golden",
      "epic and dramatic",
      "deep earthy tones",
      "--ar 16:9",
    ],
    [
      "a lone knight on a horse crossing a misty battlefield",
      "dark fantasy concept art",
      "volumetric golden",
      "epic and dramatic",
      "deep earthy tones",
      "--ar 16:9",
    ],
    "When style, light, atmosphere, and color all push in the same emotional direction, the image feels far more intentional.",
  ),
  fillStep(
    "Fill in the blanks - Add point of view",
    "Complete the prompt by combining viewpoint, style, and lighting in one scene.",
    "/imagine ___, ___ shot, ___ style, ___ lighting, ___ mood, ___ colors, ___.",
    [
      "a female astronaut floating near a space station with Earth visible below",
      "low angle worm's eye view",
      "cinematic sci-fi photography",
      "dramatic rim with deep space background",
      "awe-inspiring and meditative",
      "cool blue and silver",
      "--ar 9:16",
    ],
    [
      "a female astronaut floating near a space station with Earth visible below",
      "low angle worm's eye view",
      "cinematic sci-fi photography",
      "dramatic rim with deep space background",
      "awe-inspiring and meditative",
      "cool blue and silver",
      "--ar 9:16",
    ],
    "At this point you are no longer only describing a subject. You are directing how it must be seen, felt, and framed.",
  ),
  textStep(
    "Hybrid artistic references",
    "One of the most sophisticated techniques is combining two artistic references to create a hybrid visual language. The goal is not to feel random. The goal is to feel unique.\n\nThe power of this approach comes from taking the most recognizable strength of each universe and merging them coherently.",
    "Strong hybrids:\nmodern photography + Renaissance painting\nanime + western noir\nclassic watercolor + modern flat design",
  ),
  fillStep(
    "Fill in the blanks - Create a hybrid style",
    "Complete the prompt with two complementary artistic references.",
    "/imagine ___, ___ meets ___ style, ___ lighting, ___ color palette, ___ composition, ___.",
    [
      "a powerful empress on her throne",
      "Baroque painting",
      "modern editorial photography",
      "chiaroscuro",
      "rich gold and deep crimson",
      "symmetrical and regal",
      "--ar 2:3",
    ],
    [
      "a powerful empress on her throne",
      "Baroque painting",
      "modern editorial photography",
      "chiaroscuro",
      "rich gold and deep crimson",
      "symmetrical and regal",
      "--ar 2:3",
    ],
    "References become original when each one contributes a clear value: one brings historical weight, the other brings contemporary readability.",
  ),
  textStep(
    "Palette + mood",
    "Color palette and mood are two of the strongest elements for deciding how the viewer will feel in front of the image. When they align, emotion lands quickly. When they clash, the message loses force.",
    "Palette and mood pairings:\ncool blue and grey + melancholic = sophisticated melancholy\nwarm yellow and orange + joyful = energy and optimism\ndeep purple and black + ominous = mystery and tension",
  ),
  fillStep(
    "Fill in the blanks - Join color and emotion",
    "Complete the prompt by aligning palette, mood, and atmosphere.",
    "/imagine ___, ___ style, ___ lighting, ___ color palette, ___ mood, ___ atmosphere, ___.",
    [
      "a ballerina dancing alone on an empty stage",
      "fine art photography",
      "soft blue moonlight",
      "desaturated blue and silver",
      "melancholic and ethereal",
      "dreamlike and poetic",
      "--ar 9:16",
    ],
    [
      "a ballerina dancing alone on an empty stage",
      "fine art photography",
      "soft blue moonlight",
      "desaturated blue and silver",
      "melancholic and ethereal",
      "dreamlike and poetic",
      "--ar 9:16",
    ],
    "When palette, mood, and atmosphere tell the same story, emotion reaches the viewer much faster.",
  ),
  fillStep(
    "Fill in the blanks - Create advanced product imagery",
    "Complete the premium product photography prompt.",
    "/imagine ___, ___ angle, ___ background, ___ lighting, ___ style, ___ detail, ___ feel, ___.",
    [
      "a luxury black perfume bottle with gold details and smoke around it",
      "low angle",
      "dark marble surface with subtle reflections",
      "dramatic single directional with rim light",
      "commercial editorial photography",
      "ultra high 8K",
      "expensive premium and seductive",
      "--ar 4:5",
    ],
    [
      "a luxury black perfume bottle with gold details and smoke around it",
      "low angle",
      "dark marble surface with subtle reflections",
      "dramatic single directional with rim light",
      "commercial editorial photography",
      "ultra high 8K",
      "expensive premium and seductive",
      "--ar 4:5",
    ],
    "Premium product perception starts in context. Angle, light, background, and style create value before the viewer even knows the price.",
  ),
  fillStep(
    "Fill in the blanks - Create a cinematic portrait",
    "Complete the portrait prompt with emotional depth.",
    "/imagine ___, ___ shot, ___ style, ___ lighting, ___ background, ___ expression, ___ mood, ___.",
    [
      "a weathered old fisherman with deep wrinkles and kind eyes",
      "close up eye level",
      "cinematic documentary photography",
      "soft chiaroscuro with warm side light",
      "blurred ocean at sunset",
      "dignified and contemplative",
      "deeply human and timeless",
      "--ar 4:5",
    ],
    [
      "a weathered old fisherman with deep wrinkles and kind eyes",
      "close up eye level",
      "cinematic documentary photography",
      "soft chiaroscuro with warm side light",
      "blurred ocean at sunset",
      "dignified and contemplative",
      "deeply human and timeless",
      "--ar 4:5",
    ],
    "Here the layers work together to make the image feel lived-in, not merely attractive.",
  ),
  fillStep(
    "Fill in the blanks - Create an epic landscape",
    "Complete the landscape prompt with scale and atmosphere.",
    "/imagine ___, ___ shot, ___ style, ___ lighting, ___ atmosphere, ___ colors, ___ tiny human figure for scale, ___.",
    [
      "a massive glacier meeting a stormy arctic ocean",
      "wide establishing",
      "epic landscape photography",
      "blue hour with volumetric mist",
      "dramatic and primordial",
      "deep teal blue and white",
      "silhouetted",
      "--ar 16:9",
    ],
    [
      "a massive glacier meeting a stormy arctic ocean",
      "wide establishing",
      "epic landscape photography",
      "blue hour with volumetric mist",
      "dramatic and primordial",
      "deep teal blue and white",
      "silhouetted",
      "--ar 16:9",
    ],
    "Epic landscape work is not only about size. It is about scale contrast, atmosphere, and emotional framing.",
  ),
  fillStep(
    "Fill in the blanks - Build the definitive prompt",
    "Complete the prompt that aligns subject, environment, style, light, palette, mood, and atmosphere.",
    "/imagine ___, in ___, ___ shot, ___ style, ___ lighting, ___ palette, ___ mood, ___ atmosphere, ___.",
    [
      "a lone samurai meditating",
      "an ancient bamboo forest at dawn with morning mist",
      "low angle",
      "dark fantasy cinematic photography meets ukiyo-e art",
      "volumetric golden with rim light",
      "muted green gold and black",
      "deeply spiritual and powerful",
      "timeless and epic",
      "--ar 9:16",
    ],
    [
      "a lone samurai meditating",
      "an ancient bamboo forest at dawn with morning mist",
      "low angle",
      "dark fantasy cinematic photography meets ukiyo-e art",
      "volumetric golden with rim light",
      "muted green gold and black",
      "deeply spiritual and powerful",
      "timeless and epic",
      "--ar 9:16",
    ],
    "This kind of prompt works because all layers align. Nothing feels wasted. Nothing competes with the main idea.",
  ),
  fillStep(
    "Fill in the blanks - Avoid the mistakes",
    "Complete the sentence with the most common mistakes when combining modes.",
    "The most common mistakes when combining modes are: mixing ___ styles that contradict each other, using ___ lighting with the chosen style, pairing palette and mood that are ___, adding ___ elements without clear purpose, and ___ elements until visual ambiguity appears.",
    [
      "incompatible",
      "incoherent",
      "conflicting",
      "unnecessary",
      "accumulating",
    ],
    [
      "incompatible",
      "incoherent",
      "conflicting",
      "unnecessary",
      "accumulating",
    ],
    "The issue is not having many layers. The issue is having many layers pulling in different directions.",
  ),
  textStep(
    "Conclusion",
    "Combining modes is the skill that turns MidJourney from an image generator into a creative studio. Style with lighting, point of view with mood, palette with atmosphere, hybrid artistic references, and all layers unified inside one clear prompt create possibilities that no isolated element could produce.\n\nThe secret is not using more elements. The secret is using the right elements in the right order, reinforcing the same visual idea from start to finish.",
  ),
] as const;

export const MIDJOURNEY_MODULE_5_STEPS_ES = [
  textStep(
    "Combinar modos en MidJourney - Construir imagenes con capas de intencion",
    "Bienvenido de nuevo. En esta leccion vas a aprender a combinar modos, estilos, iluminaciones, puntos de vista, paletas y parametros dentro del mismo prompt. La idea no es acumular palabras llamativas. La idea es construir una imagen por capas, donde cada decision refuerza la anterior y empuja a MidJourney hacia una vision mucho mas precisa.\n\nLos principiantes describen el sujeto. Los intermedios agregan estilo y luz. Los avanzados combinan multiples capas con intencion y consiguen resultados dirigidos, no genericos.",
  ),
  fillStep(
    "Completa los espacios - Entiende la estructura",
    "Organiza la estructura logica de un prompt por capas desde lo esencial hasta lo refinado.",
    "La estructura ideal de un prompt combinado es: ___ + ___ + ___ + ___ + ___ + ___ + ___.",
    [
      "sujeto y accion",
      "ambiente y contexto",
      "estilo artistico",
      "punto de vista",
      "iluminacion",
      "paleta de colores",
      "parametros tecnicos",
    ],
    [
      "sujeto y accion",
      "ambiente y contexto",
      "estilo artistico",
      "punto de vista",
      "iluminacion",
      "paleta de colores",
      "parametros tecnicos",
    ],
    "Cada capa responde una pregunta distinta: que, donde, como, desde que angulo, con que luz, en que colores y en que formato.",
  ),
  textStep(
    "Estilo + iluminacion",
    "La primera combinacion poderosa es unir un estilo artistico con el tipo de luz que mejor potencia su estetica. Cuando estilo y luz apuntan a la misma atmosfera, el resultado se vuelve mucho mas coherente.\n\nAlgunas combinaciones parecen naturales porque comparten el mismo universo emocional.",
    "Combinaciones naturales:\ncinematic + golden hour = epico y cinematografico\noil painting + chiaroscuro = artistico e historico\ncyberpunk + neon = urbano y futurista",
  ),
  fillStep(
    "Completa los espacios - Une estilo e iluminacion",
    "Completa el prompt con una combinacion natural de estilo, luz, atmosfera y color.",
    "/imagine ___, estilo ___, iluminacion ___, atmosfera ___, colores ___, ___.",
    [
      "un caballero solitario a caballo cruzando un campo de batalla con niebla",
      "arte conceptual dark fantasy",
      "volumetrica dorada",
      "epica y dramatica",
      "tonos terrosos profundos",
      "--ar 16:9",
    ],
    [
      "un caballero solitario a caballo cruzando un campo de batalla con niebla",
      "arte conceptual dark fantasy",
      "volumetrica dorada",
      "epica y dramatica",
      "tonos terrosos profundos",
      "--ar 16:9",
    ],
    "Cuando estilo, luz, atmosfera y color empujan en la misma direccion emocional, la imagen se siente mucho mas intencional.",
  ),
  fillStep(
    "Completa los espacios - Agrega punto de vista",
    "Completa el prompt combinando punto de vista, estilo e iluminacion.",
    "/imagine ___, encuadre ___, estilo ___, iluminacion ___, mood ___, colores ___, ___.",
    [
      "una astronauta flotando cerca de una estacion espacial con la Tierra visible abajo",
      "low angle worm's eye view",
      "fotografia cinematografica sci-fi",
      "rim light dramatica con fondo de espacio profundo",
      "inspirador y meditativo",
      "azul frio y plata",
      "--ar 9:16",
    ],
    [
      "una astronauta flotando cerca de una estacion espacial con la Tierra visible abajo",
      "low angle worm's eye view",
      "fotografia cinematografica sci-fi",
      "rim light dramatica con fondo de espacio profundo",
      "inspirador y meditativo",
      "azul frio y plata",
      "--ar 9:16",
    ],
    "Aqui ya no solo describes un sujeto. Estas dirigiendo como debe verse, sentirse y encuadrarse.",
  ),
  textStep(
    "Referencias artisticas hibridas",
    "Una de las tecnicas mas sofisticadas es combinar dos referencias artisticas para crear un lenguaje visual hibrido. El objetivo no es verse aleatorio. El objetivo es verse unico.\n\nLa fuerza de este enfoque nace de tomar lo mas reconocible de cada universo y mezclarlo con coherencia.",
    "Hibridos potentes:\nfotografia moderna + pintura renacentista\nanime + noir occidental\nacuarela clasica + flat design moderno",
  ),
  fillStep(
    "Completa los espacios - Crea un estilo hibrido",
    "Completa el prompt con dos referencias artisticas complementarias.",
    "/imagine ___, estilo ___ encuentra ___, iluminacion ___, paleta ___, composicion ___, ___.",
    [
      "una emperatriz poderosa en su trono",
      "pintura barroca",
      "fotografia editorial moderna",
      "chiaroscuro",
      "oro intenso y rojo carmesi",
      "simetrica y regia",
      "--ar 2:3",
    ],
    [
      "una emperatriz poderosa en su trono",
      "pintura barroca",
      "fotografia editorial moderna",
      "chiaroscuro",
      "oro intenso y rojo carmesi",
      "simetrica y regia",
      "--ar 2:3",
    ],
    "Las referencias se vuelven originales cuando cada una aporta un valor claro: una da peso historico y la otra legibilidad contemporanea.",
  ),
  textStep(
    "Paleta + mood",
    "La paleta de color y el mood son dos de los elementos mas fuertes para decidir como se va a sentir el espectador frente a la imagen. Cuando se alinean, la emocion llega rapido. Cuando chocan, el mensaje pierde fuerza.",
    "Parejas de paleta y mood:\nazul frio y gris + melancolico = melancolia sofisticada\namarillo calido y naranja + alegre = energia y optimismo\nmorado profundo y negro + ominoso = misterio y tension",
  ),
  fillStep(
    "Completa los espacios - Une color y emocion",
    "Completa el prompt alineando paleta, mood y atmosfera.",
    "/imagine ___, estilo ___, iluminacion ___, paleta ___, mood ___, atmosfera ___, ___.",
    [
      "una bailarina bailando sola sobre un escenario vacio",
      "fotografia fine art",
      "luz de luna azul suave",
      "azul desaturado y plata",
      "melancolico y etereo",
      "onirica y poetica",
      "--ar 9:16",
    ],
    [
      "una bailarina bailando sola sobre un escenario vacio",
      "fotografia fine art",
      "luz de luna azul suave",
      "azul desaturado y plata",
      "melancolico y etereo",
      "onirica y poetica",
      "--ar 9:16",
    ],
    "Cuando paleta, mood y atmosfera cuentan la misma historia, la emocion llega al espectador mucho mas rapido.",
  ),
  fillStep(
    "Completa los espacios - Crea producto avanzado",
    "Completa el prompt de fotografia premium de producto.",
    "/imagine ___, angulo ___, fondo ___, iluminacion ___, estilo ___, detalle ___, sensacion ___, ___.",
    [
      "un frasco de perfume negro de lujo con detalles dorados y humo alrededor",
      "low angle",
      "superficie de marmol oscuro con reflejos sutiles",
      "luz dramatica direccional unica con rim light",
      "fotografia editorial comercial",
      "ultra alto 8K",
      "cara, premium y seductora",
      "--ar 4:5",
    ],
    [
      "un frasco de perfume negro de lujo con detalles dorados y humo alrededor",
      "low angle",
      "superficie de marmol oscuro con reflejos sutiles",
      "luz dramatica direccional unica con rim light",
      "fotografia editorial comercial",
      "ultra alto 8K",
      "cara, premium y seductora",
      "--ar 4:5",
    ],
    "La percepcion premium del producto empieza en el contexto. Angulo, luz, fondo y estilo crean valor antes de conocer el precio.",
  ),
  fillStep(
    "Completa los espacios - Crea retrato cinematografico",
    "Completa el prompt de retrato con profundidad emocional.",
    "/imagine ___, encuadre ___, estilo ___, iluminacion ___, fondo ___, expresion ___, mood ___, ___.",
    [
      "un viejo pescador de rostro marcado con ojos bondadosos",
      "close up eye level",
      "fotografia documental cinematografica",
      "chiaroscuro suave con luz lateral calida",
      "oceano desenfocado al atardecer",
      "digna y contemplativa",
      "profundamente humano y atemporal",
      "--ar 4:5",
    ],
    [
      "un viejo pescador de rostro marcado con ojos bondadosos",
      "close up eye level",
      "fotografia documental cinematografica",
      "chiaroscuro suave con luz lateral calida",
      "oceano desenfocado al atardecer",
      "digna y contemplativa",
      "profundamente humano y atemporal",
      "--ar 4:5",
    ],
    "Aqui las capas trabajan juntas para que la imagen se sienta vivida, no solo bonita.",
  ),
  fillStep(
    "Completa los espacios - Crea paisaje epico",
    "Completa el prompt de paisaje con escala y atmosfera.",
    "/imagine ___, encuadre ___, estilo ___, iluminacion ___, atmosfera ___, colores ___, figura humana ___ para escala, ___.",
    [
      "un glaciar colosal encontrandose con un oceano artico tormentoso",
      "wide establishing",
      "fotografia epica de paisaje",
      "blue hour con niebla volumetrica",
      "dramatica y primordial",
      "azul petroleo profundo y blanco",
      "en silueta",
      "--ar 16:9",
    ],
    [
      "un glaciar colosal encontrandose con un oceano artico tormentoso",
      "wide establishing",
      "fotografia epica de paisaje",
      "blue hour con niebla volumetrica",
      "dramatica y primordial",
      "azul petroleo profundo y blanco",
      "en silueta",
      "--ar 16:9",
    ],
    "El paisaje epico no depende solo del tamano. Depende del contraste de escala, de la atmosfera y del encuadre emocional.",
  ),
  fillStep(
    "Completa los espacios - Construye el prompt definitivo",
    "Completa el prompt que alinea sujeto, ambiente, estilo, luz, paleta, mood y atmosfera.",
    "/imagine ___, en ___, encuadre ___, estilo ___, iluminacion ___, paleta ___, mood ___, atmosfera ___, ___.",
    [
      "un samurai solitario meditando",
      "un antiguo bosque de bambu al amanecer con niebla matinal",
      "low angle",
      "fotografia dark fantasy cinematografica con ukiyo-e",
      "volumetrica dorada con rim light",
      "verde suave, dorado y negro",
      "profundamente espiritual y poderoso",
      "atemporal y epica",
      "--ar 9:16",
    ],
    [
      "un samurai solitario meditando",
      "un antiguo bosque de bambu al amanecer con niebla matinal",
      "low angle",
      "fotografia dark fantasy cinematografica con ukiyo-e",
      "volumetrica dorada con rim light",
      "verde suave, dorado y negro",
      "profundamente espiritual y poderoso",
      "atemporal y epica",
      "--ar 9:16",
    ],
    "Este tipo de prompt funciona porque todas las capas estan alineadas. Nada sobra. Nada compite.",
  ),
  fillStep(
    "Completa los espacios - Evita los errores",
    "Completa la frase con los errores mas comunes al combinar modos.",
    "Los errores mas comunes al combinar modos son: mezclar estilos ___ que se contradicen, usar iluminacion ___ con el estilo elegido, combinar paleta y mood ___, agregar elementos ___ sin un proposito claro y ___ elementos hasta crear ambiguedad visual.",
    [
      "incompatibles",
      "incoherente",
      "conflictivos",
      "innecesarios",
      "acumular",
    ],
    [
      "incompatibles",
      "incoherente",
      "conflictivos",
      "innecesarios",
      "acumular",
    ],
    "El problema no es tener muchas capas. El problema es tener muchas capas tirando hacia direcciones distintas.",
  ),
  textStep(
    "Conclusion",
    "Combinar modos es la habilidad que convierte MidJourney de generador de imagenes en estudio creativo. Estilo con iluminacion, punto de vista con mood, paleta con atmosfera, referencias artisticas hibridas y todas las capas reunidas en un solo prompt claro abren posibilidades que ningun elemento aislado podria producir.\n\nEl secreto no es usar mas elementos. El secreto es usar los elementos correctos, en el orden correcto, reforzando la misma idea visual de principio a fin.",
  ),
] as const;

export const MIDJOURNEY_MODULE_5_STEPS_FR = [
  textStep(
    "Combiner les modes dans MidJourney - Construire des images en couches d'intention",
    "Bon retour. Dans cette lecon, tu vas apprendre a combiner modes, styles, lumieres, points de vue, palettes et parametres dans un seul prompt. L'objectif n'est pas d'empiler des mots impressionnants. L'objectif est de construire une image par couches, ou chaque decision renforce la precedente et pousse MidJourney vers une vision beaucoup plus precise.\n\nLes debutants decrivent le sujet. Les intermediaires ajoutent style et lumiere. Les avances combinent plusieurs couches avec intention et obtiennent un resultat dirige, pas generique.",
  ),
  fillStep(
    "Complete les blancs - Comprends la structure",
    "Organise la structure logique d'un prompt en couches du plus essentiel au plus raffine.",
    "La structure ideale d'un prompt combine est : ___ + ___ + ___ + ___ + ___ + ___ + ___.",
    [
      "sujet et action",
      "environnement et contexte",
      "style artistique",
      "point de vue",
      "eclairage",
      "palette de couleurs",
      "parametres techniques",
    ],
    [
      "sujet et action",
      "environnement et contexte",
      "style artistique",
      "point de vue",
      "eclairage",
      "palette de couleurs",
      "parametres techniques",
    ],
    "Chaque couche repond a une question differente : quoi, ou, comment, sous quel angle, avec quelle lumiere, dans quelles couleurs et dans quel format.",
  ),
  textStep(
    "Style + lumiere",
    "La premiere combinaison puissante consiste a associer un style artistique au type de lumiere qui renforce le mieux son esthetique. Quand style et lumiere poussent vers la meme atmosphere, le resultat devient beaucoup plus coherent.\n\nCertaines associations paraissent naturelles parce qu'elles partagent le meme univers emotionnel.",
    "Associations naturelles :\ncinematic + golden hour = epique et cinematographique\noil painting + chiaroscuro = artistique et historique\ncyberpunk + neon = urbain et futuriste",
  ),
  fillStep(
    "Complete les blancs - Associe style et lumiere",
    "Complete le prompt avec une combinaison naturelle de style, lumiere, atmosphere et couleur.",
    "/imagine ___, style ___, eclairage ___, atmosphere ___, couleurs ___, ___.",
    [
      "un chevalier solitaire a cheval traversant un champ de bataille brumeux",
      "art conceptuel dark fantasy",
      "volumetrique doree",
      "epique et dramatique",
      "tons terreux profonds",
      "--ar 16:9",
    ],
    [
      "un chevalier solitaire a cheval traversant un champ de bataille brumeux",
      "art conceptuel dark fantasy",
      "volumetrique doree",
      "epique et dramatique",
      "tons terreux profonds",
      "--ar 16:9",
    ],
    "Quand style, lumiere, atmosphere et couleur avancent dans la meme direction emotionnelle, l'image parait beaucoup plus intentionnelle.",
  ),
  fillStep(
    "Complete les blancs - Ajoute le point de vue",
    "Complete le prompt en combinant point de vue, style et lumiere.",
    "/imagine ___, cadrage ___, style ___, eclairage ___, mood ___, couleurs ___, ___.",
    [
      "une astronaute flottant pres d'une station spatiale avec la Terre visible en dessous",
      "low angle worm's eye view",
      "photographie cinematographique sci-fi",
      "rim light dramatique avec fond d'espace profond",
      "inspirant et meditatif",
      "bleu froid et argent",
      "--ar 9:16",
    ],
    [
      "une astronaute flottant pres d'une station spatiale avec la Terre visible en dessous",
      "low angle worm's eye view",
      "photographie cinematographique sci-fi",
      "rim light dramatique avec fond d'espace profond",
      "inspirant et meditatif",
      "bleu froid et argent",
      "--ar 9:16",
    ],
    "A ce stade, tu ne decris plus seulement un sujet. Tu diriges la facon dont il doit etre vu, ressenti et cadre.",
  ),
  textStep(
    "References artistiques hybrides",
    "L'une des techniques les plus sophistiquees consiste a combiner deux references artistiques pour creer un langage visuel hybride. L'objectif n'est pas de paraitre aleatoire. L'objectif est de paraitre unique.\n\nLa force de cette approche vient du fait qu'on prend ce qu'il y a de plus reconnaissable dans chaque univers et qu'on le fusionne de facon coherente.",
    "Hybrides puissants :\nphotographie moderne + peinture de la Renaissance\nanime + noir occidental\naquarelle classique + flat design moderne",
  ),
  fillStep(
    "Complete les blancs - Cree un style hybride",
    "Complete le prompt avec deux references artistiques complementaires.",
    "/imagine ___, style ___ rencontre ___, eclairage ___, palette ___, composition ___, ___.",
    [
      "une imperatrice puissante sur son trone",
      "peinture baroque",
      "photographie editoriale moderne",
      "chiaroscuro",
      "or intense et rouge cramoisi",
      "symetrique et royale",
      "--ar 2:3",
    ],
    [
      "une imperatrice puissante sur son trone",
      "peinture baroque",
      "photographie editoriale moderne",
      "chiaroscuro",
      "or intense et rouge cramoisi",
      "symetrique et royale",
      "--ar 2:3",
    ],
    "Les references deviennent originales quand chacune apporte une valeur claire : l'une apporte le poids historique, l'autre une lecture contemporaine.",
  ),
  textStep(
    "Palette + mood",
    "La palette de couleurs et le mood sont deux des elements les plus forts pour decider de ce que le spectateur va ressentir face a l'image. Lorsqu'ils sont alignes, l'emotion arrive vite. Lorsqu'ils s'opposent, le message perd de sa force.",
    "Associations palette et mood :\nbleu froid et gris + melancolique = melancolie sophistiquee\njaune chaud et orange + joyeux = energie et optimisme\nviolet profond et noir + ominous = mystere et tension",
  ),
  fillStep(
    "Complete les blancs - Relie couleur et emotion",
    "Complete le prompt en alignant palette, mood et atmosphere.",
    "/imagine ___, style ___, eclairage ___, palette ___, mood ___, atmosphere ___, ___.",
    [
      "une ballerine dansant seule sur une scene vide",
      "photographie fine art",
      "clair de lune bleu doux",
      "bleu desature et argent",
      "melancolique et ethere",
      "onirique et poetique",
      "--ar 9:16",
    ],
    [
      "une ballerine dansant seule sur une scene vide",
      "photographie fine art",
      "clair de lune bleu doux",
      "bleu desature et argent",
      "melancolique et ethere",
      "onirique et poetique",
      "--ar 9:16",
    ],
    "Quand palette, mood et atmosphere racontent la meme histoire, l'emotion atteint le spectateur beaucoup plus vite.",
  ),
  fillStep(
    "Complete les blancs - Cree un produit avance",
    "Complete le prompt de photographie premium de produit.",
    "/imagine ___, angle ___, fond ___, eclairage ___, style ___, detail ___, sensation ___, ___.",
    [
      "un flacon de parfum noir de luxe avec des details dores et de la fumee autour",
      "low angle",
      "surface de marbre sombre avec reflets subtils",
      "lumiere dramatique directionnelle unique avec rim light",
      "photographie editoriale commerciale",
      "ultra haute 8K",
      "chere, premium et seduisante",
      "--ar 4:5",
    ],
    [
      "un flacon de parfum noir de luxe avec des details dores et de la fumee autour",
      "low angle",
      "surface de marbre sombre avec reflets subtils",
      "lumiere dramatique directionnelle unique avec rim light",
      "photographie editoriale commerciale",
      "ultra haute 8K",
      "chere, premium et seduisante",
      "--ar 4:5",
    ],
    "La perception premium d'un produit commence dans son contexte visuel. Angle, lumiere, fond et style creent de la valeur avant meme de connaitre le prix.",
  ),
  fillStep(
    "Complete les blancs - Cree un portrait cinematographique",
    "Complete le prompt de portrait avec profondeur emotionnelle.",
    "/imagine ___, cadrage ___, style ___, eclairage ___, fond ___, expression ___, mood ___, ___.",
    [
      "un vieux pecheur au visage marque avec des yeux bienveillants",
      "close up eye level",
      "photographie documentaire cinematographique",
      "chiaroscuro doux avec lumiere laterale chaude",
      "ocean flou au coucher du soleil",
      "digne et contemplative",
      "profondement humain et intemporel",
      "--ar 4:5",
    ],
    [
      "un vieux pecheur au visage marque avec des yeux bienveillants",
      "close up eye level",
      "photographie documentaire cinematographique",
      "chiaroscuro doux avec lumiere laterale chaude",
      "ocean flou au coucher du soleil",
      "digne et contemplative",
      "profondement humain et intemporel",
      "--ar 4:5",
    ],
    "Ici, les couches travaillent ensemble pour que l'image paraisse vecue, pas seulement jolie.",
  ),
  fillStep(
    "Complete les blancs - Cree un paysage epique",
    "Complete le prompt de paysage avec echelle et atmosphere.",
    "/imagine ___, cadrage ___, style ___, eclairage ___, atmosphere ___, couleurs ___, figure humaine ___ pour l'echelle, ___.",
    [
      "un glacier colossal rencontrant un ocean arctique tempetueux",
      "wide establishing",
      "photographie epique de paysage",
      "blue hour avec brume volumetrique",
      "dramatique et primordiale",
      "bleu petrolier profond et blanc",
      "en silhouette",
      "--ar 16:9",
    ],
    [
      "un glacier colossal rencontrant un ocean arctique tempetueux",
      "wide establishing",
      "photographie epique de paysage",
      "blue hour avec brume volumetrique",
      "dramatique et primordiale",
      "bleu petrolier profond et blanc",
      "en silhouette",
      "--ar 16:9",
    ],
    "Le paysage epique ne depend pas seulement de la taille. Il depend du contraste d'echelle, de l'atmosphere et du cadrage emotionnel.",
  ),
  fillStep(
    "Complete les blancs - Construis le prompt definitif",
    "Complete le prompt qui aligne sujet, environnement, style, lumiere, palette, mood et atmosphere.",
    "/imagine ___, dans ___, cadrage ___, style ___, eclairage ___, palette ___, mood ___, atmosphere ___, ___.",
    [
      "un samourai solitaire en meditation",
      "une ancienne foret de bambous a l'aube avec brume matinale",
      "low angle",
      "photographie dark fantasy cinematographique avec ukiyo-e",
      "volumetrique doree avec rim light",
      "vert doux, or et noir",
      "profondement spirituel et puissant",
      "intemporelle et epique",
      "--ar 9:16",
    ],
    [
      "un samourai solitaire en meditation",
      "une ancienne foret de bambous a l'aube avec brume matinale",
      "low angle",
      "photographie dark fantasy cinematographique avec ukiyo-e",
      "volumetrique doree avec rim light",
      "vert doux, or et noir",
      "profondement spirituel et puissant",
      "intemporelle et epique",
      "--ar 9:16",
    ],
    "Ce type de prompt fonctionne parce que toutes les couches sont alignees. Rien n'est de trop. Rien ne se bat contre l'idee centrale.",
  ),
  fillStep(
    "Complete les blancs - Evite les erreurs",
    "Complete la phrase avec les erreurs les plus courantes quand on combine les modes.",
    "Les erreurs les plus courantes quand on combine les modes sont : melanger des styles ___ qui se contredisent, utiliser un eclairage ___ avec le style choisi, associer palette et mood ___, ajouter des elements ___ sans but clair et ___ les elements jusqu'a creer une ambiguite visuelle.",
    [
      "incompatibles",
      "incoherent",
      "conflictuels",
      "inutiles",
      "accumuler",
    ],
    [
      "incompatibles",
      "incoherent",
      "conflictuels",
      "inutiles",
      "accumuler",
    ],
    "Le probleme n'est pas d'avoir beaucoup de couches. Le probleme, c'est d'avoir beaucoup de couches qui tirent dans des directions opposees.",
  ),
  textStep(
    "Conclusion",
    "Combiner les modes est la competence qui transforme MidJourney de generateur d'images en studio creatif. Style avec lumiere, point de vue avec mood, palette avec atmosphere, references artistiques hybrides et toutes les couches reunies dans un seul prompt clair ouvrent des possibilites qu'aucun element isole ne pourrait produire.\n\nLe secret n'est pas d'utiliser plus d'elements. Le secret est d'utiliser les bons elements, dans le bon ordre, en renforcant la meme idee visuelle du debut a la fin.",
  ),
] as const;
