const textStep = (title: string, content: string, promptBox?: string) => ({
  type: "text" as const,
  title,
  content,
  ...(promptBox ? { promptBox } : {}),
});

const quizStep = (
  title: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
) => ({
  type: "quiz" as const,
  title,
  question,
  options,
  correctIndex,
  explanation,
});

const fillStep = (
  title: string,
  instruction: string,
  sentence: string,
  answers: string[],
  options: string[],
  explanation: string,
) => ({
  type: "fill_blanks" as const,
  title,
  instruction,
  sentence,
  answers,
  options,
  explanation,
});

export const MIDJOURNEY_MODULE_3_STEPS_PT = [
  textStep(
    "Tamanho da imagem - Dominando a proporcao e a composicao",
    "Bem-vindo de volta! Nesta licao, voce vai aprender como o tamanho e a proporcao da imagem transformam completamente a composicao, o impacto e a aplicacao de qualquer visual criado no MidJourney, e como escolher o formato certo para cada objetivo.\n\nMuitos iniciantes ignoram o formato e ficam no quadrado padrao para tudo. Isso e um erro estrategico. A proporcao define como o olho percorre a imagem, quanto espaco cada elemento ocupa e se o visual realmente funciona na plataforma onde sera usado.",
  ),
  quizStep(
    "Por que a proporcao importa tanto",
    "Por que escolher a proporcao certa e tao importante quanto escrever um bom prompt?",
    [
      "Porque a proporcao define a composicao da cena, o espaco disponivel para cada elemento e a compatibilidade com a plataforma final.",
      "Porque o MidJourney cobra mais por imagens em formatos nao quadrados.",
      "Porque a proporcao so importa quando a imagem sera impressa fisicamente.",
      "Porque qualquer imagem pode ser cortada depois sem perder qualidade ou composicao.",
    ],
    0,
    "A proporcao muda a estrutura da cena e a aplicacao final. Nao e detalhe tecnico; e decisao estrategica.",
  ),
  fillStep(
    "Preencha a lacuna - Use o parametro corretamente",
    "Complete a explicacao do uso de --ar no MidJourney.",
    "/imagine ___, estilo cinematografico, luz golden hour ___ O parametro ___ vai ao ___ do prompt, depois de todos os elementos descritivos. Voce pode usar proporcoes como ___, ___ ou ___ dependendo do resultado desejado.",
    [
      "uma paisagem montanhosa ampla ao por do sol",
      "--ar 16:9",
      "--ar",
      "final",
      "--ar 1:1",
      "--ar 4:5",
      "--ar 9:16",
    ],
    [
      "uma paisagem montanhosa ampla ao por do sol",
      "--ar 16:9",
      "--ar",
      "final",
      "--ar 1:1",
      "--ar 4:5",
      "--ar 9:16",
    ],
    "No MidJourney, a proporcao entra no fim do prompt com --ar. Ele redefine o quadro e nao apenas um corte posterior.",
  ),
  quizStep(
    "Sem --ar no prompt",
    "O que acontece se voce nao especificar o parametro --ar no prompt?",
    [
      "O MidJourney gera um erro e pede que voce defina a proporcao.",
      "A imagem sai no formato que o modelo considera mais adequado para o sujeito.",
      "O MidJourney usa a proporcao padrao 1:1, o formato quadrado, independentemente do sujeito ou da plataforma.",
      "O formato gerado e aleatorio a cada nova tentativa.",
    ],
    2,
    "Sem --ar, o padrao e 1:1. Por isso tanta gente acaba com imagens quadradas sem perceber que entregou a decisao ao padrao da ferramenta.",
  ),
  fillStep(
    "Preencha a lacuna - Use o formato quadrado",
    "Monte o prompt para um visual 1:1 centrado.",
    "/imagine ___, fotografia ___, fundo ___, luz ___, composicao centralizada, ___",
    [
      "um relogio de luxo sobre uma superficie de madeira",
      "de produto comercial",
      "limpo e escuro",
      "suave de estudio",
      "--ar 1:1",
    ],
    [
      "um relogio de luxo sobre uma superficie de madeira",
      "de produto comercial",
      "limpo e escuro",
      "suave de estudio",
      "--ar 1:1",
    ],
    "O 1:1 funciona muito bem quando o sujeito principal ocupa o centro e precisa de leitura direta no feed.",
  ),
  quizStep(
    "Quando 1:1 e estrategico",
    "Quando o formato 1:1 e a escolha mais estrategica?",
    [
      "Para paisagens amplas e ambientes que precisam de respiro horizontal.",
      "Para Stories e Reels no Instagram.",
      "Para feed do Instagram e Pinterest, fotos de perfil, produto isolado e composicoes centralizadas.",
      "O formato 1:1 esta ultrapassado e nao deveria mais ser usado.",
    ],
    2,
    "O quadrado ainda e forte quando a composicao e central, simples e precisa caber bem em feed e grade visual.",
  ),
  fillStep(
    "Preencha a lacuna - Crie no formato horizontal amplo",
    "Complete o prompt para uma cena 16:9 cinematografica.",
    "/imagine ___, estilo ___, luz ___, atmosfera ___, plano geral aberto, ___",
    [
      "um horizonte de cidade futurista a noite com carros voadores",
      "arte conceitual cyberpunk",
      "neon",
      "epica e imersiva",
      "--ar 16:9",
    ],
    [
      "um horizonte de cidade futurista a noite com carros voadores",
      "arte conceitual cyberpunk",
      "neon",
      "epica e imersiva",
      "--ar 16:9",
    ],
    "O 16:9 abre a cena e cria espaco para narrativa visual, horizonte e ambientacao.",
  ),
  quizStep(
    "Aplicacao ideal do 16:9",
    "Para qual aplicacao o formato 16:9 e mais indicado?",
    [
      "Para posts verticais no feed do Instagram.",
      "Para fotos de perfil em redes sociais.",
      "Para thumbnails de YouTube, capas de apresentacoes, banners de sites e qualquer visual de tela horizontal.",
      "O formato 16:9 so funciona para arquitetura e paisagens urbanas.",
    ],
    2,
    "Quando a tela final e horizontal, o 16:9 conversa melhor com a plataforma e aproveita muito mais o espaco visivel.",
  ),
  fillStep(
    "Preencha a lacuna - Crie para o mobile",
    "Monte o prompt pensando em 9:16 para tela cheia no celular.",
    "/imagine ___, estilo ___, luz ___, composicao ___, humor ___, deixando espaco no topo e na base para texto, ___",
    [
      "uma jovem confiante caminhando em um distrito de moda",
      "fotografia de estilo urbano",
      "natural urbana",
      "corpo inteiro vertical",
      "forte e energetico",
      "--ar 9:16",
    ],
    [
      "uma jovem confiante caminhando em um distrito de moda",
      "fotografia de estilo urbano",
      "natural urbana",
      "corpo inteiro vertical",
      "forte e energetico",
      "--ar 9:16",
    ],
    "O 9:16 funciona melhor quando voce pensa na experiencia real de tela cheia no celular, inclusive reservando espaco para texto e CTA.",
  ),
  quizStep(
    "Por que 9:16 domina o mobile",
    "Por que o formato 9:16 domina o consumo de conteudo mobile atualmente?",
    [
      "Porque os algoritmos favorecem automaticamente qualquer conteudo vertical.",
      "Porque economiza dados moveis no consumo.",
      "Porque ocupa 100% da tela do celular em modo retrato, reduz distracoes e aumenta a imersao visual.",
      "Porque o 9:16 so funciona para video, nao para imagens estaticas.",
    ],
    2,
    "O impacto do 9:16 vem da ocupacao total da tela. E menos sobre algoritmo e mais sobre experiencia de consumo.",
  ),
  fillStep(
    "Preencha a lacuna - Crie para o feed",
    "Complete o prompt pensado para o feed em 4:5.",
    "/imagine ___, estilo ___, luz ___, cores ___, composicao ___, ___",
    [
      "um flat lay de cafe, um livro e folhas de outono sobre uma mesa rustica de madeira",
      "fotografia de lifestyle",
      "natural suave e quente",
      "ambar e marrom aconchegantes",
      "vista superior",
      "--ar 4:5",
    ],
    [
      "um flat lay de cafe, um livro e folhas de outono sobre uma mesa rustica de madeira",
      "fotografia de lifestyle",
      "natural suave e quente",
      "ambar e marrom aconchegantes",
      "vista superior",
      "--ar 4:5",
    ],
    "O 4:5 entrega mais presenca vertical no feed sem virar formato de story, por isso e tao bom para conteudo social.",
  ),
  quizStep(
    "Por que 4:5 e favorito no feed",
    "Por que o 4:5 e considerado o formato mais estrategico para o feed do Instagram?",
    [
      "Porque o Instagram exige que todos os posts sejam em 4:5.",
      "Porque cria uma aparencia diferente dos outros posts no feed.",
      "Porque ocupa mais espaco vertical que 1:1 sem virar story, aumentando o tempo de atencao antes do scroll.",
      "Porque o 4:5 gera imagens automaticamente com mais resolucao.",
    ],
    2,
    "No feed, ocupar mais altura significa aparecer com mais presenca e segurar mais a atencao do usuario por alguns instantes extras.",
  ),
  fillStep(
    "Preencha a lacuna - Crie no formato fotografico classico",
    "Monte o prompt em 3:2 com linguagem fotografica profissional.",
    "/imagine ___, estilo fotografico ___, luz ___, profundidade de campo ___, cores ___, ___",
    [
      "uma noiva e um noivo caminhando por um jardim de flores",
      "editorial de casamento",
      "golden hour suave",
      "rasa",
      "quentes e romanticas",
      "--ar 3:2",
    ],
    [
      "uma noiva e um noivo caminhando por um jardim de flores",
      "editorial de casamento",
      "golden hour suave",
      "rasa",
      "quentes e romanticas",
      "--ar 3:2",
    ],
    "O 3:2 aproxima a imagem da linguagem tradicional de camera, muito util quando voce quer realismo fotografico refinado.",
  ),
  quizStep(
    "Quando 3:2 parece mais natural",
    "Quando o formato 3:2 e a escolha mais natural?",
    [
      "Para conteudo de redes sociais que exige formato vertical.",
      "Para thumbnails e banners horizontais extremos.",
      "Para imagens com aparencia de fotografia profissional capturada por camera, como editorial, retrato e paisagem.",
      "O formato 3:2 e obsoleto e nao deve ser usado digitalmente.",
    ],
    2,
    "O 3:2 conversa com a memoria visual da fotografia tradicional. Ele parece mais 'camera real' para o publico.",
  ),
  fillStep(
    "Preencha a lacuna - Crie um retrato vertical",
    "Complete o prompt para 2:3.",
    "/imagine ___, estilo ___, luz ___, fundo ___, composicao de retrato ___, ___",
    [
      "uma executiva poderosa com um terno impecavel",
      "fotografia editorial de moda",
      "dramatic studio",
      "escuro, desfocado e melancolico",
      "de corpo inteiro vertical",
      "--ar 2:3",
    ],
    [
      "uma executiva poderosa com um terno impecavel",
      "fotografia editorial de moda",
      "dramatic studio",
      "escuro, desfocado e melancolico",
      "de corpo inteiro vertical",
      "--ar 2:3",
    ],
    "O 2:3 funciona muito bem para retrato vertical, capa, poster e todo visual que precisa crescer em altura sem parecer um story.",
  ),
  quizStep(
    "Onde 2:3 se destaca",
    "Para qual plataforma o formato 2:3 e especialmente estrategico?",
    [
      "Para YouTube e plataformas de video horizontal.",
      "Para banners e cabecalhos de sites.",
      "Para Pinterest, capas de livros, posteres e materiais impressos em retrato.",
      "O formato 2:3 so funciona para moda e beleza.",
    ],
    2,
    "Pins verticais ocupam mais espaco no feed do Pinterest e materiais editoriais tambem se beneficiam muito desse formato.",
  ),
  fillStep(
    "Preencha a lacuna - Explore formatos extremos",
    "Complete os dois prompts com proporcoes ultra amplas e ultra altas.",
    "/imagine ___, vista panoramica, estilo ___ ___ - banner ultra horizontal. /imagine ___, estilo ___ ___ - formato ultra vertical para outdoor.",
    [
      "uma vista aerea impressionante da floresta amazonica",
      "fotografia cinematografica",
      "--ar 21:9",
      "um arranha-ceu desaparecendo nas nuvens",
      "fotografia arquitetonica",
      "--ar 1:3",
    ],
    [
      "uma vista aerea impressionante da floresta amazonica",
      "fotografia cinematografica",
      "--ar 21:9",
      "um arranha-ceu desaparecendo nas nuvens",
      "fotografia arquitetonica",
      "--ar 1:3",
    ],
    "Formatos extremos fazem sentido quando a proporcao em si e parte intencional da peca final, como banner amplo ou painel vertical.",
  ),
  quizStep(
    "Quando formatos extremos se justificam",
    "Quando formatos extremos como 21:9 ou 1:3 sao justificados?",
    [
      "Para todos os posts nas redes sociais, so para chamar mais atencao.",
      "Quando o usuario quer testar os limites tecnicos do MidJourney.",
      "Para banners ultra horizontais, capas de perfil e outdoor vertical, quando a proporcao extrema faz parte do conceito visual.",
      "Formatos extremos geram erros e devem ser evitados sempre.",
    ],
    2,
    "O formato extremo precisa nascer da aplicacao final. Fora disso, ele vira exibicao tecnica sem funcao estrategica.",
  ),
  fillStep(
    "Preencha a lacuna - Entenda o impacto da proporcao",
    "Complete como o mesmo prompt muda de enquadramento conforme o formato.",
    "O prompt '/imagine um chef cozinhando em uma cozinha profissional' em ___ mostra o chef em close com foco no rosto e nas maos. Em ___ mostra o chef em plano aberto com toda a cozinha ao fundo. Em ___ mostra o chef em plano medio com equilibrio entre personagem e ambiente.",
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    "A mesma descricao muda de enquadramento porque o MidJourney reorganiza os elementos para preencher o espaco disponivel da melhor forma.",
  ),
  quizStep(
    "Por que a composicao muda",
    "Por que o MidJourney gera composicoes diferentes para o mesmo prompt em proporcoes diferentes?",
    [
      "Porque o modelo comete erros ao interpretar prompts com parametros.",
      "Para forcar o usuario a comprar mais geracoes.",
      "Porque o modelo adapta o enquadramento e a composicao para preencher o espaco disponivel da forma mais equilibrada.",
      "O MidJourney gera exatamente a mesma composicao independentemente da proporcao.",
    ],
    2,
    "Formato vertical tende a puxar close e figura; formato horizontal tende a abrir cena e contexto. A IA recompõe a imagem para caber melhor naquele quadro.",
  ),
  fillStep(
    "Preencha a lacuna - Escolha a proporcao certa",
    "Complete o guia rapido de proporcoes por plataforma.",
    "Para ___ e Stories use ___. Para feed do ___ use ___. Para ___ e banners horizontais use ___. Para ___ e posteres use ___. Para Pinterest use ___. Para fotos com aparencia de ___ profissional use ___.",
    [
      "Reels e TikTok",
      "--ar 9:16",
      "Instagram",
      "--ar 4:5",
      "YouTube e apresentacoes",
      "--ar 16:9",
      "capas de livros",
      "--ar 2:3",
      "--ar 2:3",
      "camera",
      "--ar 3:2",
    ],
    [
      "Reels e TikTok",
      "--ar 9:16",
      "Instagram",
      "--ar 4:5",
      "YouTube e apresentacoes",
      "--ar 16:9",
      "capas de livros",
      "--ar 2:3",
      "--ar 2:3",
      "camera",
      "--ar 3:2",
    ],
    "Escolher a proporcao certa e alinhar a imagem com a plataforma real onde ela vai viver, e nao tentar adaptar tudo depois.",
  ),
  quizStep(
    "Erro mais comum com tamanho de imagem",
    "Qual e o erro mais comum relacionado ao tamanho de imagem no MidJourney?",
    [
      "Usar 16:9 para YouTube.",
      "Experimentar proporcoes diferentes para o mesmo prompt.",
      "Criar tudo em 1:1 e depois tentar adaptar para plataformas diferentes, perdendo composicao e enquadramento.",
      "Usar o parametro --ar com numeros muito diferentes entre si.",
    ],
    2,
    "Gerar tudo em quadrado e cortar depois parece pratico, mas destrui a composicao certa para cada canal.",
  ),
  fillStep(
    "Preencha a lacuna - Altere a proporcao",
    "Complete o processo de adaptar um prompt para outro formato.",
    "Para gerar a mesma imagem em uma proporcao diferente: copie o ___ original, substitua o parametro ___ pela nova proporcao desejada e envie novamente. O MidJourney vai ___ os mesmos elementos visuais em um ___ diferente, mantendo o ___ e o ___, mas com um enquadramento completamente novo.",
    ["prompt", "--ar", "recompor", "formato", "estilo", "humor"],
    ["prompt", "--ar", "recompor", "formato", "estilo", "humor"],
    "Quando voce muda so o --ar, preserva a base criativa e pede uma nova composicao para outra plataforma.",
  ),
  quizStep(
    "Multiplos formatos, mesma campanha",
    "O que voce deve fazer quando precisa de uma imagem em multiplos formatos para diferentes plataformas?",
    [
      "Gerar uma unica imagem e cortar para cada formato necessario.",
      "Criar um prompt totalmente diferente para cada plataforma.",
      "Usar o mesmo prompt base e variar apenas o parametro --ar para manter consistencia visual entre as versoes.",
      "Multiplos formatos so sao necessarios para campanhas pagas.",
    ],
    2,
    "O melhor caminho e preservar a identidade visual do prompt e deixar a proporcao adaptar o enquadramento a cada canal.",
  ),
  textStep(
    "Conclusao",
    "O tamanho e a proporcao da imagem nao sao detalhe tecnico. Sao decisoes estrategicas que definem composicao, impacto e aplicabilidade de cada visual criado no MidJourney. 1:1 para o feed, 9:16 para Stories e Reels, 16:9 para YouTube e apresentacoes, 4:5 para maximizar o feed, 2:3 para retratos e Pinterest - cada proporcao tem sua funcao e seu poder.\n\nDominar o parametro --ar e o que separa quem cria imagens bonitas de quem cria imagens estrategicas, pensadas para o canal certo, no formato certo e com a composicao certa.",
  ),
] as const;

export const MIDJOURNEY_MODULE_3_STEPS_EN = [
  textStep(
    "Image size - mastering aspect ratio and composition",
    "Welcome back! In this lesson, you will learn how image size and aspect ratio completely transform the composition, impact, and application of any visual created in MidJourney, and how to choose the right format for each goal.\n\nMany beginners ignore format and stay with the default square for everything. That is a strategic mistake. Ratio defines how the eye moves through the image, how much space each element occupies, and whether the visual fits the platform where it will be used.",
  ),
  quizStep(
    "Why aspect ratio matters",
    "Why is choosing the right ratio as important as writing a strong prompt?",
    [
      "Because ratio defines scene composition, space for each element, and compatibility with the platform where the image will be published.",
      "Because MidJourney charges more for non-square formats.",
      "Because ratio only matters when the image will be printed.",
      "Because any image can be cropped later without losing quality or composition.",
    ],
    0,
    "Ratio changes the structure of the scene and the final use case. It is not a technical footnote; it is a strategic decision.",
  ),
  fillStep(
    "Fill in the blanks - Use the parameter correctly",
    "Complete the explanation of how --ar works in MidJourney.",
    "/imagine ___, cinematic style, golden hour lighting ___ The parameter ___ goes at the ___ of the prompt, after all descriptive elements. You can use ratios like ___, ___, or ___ depending on the result you need.",
    [
      "a vast mountain landscape at sunset",
      "--ar 16:9",
      "--ar",
      "end",
      "--ar 1:1",
      "--ar 4:5",
      "--ar 9:16",
    ],
    [
      "a vast mountain landscape at sunset",
      "--ar 16:9",
      "--ar",
      "end",
      "--ar 1:1",
      "--ar 4:5",
      "--ar 9:16",
    ],
    "In MidJourney, aspect ratio is controlled with --ar at the end of the prompt. It changes the frame itself, not just a later crop.",
  ),
  quizStep(
    "No --ar in the prompt",
    "What happens if you do not specify --ar in the prompt?",
    [
      "MidJourney throws an error and asks you to define a ratio.",
      "The image is generated in whatever format the model finds most appropriate.",
      "MidJourney uses the default 1:1 square ratio, regardless of subject, style, or destination.",
      "The generated format is random every time.",
    ],
    2,
    "Without --ar, the default is 1:1. That is why so many people end up with square visuals without realizing the tool made the decision for them.",
  ),
  fillStep(
    "Fill in the blanks - Use the square format",
    "Build the prompt for a centered 1:1 visual.",
    "/imagine ___, ___ photography, ___ background, ___ lighting, centered composition, ___",
    [
      "a luxury watch on a wooden surface",
      "commercial product",
      "clean dark",
      "soft studio",
      "--ar 1:1",
    ],
    [
      "a luxury watch on a wooden surface",
      "commercial product",
      "clean dark",
      "soft studio",
      "--ar 1:1",
    ],
    "1:1 works well when the main subject sits in the middle and needs clear reading in a feed or grid.",
  ),
  quizStep(
    "When 1:1 is strategic",
    "When is 1:1 the most strategic choice?",
    [
      "For wide landscapes and environments that need horizontal breathing room.",
      "For Stories and Reels on Instagram.",
      "For Instagram and Pinterest feed posts, profile photos, isolated product shots, and centered compositions.",
      "1:1 is outdated and should not be used anymore.",
    ],
    2,
    "Square still works extremely well when the composition is central, direct, and meant for feed-based layouts.",
  ),
  fillStep(
    "Fill in the blanks - Create in wide screen",
    "Complete the prompt for a cinematic 16:9 scene.",
    "/imagine ___, ___ style, ___ lighting, ___ atmosphere, wide establishing shot, ___",
    [
      "a futuristic city skyline at night with flying cars",
      "cyberpunk concept art",
      "neon",
      "epic and immersive",
      "--ar 16:9",
    ],
    [
      "a futuristic city skyline at night with flying cars",
      "cyberpunk concept art",
      "neon",
      "epic and immersive",
      "--ar 16:9",
    ],
    "16:9 opens the frame and gives space for narrative, horizon, and environmental storytelling.",
  ),
  quizStep(
    "Best use of 16:9",
    "Which application is 16:9 most suitable for?",
    [
      "Vertical Instagram feed posts.",
      "Profile photos on social networks.",
      "YouTube thumbnails, presentation covers, website banners, wallpapers, and any horizontal-screen visual.",
      "16:9 only works for architecture and urban landscapes.",
    ],
    2,
    "When the final screen is horizontal, 16:9 makes better use of the visible area and feels native to the platform.",
  ),
  fillStep(
    "Fill in the blanks - Create for mobile",
    "Build the prompt for a 9:16 mobile-first image.",
    "/imagine ___, ___ style, ___ lighting, ___ composition, ___ mood, leaving space at top and bottom for text overlay, ___",
    [
      "a confident young woman walking in a fashion district",
      "street style photography",
      "natural urban",
      "vertical full body",
      "bold and energetic",
      "--ar 9:16",
    ],
    [
      "a confident young woman walking in a fashion district",
      "street style photography",
      "natural urban",
      "vertical full body",
      "bold and energetic",
      "--ar 9:16",
    ],
    "9:16 works best when you think about the real mobile experience, including room for text and CTA overlays.",
  ),
  quizStep(
    "Why 9:16 dominates mobile",
    "Why does 9:16 dominate mobile content consumption today?",
    [
      "Because social media algorithms automatically favor any vertical content.",
      "Because it saves mobile data.",
      "Because it fills 100% of the phone screen in portrait mode, reducing distractions and maximizing immersion.",
      "Because 9:16 only works for video, not static images.",
    ],
    2,
    "The power of 9:16 comes from full-screen occupation. It is more about viewing experience than algorithm myths.",
  ),
  fillStep(
    "Fill in the blanks - Create for the feed",
    "Complete the prompt designed for a 4:5 feed image.",
    "/imagine ___, ___ style, ___ lighting, ___ colors, ___ composition, ___",
    [
      "a flat lay of coffee, a book and autumn leaves on a rustic wooden table",
      "lifestyle photography",
      "warm soft natural",
      "cozy amber and brown",
      "overhead top-down",
      "--ar 4:5",
    ],
    [
      "a flat lay of coffee, a book and autumn leaves on a rustic wooden table",
      "lifestyle photography",
      "warm soft natural",
      "cozy amber and brown",
      "overhead top-down",
      "--ar 4:5",
    ],
    "4:5 gives more vertical presence in the feed without turning the post into a story format.",
  ),
  quizStep(
    "Why 4:5 wins in the feed",
    "Why is 4:5 considered the most strategic format for the Instagram feed?",
    [
      "Because Instagram requires every post to be 4:5.",
      "Because it creates a different look from other feed posts.",
      "Because it is the tallest ratio Instagram shows in-feed without turning it into a story, giving the post more screen presence.",
      "Because 4:5 automatically generates higher resolution.",
    ],
    2,
    "In the feed, more height means more presence and a better chance of holding attention before the user scrolls away.",
  ),
  fillStep(
    "Fill in the blanks - Create in classic photographic format",
    "Build the prompt in 3:2 with professional photography language.",
    "/imagine ___, ___ photography style, ___ lighting, ___ depth of field, ___ colors, ___",
    [
      "a bride and groom walking through a flower garden",
      "editorial wedding",
      "soft golden hour",
      "shallow",
      "warm and romantic",
      "--ar 3:2",
    ],
    [
      "a bride and groom walking through a flower garden",
      "editorial wedding",
      "soft golden hour",
      "shallow",
      "warm and romantic",
      "--ar 3:2",
    ],
    "3:2 brings the image closer to traditional camera language, which is useful when you want refined photographic realism.",
  ),
  quizStep(
    "When 3:2 feels natural",
    "When is 3:2 the most natural choice?",
    [
      "For social content that needs a vertical format.",
      "For ultra-wide thumbnails and banners.",
      "For images that should feel like professional camera photography, such as editorial, portrait, and landscape work.",
      "3:2 is obsolete and should not be used digitally.",
    ],
    2,
    "3:2 matches the visual memory people associate with traditional photography, so it feels familiar and high quality.",
  ),
  fillStep(
    "Fill in the blanks - Create a classic vertical portrait",
    "Complete the prompt for 2:3.",
    "/imagine ___, ___ style, ___ lighting, ___ background, ___ portrait composition, ___",
    [
      "a powerful female executive in a sharp business suit",
      "editorial fashion photography",
      "dramatic studio",
      "dark moody blurred",
      "full body vertical",
      "--ar 2:3",
    ],
    [
      "a powerful female executive in a sharp business suit",
      "editorial fashion photography",
      "dramatic studio",
      "dark moody blurred",
      "full body vertical",
      "--ar 2:3",
    ],
    "2:3 works very well for vertical portraits, covers, posters, and any visual that needs height without becoming story-shaped.",
  ),
  quizStep(
    "Where 2:3 stands out",
    "For which platform is 2:3 especially strategic?",
    [
      "For YouTube and horizontal video platforms.",
      "For website headers and banners.",
      "For Pinterest, book covers, posters, and portrait-oriented print material.",
      "2:3 only works for fashion and beauty photography.",
    ],
    2,
    "Vertical pins take more space in Pinterest feeds, and editorial formats like covers and posters also benefit from this ratio.",
  ),
  fillStep(
    "Fill in the blanks - Explore extreme formats",
    "Complete both prompts with ultra-wide and ultra-tall ratios.",
    "/imagine ___, panoramic view, ___ style ___ - ultra-wide banner. /imagine ___, ___ style ___ - ultra-vertical outdoor format.",
    [
      "a breathtaking aerial view of the Amazon rainforest",
      "cinematic photography",
      "--ar 21:9",
      "a tall skyscraper disappearing into the clouds",
      "architectural photography",
      "--ar 1:3",
    ],
    [
      "a breathtaking aerial view of the Amazon rainforest",
      "cinematic photography",
      "--ar 21:9",
      "a tall skyscraper disappearing into the clouds",
      "architectural photography",
      "--ar 1:3",
    ],
    "Extreme formats make sense when the ratio itself is part of the final piece, such as a panoramic banner or a vertical billboard.",
  ),
  quizStep(
    "When extreme formats make sense",
    "When are extreme formats like 21:9 or 1:3 justified?",
    [
      "For every social post, just to attract more attention.",
      "When the user wants to test MidJourney's technical limits.",
      "For specific applications like ultra-wide website banners, profile covers, vertical outdoor media, and concept-driven compositions.",
      "Extreme formats generate errors and should always be avoided.",
    ],
    2,
    "An extreme ratio should come from the final application. Otherwise it becomes technical excess without strategic value.",
  ),
  fillStep(
    "Fill in the blanks - Understand ratio impact",
    "Complete how the same prompt changes framing based on ratio.",
    "The prompt '/imagine a chef cooking in a professional kitchen' in ___ shows the chef in a closer frame focused on face and hands. In ___ it shows the chef in a wider shot with the whole kitchen behind. In ___ it shows a medium frame balancing the character and the environment.",
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    "The same description changes framing because MidJourney reorganizes the scene to fill the available shape in the most balanced way.",
  ),
  quizStep(
    "Why composition changes",
    "Why does MidJourney generate different compositions for the same prompt in different ratios?",
    [
      "Because the model makes mistakes when interpreting prompt parameters.",
      "To force users to buy more generations.",
      "Because the model adapts framing and composition to fill the available space in the most balanced way.",
      "MidJourney generates exactly the same composition regardless of ratio.",
    ],
    2,
    "A vertical format tends to favor closeness and subject focus, while a horizontal one tends to open up space and environment.",
  ),
  fillStep(
    "Fill in the blanks - Choose the right ratio",
    "Complete the quick guide for platform-based ratios.",
    "For ___ and Stories use ___. For the ___ feed use ___. For ___ and horizontal banners use ___. For ___ and posters use ___. For Pinterest use ___. For images with a ___ photography feel use ___.",
    [
      "Reels and TikTok",
      "--ar 9:16",
      "Instagram",
      "--ar 4:5",
      "YouTube and presentations",
      "--ar 16:9",
      "book covers",
      "--ar 2:3",
      "--ar 2:3",
      "camera",
      "--ar 3:2",
    ],
    [
      "Reels and TikTok",
      "--ar 9:16",
      "Instagram",
      "--ar 4:5",
      "YouTube and presentations",
      "--ar 16:9",
      "book covers",
      "--ar 2:3",
      "--ar 2:3",
      "camera",
      "--ar 3:2",
    ],
    "Choosing the right ratio means aligning the image with the platform where it will actually live, instead of trying to force adaptation later.",
  ),
  quizStep(
    "Most common image-size mistake",
    "What is the most common mistake related to image size in MidJourney?",
    [
      "Using 16:9 for YouTube.",
      "Experimenting with different ratios for the same prompt.",
      "Creating everything in 1:1 and then trying to adapt it to different platforms, losing composition and framing.",
      "Using --ar with ratios that are too different from one another.",
    ],
    2,
    "Generating everything as square and cropping later may feel practical, but it breaks the composition designed for each channel.",
  ),
  fillStep(
    "Fill in the blanks - Change the ratio",
    "Complete the process of adapting a prompt to another format.",
    "To generate the same image in a different ratio: copy the original ___, replace the parameter ___ with the new ratio, and send it again. MidJourney will ___ the same visual elements in a different ___, while keeping the ___ and the ___ with a completely new framing.",
    ["prompt", "--ar", "recompose", "format", "style", "mood"],
    ["prompt", "--ar", "recompose", "format", "style", "mood"],
    "When you change only --ar, you preserve the core creative direction and ask for a new composition for another platform.",
  ),
  quizStep(
    "Multiple formats, same campaign",
    "What should you do when you need one image in multiple formats for different platforms?",
    [
      "Generate a single image and crop it for each needed format.",
      "Create a completely different prompt for every platform.",
      "Use the same base prompt and vary only --ar to keep visual consistency across versions.",
      "Multiple formats are only needed for paid campaigns.",
    ],
    2,
    "The strongest approach is to preserve the visual identity of the prompt while letting ratio adapt framing to each channel.",
  ),
  textStep(
    "Conclusion",
    "Image size and ratio are not technical details. They are strategic decisions that define composition, impact, and applicability for every visual created in MidJourney. 1:1 for feed, 9:16 for Stories and Reels, 16:9 for YouTube and presentations, 4:5 to maximize feed space, 2:3 for portraits and Pinterest - each ratio has a function and a strength.\n\nMastering --ar is what separates someone who creates pretty images from someone who creates strategic images, built for the right channel, in the right format, with the right composition.",
  ),
] as const;
export const MIDJOURNEY_MODULE_3_STEPS_ES = [
  textStep(
    "Tamano de imagen - dominar la proporcion y la composicion",
    "Bienvenido de nuevo. En esta leccion vas a aprender como el tamano y la proporcion de la imagen transforman por completo la composicion, el impacto y la aplicacion de cualquier visual creado en MidJourney, y como elegir el formato correcto para cada objetivo.\n\nMuchos principiantes ignoran el formato y dejan todo en el cuadrado por defecto. Eso es un error estrategico. La proporcion define como recorre el ojo la imagen, cuanto espacio ocupa cada elemento y si el visual realmente funciona en la plataforma final.",
  ),
  quizStep(
    "Por que la proporcion importa",
    "Por que elegir la proporcion correcta es tan importante como escribir un buen prompt?",
    [
      "Porque la proporcion define la composicion de la escena, el espacio disponible para cada elemento y la compatibilidad con la plataforma final.",
      "Porque MidJourney cobra mas por formatos no cuadrados.",
      "Porque la proporcion solo importa si la imagen va a imprimirse.",
      "Porque cualquier imagen se puede recortar despues sin perder composicion ni calidad.",
    ],
    0,
    "La proporcion cambia la estructura de la escena y el uso final. No es un detalle tecnico; es una decision estrategica.",
  ),
  fillStep(
    "Rellena el espacio - Usa el parametro correctamente",
    "Completa la explicacion del uso de --ar en MidJourney.",
    "/imagine ___, estilo cinematografico, luz golden hour ___ El parametro ___ va al ___ del prompt, despues de todos los elementos descriptivos. Puedes usar proporciones como ___, ___ o ___ segun el resultado que necesites.",
    [
      "un paisaje montanoso inmenso al atardecer",
      "--ar 16:9",
      "--ar",
      "final",
      "--ar 1:1",
      "--ar 4:5",
      "--ar 9:16",
    ],
    [
      "un paisaje montanoso inmenso al atardecer",
      "--ar 16:9",
      "--ar",
      "final",
      "--ar 1:1",
      "--ar 4:5",
      "--ar 9:16",
    ],
    "En MidJourney, la proporcion se controla con --ar al final del prompt. No es solo un recorte: redefine el encuadre entero.",
  ),
  quizStep(
    "Sin --ar en el prompt",
    "Que pasa si no especificas el parametro --ar en el prompt?",
    [
      "MidJourney genera un error y te pide definir una proporcion.",
      "La imagen sale en el formato que el modelo considere mas adecuado.",
      "MidJourney usa 1:1 por defecto, el formato cuadrado, sin importar sujeto ni plataforma.",
      "El formato es aleatorio en cada generacion.",
    ],
    2,
    "Sin --ar, el comportamiento por defecto es 1:1. Por eso tanta gente termina con imagenes cuadradas sin haberlo decidido realmente.",
  ),
  fillStep(
    "Rellena el espacio - Usa el formato cuadrado",
    "Construye el prompt para un visual 1:1 centrado.",
    "/imagine ___, fotografia ___, fondo ___, luz ___, composicion centrada, ___",
    [
      "un reloj de lujo sobre una superficie de madera",
      "de producto comercial",
      "limpio y oscuro",
      "suave de estudio",
      "--ar 1:1",
    ],
    [
      "un reloj de lujo sobre una superficie de madera",
      "de producto comercial",
      "limpio y oscuro",
      "suave de estudio",
      "--ar 1:1",
    ],
    "El 1:1 funciona muy bien cuando el sujeto principal esta centrado y necesita lectura directa en feed o cuadrícula.",
  ),
  quizStep(
    "Cuando 1:1 es estrategico",
    "Cuando el formato 1:1 es la eleccion mas estrategica?",
    [
      "Para paisajes amplios y ambientes que necesitan aire horizontal.",
      "Para Stories y Reels de Instagram.",
      "Para feed de Instagram y Pinterest, fotos de perfil, producto aislado y composiciones centradas.",
      "El 1:1 esta obsoleto y ya no deberia usarse.",
    ],
    2,
    "El cuadrado sigue siendo muy fuerte cuando la composicion es central, directa y pensada para feed.",
  ),
  fillStep(
    "Rellena el espacio - Crea en formato horizontal amplio",
    "Completa el prompt para una escena 16:9 cinematografica.",
    "/imagine ___, estilo ___, luz ___, atmosfera ___, plano general abierto, ___",
    [
      "un horizonte de ciudad futurista de noche con coches voladores",
      "arte conceptual cyberpunk",
      "neon",
      "epica e inmersiva",
      "--ar 16:9",
    ],
    [
      "un horizonte de ciudad futurista de noche con coches voladores",
      "arte conceptual cyberpunk",
      "neon",
      "epica e inmersiva",
      "--ar 16:9",
    ],
    "El 16:9 abre la escena y da espacio para narrativa, horizonte y contexto visual.",
  ),
  quizStep(
    "Aplicacion ideal del 16:9",
    "Para que aplicacion es mas indicado el formato 16:9?",
    [
      "Para posts verticales del feed de Instagram.",
      "Para fotos de perfil.",
      "Para thumbnails de YouTube, portadas de presentaciones, banners de sitios y cualquier visual de pantalla horizontal.",
      "El 16:9 solo funciona para arquitectura y paisajes urbanos.",
    ],
    2,
    "Cuando la pantalla final es horizontal, 16:9 aprovecha mejor el espacio visible y se siente natural para la plataforma.",
  ),
  fillStep(
    "Rellena el espacio - Crea para mobile",
    "Arma el prompt pensando en 9:16 para pantalla completa en celular.",
    "/imagine ___, estilo ___, luz ___, composicion ___, animo ___, dejando espacio arriba y abajo para texto, ___",
    [
      "una joven segura caminando por un distrito de moda",
      "fotografia street style",
      "natural urbana",
      "cuerpo entero vertical",
      "fuerte y energetico",
      "--ar 9:16",
    ],
    [
      "una joven segura caminando por un distrito de moda",
      "fotografia street style",
      "natural urbana",
      "cuerpo entero vertical",
      "fuerte y energetico",
      "--ar 9:16",
    ],
    "El 9:16 funciona mejor cuando piensas en la experiencia real de pantalla completa en el movil, incluyendo texto y CTA.",
  ),
  quizStep(
    "Por que 9:16 domina mobile",
    "Por que el 9:16 domina el consumo de contenido mobile actualmente?",
    [
      "Porque los algoritmos favorecen automaticamente cualquier contenido vertical.",
      "Porque ahorra datos moviles.",
      "Porque ocupa el 100% de la pantalla del movil en vertical, reduce distracciones y maximiza la inmersion.",
      "Porque 9:16 solo funciona para video.",
    ],
    2,
    "El poder del 9:16 viene de llenar toda la pantalla. Es una ventaja de experiencia, no solo de algoritmo.",
  ),
  fillStep(
    "Rellena el espacio - Crea para el feed",
    "Completa el prompt pensado para 4:5.",
    "/imagine ___, estilo ___, luz ___, colores ___, composicion ___, ___",
    [
      "un flat lay de cafe, un libro y hojas de otono sobre una mesa rustica",
      "fotografia lifestyle",
      "natural suave y calida",
      "ambar y marron acogedores",
      "vista superior",
      "--ar 4:5",
    ],
    [
      "un flat lay de cafe, un libro y hojas de otono sobre una mesa rustica",
      "fotografia lifestyle",
      "natural suave y calida",
      "ambar y marron acogedores",
      "vista superior",
      "--ar 4:5",
    ],
    "El 4:5 ofrece mas presencia vertical en el feed sin convertirse en story, por eso es tan eficaz para redes.",
  ),
  quizStep(
    "Por que 4:5 gana en el feed",
    "Por que el 4:5 se considera el formato mas estrategico para el feed de Instagram?",
    [
      "Porque Instagram exige que todos los posts sean 4:5.",
      "Porque crea una apariencia distinta frente a otros posts.",
      "Porque ocupa mas altura que 1:1 sin volverse story, aumentando la atencion antes del scroll.",
      "Porque el 4:5 genera mas resolucion automaticamente.",
    ],
    2,
    "En el feed, mas altura significa mas presencia y mas oportunidad de sostener la atencion durante unos segundos extra.",
  ),
  fillStep(
    "Rellena el espacio - Crea en formato fotografico clasico",
    "Construye el prompt en 3:2 con lenguaje fotografico profesional.",
    "/imagine ___, estilo fotografico ___, luz ___, profundidad de campo ___, colores ___, ___",
    [
      "unos novios caminando por un jardin de flores",
      "editorial de boda",
      "golden hour suave",
      "poca",
      "calidos y romanticos",
      "--ar 3:2",
    ],
    [
      "unos novios caminando por un jardin de flores",
      "editorial de boda",
      "golden hour suave",
      "poca",
      "calidos y romanticos",
      "--ar 3:2",
    ],
    "El 3:2 acerca la imagen al lenguaje clasico de camara, ideal cuando buscas realismo fotografico refinado.",
  ),
  quizStep(
    "Cuando 3:2 se siente natural",
    "Cuando el formato 3:2 es la eleccion mas natural?",
    [
      "Para contenido social que necesita formato vertical.",
      "Para thumbnails y banners ultrahorizontales.",
      "Para imagenes con apariencia de fotografia profesional capturada con camara, como editorial, retrato y paisaje.",
      "El 3:2 esta obsoleto y ya no deberia usarse digitalmente.",
    ],
    2,
    "El 3:2 conecta con la memoria visual de la fotografia tradicional, por eso se siente mas autentico para el publico.",
  ),
  fillStep(
    "Rellena el espacio - Crea un retrato vertical clasico",
    "Completa el prompt para 2:3.",
    "/imagine ___, estilo ___, luz ___, fondo ___, composicion de retrato ___, ___",
    [
      "una ejecutiva poderosa con un traje impecable",
      "fotografia editorial de moda",
      "dramatic studio",
      "oscuro, difuminado y melancolico",
      "de cuerpo entero vertical",
      "--ar 2:3",
    ],
    [
      "una ejecutiva poderosa con un traje impecable",
      "fotografia editorial de moda",
      "dramatic studio",
      "oscuro, difuminado y melancolico",
      "de cuerpo entero vertical",
      "--ar 2:3",
    ],
    "El 2:3 funciona muy bien para retrato vertical, portada, poster y cualquier visual que necesita crecer en altura sin parecer story.",
  ),
  quizStep(
    "Donde 2:3 destaca",
    "Para que plataforma el formato 2:3 es especialmente estrategico?",
    [
      "Para YouTube y plataformas de video horizontal.",
      "Para banners y cabeceras de sitios.",
      "Para Pinterest, portadas de libros, posters y materiales impresos en retrato.",
      "El 2:3 solo funciona para moda y belleza.",
    ],
    2,
    "Los pins verticales ocupan mas espacio en Pinterest y los formatos editoriales tambien se benefician mucho de esta proporcion.",
  ),
  fillStep(
    "Rellena el espacio - Explora formatos extremos",
    "Completa los dos prompts con proporciones ultra amplias y ultra altas.",
    "/imagine ___, vista panoramica, estilo ___ ___ - banner ultra horizontal. /imagine ___, estilo ___ ___ - formato ultra vertical para exterior.",
    [
      "una vista aerea impresionante de la selva amazonica",
      "fotografia cinematografica",
      "--ar 21:9",
      "un rascacielos desapareciendo entre las nubes",
      "fotografia arquitectonica",
      "--ar 1:3",
    ],
    [
      "una vista aerea impresionante de la selva amazonica",
      "fotografia cinematografica",
      "--ar 21:9",
      "un rascacielos desapareciendo entre las nubes",
      "fotografia arquitectonica",
      "--ar 1:3",
    ],
    "Los formatos extremos solo tienen sentido cuando la proporcion forma parte del concepto final de la pieza.",
  ),
  quizStep(
    "Cuando se justifican formatos extremos",
    "Cuando se justifican formatos extremos como 21:9 o 1:3?",
    [
      "Para cualquier post en redes, solo para llamar la atencion.",
      "Cuando el usuario quiere probar los limites tecnicos de MidJourney.",
      "Para aplicaciones especificas como banners ultra horizontales, portadas de perfil, soportes verticales y composiciones conceptuales.",
      "Los formatos extremos generan errores y siempre deben evitarse.",
    ],
    2,
    "La proporcion extrema debe nacer del uso final. Si no, se convierte en exceso tecnico sin funcion estrategica.",
  ),
  fillStep(
    "Rellena el espacio - Entiende el impacto de la proporcion",
    "Completa como cambia el encuadre del mismo prompt segun el formato.",
    "El prompt '/imagine un chef cocinando en una cocina profesional' en ___ muestra al chef en primer plano con foco en rostro y manos. En ___ muestra al chef en plano abierto con toda la cocina al fondo. En ___ muestra un plano medio con equilibrio entre personaje y ambiente.",
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    "La misma descripcion cambia de encuadre porque MidJourney reorganiza los elementos para llenar mejor el espacio disponible.",
  ),
  quizStep(
    "Por que cambia la composicion",
    "Por que MidJourney genera composiciones distintas para el mismo prompt en proporciones diferentes?",
    [
      "Porque el modelo comete errores al interpretar parametros.",
      "Para obligar al usuario a comprar mas generaciones.",
      "Porque adapta inteligentemente el encuadre y la composicion para llenar el espacio disponible del modo mas equilibrado.",
      "MidJourney genera exactamente la misma composicion sin importar la proporcion.",
    ],
    2,
    "Un formato vertical favorece cercania y figura; uno horizontal favorece apertura y contexto. La IA recompone la escena segun el marco.",
  ),
  fillStep(
    "Rellena el espacio - Elige la proporcion correcta",
    "Completa la guia rapida por plataforma.",
    "Para ___ y Stories usa ___. Para el feed de ___ usa ___. Para ___ y banners horizontales usa ___. Para ___ y posters usa ___. Para Pinterest usa ___. Para fotos con apariencia de ___ profesional usa ___.",
    [
      "Reels y TikTok",
      "--ar 9:16",
      "Instagram",
      "--ar 4:5",
      "YouTube y presentaciones",
      "--ar 16:9",
      "portadas de libros",
      "--ar 2:3",
      "--ar 2:3",
      "camara",
      "--ar 3:2",
    ],
    [
      "Reels y TikTok",
      "--ar 9:16",
      "Instagram",
      "--ar 4:5",
      "YouTube y presentaciones",
      "--ar 16:9",
      "portadas de libros",
      "--ar 2:3",
      "--ar 2:3",
      "camara",
      "--ar 3:2",
    ],
    "Elegir bien la proporcion significa alinear la imagen con la plataforma real donde va a vivir.",
  ),
  quizStep(
    "Error mas comun con el tamano de imagen",
    "Cual es el error mas comun relacionado con el tamano de imagen en MidJourney?",
    [
      "Usar 16:9 para YouTube.",
      "Probar distintas proporciones con el mismo prompt.",
      "Crear todo en 1:1 y luego intentar adaptarlo a plataformas distintas, perdiendo composicion y encuadre.",
      "Usar --ar con numeros demasiado diferentes entre si.",
    ],
    2,
    "Generar todo en cuadrado y recortar despues parece practico, pero destruye la composicion pensada para cada canal.",
  ),
  fillStep(
    "Rellena el espacio - Cambia la proporcion",
    "Completa el proceso para adaptar un prompt a otro formato.",
    "Para generar la misma imagen en una proporcion distinta: copia el ___ original, sustituye el parametro ___ por la nueva proporcion y vuelve a enviarlo. MidJourney va a ___ los mismos elementos visuales en un ___ diferente, manteniendo el ___ y el ___ con un encuadre completamente nuevo.",
    ["prompt", "--ar", "recomponer", "formato", "estilo", "mood"],
    ["prompt", "--ar", "recomponer", "formato", "estilo", "mood"],
    "Al cambiar solo --ar, mantienes la base creativa y pides una composicion nueva para otra plataforma.",
  ),
  quizStep(
    "Multiples formatos, misma campana",
    "Que deberias hacer cuando necesitas una imagen en varios formatos para distintas plataformas?",
    [
      "Generar una sola imagen y recortarla para cada formato.",
      "Crear un prompt completamente distinto para cada plataforma.",
      "Usar el mismo prompt base y variar solo --ar para mantener consistencia visual entre versiones.",
      "Los multiples formatos solo son necesarios en campanas pagas.",
    ],
    2,
    "La mejor estrategia es conservar la identidad visual del prompt y dejar que la proporcion adapte el encuadre a cada canal.",
  ),
  textStep(
    "Conclusion",
    "El tamano y la proporcion de la imagen no son detalles tecnicos. Son decisiones estrategicas que definen composicion, impacto y aplicacion de cada visual creado en MidJourney. 1:1 para feed, 9:16 para Stories y Reels, 16:9 para YouTube y presentaciones, 4:5 para maximizar el feed, 2:3 para retratos y Pinterest: cada proporcion tiene una funcion y un poder.\n\nDominar --ar es lo que separa a quien crea imagenes bonitas de quien crea imagenes estrategicas, pensadas para el canal correcto, en el formato correcto y con la composicion correcta.",
  ),
] as const;
export const MIDJOURNEY_MODULE_3_STEPS_FR = [
  textStep(
    "Taille de l'image - maitriser la proportion et la composition",
    "Bienvenue a nouveau. Dans cette lecon, tu vas apprendre comment la taille et la proportion de l'image transforment completement la composition, l'impact et l'usage de n'importe quel visuel cree avec MidJourney, et comment choisir le bon format selon l'objectif.\n\nBeaucoup de debutants ignorent le format et gardent le carre par defaut pour tout. C'est une erreur strategique. La proportion definit la maniere dont l'oeil parcourt l'image, la place de chaque element et l'efficacite du visuel sur la plateforme finale.",
  ),
  quizStep(
    "Pourquoi la proportion compte",
    "Pourquoi choisir la bonne proportion est-il aussi important qu'ecrire un bon prompt?",
    [
      "Parce que la proportion definit la composition de la scene, l'espace disponible pour chaque element et la compatibilite avec la plateforme finale.",
      "Parce que MidJourney facture plus cher les formats non carres.",
      "Parce que la proportion ne compte que si l'image est imprimee.",
      "Parce que toute image peut etre recadree plus tard sans perte de composition ou de qualite.",
    ],
    0,
    "La proportion change la structure de la scene et l'usage final. Ce n'est pas un detail technique; c'est une decision strategique.",
  ),
  fillStep(
    "Completez les blancs - Utilisez correctement le parametre",
    "Completez l'explication de l'usage de --ar dans MidJourney.",
    "/imagine ___, style cinematographique, lumiere golden hour ___ Le parametre ___ se place a la ___ du prompt, apres tous les elements descriptifs. Vous pouvez utiliser des proportions comme ___, ___ ou ___ selon le resultat souhaite.",
    [
      "un vaste paysage de montagnes au coucher du soleil",
      "--ar 16:9",
      "--ar",
      "fin",
      "--ar 1:1",
      "--ar 4:5",
      "--ar 9:16",
    ],
    [
      "un vaste paysage de montagnes au coucher du soleil",
      "--ar 16:9",
      "--ar",
      "fin",
      "--ar 1:1",
      "--ar 4:5",
      "--ar 9:16",
    ],
    "Dans MidJourney, la proportion se regle avec --ar a la fin du prompt. Cela modifie le cadre lui-meme, pas seulement un recadrage apres coup.",
  ),
  quizStep(
    "Sans --ar dans le prompt",
    "Que se passe-t-il si vous ne precisez pas --ar dans le prompt?",
    [
      "MidJourney genere une erreur et demande une proportion.",
      "L'image sort dans le format que le modele juge le plus adapte.",
      "MidJourney utilise le 1:1 par defaut, le format carre, quel que soit le sujet ou la plateforme.",
      "Le format est aleatoire a chaque generation.",
    ],
    2,
    "Sans --ar, le comportement par defaut est 1:1. C'est pour cela que beaucoup de gens finissent avec des visuels carres sans l'avoir vraiment choisi.",
  ),
  fillStep(
    "Completez les blancs - Utilisez le format carre",
    "Construisez le prompt pour un visuel 1:1 centre.",
    "/imagine ___, photographie ___, fond ___, lumiere ___, composition centree, ___",
    [
      "une montre de luxe sur une surface en bois",
      "de produit commercial",
      "propre et sombre",
      "douce de studio",
      "--ar 1:1",
    ],
    [
      "une montre de luxe sur une surface en bois",
      "de produit commercial",
      "propre et sombre",
      "douce de studio",
      "--ar 1:1",
    ],
    "Le 1:1 fonctionne tres bien quand le sujet principal est centre et doit etre lu rapidement dans un feed ou une grille.",
  ),
  quizStep(
    "Quand le 1:1 est strategique",
    "Quand le format 1:1 est-il le plus strategique?",
    [
      "Pour des paysages larges et des environnements qui ont besoin d'air horizontal.",
      "Pour les Stories et les Reels Instagram.",
      "Pour le feed Instagram et Pinterest, les photos de profil, les produits isoles et les compositions centrees.",
      "Le 1:1 est depasse et ne devrait plus etre utilise.",
    ],
    2,
    "Le carre reste tres puissant quand la composition est centrale, directe et pensee pour le feed.",
  ),
  fillStep(
    "Completez les blancs - Creez en format large",
    "Completez le prompt pour une scene 16:9 cinematographique.",
    "/imagine ___, style ___, lumiere ___, atmosphere ___, plan general large, ___",
    [
      "un horizon de ville futuriste la nuit avec des voitures volantes",
      "concept art cyberpunk",
      "neon",
      "epique et immersive",
      "--ar 16:9",
    ],
    [
      "un horizon de ville futuriste la nuit avec des voitures volantes",
      "concept art cyberpunk",
      "neon",
      "epique et immersive",
      "--ar 16:9",
    ],
    "Le 16:9 ouvre la scene et laisse plus de place a la narration, a l'horizon et au contexte visuel.",
  ),
  quizStep(
    "Application ideale du 16:9",
    "Pour quelle application le 16:9 est-il le plus adapte?",
    [
      "Pour les posts verticaux du feed Instagram.",
      "Pour les photos de profil.",
      "Pour les thumbnails YouTube, couvertures de presentation, banniere web et tout visuel prevu pour un ecran horizontal.",
      "Le 16:9 ne fonctionne que pour l'architecture et les paysages urbains.",
    ],
    2,
    "Quand l'ecran final est horizontal, le 16:9 exploite mieux l'espace visible et semble naturel pour la plateforme.",
  ),
  fillStep(
    "Completez les blancs - Creez pour le mobile",
    "Construisez le prompt pour du 9:16 en plein ecran mobile.",
    "/imagine ___, style ___, lumiere ___, composition ___, humeur ___, en laissant de l'espace en haut et en bas pour du texte, ___",
    [
      "une jeune femme sure d'elle marchant dans un quartier de mode",
      "photographie street style",
      "naturelle urbaine",
      "corps entier vertical",
      "forte et energique",
      "--ar 9:16",
    ],
    [
      "une jeune femme sure d'elle marchant dans un quartier de mode",
      "photographie street style",
      "naturelle urbaine",
      "corps entier vertical",
      "forte et energique",
      "--ar 9:16",
    ],
    "Le 9:16 fonctionne mieux quand tu penses a la vraie experience plein ecran sur mobile, y compris l'espace pour le texte et le CTA.",
  ),
  quizStep(
    "Pourquoi le 9:16 domine le mobile",
    "Pourquoi le 9:16 domine-t-il aujourd'hui la consommation mobile?",
    [
      "Parce que les algorithmes favorisent automatiquement tout contenu vertical.",
      "Parce qu'il economise les donnees mobiles.",
      "Parce qu'il occupe 100 % de l'ecran du telephone en mode portrait, reduit les distractions et maximise l'immersion.",
      "Parce que le 9:16 ne fonctionne que pour la video.",
    ],
    2,
    "La puissance du 9:16 vient du plein ecran. C'est un avantage d'experience bien plus qu'un simple effet d'algorithme.",
  ),
  fillStep(
    "Completez les blancs - Creez pour le feed",
    "Completez le prompt pense pour un visuel 4:5.",
    "/imagine ___, style ___, lumiere ___, couleurs ___, composition ___, ___",
    [
      "un flat lay de cafe, un livre et des feuilles d'automne sur une table rustique",
      "photographie lifestyle",
      "naturelle, douce et chaude",
      "ambre et brun chaleureux",
      "vue du dessus",
      "--ar 4:5",
    ],
    [
      "un flat lay de cafe, un livre et des feuilles d'automne sur une table rustique",
      "photographie lifestyle",
      "naturelle, douce et chaude",
      "ambre et brun chaleureux",
      "vue du dessus",
      "--ar 4:5",
    ],
    "Le 4:5 donne plus de presence verticale dans le feed sans glisser vers un format story.",
  ),
  quizStep(
    "Pourquoi le 4:5 gagne dans le feed",
    "Pourquoi le 4:5 est-il considere comme le format le plus strategique pour le feed Instagram?",
    [
      "Parce qu'Instagram exige que tous les posts soient en 4:5.",
      "Parce qu'il cree une apparence differente des autres posts.",
      "Parce qu'il occupe plus de hauteur que le 1:1 sans devenir un story, ce qui augmente la presence du post dans le feed.",
      "Parce que le 4:5 genere automatiquement une meilleure resolution.",
    ],
    2,
    "Dans le feed, plus de hauteur signifie plus de presence et plus de chances de retenir l'attention avant le scroll.",
  ),
  fillStep(
    "Completez les blancs - Creez en format photo classique",
    "Construisez le prompt en 3:2 avec un langage photographique professionnel.",
    "/imagine ___, style photo ___, lumiere ___, profondeur de champ ___, couleurs ___, ___",
    [
      "des maries marchant dans un jardin fleuri",
      "editorial de mariage",
      "golden hour douce",
      "faible",
      "chaudes et romantiques",
      "--ar 3:2",
    ],
    [
      "des maries marchant dans un jardin fleuri",
      "editorial de mariage",
      "golden hour douce",
      "faible",
      "chaudes et romantiques",
      "--ar 3:2",
    ],
    "Le 3:2 rapproche l'image du langage classique de l'appareil photo, ideal pour un realisme photographique plus raffine.",
  ),
  quizStep(
    "Quand le 3:2 parait naturel",
    "Quand le format 3:2 est-il le plus naturel?",
    [
      "Pour du contenu social qui a besoin d'un format vertical.",
      "Pour des thumbnails et bannieres ultra larges.",
      "Pour des images qui doivent ressembler a une photo professionnelle prise avec un appareil, comme l'editorial, le portrait ou le paysage.",
      "Le 3:2 est obsolete et ne devrait plus etre utilise en digital.",
    ],
    2,
    "Le 3:2 correspond a la memoire visuelle de la photographie traditionnelle et parait donc plus naturel au public.",
  ),
  fillStep(
    "Completez les blancs - Creez un portrait vertical classique",
    "Completez le prompt pour du 2:3.",
    "/imagine ___, style ___, lumiere ___, fond ___, composition portrait ___, ___",
    [
      "une dirigeante puissante dans un tailleur impeccable",
      "photographie editoriale de mode",
      "dramatic studio",
      "sombre, flou et melancolique",
      "corps entier vertical",
      "--ar 2:3",
    ],
    [
      "une dirigeante puissante dans un tailleur impeccable",
      "photographie editoriale de mode",
      "dramatic studio",
      "sombre, flou et melancolique",
      "corps entier vertical",
      "--ar 2:3",
    ],
    "Le 2:3 marche tres bien pour le portrait vertical, la couverture, l'affiche et tout visuel qui a besoin de hauteur sans devenir un story.",
  ),
  quizStep(
    "Ou le 2:3 se distingue",
    "Pour quelle plateforme le 2:3 est-il particulierement strategique?",
    [
      "Pour YouTube et les plateformes video horizontales.",
      "Pour les bannieres et entetes de sites.",
      "Pour Pinterest, les couvertures de livres, les affiches et les supports imprimes en portrait.",
      "Le 2:3 ne fonctionne que pour la mode et la beaute.",
    ],
    2,
    "Les pins verticaux prennent plus de place dans Pinterest et les formats editoriaux profitent aussi beaucoup de cette proportion.",
  ),
  fillStep(
    "Completez les blancs - Explorez les formats extremes",
    "Completez les deux prompts avec des proportions ultra larges et ultra hautes.",
    "/imagine ___, vue panoramique, style ___ ___ - banniere ultra horizontale. /imagine ___, style ___ ___ - format ultra vertical pour affichage.",
    [
      "une vue aerienne spectaculaire de la foret amazonienne",
      "photographie cinematographique",
      "--ar 21:9",
      "un gratte-ciel disparaissant dans les nuages",
      "photographie architecturale",
      "--ar 1:3",
    ],
    [
      "une vue aerienne spectaculaire de la foret amazonienne",
      "photographie cinematographique",
      "--ar 21:9",
      "un gratte-ciel disparaissant dans les nuages",
      "photographie architecturale",
      "--ar 1:3",
    ],
    "Les formats extremes n'ont de sens que lorsque la proportion fait partie du concept final de la piece.",
  ),
  quizStep(
    "Quand les formats extremes se justifient",
    "Quand des formats extremes comme 21:9 ou 1:3 sont-ils justifies?",
    [
      "Pour tous les posts reseaux, juste pour attirer l'attention.",
      "Quand l'utilisateur veut tester les limites techniques de MidJourney.",
      "Pour des usages specifiques comme des bannieres ultra larges, des couvertures de profil, des supports verticaux et des compositions conceptuelles.",
      "Les formats extremes generent des erreurs et doivent toujours etre evites.",
    ],
    2,
    "La proportion extreme doit venir de l'usage final. Sinon, elle devient un exces technique sans valeur strategique.",
  ),
  fillStep(
    "Completez les blancs - Comprenez l'impact de la proportion",
    "Completez comment le cadrage change avec la meme consigne selon le format.",
    "Le prompt '/imagine un chef cuisinant dans une cuisine professionnelle' en ___ montre le chef en plan rapproche avec le visage et les mains en focus. En ___ il montre le chef en plan large avec toute la cuisine en fond. En ___ il montre un plan moyen avec un equilibre entre personnage et environnement.",
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    "La meme description change de cadrage parce que MidJourney reorganise la scene pour remplir au mieux l'espace disponible.",
  ),
  quizStep(
    "Pourquoi la composition change",
    "Pourquoi MidJourney genere-t-il des compositions differentes pour le meme prompt selon la proportion?",
    [
      "Parce que le modele fait des erreurs avec les parametres.",
      "Pour obliger l'utilisateur a acheter plus de generations.",
      "Parce qu'il adapte intelligemment le cadrage et la composition afin de remplir l'espace disponible de la facon la plus equilibree.",
      "MidJourney genere exactement la meme composition quelle que soit la proportion.",
    ],
    2,
    "Un format vertical favorise la proximite et le personnage, tandis qu'un format horizontal ouvre la scene et le contexte. L'IA recompose selon le cadre.",
  ),
  fillStep(
    "Completez les blancs - Choisissez la bonne proportion",
    "Completez le guide rapide par plateforme.",
    "Pour ___ et les Stories utilisez ___. Pour le feed ___ utilisez ___. Pour ___ et les bannieres horizontales utilisez ___. Pour ___ et les affiches utilisez ___. Pour Pinterest utilisez ___. Pour des photos avec une apparence d'appareil ___ utilisez ___.",
    [
      "Reels et TikTok",
      "--ar 9:16",
      "Instagram",
      "--ar 4:5",
      "YouTube et presentations",
      "--ar 16:9",
      "couvertures de livres",
      "--ar 2:3",
      "--ar 2:3",
      "photo",
      "--ar 3:2",
    ],
    [
      "Reels et TikTok",
      "--ar 9:16",
      "Instagram",
      "--ar 4:5",
      "YouTube et presentations",
      "--ar 16:9",
      "couvertures de livres",
      "--ar 2:3",
      "--ar 2:3",
      "photo",
      "--ar 3:2",
    ],
    "Bien choisir la proportion, c'est aligner l'image avec la plateforme ou elle va vraiment vivre.",
  ),
  quizStep(
    "Erreur la plus courante avec la taille d'image",
    "Quelle est l'erreur la plus courante concernant la taille d'image dans MidJourney?",
    [
      "Utiliser le 16:9 pour YouTube.",
      "Tester differentes proportions pour le meme prompt.",
      "Tout creer en 1:1 puis essayer d'adapter a plusieurs plateformes, en perdant cadrage et composition.",
      "Utiliser --ar avec des nombres trop eloignes les uns des autres.",
    ],
    2,
    "Tout generer en carre puis recadrer ensuite parait pratique, mais detruit la composition pensee pour chaque canal.",
  ),
  fillStep(
    "Completez les blancs - Changez la proportion",
    "Completez le processus pour adapter un prompt a un autre format.",
    "Pour generer la meme image dans une autre proportion: copiez le ___ original, remplacez le parametre ___ par la nouvelle proportion et renvoyez-le. MidJourney va ___ les memes elements visuels dans un ___ different, en gardant le ___ et le ___ avec un cadrage completement nouveau.",
    ["prompt", "--ar", "recomposer", "format", "style", "mood"],
    ["prompt", "--ar", "recomposer", "format", "style", "mood"],
    "Quand vous changez seulement --ar, vous gardez la base creative et vous demandez une nouvelle composition pour une autre plateforme.",
  ),
  quizStep(
    "Plusieurs formats, meme campagne",
    "Que faut-il faire lorsqu'une image doit exister dans plusieurs formats pour differentes plateformes?",
    [
      "Generer une seule image puis la recadrer pour chaque format.",
      "Creer un prompt totalement different pour chaque plateforme.",
      "Utiliser le meme prompt de base et ne faire varier que --ar afin de garder une coherence visuelle entre les versions.",
      "Les formats multiples ne sont necessaires que pour les campagnes payantes.",
    ],
    2,
    "La meilleure strategie consiste a conserver l'identite visuelle du prompt et a laisser la proportion adapter le cadrage selon le canal.",
  ),
  textStep(
    "Conclusion",
    "La taille et la proportion de l'image ne sont pas des details techniques. Ce sont des decisions strategiques qui definissent la composition, l'impact et l'usage de chaque visuel cree dans MidJourney. 1:1 pour le feed, 9:16 pour Stories et Reels, 16:9 pour YouTube et les presentations, 4:5 pour maximiser la presence dans le feed, 2:3 pour les portraits et Pinterest - chaque proportion a sa fonction et sa force.\n\nMaitriser --ar, c'est ce qui separe une personne qui cree de belles images d'une personne qui cree des images strategiques, pensees pour le bon canal, dans le bon format et avec la bonne composition.",
  ),
] as const;
