const textStep = (title: string, content: string, promptBox?: string) => ({
  type: "text" as const,
  title,
  content,
  ...(promptBox ? { promptBox } : {}),
});

const quizStep = (
  title: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
) => ({
  type: "quiz" as const,
  title,
  question,
  options,
  correctIndex,
  explanation,
});

const fillStep = (
  title: string,
  instruction: string,
  sentence: string,
  answers: string[],
  options: string[],
  explanation: string,
) => ({
  type: "fill_blanks" as const,
  title,
  instruction,
  sentence,
  answers,
  options,
  explanation,
});

export const MIDJOURNEY_MODULE_5_STEPS_PT = [
  textStep(
    "Combinando modos no MidJourney - Camadas de intencao no mesmo prompt",
    "Bem-vindo de volta. Nesta licao, voce vai aprender a combinar modos, estilos, iluminacoes, pontos de vista, paletas e parametros no mesmo prompt. A ideia aqui nao e empilhar termos bonitos. E construir uma imagem em camadas, em que cada decisao reforca a anterior e empurra o MidJourney para uma visao muito mais precisa.\n\nIniciantes descrevem o sujeito. Intermediarios adicionam estilo e luz. Avancados combinam multiplas camadas com intencao, criando um resultado que parece pensado por uma direcao criativa inteira, nao por um prompt generico.",
  ),
  quizStep(
    "O que torna um prompt combinado avancado",
    "O que diferencia um prompt com modos combinados de um prompt simples?",
    [
      "Cada elemento funciona como uma instrucao especifica que guia o MidJourney em uma direcao criativa precisa.",
      "Prompts com mais elementos sao sempre mais longos e lentos para gerar.",
      "Combinar modos so funciona para quem tem plano premium.",
      "Adicionar muitos elementos sempre confunde o modelo e piora o resultado.",
    ],
    0,
    "O valor nao esta na quantidade de palavras. Esta em como cada camada reforca uma intencao criativa clara.",
  ),
  fillStep(
    "Preencha a lacuna - Entenda a estrutura",
    "Organize a estrutura logica de um prompt combinado do mais essencial ao mais refinado.",
    "A estrutura ideal de um prompt combinado e: ___ + ___ + ___ + ___ + ___ + ___ + ___.",
    [
      "sujeito e acao",
      "ambiente e contexto",
      "estilo artistico",
      "ponto de vista",
      "iluminacao",
      "paleta de cores",
      "parametros tecnicos",
    ],
    [
      "sujeito e acao",
      "ambiente e contexto",
      "estilo artistico",
      "ponto de vista",
      "iluminacao",
      "paleta de cores",
      "parametros tecnicos",
    ],
    "Cada camada responde a uma pergunta diferente: o que, onde, como, de qual angulo, com qual luz, em quais cores e em qual formato.",
  ),
  quizStep(
    "Por que a estrutura melhora o resultado",
    "Por que seguir uma estrutura logica ao combinar modos melhora o resultado?",
    [
      "Porque o MidJourney le o prompt em ordem e ignora o resto.",
      "Para deixar o prompt visualmente bonito, sem impacto real.",
      "Porque cada camada responde a uma pergunta especifica e juntas formam uma instrucao visual completa.",
      "Porque a ordem nao influencia nada, mas deixa o criador mais calmo.",
    ],
    2,
    "Estrutura nao e enfeite. E organizacao de pensamento. Quanto mais coerente a ordem, mais clara fica a imagem final.",
  ),
  textStep(
    "Estilo + iluminacao",
    "A primeira combinacao poderosa e unir um estilo artistico com a iluminacao que melhor amplifica sua estetica. Quando estilo e luz apontam para a mesma atmosfera, o resultado fica muito mais coeso.\n\nPense assim: algumas combinacoes parecem naturais porque compartilham o mesmo universo emocional.",
    "Combinacoes naturais:\ncinematografico + golden hour = epico e cinematografico\npintura a oleo + chiaroscuro = artistico e historico\ncyberpunk + neon = urbano e futurista",
  ),
  fillStep(
    "Preencha a lacuna - Una estilo e iluminacao",
    "Complete o prompt com uma combinacao natural entre estilo, luz, atmosfera e cor.",
    "/imagine ___, estilo ___, iluminacao ___, atmosfera ___, cores ___, ___.",
    [
      "um cavaleiro solitario a cavalo cruzando um campo de batalha enevoado",
      "arte conceitual dark fantasy",
      "volumetrica dourada",
      "epica e dramatica",
      "tons terrosos profundos",
      "--ar 16:9",
    ],
    [
      "um cavaleiro solitario a cavalo cruzando um campo de batalha enevoado",
      "arte conceitual dark fantasy",
      "volumetrica dourada",
      "epica e dramatica",
      "tons terrosos profundos",
      "--ar 16:9",
    ],
    "Quando estilo, luz, atmosfera e cor falam a mesma lingua emocional, a imagem parece muito mais intencional.",
  ),
  quizStep(
    "Cyberpunk + Neon",
    "Por que combinar Cyberpunk com Neon Lighting cria um resultado mais coeso do que Cyberpunk com Golden Hour?",
    [
      "Porque o MidJourney tem restricoes tecnicas para Golden Hour.",
      "Porque toda combinacao urbana precisa seguir essa convencao.",
      "Porque o cyberpunk depende de artificialidade urbana noturna, e o neon reforca exatamente essa identidade.",
      "Porque qualquer combinacao de estilo e iluminacao gera resultados equivalentes.",
    ],
    2,
    "Cyberpunk e sintese de cidade, artificialidade e noite. Neon amplifica isso. Golden Hour empurra a imagem para outra atmosfera.",
  ),
  fillStep(
    "Preencha a lacuna - Adicione ponto de vista",
    "Complete o prompt combinando ponto de vista, estilo e luz na mesma cena.",
    "/imagine ___, enquadramento ___, estilo ___, iluminacao ___, clima ___, cores ___, ___.",
    [
      "uma astronauta flutuando perto de uma estacao espacial com a Terra visivel ao fundo",
      "low angle worm's eye view",
      "fotografia cinematografica sci-fi",
      "rim light dramatica com fundo de espaco profundo",
      "inspirador e meditativo",
      "azul frio e prata",
      "--ar 9:16",
    ],
    [
      "uma astronauta flutuando perto de uma estacao espacial com a Terra visivel ao fundo",
      "low angle worm's eye view",
      "fotografia cinematografica sci-fi",
      "rim light dramatica com fundo de espaco profundo",
      "inspirador e meditativo",
      "azul frio e prata",
      "--ar 9:16",
    ],
    "Aqui voce ja nao esta so descrevendo um sujeito. Esta dizendo como ele deve ser visto, sentido e enquadrado.",
  ),
  quizStep(
    "Low Angle + Rim + cinematografico",
    "O que a combinacao de Low Angle com Rim Lighting e estilo cinematografico cria nessa imagem?",
    [
      "Uma imagem tecnica e informativa sobre exploracao espacial.",
      "Um retrato documental simples de uma astronauta em trabalho.",
      "Uma composicao epica em que angulo, luz e estilo se unem como um frame de filme de grande orcamento.",
      "Um conflito visual em que as tecnicas se anulam.",
    ],
    2,
    "O angulo amplia poder, a rim light adiciona presenca e o estilo cinematografico costura tudo em uma linguagem unica.",
  ),
  textStep(
    "Referencias artisticas hibridas",
    "Uma das tecnicas mais sofisticadas e combinar duas referencias artisticas diferentes para criar um estilo hibrido. O objetivo nao e parecer estranho. E parecer unico.\n\nA forca dessa abordagem esta em pegar o que cada universo tem de mais reconhecivel e unir isso de forma coerente.",
    "Hibridos fortes:\nfotografia moderna + pintura renascentista\nanime japones + noir ocidental\naquarela classica + flat design moderno",
  ),
  fillStep(
    "Preencha a lacuna - Crie um estilo hibrido",
    "Complete o prompt com duas referencias artisticas que se complementam.",
    "/imagine ___, estilo ___ encontra ___, iluminacao ___, paleta ___, composicao ___, ___.",
    [
      "uma imperatriz poderosa em seu trono",
      "pintura barroca",
      "fotografia editorial moderna",
      "chiaroscuro",
      "ouro intenso e vermelho carmim",
      "simetrica e imponente",
      "--ar 2:3",
    ],
    [
      "uma imperatriz poderosa em seu trono",
      "pintura barroca",
      "fotografia editorial moderna",
      "chiaroscuro",
      "ouro intenso e vermelho carmim",
      "simetrica e imponente",
      "--ar 2:3",
    ],
    "As referencias se tornam originais quando cada uma entrega um valor claro: uma traz heranca visual, a outra traz leitura contemporanea.",
  ),
  quizStep(
    "Por que o hibrido gera originalidade",
    "Por que combinar duas referencias artisticas diferentes cria resultados mais originais?",
    [
      "Porque o MidJourney nao entende estilos hibridos e improvisa.",
      "Para criar imagens que ninguem consiga identificar.",
      "Porque cada referencia contribui com elementos reconheciveis e a fusao cria uma estetica nova sem copiar nenhuma delas por inteiro.",
      "Porque combinar referencias sempre gera imagens confusas e experimentais.",
    ],
    2,
    "Originalidade vem de fusao coerente, nao de aleatoriedade. Hibrido bom soma identidades sem destruir legibilidade.",
  ),
  textStep(
    "Paleta + mood",
    "Paleta de cores e mood sao dois dos elementos mais importantes para decidir como o espectador vai se sentir diante da imagem. Quando eles estao alinhados, a emocao chega rapido. Quando entram em conflito, a mensagem perde forca.",
    "Combinacoes de paleta e mood:\nazul frio e cinza + melancolico = melancolia sofisticada\namarelo quente e laranja + alegre = energia e otimismo\nroxo profundo e preto + ominoso = misterio e tensao",
  ),
  fillStep(
    "Preencha a lacuna - Una cores e emocao",
    "Complete o prompt alinhando paleta, clima e atmosfera emocional.",
    "/imagine ___, estilo ___, iluminacao ___, paleta ___, clima ___, atmosfera ___, ___.",
    [
      "uma bailarina dancando sozinha em um palco vazio",
      "fotografia fine art",
      "luar azul suave",
      "azul dessaturado e prata",
      "melancolico e etereo",
      "onirica e poetica",
      "--ar 9:16",
    ],
    [
      "uma bailarina dancando sozinha em um palco vazio",
      "fotografia fine art",
      "luar azul suave",
      "azul dessaturado e prata",
      "melancolico e etereo",
      "onirica e poetica",
      "--ar 9:16",
    ],
    "Quando paleta, clima e atmosfera contam a mesma historia, a emocao da imagem chega de forma muito mais imediata.",
  ),
  quizStep(
    "Paleta e mood no marketing",
    "Por que alinhar paleta de cores e mood e essencial em imagens para marketing?",
    [
      "Porque cada cor tem um significado universal fixo.",
      "Porque isso torna a imagem tecnicamente mais correta.",
      "Porque quando paleta e mood estao alinhados, o cerebro le a emocao da imagem de forma coerente e imediata.",
      "Porque paleta e mood sao independentes e servem apenas como decoracao.",
    ],
    2,
    "Marketing visual depende de leitura rapida. Se cor e emocao brigam entre si, a mensagem enfraquece.",
  ),
  fillStep(
    "Preencha a lacuna - Crie produto avancado",
    "Complete o prompt de fotografia de produto premium.",
    "/imagine ___, angulo ___, fundo ___, iluminacao ___, estilo ___, detalhe ___, sensacao ___, ___.",
    [
      "um frasco de perfume preto de luxo com detalhes dourados e fumaca ao redor",
      "low angle",
      "superficie de marmore escuro com reflexos sutis",
      "luz dramatica direcional unica com rim light",
      "fotografia editorial comercial",
      "ultra alto 8K",
      "cara, premium e sedutora",
      "--ar 4:5",
    ],
    [
      "um frasco de perfume preto de luxo com detalhes dourados e fumaca ao redor",
      "low angle",
      "superficie de marmore escuro com reflexos sutis",
      "luz dramatica direcional unica com rim light",
      "fotografia editorial comercial",
      "ultra alto 8K",
      "cara, premium e sedutora",
      "--ar 4:5",
    ],
    "Produto premium nasce de contexto visual. Angulo, luz, fundo e estilo criam valor antes mesmo da pessoa saber o preco.",
  ),
  quizStep(
    "Luxo visual em produto",
    "Qual combinacao de modos cria a percepcao de luxo e premium em fotografia de produto?",
    [
      "High Angle com Soft Box e fundo branco limpo.",
      "Bird's Eye View com luz natural e cores neutras.",
      "Low Angle para grandiosidade, rim light para presenca, fundo escuro para sofisticacao e estilo editorial para posicionamento premium.",
      "A percepcao de luxo vem apenas da qualidade do produto, nao do prompt.",
    ],
    2,
    "Antes de conhecer o produto, o publico ja le status, valor e desejo por meio da imagem.",
  ),
  fillStep(
    "Preencha a lacuna - Crie retrato cinematografico",
    "Complete o prompt de retrato com profundidade emocional.",
    "/imagine ___, enquadramento ___, estilo ___, iluminacao ___, fundo ___, expressao ___, clima ___, ___.",
    [
      "um velho pescador de rosto marcado com olhos bondosos",
      "close up eye level",
      "fotografia documental cinematografica",
      "chiaroscuro suave com luz lateral quente",
      "oceano desfocado ao por do sol",
      "digna e contemplativa",
      "profundamente humano e atemporal",
      "--ar 4:5",
    ],
    [
      "um velho pescador de rosto marcado com olhos bondosos",
      "close up eye level",
      "fotografia documental cinematografica",
      "chiaroscuro suave com luz lateral quente",
      "oceano desfocado ao por do sol",
      "digna e contemplativa",
      "profundamente humano e atemporal",
      "--ar 4:5",
    ],
    "Aqui as camadas funcionam juntas para fazer a imagem parecer um retrato vivido, nao apenas bonito.",
  ),
  quizStep(
    "Retrato cinematografico poderoso",
    "Por que a combinacao de Close Up com Chiaroscuro e estilo documentario cria um retrato tao poderoso?",
    [
      "Porque sao tres tecnicas avancadas e raras no MidJourney.",
      "Porque geram um retrato tecnicamente chamativo, mesmo sem emocao.",
      "Porque o Close Up revela o humano, o Chiaroscuro traz profundidade dramatica e o documentario adiciona autenticidade.",
      "Porque essas tecnicas sempre produzem o mesmo retrato, independentemente do sujeito.",
    ],
    2,
    "O rosto deixa de ser so um rosto. Ele passa a carregar tempo, historia e presenca emocional.",
  ),
  fillStep(
    "Preencha a lacuna - Crie paisagem epica",
    "Complete o prompt de paisagem com escala e atmosfera.",
    "/imagine ___, enquadramento ___, estilo ___, iluminacao ___, atmosfera ___, cores ___, figura humana ___ para escala, ___.",
    [
      "um glaciar colossal encontrando um oceano artico tempestuoso",
      "wide establishing",
      "fotografia epica de paisagem",
      "blue hour com neblina volumetrica",
      "dramatica e primordial",
      "azul petroleo profundo e branco",
      "em silhueta",
      "--ar 16:9",
    ],
    [
      "um glaciar colossal encontrando um oceano artico tempestuoso",
      "wide establishing",
      "fotografia epica de paisagem",
      "blue hour com neblina volumetrica",
      "dramatica e primordial",
      "azul petroleo profundo e branco",
      "em silhueta",
      "--ar 16:9",
    ],
    "Paisagem epica nao depende so de tamanho. Depende de contraste de escala, atmosfera e leitura emocional.",
  ),
  quizStep(
    "Silhueta em paisagem epica",
    "Por que adicionar uma figura humana em silhueta a uma paisagem epica amplifica o impacto visual?",
    [
      "Para mostrar que a cena e segura para o ser humano.",
      "Porque MidJourney gera paisagens melhores quando ha personagens.",
      "Porque o contraste entre a escala minuscula da figura e a imensidao da paisagem comunica grandiosidade e aventura de forma imediata.",
      "Porque figuras humanas sempre desviam o olhar do elemento principal.",
    ],
    2,
    "Sem comparacao de escala, o espectador pode ate achar a paisagem bonita, mas sente menos a sua grandeza.",
  ),
  fillStep(
    "Preencha a lacuna - Monte o prompt definitivo",
    "Complete o prompt que alinha sujeito, ambiente, estilo, luz, paleta, clima e atmosfera.",
    "/imagine ___, em ___, enquadramento ___, estilo ___, iluminacao ___, paleta ___, clima ___, atmosfera ___, ___.",
    [
      "um samurai solitario meditando",
      "uma antiga floresta de bambu ao amanhecer com neblina matinal",
      "low angle",
      "fotografia dark fantasy cinematografica com ukiyo-e",
      "volumetrica dourada com rim light",
      "verde suave, dourado e preto",
      "profundamente espiritual e poderoso",
      "atemporal e epica",
      "--ar 9:16",
    ],
    [
      "um samurai solitario meditando",
      "uma antiga floresta de bambu ao amanhecer com neblina matinal",
      "low angle",
      "fotografia dark fantasy cinematografica com ukiyo-e",
      "volumetrica dourada com rim light",
      "verde suave, dourado e preto",
      "profundamente espiritual e poderoso",
      "atemporal e epica",
      "--ar 9:16",
    ],
    "Esse tipo de prompt funciona porque todas as camadas estao alinhadas. Nada esta sobrando. Nada esta competindo.",
  ),
  quizStep(
    "Quando todas as camadas encaixam",
    "Qual e o resultado quando todas as camadas de um prompt estao perfeitamente alinhadas?",
    [
      "Uma imagem tecnicamente perfeita, mas emocionalmente vazia.",
      "Uma imagem confusa, com muitos elementos competindo.",
      "Uma imagem com identidade visual unica e coerente, em que cada camada reforca as outras.",
      "Um resultado pior do que um prompt simples.",
    ],
    2,
    "Coerencia nao simplifica a imagem. Ela da direcao. E direcao e o que faz o visual parecer profissional.",
  ),
  fillStep(
    "Preencha a lacuna - Evite os erros",
    "Complete a frase com os erros mais comuns ao combinar modos.",
    "Os erros mais comuns ao combinar modos sao: misturar estilos ___ que se contradizem, usar iluminacao ___ com o estilo escolhido, combinar paleta e clima ___, adicionar elementos ___ sem proposito claro e ___ elementos ate criar ambiguidade visual.",
    [
      "incompativeis",
      "incoerente",
      "conflitantes",
      "desnecessarios",
      "acumular",
    ],
    [
      "incompativeis",
      "incoerente",
      "conflitantes",
      "desnecessarios",
      "acumular",
    ],
    "O problema nao e ter varias camadas. O problema e ter varias camadas puxando para direcoes diferentes.",
  ),
  quizStep(
    "Erro mais comum em modos avancados",
    "Qual e o erro mais comum ao tentar combinar modos avancados no MidJourney?",
    [
      "Usar mais de dois tipos de iluminacao no mesmo prompt.",
      "Combinar estilos de periodos historicos diferentes.",
      "Adicionar elementos sem intencao criativa clara, acumulando termos fortes que nao se comunicam entre si.",
      "Combinar ponto de vista com iluminacao no mesmo prompt.",
    ],
    2,
    "Prompt avancado nao e lista de palavras impressionantes. E composicao intencional. Sem isso, o resultado fica confuso.",
  ),
  textStep(
    "Conclusao",
    "Combinar modos e a habilidade que transforma o MidJourney de um gerador de imagens em um estudio criativo. Estilo com iluminacao, ponto de vista com mood, paleta com atmosfera, referencias artisticas hibridas e todas as camadas unidas em um unico prompt com intencao clara criam possibilidades que nenhum elemento isolado conseguiria produzir.\n\nO segredo nao e usar mais elementos. E usar os elementos certos, na ordem certa, reforcando a mesma ideia visual do inicio ao fim.",
  ),
] as const;

export const MIDJOURNEY_MODULE_5_STEPS_EN = [
  textStep(
    "Combining modes in MidJourney - Building images with layered intent",
    "Welcome back. In this lesson, you will learn how to combine modes, styles, lighting, point of view, palettes, and parameters inside the same prompt. The goal is not to stack impressive words. The goal is to build an image in layers, where each choice reinforces the previous one and pushes MidJourney toward a much more precise vision.\n\nBeginners describe the subject. Intermediate users add style and light. Advanced users combine multiple layers with intent, creating results that feel directed instead of generic.",
  ),
  quizStep(
    "What makes a combined prompt advanced",
    "What differentiates a prompt with combined modes from a simple prompt?",
    [
      "Each added element works as a specific instruction that guides MidJourney toward a precise creative direction.",
      "Prompts with more elements are always longer and slower to generate.",
      "Combining modes only works for premium subscribers.",
      "Adding many elements always confuses the model and worsens the result.",
    ],
    0,
    "The power does not come from word count. It comes from how each layer reinforces a clear creative intention.",
  ),
  fillStep(
    "Fill in the blanks - Understand the structure",
    "Organize the logical structure of a layered prompt from essential to refined.",
    "The ideal structure of a combined prompt is: ___ + ___ + ___ + ___ + ___ + ___ + ___.",
    [
      "subject and action",
      "environment and context",
      "artistic style",
      "point of view",
      "lighting",
      "color palette",
      "technical parameters",
    ],
    [
      "subject and action",
      "environment and context",
      "artistic style",
      "point of view",
      "lighting",
      "color palette",
      "technical parameters",
    ],
    "Each layer answers a different question: what, where, how, from which angle, with what light, in which colors, and in what format.",
  ),
  quizStep(
    "Why structure improves results",
    "Why does following a logical structure improve the result when combining modes?",
    [
      "Because MidJourney reads prompts in order and ignores the end.",
      "Because it makes the prompt look neat without any real benefit.",
      "Because each layer answers a specific question and together they create a complete visual instruction.",
      "Because order does not matter, but it helps the creator feel organized.",
    ],
    2,
    "Structure is not decoration. It is organized thinking. The more coherent the order, the clearer the image becomes.",
  ),
  textStep(
    "Style + lighting",
    "The first powerful combination is pairing an artistic style with the type of lighting that best amplifies its aesthetic. When style and light point toward the same atmosphere, the result becomes much more cohesive.\n\nSome combinations feel natural because they share the same emotional universe.",
    "Natural combinations:\ncinematic + golden hour = epic and cinematic\noil painting + chiaroscuro = artistic and historical\ncyberpunk + neon = urban and futuristic",
  ),
  fillStep(
    "Fill in the blanks - Match style and lighting",
    "Complete the prompt with a natural combination of style, light, atmosphere, and color.",
    "/imagine ___, ___ style, ___ lighting, ___ atmosphere, ___ colors, ___.",
    [
      "a lone knight on a horse crossing a misty battlefield",
      "dark fantasy concept art",
      "volumetric golden",
      "epic and dramatic",
      "deep earthy tones",
      "--ar 16:9",
    ],
    [
      "a lone knight on a horse crossing a misty battlefield",
      "dark fantasy concept art",
      "volumetric golden",
      "epic and dramatic",
      "deep earthy tones",
      "--ar 16:9",
    ],
    "When style, light, atmosphere, and color all push in the same emotional direction, the image feels far more intentional.",
  ),
  quizStep(
    "Cyberpunk + Neon",
    "Why does pairing Cyberpunk with Neon Lighting feel more cohesive than Cyberpunk with Golden Hour?",
    [
      "Because MidJourney technically restricts Golden Hour with cyberpunk.",
      "Because every urban style must follow that convention.",
      "Because cyberpunk depends on synthetic urban night energy, and neon reinforces that identity directly.",
      "Because any style and lighting combination works equally well.",
    ],
    2,
    "Cyberpunk is built on artificial city energy and night atmosphere. Neon supports that. Golden Hour pushes the image somewhere else.",
  ),
  fillStep(
    "Fill in the blanks - Add point of view",
    "Complete the prompt by combining viewpoint, style, and lighting in one scene.",
    "/imagine ___, ___ shot, ___ style, ___ lighting, ___ mood, ___ colors, ___.",
    [
      "a female astronaut floating near a space station with Earth visible below",
      "low angle worm's eye view",
      "cinematic sci-fi photography",
      "dramatic rim with deep space background",
      "awe-inspiring and meditative",
      "cool blue and silver",
      "--ar 9:16",
    ],
    [
      "a female astronaut floating near a space station with Earth visible below",
      "low angle worm's eye view",
      "cinematic sci-fi photography",
      "dramatic rim with deep space background",
      "awe-inspiring and meditative",
      "cool blue and silver",
      "--ar 9:16",
    ],
    "At this point you are no longer only describing a subject. You are directing how it must be seen, felt, and framed.",
  ),
  quizStep(
    "Low Angle + Rim + cinematic",
    "What does the combination of Low Angle, Rim Lighting, and cinematic style create in this image?",
    [
      "A technical and informative image about space exploration.",
      "A documentary portrait of an astronaut at work.",
      "An epic composition where angle, light, and style work together like a large-budget film frame.",
      "A visual conflict in which the techniques cancel one another out.",
    ],
    2,
    "The angle expands power, the rim light adds presence, and the cinematic style unifies everything into one language.",
  ),
  textStep(
    "Hybrid artistic references",
    "One of the most sophisticated techniques is combining two artistic references to create a hybrid visual language. The goal is not to feel random. The goal is to feel unique.\n\nThe power of this approach comes from taking the most recognizable strength of each universe and merging them coherently.",
    "Strong hybrids:\nmodern photography + Renaissance painting\nanime + western noir\nclassic watercolor + modern flat design",
  ),
  fillStep(
    "Fill in the blanks - Create a hybrid style",
    "Complete the prompt with two complementary artistic references.",
    "/imagine ___, ___ meets ___ style, ___ lighting, ___ color palette, ___ composition, ___.",
    [
      "a powerful empress on her throne",
      "Baroque painting",
      "modern editorial photography",
      "chiaroscuro",
      "rich gold and deep crimson",
      "symmetrical and regal",
      "--ar 2:3",
    ],
    [
      "a powerful empress on her throne",
      "Baroque painting",
      "modern editorial photography",
      "chiaroscuro",
      "rich gold and deep crimson",
      "symmetrical and regal",
      "--ar 2:3",
    ],
    "References become original when each one contributes a clear value: one brings historical weight, the other brings contemporary readability.",
  ),
  quizStep(
    "Why hybrid references feel original",
    "Why does combining two different artistic references create more original results?",
    [
      "Because MidJourney does not understand hybrid styles and improvises.",
      "To make images that nobody can identify.",
      "Because each reference contributes recognizable elements, and their fusion creates a new aesthetic without copying either one fully.",
      "Because combining references always produces confusing experimental images.",
    ],
    2,
    "Originality comes from coherent fusion, not from randomness. A good hybrid adds identities without breaking legibility.",
  ),
  textStep(
    "Palette + mood",
    "Color palette and mood are two of the strongest elements for deciding how the viewer will feel in front of the image. When they align, emotion lands quickly. When they clash, the message loses force.",
    "Palette and mood pairings:\ncool blue and grey + melancholic = sophisticated melancholy\nwarm yellow and orange + joyful = energy and optimism\ndeep purple and black + ominous = mystery and tension",
  ),
  fillStep(
    "Fill in the blanks - Join color and emotion",
    "Complete the prompt by aligning palette, mood, and atmosphere.",
    "/imagine ___, ___ style, ___ lighting, ___ color palette, ___ mood, ___ atmosphere, ___.",
    [
      "a ballerina dancing alone on an empty stage",
      "fine art photography",
      "soft blue moonlight",
      "desaturated blue and silver",
      "melancholic and ethereal",
      "dreamlike and poetic",
      "--ar 9:16",
    ],
    [
      "a ballerina dancing alone on an empty stage",
      "fine art photography",
      "soft blue moonlight",
      "desaturated blue and silver",
      "melancholic and ethereal",
      "dreamlike and poetic",
      "--ar 9:16",
    ],
    "When palette, mood, and atmosphere tell the same story, emotion reaches the viewer much faster.",
  ),
  quizStep(
    "Palette and mood in marketing",
    "Why is aligning color palette and mood essential in marketing images?",
    [
      "Because every color has a fixed universal meaning.",
      "Because it makes the image technically more correct.",
      "Because when palette and mood align, the brain reads the emotion of the image in a coherent and immediate way.",
      "Because palette and mood are decorative and independent.",
    ],
    2,
    "Visual marketing depends on fast reading. If color and emotion fight each other, the message weakens.",
  ),
  fillStep(
    "Fill in the blanks - Create advanced product imagery",
    "Complete the premium product photography prompt.",
    "/imagine ___, ___ angle, ___ background, ___ lighting, ___ style, ___ detail, ___ feel, ___.",
    [
      "a luxury black perfume bottle with gold details and smoke around it",
      "low angle",
      "dark marble surface with subtle reflections",
      "dramatic single directional with rim light",
      "commercial editorial photography",
      "ultra high 8K",
      "expensive premium and seductive",
      "--ar 4:5",
    ],
    [
      "a luxury black perfume bottle with gold details and smoke around it",
      "low angle",
      "dark marble surface with subtle reflections",
      "dramatic single directional with rim light",
      "commercial editorial photography",
      "ultra high 8K",
      "expensive premium and seductive",
      "--ar 4:5",
    ],
    "Premium product perception starts in context. Angle, light, background, and style create value before the viewer even knows the price.",
  ),
  quizStep(
    "Luxury visual language",
    "Which combination of modes creates the strongest luxury and premium perception in product photography?",
    [
      "High Angle with Soft Box and a clean white background.",
      "Bird's Eye View with natural lighting and neutral colors.",
      "Low Angle for grandeur, rim light for presence, dark background for sophistication, and editorial style for premium positioning.",
      "Luxury comes only from product quality, not from prompt choices.",
    ],
    2,
    "Before the product is understood, the audience is already reading status, value, and desire through the image.",
  ),
  fillStep(
    "Fill in the blanks - Create a cinematic portrait",
    "Complete the portrait prompt with emotional depth.",
    "/imagine ___, ___ shot, ___ style, ___ lighting, ___ background, ___ expression, ___ mood, ___.",
    [
      "a weathered old fisherman with deep wrinkles and kind eyes",
      "close up eye level",
      "cinematic documentary photography",
      "soft chiaroscuro with warm side light",
      "blurred ocean at sunset",
      "dignified and contemplative",
      "deeply human and timeless",
      "--ar 4:5",
    ],
    [
      "a weathered old fisherman with deep wrinkles and kind eyes",
      "close up eye level",
      "cinematic documentary photography",
      "soft chiaroscuro with warm side light",
      "blurred ocean at sunset",
      "dignified and contemplative",
      "deeply human and timeless",
      "--ar 4:5",
    ],
    "Here the layers work together to make the image feel lived-in, not merely attractive.",
  ),
  quizStep(
    "Why the portrait feels powerful",
    "Why does combining Close Up, Chiaroscuro, and documentary style create such a powerful portrait?",
    [
      "Because they are three rare advanced techniques in MidJourney.",
      "Because they generate a technically striking image, even without emotion.",
      "Because Close Up reveals the human details, Chiaroscuro adds dramatic depth, and documentary style adds authenticity.",
      "Because those techniques always create the same portrait no matter the subject.",
    ],
    2,
    "The face stops being just a face. It starts carrying time, history, and emotional presence.",
  ),
  fillStep(
    "Fill in the blanks - Create an epic landscape",
    "Complete the landscape prompt with scale and atmosphere.",
    "/imagine ___, ___ shot, ___ style, ___ lighting, ___ atmosphere, ___ colors, ___ tiny human figure for scale, ___.",
    [
      "a massive glacier meeting a stormy arctic ocean",
      "wide establishing",
      "epic landscape photography",
      "blue hour with volumetric mist",
      "dramatic and primordial",
      "deep teal blue and white",
      "silhouetted",
      "--ar 16:9",
    ],
    [
      "a massive glacier meeting a stormy arctic ocean",
      "wide establishing",
      "epic landscape photography",
      "blue hour with volumetric mist",
      "dramatic and primordial",
      "deep teal blue and white",
      "silhouetted",
      "--ar 16:9",
    ],
    "Epic landscape work is not only about size. It is about scale contrast, atmosphere, and emotional framing.",
  ),
  quizStep(
    "Silhouette in an epic landscape",
    "Why does adding a silhouetted human figure amplify the impact of an epic landscape?",
    [
      "To show that the environment is safe for humans.",
      "Because MidJourney always generates better landscapes when a character is present.",
      "Because the contrast between tiny human scale and environmental immensity communicates grandeur and adventure immediately.",
      "Because human figures always pull focus away from the landscape.",
    ],
    2,
    "Without scale comparison, the viewer may find the landscape beautiful, but will feel less of its true magnitude.",
  ),
  fillStep(
    "Fill in the blanks - Build the definitive prompt",
    "Complete the prompt that aligns subject, environment, style, light, palette, mood, and atmosphere.",
    "/imagine ___, in ___, ___ shot, ___ style, ___ lighting, ___ palette, ___ mood, ___ atmosphere, ___.",
    [
      "a lone samurai meditating",
      "an ancient bamboo forest at dawn with morning mist",
      "low angle",
      "dark fantasy cinematic photography meets ukiyo-e art",
      "volumetric golden with rim light",
      "muted green gold and black",
      "deeply spiritual and powerful",
      "timeless and epic",
      "--ar 9:16",
    ],
    [
      "a lone samurai meditating",
      "an ancient bamboo forest at dawn with morning mist",
      "low angle",
      "dark fantasy cinematic photography meets ukiyo-e art",
      "volumetric golden with rim light",
      "muted green gold and black",
      "deeply spiritual and powerful",
      "timeless and epic",
      "--ar 9:16",
    ],
    "This kind of prompt works because all layers align. Nothing feels wasted. Nothing competes with the main idea.",
  ),
  quizStep(
    "When every layer aligns",
    "What happens when all layers of a prompt are perfectly aligned?",
    [
      "You get a technically perfect but emotionally empty image.",
      "You get a confused image with too many competing elements.",
      "You get a unique and coherent visual identity where every layer reinforces the others.",
      "You get a worse result than a simpler prompt.",
    ],
    2,
    "Coherence does not flatten the image. It gives it direction, and direction is what makes the visual feel professional.",
  ),
  fillStep(
    "Fill in the blanks - Avoid the mistakes",
    "Complete the sentence with the most common mistakes when combining modes.",
    "The most common mistakes when combining modes are: mixing ___ styles that contradict each other, using ___ lighting with the chosen style, pairing palette and mood that are ___, adding ___ elements without clear purpose, and ___ elements until visual ambiguity appears.",
    [
      "incompatible",
      "incoherent",
      "conflicting",
      "unnecessary",
      "accumulating",
    ],
    [
      "incompatible",
      "incoherent",
      "conflicting",
      "unnecessary",
      "accumulating",
    ],
    "The issue is not having many layers. The issue is having many layers pulling in different directions.",
  ),
  quizStep(
    "Most common advanced-mode mistake",
    "What is the most common mistake when trying to combine advanced modes in MidJourney?",
    [
      "Using more than two lighting styles in the same prompt.",
      "Combining styles from different historical periods.",
      "Adding elements without clear creative intent, stacking strong terms that do not communicate with one another.",
      "Combining point of view with lighting in the same prompt.",
    ],
    2,
    "An advanced prompt is not a list of impressive words. It is intentional composition. Without that, the image turns muddy.",
  ),
  textStep(
    "Conclusion",
    "Combining modes is the skill that turns MidJourney from an image generator into a creative studio. Style with lighting, point of view with mood, palette with atmosphere, hybrid artistic references, and all layers unified inside one clear prompt create possibilities that no isolated element could produce.\n\nThe secret is not using more elements. The secret is using the right elements in the right order, reinforcing the same visual idea from start to finish.",
  ),
] as const;

export const MIDJOURNEY_MODULE_5_STEPS_ES = [
  textStep(
    "Combinar modos en MidJourney - Construir imagenes con capas de intencion",
    "Bienvenido de nuevo. En esta leccion vas a aprender a combinar modos, estilos, iluminaciones, puntos de vista, paletas y parametros dentro del mismo prompt. La idea no es acumular palabras llamativas. La idea es construir una imagen por capas, donde cada decision refuerza la anterior y empuja a MidJourney hacia una vision mucho mas precisa.\n\nLos principiantes describen el sujeto. Los intermedios agregan estilo y luz. Los avanzados combinan multiples capas con intencion y consiguen resultados dirigidos, no genericos.",
  ),
  quizStep(
    "Que vuelve avanzado a un prompt combinado",
    "Que diferencia a un prompt con modos combinados de un prompt simple?",
    [
      "Cada elemento agregado funciona como una instruccion especifica que guia a MidJourney hacia una direccion creativa precisa.",
      "Los prompts con mas elementos siempre son mas largos y tardan mas.",
      "Combinar modos solo funciona para usuarios premium.",
      "Agregar muchos elementos siempre confunde al modelo y empeora el resultado.",
    ],
    0,
    "El poder no viene de la cantidad de palabras. Viene de como cada capa refuerza una intencion creativa clara.",
  ),
  fillStep(
    "Completa los espacios - Entiende la estructura",
    "Organiza la estructura logica de un prompt por capas desde lo esencial hasta lo refinado.",
    "La estructura ideal de un prompt combinado es: ___ + ___ + ___ + ___ + ___ + ___ + ___.",
    [
      "sujeto y accion",
      "ambiente y contexto",
      "estilo artistico",
      "punto de vista",
      "iluminacion",
      "paleta de colores",
      "parametros tecnicos",
    ],
    [
      "sujeto y accion",
      "ambiente y contexto",
      "estilo artistico",
      "punto de vista",
      "iluminacion",
      "paleta de colores",
      "parametros tecnicos",
    ],
    "Cada capa responde una pregunta distinta: que, donde, como, desde que angulo, con que luz, en que colores y en que formato.",
  ),
  quizStep(
    "Por que la estructura mejora el resultado",
    "Por que seguir una estructura logica mejora el resultado al combinar modos?",
    [
      "Porque MidJourney lee en orden y luego ignora el resto.",
      "Porque hace que el prompt se vea ordenado sin beneficio real.",
      "Porque cada capa responde una pregunta concreta y juntas forman una instruccion visual completa.",
      "Porque el orden no importa, pero deja tranquilo al creador.",
    ],
    2,
    "La estructura no es decoracion. Es pensamiento organizado. Cuanto mas coherente es el orden, mas clara sale la imagen.",
  ),
  textStep(
    "Estilo + iluminacion",
    "La primera combinacion poderosa es unir un estilo artistico con el tipo de luz que mejor potencia su estetica. Cuando estilo y luz apuntan a la misma atmosfera, el resultado se vuelve mucho mas coherente.\n\nAlgunas combinaciones parecen naturales porque comparten el mismo universo emocional.",
    "Combinaciones naturales:\ncinematic + golden hour = epico y cinematografico\noil painting + chiaroscuro = artistico e historico\ncyberpunk + neon = urbano y futurista",
  ),
  fillStep(
    "Completa los espacios - Une estilo e iluminacion",
    "Completa el prompt con una combinacion natural de estilo, luz, atmosfera y color.",
    "/imagine ___, estilo ___, iluminacion ___, atmosfera ___, colores ___, ___.",
    [
      "un caballero solitario a caballo cruzando un campo de batalla con niebla",
      "arte conceptual dark fantasy",
      "volumetrica dorada",
      "epica y dramatica",
      "tonos terrosos profundos",
      "--ar 16:9",
    ],
    [
      "un caballero solitario a caballo cruzando un campo de batalla con niebla",
      "arte conceptual dark fantasy",
      "volumetrica dorada",
      "epica y dramatica",
      "tonos terrosos profundos",
      "--ar 16:9",
    ],
    "Cuando estilo, luz, atmosfera y color empujan en la misma direccion emocional, la imagen se siente mucho mas intencional.",
  ),
  quizStep(
    "Cyberpunk + Neon",
    "Por que combinar Cyberpunk con Neon Lighting se siente mas coherente que combinar Cyberpunk con Golden Hour?",
    [
      "Porque MidJourney restringe tecnicamente Golden Hour con cyberpunk.",
      "Porque todo estilo urbano debe seguir esa convencion.",
      "Porque el cyberpunk depende de energia urbana nocturna y sintetica, y el neon refuerza exactamente esa identidad.",
      "Porque cualquier combinacion de estilo e iluminacion funciona igual de bien.",
    ],
    2,
    "Cyberpunk esta construido sobre artificialidad, ciudad y noche. Neon lo empuja aun mas hacia esa identidad.",
  ),
  fillStep(
    "Completa los espacios - Agrega punto de vista",
    "Completa el prompt combinando punto de vista, estilo e iluminacion.",
    "/imagine ___, encuadre ___, estilo ___, iluminacion ___, mood ___, colores ___, ___.",
    [
      "una astronauta flotando cerca de una estacion espacial con la Tierra visible abajo",
      "low angle worm's eye view",
      "fotografia cinematografica sci-fi",
      "rim light dramatica con fondo de espacio profundo",
      "inspirador y meditativo",
      "azul frio y plata",
      "--ar 9:16",
    ],
    [
      "una astronauta flotando cerca de una estacion espacial con la Tierra visible abajo",
      "low angle worm's eye view",
      "fotografia cinematografica sci-fi",
      "rim light dramatica con fondo de espacio profundo",
      "inspirador y meditativo",
      "azul frio y plata",
      "--ar 9:16",
    ],
    "Aqui ya no solo describes un sujeto. Estas dirigiendo como debe verse, sentirse y encuadrarse.",
  ),
  quizStep(
    "Low Angle + Rim + cinematografico",
    "Que crea la combinacion de Low Angle, Rim Lighting y estilo cinematografico en esta imagen?",
    [
      "Una imagen tecnica e informativa sobre exploracion espacial.",
      "Un retrato documental sencillo de una astronauta trabajando.",
      "Una composicion epica donde angulo, luz y estilo se unen como un fotograma de gran presupuesto.",
      "Un conflicto visual en el que las tecnicas se anulan.",
    ],
    2,
    "El angulo amplifica poder, la rim light agrega presencia y el estilo cinematografico unifica todo en un mismo lenguaje.",
  ),
  textStep(
    "Referencias artisticas hibridas",
    "Una de las tecnicas mas sofisticadas es combinar dos referencias artisticas para crear un lenguaje visual hibrido. El objetivo no es verse aleatorio. El objetivo es verse unico.\n\nLa fuerza de este enfoque nace de tomar lo mas reconocible de cada universo y mezclarlo con coherencia.",
    "Hibridos potentes:\nfotografia moderna + pintura renacentista\nanime + noir occidental\nacuarela clasica + flat design moderno",
  ),
  fillStep(
    "Completa los espacios - Crea un estilo hibrido",
    "Completa el prompt con dos referencias artisticas complementarias.",
    "/imagine ___, estilo ___ encuentra ___, iluminacion ___, paleta ___, composicion ___, ___.",
    [
      "una emperatriz poderosa en su trono",
      "pintura barroca",
      "fotografia editorial moderna",
      "chiaroscuro",
      "oro intenso y rojo carmesi",
      "simetrica y regia",
      "--ar 2:3",
    ],
    [
      "una emperatriz poderosa en su trono",
      "pintura barroca",
      "fotografia editorial moderna",
      "chiaroscuro",
      "oro intenso y rojo carmesi",
      "simetrica y regia",
      "--ar 2:3",
    ],
    "Las referencias se vuelven originales cuando cada una aporta un valor claro: una da peso historico y la otra legibilidad contemporanea.",
  ),
  quizStep(
    "Por que el hibrido se siente original",
    "Por que combinar dos referencias artisticas diferentes produce resultados mas originales?",
    [
      "Porque MidJourney no entiende estilos hibridos y improvisa.",
      "Para crear imagenes que nadie pueda identificar.",
      "Porque cada referencia aporta elementos reconocibles y la fusion crea una estetica nueva sin copiar ninguna por completo.",
      "Porque combinar referencias siempre produce imagenes confusas.",
    ],
    2,
    "La originalidad nace de una fusion coherente, no del caos. Un buen hibrido suma identidades sin romper legibilidad.",
  ),
  textStep(
    "Paleta + mood",
    "La paleta de color y el mood son dos de los elementos mas fuertes para decidir como se va a sentir el espectador frente a la imagen. Cuando se alinean, la emocion llega rapido. Cuando chocan, el mensaje pierde fuerza.",
    "Parejas de paleta y mood:\nazul frio y gris + melancolico = melancolia sofisticada\namarillo calido y naranja + alegre = energia y optimismo\nmorado profundo y negro + ominoso = misterio y tension",
  ),
  fillStep(
    "Completa los espacios - Une color y emocion",
    "Completa el prompt alineando paleta, mood y atmosfera.",
    "/imagine ___, estilo ___, iluminacion ___, paleta ___, mood ___, atmosfera ___, ___.",
    [
      "una bailarina bailando sola sobre un escenario vacio",
      "fotografia fine art",
      "luz de luna azul suave",
      "azul desaturado y plata",
      "melancolico y etereo",
      "onirica y poetica",
      "--ar 9:16",
    ],
    [
      "una bailarina bailando sola sobre un escenario vacio",
      "fotografia fine art",
      "luz de luna azul suave",
      "azul desaturado y plata",
      "melancolico y etereo",
      "onirica y poetica",
      "--ar 9:16",
    ],
    "Cuando paleta, mood y atmosfera cuentan la misma historia, la emocion llega al espectador mucho mas rapido.",
  ),
  quizStep(
    "Paleta y mood en marketing",
    "Por que alinear paleta de colores y mood es esencial en imagenes de marketing?",
    [
      "Porque cada color tiene un significado universal fijo.",
      "Porque vuelve la imagen tecnicamente mas correcta.",
      "Porque cuando paleta y mood se alinean, el cerebro lee la emocion de forma coherente e inmediata.",
      "Porque paleta y mood son decorativos e independientes.",
    ],
    2,
    "El marketing visual depende de lectura rapida. Si color y emocion chocan, el mensaje pierde fuerza.",
  ),
  fillStep(
    "Completa los espacios - Crea producto avanzado",
    "Completa el prompt de fotografia premium de producto.",
    "/imagine ___, angulo ___, fondo ___, iluminacion ___, estilo ___, detalle ___, sensacion ___, ___.",
    [
      "un frasco de perfume negro de lujo con detalles dorados y humo alrededor",
      "low angle",
      "superficie de marmol oscuro con reflejos sutiles",
      "luz dramatica direccional unica con rim light",
      "fotografia editorial comercial",
      "ultra alto 8K",
      "cara, premium y seductora",
      "--ar 4:5",
    ],
    [
      "un frasco de perfume negro de lujo con detalles dorados y humo alrededor",
      "low angle",
      "superficie de marmol oscuro con reflejos sutiles",
      "luz dramatica direccional unica con rim light",
      "fotografia editorial comercial",
      "ultra alto 8K",
      "cara, premium y seductora",
      "--ar 4:5",
    ],
    "La percepcion premium del producto empieza en el contexto. Angulo, luz, fondo y estilo crean valor antes de conocer el precio.",
  ),
  quizStep(
    "Lenguaje visual del lujo",
    "Que combinacion de modos crea la percepcion mas fuerte de lujo y premium en fotografia de producto?",
    [
      "High Angle con Soft Box y fondo blanco limpio.",
      "Bird's Eye View con luz natural y colores neutros.",
      "Low Angle para grandeza, rim light para presencia, fondo oscuro para sofisticacion y estilo editorial para posicionamiento premium.",
      "El lujo depende solo de la calidad del producto, no del prompt.",
    ],
    2,
    "Antes de entender el producto, el publico ya esta leyendo estatus, valor y deseo a traves de la imagen.",
  ),
  fillStep(
    "Completa los espacios - Crea retrato cinematografico",
    "Completa el prompt de retrato con profundidad emocional.",
    "/imagine ___, encuadre ___, estilo ___, iluminacion ___, fondo ___, expresion ___, mood ___, ___.",
    [
      "un viejo pescador de rostro marcado con ojos bondadosos",
      "close up eye level",
      "fotografia documental cinematografica",
      "chiaroscuro suave con luz lateral calida",
      "oceano desenfocado al atardecer",
      "digna y contemplativa",
      "profundamente humano y atemporal",
      "--ar 4:5",
    ],
    [
      "un viejo pescador de rostro marcado con ojos bondadosos",
      "close up eye level",
      "fotografia documental cinematografica",
      "chiaroscuro suave con luz lateral calida",
      "oceano desenfocado al atardecer",
      "digna y contemplativa",
      "profundamente humano y atemporal",
      "--ar 4:5",
    ],
    "Aqui las capas trabajan juntas para que la imagen se sienta vivida, no solo bonita.",
  ),
  quizStep(
    "Por que el retrato se siente potente",
    "Por que la combinacion de Close Up, Chiaroscuro y estilo documental crea un retrato tan poderoso?",
    [
      "Porque son tres tecnicas raras y avanzadas de MidJourney.",
      "Porque generan una imagen tecnicamente llamativa, aunque no tenga emocion.",
      "Porque Close Up revela lo humano, Chiaroscuro agrega profundidad dramatica y el documental aporta autenticidad.",
      "Porque esas tecnicas siempre generan el mismo retrato sin importar el sujeto.",
    ],
    2,
    "El rostro deja de ser solo un rostro. Empieza a cargar tiempo, historia y presencia emocional.",
  ),
  fillStep(
    "Completa los espacios - Crea paisaje epico",
    "Completa el prompt de paisaje con escala y atmosfera.",
    "/imagine ___, encuadre ___, estilo ___, iluminacion ___, atmosfera ___, colores ___, figura humana ___ para escala, ___.",
    [
      "un glaciar colosal encontrandose con un oceano artico tormentoso",
      "wide establishing",
      "fotografia epica de paisaje",
      "blue hour con niebla volumetrica",
      "dramatica y primordial",
      "azul petroleo profundo y blanco",
      "en silueta",
      "--ar 16:9",
    ],
    [
      "un glaciar colosal encontrandose con un oceano artico tormentoso",
      "wide establishing",
      "fotografia epica de paisaje",
      "blue hour con niebla volumetrica",
      "dramatica y primordial",
      "azul petroleo profundo y blanco",
      "en silueta",
      "--ar 16:9",
    ],
    "El paisaje epico no depende solo del tamano. Depende del contraste de escala, de la atmosfera y del encuadre emocional.",
  ),
  quizStep(
    "Silueta en paisaje epico",
    "Por que agregar una figura humana en silueta amplifica el impacto de un paisaje epico?",
    [
      "Para mostrar que el entorno es seguro para el ser humano.",
      "Porque MidJourney genera mejores paisajes si hay personajes.",
      "Porque el contraste entre la escala minuscula de la figura y la inmensidad del entorno comunica grandeza y aventura de inmediato.",
      "Porque las figuras humanas siempre distraen del paisaje.",
    ],
    2,
    "Sin comparacion de escala, el espectador puede ver belleza, pero sentir menos la verdadera magnitud del entorno.",
  ),
  fillStep(
    "Completa los espacios - Construye el prompt definitivo",
    "Completa el prompt que alinea sujeto, ambiente, estilo, luz, paleta, mood y atmosfera.",
    "/imagine ___, en ___, encuadre ___, estilo ___, iluminacion ___, paleta ___, mood ___, atmosfera ___, ___.",
    [
      "un samurai solitario meditando",
      "un antiguo bosque de bambu al amanecer con niebla matinal",
      "low angle",
      "fotografia dark fantasy cinematografica con ukiyo-e",
      "volumetrica dorada con rim light",
      "verde suave, dorado y negro",
      "profundamente espiritual y poderoso",
      "atemporal y epica",
      "--ar 9:16",
    ],
    [
      "un samurai solitario meditando",
      "un antiguo bosque de bambu al amanecer con niebla matinal",
      "low angle",
      "fotografia dark fantasy cinematografica con ukiyo-e",
      "volumetrica dorada con rim light",
      "verde suave, dorado y negro",
      "profundamente espiritual y poderoso",
      "atemporal y epica",
      "--ar 9:16",
    ],
    "Este tipo de prompt funciona porque todas las capas estan alineadas. Nada sobra. Nada compite.",
  ),
  quizStep(
    "Cuando todas las capas encajan",
    "Que ocurre cuando todas las capas de un prompt estan perfectamente alineadas?",
    [
      "Obtienes una imagen tecnicamente perfecta pero emocionalmente vacia.",
      "Obtienes una imagen confusa con demasiados elementos compitiendo.",
      "Obtienes una identidad visual unica y coherente donde cada capa refuerza a las demas.",
      "Obtienes un resultado peor que con un prompt simple.",
    ],
    2,
    "La coherencia no simplifica la imagen. Le da direccion, y la direccion es lo que hace que el visual se sienta profesional.",
  ),
  fillStep(
    "Completa los espacios - Evita los errores",
    "Completa la frase con los errores mas comunes al combinar modos.",
    "Los errores mas comunes al combinar modos son: mezclar estilos ___ que se contradicen, usar iluminacion ___ con el estilo elegido, combinar paleta y mood ___, agregar elementos ___ sin un proposito claro y ___ elementos hasta crear ambiguedad visual.",
    [
      "incompatibles",
      "incoherente",
      "conflictivos",
      "innecesarios",
      "acumular",
    ],
    [
      "incompatibles",
      "incoherente",
      "conflictivos",
      "innecesarios",
      "acumular",
    ],
    "El problema no es tener muchas capas. El problema es tener muchas capas tirando hacia direcciones distintas.",
  ),
  quizStep(
    "Error mas comun en modos avanzados",
    "Cual es el error mas comun al intentar combinar modos avanzados en MidJourney?",
    [
      "Usar mas de dos tipos de iluminacion en el mismo prompt.",
      "Combinar estilos de periodos historicos distintos.",
      "Agregar elementos sin intencion creativa clara, apilando terminos fuertes que no se comunican entre si.",
      "Combinar punto de vista con iluminacion en el mismo prompt.",
    ],
    2,
    "Un prompt avanzado no es una lista de palabras impresionantes. Es composicion intencional. Sin eso, la imagen se ensucia.",
  ),
  textStep(
    "Conclusion",
    "Combinar modos es la habilidad que convierte MidJourney de generador de imagenes en estudio creativo. Estilo con iluminacion, punto de vista con mood, paleta con atmosfera, referencias artisticas hibridas y todas las capas reunidas en un solo prompt claro abren posibilidades que ningun elemento aislado podria producir.\n\nEl secreto no es usar mas elementos. El secreto es usar los elementos correctos, en el orden correcto, reforzando la misma idea visual de principio a fin.",
  ),
] as const;

export const MIDJOURNEY_MODULE_5_STEPS_FR = [
  textStep(
    "Combiner les modes dans MidJourney - Construire des images en couches d'intention",
    "Bon retour. Dans cette lecon, tu vas apprendre a combiner modes, styles, lumieres, points de vue, palettes et parametres dans un seul prompt. L'objectif n'est pas d'empiler des mots impressionnants. L'objectif est de construire une image par couches, ou chaque decision renforce la precedente et pousse MidJourney vers une vision beaucoup plus precise.\n\nLes debutants decrivent le sujet. Les intermediaires ajoutent style et lumiere. Les avances combinent plusieurs couches avec intention et obtiennent un resultat dirige, pas generique.",
  ),
  quizStep(
    "Ce qui rend un prompt avance",
    "Qu'est-ce qui differencie un prompt a modes combines d'un prompt simple ?",
    [
      "Chaque element ajoute agit comme une instruction precise qui guide MidJourney vers une direction creative claire.",
      "Les prompts avec plus d'elements sont toujours plus longs et plus lents.",
      "Combiner les modes fonctionne seulement pour les abonnements premium.",
      "Ajouter beaucoup d'elements embrouille toujours le modele et degrade le resultat.",
    ],
    0,
    "La force ne vient pas du nombre de mots. Elle vient de la maniere dont chaque couche renforce une intention creative nette.",
  ),
  fillStep(
    "Complete les blancs - Comprends la structure",
    "Organise la structure logique d'un prompt en couches du plus essentiel au plus raffine.",
    "La structure ideale d'un prompt combine est : ___ + ___ + ___ + ___ + ___ + ___ + ___.",
    [
      "sujet et action",
      "environnement et contexte",
      "style artistique",
      "point de vue",
      "eclairage",
      "palette de couleurs",
      "parametres techniques",
    ],
    [
      "sujet et action",
      "environnement et contexte",
      "style artistique",
      "point de vue",
      "eclairage",
      "palette de couleurs",
      "parametres techniques",
    ],
    "Chaque couche repond a une question differente : quoi, ou, comment, sous quel angle, avec quelle lumiere, dans quelles couleurs et dans quel format.",
  ),
  quizStep(
    "Pourquoi la structure ameliore le resultat",
    "Pourquoi suivre une structure logique ameliore-t-il le resultat quand on combine les modes ?",
    [
      "Parce que MidJourney lit dans l'ordre puis ignore la fin.",
      "Parce que cela rend le prompt plus propre sans vrai effet.",
      "Parce que chaque couche repond a une question precise et qu'ensemble elles forment une instruction visuelle complete.",
      "Parce que l'ordre n'a pas d'importance, mais rassure le createur.",
    ],
    2,
    "La structure n'est pas decorative. C'est une pensee organisee. Plus l'ordre est coherent, plus l'image devient claire.",
  ),
  textStep(
    "Style + lumiere",
    "La premiere combinaison puissante consiste a associer un style artistique au type de lumiere qui renforce le mieux son esthetique. Quand style et lumiere poussent vers la meme atmosphere, le resultat devient beaucoup plus coherent.\n\nCertaines associations paraissent naturelles parce qu'elles partagent le meme univers emotionnel.",
    "Associations naturelles :\ncinematic + golden hour = epique et cinematographique\noil painting + chiaroscuro = artistique et historique\ncyberpunk + neon = urbain et futuriste",
  ),
  fillStep(
    "Complete les blancs - Associe style et lumiere",
    "Complete le prompt avec une combinaison naturelle de style, lumiere, atmosphere et couleur.",
    "/imagine ___, style ___, eclairage ___, atmosphere ___, couleurs ___, ___.",
    [
      "un chevalier solitaire a cheval traversant un champ de bataille brumeux",
      "art conceptuel dark fantasy",
      "volumetrique doree",
      "epique et dramatique",
      "tons terreux profonds",
      "--ar 16:9",
    ],
    [
      "un chevalier solitaire a cheval traversant un champ de bataille brumeux",
      "art conceptuel dark fantasy",
      "volumetrique doree",
      "epique et dramatique",
      "tons terreux profonds",
      "--ar 16:9",
    ],
    "Quand style, lumiere, atmosphere et couleur avancent dans la meme direction emotionnelle, l'image parait beaucoup plus intentionnelle.",
  ),
  quizStep(
    "Cyberpunk + Neon",
    "Pourquoi l'association Cyberpunk + Neon Lighting parait-elle plus coherente que Cyberpunk + Golden Hour ?",
    [
      "Parce que MidJourney limite techniquement Golden Hour avec cyberpunk.",
      "Parce que tout style urbain doit suivre cette convention.",
      "Parce que le cyberpunk repose sur une energie nocturne, urbaine et artificielle, que le neon renforce directement.",
      "Parce que toutes les combinaisons style + lumiere fonctionnent de la meme maniere.",
    ],
    2,
    "Le cyberpunk est construit sur l'artificialite, la ville et la nuit. Le neon pousse encore plus cette identite.",
  ),
  fillStep(
    "Complete les blancs - Ajoute le point de vue",
    "Complete le prompt en combinant point de vue, style et lumiere.",
    "/imagine ___, cadrage ___, style ___, eclairage ___, mood ___, couleurs ___, ___.",
    [
      "une astronaute flottant pres d'une station spatiale avec la Terre visible en dessous",
      "low angle worm's eye view",
      "photographie cinematographique sci-fi",
      "rim light dramatique avec fond d'espace profond",
      "inspirant et meditatif",
      "bleu froid et argent",
      "--ar 9:16",
    ],
    [
      "une astronaute flottant pres d'une station spatiale avec la Terre visible en dessous",
      "low angle worm's eye view",
      "photographie cinematographique sci-fi",
      "rim light dramatique avec fond d'espace profond",
      "inspirant et meditatif",
      "bleu froid et argent",
      "--ar 9:16",
    ],
    "A ce stade, tu ne decris plus seulement un sujet. Tu diriges la facon dont il doit etre vu, ressenti et cadre.",
  ),
  quizStep(
    "Low Angle + Rim + cinematographique",
    "Que cree la combinaison Low Angle + Rim Lighting + style cinematographique dans cette image ?",
    [
      "Une image technique et informative sur l'exploration spatiale.",
      "Un portrait documentaire simple d'une astronaute au travail.",
      "Une composition epique ou angle, lumiere et style s'unissent comme un plan de film a gros budget.",
      "Un conflit visuel dans lequel les techniques s'annulent.",
    ],
    2,
    "L'angle amplifie la puissance, la rim light ajoute de la presence et le style cinematographique relie le tout dans un seul langage.",
  ),
  textStep(
    "References artistiques hybrides",
    "L'une des techniques les plus sophistiquees consiste a combiner deux references artistiques pour creer un langage visuel hybride. L'objectif n'est pas de paraitre aleatoire. L'objectif est de paraitre unique.\n\nLa force de cette approche vient du fait qu'on prend ce qu'il y a de plus reconnaissable dans chaque univers et qu'on le fusionne de facon coherente.",
    "Hybrides puissants :\nphotographie moderne + peinture de la Renaissance\nanime + noir occidental\naquarelle classique + flat design moderne",
  ),
  fillStep(
    "Complete les blancs - Cree un style hybride",
    "Complete le prompt avec deux references artistiques complementaires.",
    "/imagine ___, style ___ rencontre ___, eclairage ___, palette ___, composition ___, ___.",
    [
      "une imperatrice puissante sur son trone",
      "peinture baroque",
      "photographie editoriale moderne",
      "chiaroscuro",
      "or intense et rouge cramoisi",
      "symetrique et royale",
      "--ar 2:3",
    ],
    [
      "une imperatrice puissante sur son trone",
      "peinture baroque",
      "photographie editoriale moderne",
      "chiaroscuro",
      "or intense et rouge cramoisi",
      "symetrique et royale",
      "--ar 2:3",
    ],
    "Les references deviennent originales quand chacune apporte une valeur claire : l'une apporte le poids historique, l'autre une lecture contemporaine.",
  ),
  quizStep(
    "Pourquoi l'hybride parait original",
    "Pourquoi combiner deux references artistiques differentes produit-il des resultats plus originaux ?",
    [
      "Parce que MidJourney ne comprend pas les styles hybrides et improvise.",
      "Pour creer des images que personne ne peut identifier.",
      "Parce que chaque reference apporte des elements reconnaissables et leur fusion cree une esthetique nouvelle sans copier entierement l'une d'elles.",
      "Parce que combiner des references produit toujours des images confuses.",
    ],
    2,
    "L'originalite vient d'une fusion coherente, pas du chaos. Un bon hybride additionne les identites sans casser la lisibilite.",
  ),
  textStep(
    "Palette + mood",
    "La palette de couleurs et le mood sont deux des elements les plus forts pour decider de ce que le spectateur va ressentir face a l'image. Lorsqu'ils sont alignes, l'emotion arrive vite. Lorsqu'ils s'opposent, le message perd de sa force.",
    "Associations palette et mood :\nbleu froid et gris + melancolique = melancolie sophistiquee\njaune chaud et orange + joyeux = energie et optimisme\nviolet profond et noir + ominous = mystere et tension",
  ),
  fillStep(
    "Complete les blancs - Relie couleur et emotion",
    "Complete le prompt en alignant palette, mood et atmosphere.",
    "/imagine ___, style ___, eclairage ___, palette ___, mood ___, atmosphere ___, ___.",
    [
      "une ballerine dansant seule sur une scene vide",
      "photographie fine art",
      "clair de lune bleu doux",
      "bleu desature et argent",
      "melancolique et ethere",
      "onirique et poetique",
      "--ar 9:16",
    ],
    [
      "une ballerine dansant seule sur une scene vide",
      "photographie fine art",
      "clair de lune bleu doux",
      "bleu desature et argent",
      "melancolique et ethere",
      "onirique et poetique",
      "--ar 9:16",
    ],
    "Quand palette, mood et atmosphere racontent la meme histoire, l'emotion atteint le spectateur beaucoup plus vite.",
  ),
  quizStep(
    "Palette et mood en marketing",
    "Pourquoi aligner palette de couleurs et mood est-il essentiel dans les images marketing ?",
    [
      "Parce que chaque couleur a une signification universelle fixe.",
      "Parce que cela rend l'image techniquement plus correcte.",
      "Parce que lorsque palette et mood sont alignes, le cerveau lit l'emotion de facon coherente et immediate.",
      "Parce que palette et mood sont decoratifs et independants.",
    ],
    2,
    "Le marketing visuel depend d'une lecture rapide. Si couleur et emotion s'opposent, le message faiblit.",
  ),
  fillStep(
    "Complete les blancs - Cree un produit avance",
    "Complete le prompt de photographie premium de produit.",
    "/imagine ___, angle ___, fond ___, eclairage ___, style ___, detail ___, sensation ___, ___.",
    [
      "un flacon de parfum noir de luxe avec des details dores et de la fumee autour",
      "low angle",
      "surface de marbre sombre avec reflets subtils",
      "lumiere dramatique directionnelle unique avec rim light",
      "photographie editoriale commerciale",
      "ultra haute 8K",
      "chere, premium et seduisante",
      "--ar 4:5",
    ],
    [
      "un flacon de parfum noir de luxe avec des details dores et de la fumee autour",
      "low angle",
      "surface de marbre sombre avec reflets subtils",
      "lumiere dramatique directionnelle unique avec rim light",
      "photographie editoriale commerciale",
      "ultra haute 8K",
      "chere, premium et seduisante",
      "--ar 4:5",
    ],
    "La perception premium d'un produit commence dans son contexte visuel. Angle, lumiere, fond et style creent de la valeur avant meme de connaitre le prix.",
  ),
  quizStep(
    "Langage visuel du luxe",
    "Quelle combinaison de modes cree la perception de luxe la plus forte en photographie de produit ?",
    [
      "High Angle avec Soft Box et fond blanc propre.",
      "Bird's Eye View avec lumiere naturelle et couleurs neutres.",
      "Low Angle pour la grandeur, rim light pour la presence, fond sombre pour la sophistication et style editorial pour le positionnement premium.",
      "Le luxe depend uniquement de la qualite du produit, pas du prompt.",
    ],
    2,
    "Avant de comprendre le produit, le public lit deja le statut, la valeur et le desir a travers l'image.",
  ),
  fillStep(
    "Complete les blancs - Cree un portrait cinematographique",
    "Complete le prompt de portrait avec profondeur emotionnelle.",
    "/imagine ___, cadrage ___, style ___, eclairage ___, fond ___, expression ___, mood ___, ___.",
    [
      "un vieux pecheur au visage marque avec des yeux bienveillants",
      "close up eye level",
      "photographie documentaire cinematographique",
      "chiaroscuro doux avec lumiere laterale chaude",
      "ocean flou au coucher du soleil",
      "digne et contemplative",
      "profondement humain et intemporel",
      "--ar 4:5",
    ],
    [
      "un vieux pecheur au visage marque avec des yeux bienveillants",
      "close up eye level",
      "photographie documentaire cinematographique",
      "chiaroscuro doux avec lumiere laterale chaude",
      "ocean flou au coucher du soleil",
      "digne et contemplative",
      "profondement humain et intemporel",
      "--ar 4:5",
    ],
    "Ici, les couches travaillent ensemble pour que l'image paraisse vecue, pas seulement jolie.",
  ),
  quizStep(
    "Pourquoi le portrait semble puissant",
    "Pourquoi la combinaison Close Up + Chiaroscuro + style documentaire cree-t-elle un portrait si puissant ?",
    [
      "Parce qu'il s'agit de trois techniques rares et avancees de MidJourney.",
      "Parce qu'elles produisent une image techniquement frappante, meme sans emotion.",
      "Parce que Close Up revele l'humain, Chiaroscuro ajoute de la profondeur dramatique et le documentaire apporte de l'authenticite.",
      "Parce que ces techniques creent toujours le meme portrait, quel que soit le sujet.",
    ],
    2,
    "Le visage cesse d'etre seulement un visage. Il commence a porter du temps, de l'histoire et une presence emotionnelle.",
  ),
  fillStep(
    "Complete les blancs - Cree un paysage epique",
    "Complete le prompt de paysage avec echelle et atmosphere.",
    "/imagine ___, cadrage ___, style ___, eclairage ___, atmosphere ___, couleurs ___, figure humaine ___ pour l'echelle, ___.",
    [
      "un glacier colossal rencontrant un ocean arctique tempetueux",
      "wide establishing",
      "photographie epique de paysage",
      "blue hour avec brume volumetrique",
      "dramatique et primordiale",
      "bleu petrolier profond et blanc",
      "en silhouette",
      "--ar 16:9",
    ],
    [
      "un glacier colossal rencontrant un ocean arctique tempetueux",
      "wide establishing",
      "photographie epique de paysage",
      "blue hour avec brume volumetrique",
      "dramatique et primordiale",
      "bleu petrolier profond et blanc",
      "en silhouette",
      "--ar 16:9",
    ],
    "Le paysage epique ne depend pas seulement de la taille. Il depend du contraste d'echelle, de l'atmosphere et du cadrage emotionnel.",
  ),
  quizStep(
    "Silhouette dans un paysage epique",
    "Pourquoi ajouter une figure humaine en silhouette amplifie-t-il l'impact d'un paysage epique ?",
    [
      "Pour montrer que l'environnement est sur pour l'humain.",
      "Parce que MidJourney genere toujours de meilleurs paysages quand un personnage est present.",
      "Parce que le contraste entre la petite echelle humaine et l'immensite du decor communique grandeur et aventure immediatement.",
      "Parce que les figures humaines detournent toujours l'attention du paysage.",
    ],
    2,
    "Sans comparaison d'echelle, le spectateur peut voir la beaute, mais ressent moins la veritable ampleur du decor.",
  ),
  fillStep(
    "Complete les blancs - Construis le prompt definitif",
    "Complete le prompt qui aligne sujet, environnement, style, lumiere, palette, mood et atmosphere.",
    "/imagine ___, dans ___, cadrage ___, style ___, eclairage ___, palette ___, mood ___, atmosphere ___, ___.",
    [
      "un samourai solitaire en meditation",
      "une ancienne foret de bambous a l'aube avec brume matinale",
      "low angle",
      "photographie dark fantasy cinematographique avec ukiyo-e",
      "volumetrique doree avec rim light",
      "vert doux, or et noir",
      "profondement spirituel et puissant",
      "intemporelle et epique",
      "--ar 9:16",
    ],
    [
      "un samourai solitaire en meditation",
      "une ancienne foret de bambous a l'aube avec brume matinale",
      "low angle",
      "photographie dark fantasy cinematographique avec ukiyo-e",
      "volumetrique doree avec rim light",
      "vert doux, or et noir",
      "profondement spirituel et puissant",
      "intemporelle et epique",
      "--ar 9:16",
    ],
    "Ce type de prompt fonctionne parce que toutes les couches sont alignees. Rien n'est de trop. Rien ne se bat contre l'idee centrale.",
  ),
  quizStep(
    "Quand toutes les couches s'alignent",
    "Que se passe-t-il quand toutes les couches d'un prompt sont parfaitement alignees ?",
    [
      "On obtient une image techniquement parfaite mais vide emotionnellement.",
      "On obtient une image confuse avec trop d'elements en concurrence.",
      "On obtient une identite visuelle unique et coherente ou chaque couche renforce les autres.",
      "On obtient un resultat pire qu'avec un prompt plus simple.",
    ],
    2,
    "La coherence ne simplifie pas l'image. Elle lui donne une direction, et c'est cette direction qui donne une impression professionnelle.",
  ),
  fillStep(
    "Complete les blancs - Evite les erreurs",
    "Complete la phrase avec les erreurs les plus courantes quand on combine les modes.",
    "Les erreurs les plus courantes quand on combine les modes sont : melanger des styles ___ qui se contredisent, utiliser un eclairage ___ avec le style choisi, associer palette et mood ___, ajouter des elements ___ sans but clair et ___ les elements jusqu'a creer une ambiguite visuelle.",
    [
      "incompatibles",
      "incoherent",
      "conflictuels",
      "inutiles",
      "accumuler",
    ],
    [
      "incompatibles",
      "incoherent",
      "conflictuels",
      "inutiles",
      "accumuler",
    ],
    "Le probleme n'est pas d'avoir beaucoup de couches. Le probleme, c'est d'avoir beaucoup de couches qui tirent dans des directions opposees.",
  ),
  quizStep(
    "Erreur la plus courante en mode avance",
    "Quelle est l'erreur la plus courante lorsqu'on essaie de combiner des modes avances dans MidJourney ?",
    [
      "Utiliser plus de deux types de lumiere dans le meme prompt.",
      "Combiner des styles de periodes historiques differentes.",
      "Ajouter des elements sans intention creative claire, en empilant des termes forts qui ne communiquent pas entre eux.",
      "Combiner point de vue et eclairage dans le meme prompt.",
    ],
    2,
    "Un prompt avance n'est pas une liste de mots impressionnants. C'est une composition intentionnelle. Sans cela, l'image devient confuse.",
  ),
  textStep(
    "Conclusion",
    "Combiner les modes est la competence qui transforme MidJourney de generateur d'images en studio creatif. Style avec lumiere, point de vue avec mood, palette avec atmosphere, references artistiques hybrides et toutes les couches reunies dans un seul prompt clair ouvrent des possibilites qu'aucun element isole ne pourrait produire.\n\nLe secret n'est pas d'utiliser plus d'elements. Le secret est d'utiliser les bons elements, dans le bon ordre, en renforcant la meme idee visuelle du debut a la fin.",
  ),
] as const;
