const textStep = (title: string, content: string, promptBox?: string) => ({
  type: "text" as const,
  title,
  content,
  ...(promptBox ? { promptBox } : {}),
});

const quizStep = (
  title: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
) => ({
  type: "quiz" as const,
  title,
  question,
  options,
  correctIndex,
  explanation,
});

const fillStep = (
  title: string,
  instruction: string,
  sentence: string,
  answers: string[],
  options: string[],
  explanation: string,
) => ({
  type: "fill_blanks" as const,
  title,
  instruction,
  sentence,
  answers,
  options,
  explanation,
});

export const MIDJOURNEY_MODULE_3_STEPS_PT = [
  textStep(
    "Tamanho da imagem - Dominando a proporcao e a composicao",
    "Bem-vindo de volta! Nesta licao, voce vai aprender como o tamanho e a proporcao da imagem transformam completamente a composicao, o impacto e a aplicacao de qualquer visual criado no MidJourney, e como escolher o formato certo para cada objetivo.\n\nMuitos iniciantes ignoram o formato e ficam no quadrado padrao para tudo. Isso e um erro estrategico. A proporcao define como o olho percorre a imagem, quanto espaco cada elemento ocupa e se o visual realmente funciona na plataforma onde sera usado.",
  ),
  fillStep(
    "Preencha a lacuna - Crie no formato horizontal amplo",
    "Complete o prompt para uma cena 16:9 cinematografica.",
    "/imagine ___, estilo ___, luz ___, atmosfera ___, plano geral aberto, ___",
    [
      "um horizonte de cidade futurista a noite com carros voadores",
      "arte conceitual cyberpunk",
      "neon",
      "epica e imersiva",
      "--ar 16:9",
    ],
    [
      "um horizonte de cidade futurista a noite com carros voadores",
      "arte conceitual cyberpunk",
      "neon",
      "epica e imersiva",
      "--ar 16:9",
    ],
    "O 16:9 abre a cena e cria espaco para narrativa visual, horizonte e ambientacao.",
  ),
  fillStep(
    "Preencha a lacuna - Crie para o mobile",
    "Monte o prompt pensando em 9:16 para tela cheia no celular.",
    "/imagine ___, estilo ___, luz ___, composicao ___, humor ___, deixando espaco no topo e na base para texto, ___",
    [
      "uma jovem confiante caminhando em um distrito de moda",
      "fotografia de estilo urbano",
      "natural urbana",
      "corpo inteiro vertical",
      "forte e energetico",
      "--ar 9:16",
    ],
    [
      "uma jovem confiante caminhando em um distrito de moda",
      "fotografia de estilo urbano",
      "natural urbana",
      "corpo inteiro vertical",
      "forte e energetico",
      "--ar 9:16",
    ],
    "O 9:16 funciona melhor quando voce pensa na experiencia real de tela cheia no celular, inclusive reservando espaco para texto e CTA.",
  ),
  fillStep(
    "Preencha a lacuna - Crie para o feed",
    "Complete o prompt pensado para o feed em 4:5.",
    "/imagine ___, estilo ___, luz ___, cores ___, composicao ___, ___",
    [
      "um flat lay de cafe, um livro e folhas de outono sobre uma mesa rustica de madeira",
      "fotografia de lifestyle",
      "natural suave e quente",
      "ambar e marrom aconchegantes",
      "vista superior",
      "--ar 4:5",
    ],
    [
      "um flat lay de cafe, um livro e folhas de outono sobre uma mesa rustica de madeira",
      "fotografia de lifestyle",
      "natural suave e quente",
      "ambar e marrom aconchegantes",
      "vista superior",
      "--ar 4:5",
    ],
    "O 4:5 entrega mais presenca vertical no feed sem virar formato de story, por isso e tao bom para conteudo social.",
  ),
  quizStep(
    "Por que 4:5 e favorito no feed",
    "Por que o 4:5 e considerado o formato mais estrategico para o feed do Instagram?",
    [
      "Porque o Instagram exige que todos os posts sejam em 4:5.",
      "Porque cria uma aparencia diferente dos outros posts no feed.",
      "Porque ocupa mais espaco vertical que 1:1 sem virar story, aumentando o tempo de atencao antes do scroll.",
      "Porque o 4:5 gera imagens automaticamente com mais resolucao.",
    ],
    2,
    "No feed, ocupar mais altura significa aparecer com mais presenca e segurar mais a atencao do usuario por alguns instantes extras.",
  ),
  fillStep(
    "Preencha a lacuna - Crie um retrato vertical",
    "Complete o prompt para 2:3.",
    "/imagine ___, estilo ___, luz ___, fundo ___, composicao de retrato ___, ___",
    [
      "uma executiva poderosa com um terno impecavel",
      "fotografia editorial de moda",
      "dramatic studio",
      "escuro, desfocado e melancolico",
      "de corpo inteiro vertical",
      "--ar 2:3",
    ],
    [
      "uma executiva poderosa com um terno impecavel",
      "fotografia editorial de moda",
      "dramatic studio",
      "escuro, desfocado e melancolico",
      "de corpo inteiro vertical",
      "--ar 2:3",
    ],
    "O 2:3 funciona muito bem para retrato vertical, capa, poster e todo visual que precisa crescer em altura sem parecer um story.",
  ),
  fillStep(
    "Preencha a lacuna - Entenda o impacto da proporcao",
    "Complete como o mesmo prompt muda de enquadramento conforme o formato.",
    "O prompt '/imagine um chef cozinhando em uma cozinha profissional' em ___ mostra o chef em close com foco no rosto e nas maos. Em ___ mostra o chef em plano aberto com toda a cozinha ao fundo. Em ___ mostra o chef em plano medio com equilibrio entre personagem e ambiente.",
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    "A mesma descricao muda de enquadramento porque o MidJourney reorganiza os elementos para preencher o espaco disponivel da melhor forma.",
  ),
  quizStep(
    "Multiplos formatos, mesma campanha",
    "O que voce deve fazer quando precisa de uma imagem em multiplos formatos para diferentes plataformas?",
    [
      "Gerar uma unica imagem e cortar para cada formato necessario.",
      "Criar um prompt totalmente diferente para cada plataforma.",
      "Usar o mesmo prompt base e variar apenas o parametro --ar para manter consistencia visual entre as versoes.",
      "Multiplos formatos so sao necessarios para campanhas pagas.",
    ],
    2,
    "O melhor caminho e preservar a identidade visual do prompt e deixar a proporcao adaptar o enquadramento a cada canal.",
  ),
  textStep(
    "Conclusao",
    "O tamanho e a proporcao da imagem nao sao detalhe tecnico. Sao decisoes estrategicas que definem composicao, impacto e aplicabilidade de cada visual criado no MidJourney. 1:1 para o feed, 9:16 para Stories e Reels, 16:9 para YouTube e apresentacoes, 4:5 para maximizar o feed, 2:3 para retratos e Pinterest - cada proporcao tem sua funcao e seu poder.\n\nDominar o parametro --ar e o que separa quem cria imagens bonitas de quem cria imagens estrategicas, pensadas para o canal certo, no formato certo e com a composicao certa.",
  ),
] as const;

export const MIDJOURNEY_MODULE_3_STEPS_EN = [
  textStep(
    "Image size - mastering aspect ratio and composition",
    "Welcome back! In this lesson, you will learn how image size and aspect ratio completely transform the composition, impact, and application of any visual created in MidJourney, and how to choose the right format for each goal.\n\nMany beginners ignore format and stay with the default square for everything. That is a strategic mistake. Ratio defines how the eye moves through the image, how much space each element occupies, and whether the visual fits the platform where it will be used.",
  ),
  fillStep(
    "Fill in the blanks - Create in wide screen",
    "Complete the prompt for a cinematic 16:9 scene.",
    "/imagine ___, ___ style, ___ lighting, ___ atmosphere, wide establishing shot, ___",
    [
      "a futuristic city skyline at night with flying cars",
      "cyberpunk concept art",
      "neon",
      "epic and immersive",
      "--ar 16:9",
    ],
    [
      "a futuristic city skyline at night with flying cars",
      "cyberpunk concept art",
      "neon",
      "epic and immersive",
      "--ar 16:9",
    ],
    "16:9 opens the frame and gives space for narrative, horizon, and environmental storytelling.",
  ),
  fillStep(
    "Fill in the blanks - Create for mobile",
    "Build the prompt for a 9:16 mobile-first image.",
    "/imagine ___, ___ style, ___ lighting, ___ composition, ___ mood, leaving space at top and bottom for text overlay, ___",
    [
      "a confident young woman walking in a fashion district",
      "street style photography",
      "natural urban",
      "vertical full body",
      "bold and energetic",
      "--ar 9:16",
    ],
    [
      "a confident young woman walking in a fashion district",
      "street style photography",
      "natural urban",
      "vertical full body",
      "bold and energetic",
      "--ar 9:16",
    ],
    "9:16 works best when you think about the real mobile experience, including room for text and CTA overlays.",
  ),
  fillStep(
    "Fill in the blanks - Create for the feed",
    "Complete the prompt designed for a 4:5 feed image.",
    "/imagine ___, ___ style, ___ lighting, ___ colors, ___ composition, ___",
    [
      "a flat lay of coffee, a book and autumn leaves on a rustic wooden table",
      "lifestyle photography",
      "warm soft natural",
      "cozy amber and brown",
      "overhead top-down",
      "--ar 4:5",
    ],
    [
      "a flat lay of coffee, a book and autumn leaves on a rustic wooden table",
      "lifestyle photography",
      "warm soft natural",
      "cozy amber and brown",
      "overhead top-down",
      "--ar 4:5",
    ],
    "4:5 gives more vertical presence in the feed without turning the post into a story format.",
  ),
  quizStep(
    "Why 4:5 wins in the feed",
    "Why is 4:5 considered the most strategic format for the Instagram feed?",
    [
      "Because Instagram requires every post to be 4:5.",
      "Because it creates a different look from other feed posts.",
      "Because it is the tallest ratio Instagram shows in-feed without turning it into a story, giving the post more screen presence.",
      "Because 4:5 automatically generates higher resolution.",
    ],
    2,
    "In the feed, more height means more presence and a better chance of holding attention before the user scrolls away.",
  ),
  fillStep(
    "Fill in the blanks - Create a classic vertical portrait",
    "Complete the prompt for 2:3.",
    "/imagine ___, ___ style, ___ lighting, ___ background, ___ portrait composition, ___",
    [
      "a powerful female executive in a sharp business suit",
      "editorial fashion photography",
      "dramatic studio",
      "dark moody blurred",
      "full body vertical",
      "--ar 2:3",
    ],
    [
      "a powerful female executive in a sharp business suit",
      "editorial fashion photography",
      "dramatic studio",
      "dark moody blurred",
      "full body vertical",
      "--ar 2:3",
    ],
    "2:3 works very well for vertical portraits, covers, posters, and any visual that needs height without becoming story-shaped.",
  ),
  fillStep(
    "Fill in the blanks - Understand ratio impact",
    "Complete how the same prompt changes framing based on ratio.",
    "The prompt '/imagine a chef cooking in a professional kitchen' in ___ shows the chef in a closer frame focused on face and hands. In ___ it shows the chef in a wider shot with the whole kitchen behind. In ___ it shows a medium frame balancing the character and the environment.",
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    "The same description changes framing because MidJourney reorganizes the scene to fill the available shape in the most balanced way.",
  ),
  quizStep(
    "Multiple formats, same campaign",
    "What should you do when you need one image in multiple formats for different platforms?",
    [
      "Generate a single image and crop it for each needed format.",
      "Create a completely different prompt for every platform.",
      "Use the same base prompt and vary only --ar to keep visual consistency across versions.",
      "Multiple formats are only needed for paid campaigns.",
    ],
    2,
    "The strongest approach is to preserve the visual identity of the prompt while letting ratio adapt framing to each channel.",
  ),
  textStep(
    "Conclusion",
    "Image size and ratio are not technical details. They are strategic decisions that define composition, impact, and applicability for every visual created in MidJourney. 1:1 for feed, 9:16 for Stories and Reels, 16:9 for YouTube and presentations, 4:5 to maximize feed space, 2:3 for portraits and Pinterest - each ratio has a function and a strength.\n\nMastering --ar is what separates someone who creates pretty images from someone who creates strategic images, built for the right channel, in the right format, with the right composition.",
  ),
] as const;
export const MIDJOURNEY_MODULE_3_STEPS_ES = [
  textStep(
    "Tamano de imagen - dominar la proporcion y la composicion",
    "Bienvenido de nuevo. En esta leccion vas a aprender como el tamano y la proporcion de la imagen transforman por completo la composicion, el impacto y la aplicacion de cualquier visual creado en MidJourney, y como elegir el formato correcto para cada objetivo.\n\nMuchos principiantes ignoran el formato y dejan todo en el cuadrado por defecto. Eso es un error estrategico. La proporcion define como recorre el ojo la imagen, cuanto espacio ocupa cada elemento y si el visual realmente funciona en la plataforma final.",
  ),
  fillStep(
    "Rellena el espacio - Crea en formato horizontal amplio",
    "Completa el prompt para una escena 16:9 cinematografica.",
    "/imagine ___, estilo ___, luz ___, atmosfera ___, plano general abierto, ___",
    [
      "un horizonte de ciudad futurista de noche con coches voladores",
      "arte conceptual cyberpunk",
      "neon",
      "epica e inmersiva",
      "--ar 16:9",
    ],
    [
      "un horizonte de ciudad futurista de noche con coches voladores",
      "arte conceptual cyberpunk",
      "neon",
      "epica e inmersiva",
      "--ar 16:9",
    ],
    "El 16:9 abre la escena y da espacio para narrativa, horizonte y contexto visual.",
  ),
  fillStep(
    "Rellena el espacio - Crea para mobile",
    "Arma el prompt pensando en 9:16 para pantalla completa en celular.",
    "/imagine ___, estilo ___, luz ___, composicion ___, animo ___, dejando espacio arriba y abajo para texto, ___",
    [
      "una joven segura caminando por un distrito de moda",
      "fotografia street style",
      "natural urbana",
      "cuerpo entero vertical",
      "fuerte y energetico",
      "--ar 9:16",
    ],
    [
      "una joven segura caminando por un distrito de moda",
      "fotografia street style",
      "natural urbana",
      "cuerpo entero vertical",
      "fuerte y energetico",
      "--ar 9:16",
    ],
    "El 9:16 funciona mejor cuando piensas en la experiencia real de pantalla completa en el movil, incluyendo texto y CTA.",
  ),
  fillStep(
    "Rellena el espacio - Crea para el feed",
    "Completa el prompt pensado para 4:5.",
    "/imagine ___, estilo ___, luz ___, colores ___, composicion ___, ___",
    [
      "un flat lay de cafe, un libro y hojas de otono sobre una mesa rustica",
      "fotografia lifestyle",
      "natural suave y calida",
      "ambar y marron acogedores",
      "vista superior",
      "--ar 4:5",
    ],
    [
      "un flat lay de cafe, un libro y hojas de otono sobre una mesa rustica",
      "fotografia lifestyle",
      "natural suave y calida",
      "ambar y marron acogedores",
      "vista superior",
      "--ar 4:5",
    ],
    "El 4:5 ofrece mas presencia vertical en el feed sin convertirse en story, por eso es tan eficaz para redes.",
  ),
  quizStep(
    "Por que 4:5 gana en el feed",
    "Por que el 4:5 se considera el formato mas estrategico para el feed de Instagram?",
    [
      "Porque Instagram exige que todos los posts sean 4:5.",
      "Porque crea una apariencia distinta frente a otros posts.",
      "Porque ocupa mas altura que 1:1 sin volverse story, aumentando la atencion antes del scroll.",
      "Porque el 4:5 genera mas resolucion automaticamente.",
    ],
    2,
    "En el feed, mas altura significa mas presencia y mas oportunidad de sostener la atencion durante unos segundos extra.",
  ),
  fillStep(
    "Rellena el espacio - Crea un retrato vertical clasico",
    "Completa el prompt para 2:3.",
    "/imagine ___, estilo ___, luz ___, fondo ___, composicion de retrato ___, ___",
    [
      "una ejecutiva poderosa con un traje impecable",
      "fotografia editorial de moda",
      "dramatic studio",
      "oscuro, difuminado y melancolico",
      "de cuerpo entero vertical",
      "--ar 2:3",
    ],
    [
      "una ejecutiva poderosa con un traje impecable",
      "fotografia editorial de moda",
      "dramatic studio",
      "oscuro, difuminado y melancolico",
      "de cuerpo entero vertical",
      "--ar 2:3",
    ],
    "El 2:3 funciona muy bien para retrato vertical, portada, poster y cualquier visual que necesita crecer en altura sin parecer story.",
  ),
  fillStep(
    "Rellena el espacio - Entiende el impacto de la proporcion",
    "Completa como cambia el encuadre del mismo prompt segun el formato.",
    "El prompt '/imagine un chef cocinando en una cocina profesional' en ___ muestra al chef en primer plano con foco en rostro y manos. En ___ muestra al chef en plano abierto con toda la cocina al fondo. En ___ muestra un plano medio con equilibrio entre personaje y ambiente.",
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    "La misma descripcion cambia de encuadre porque MidJourney reorganiza los elementos para llenar mejor el espacio disponible.",
  ),
  quizStep(
    "Multiples formatos, misma campana",
    "Que deberias hacer cuando necesitas una imagen en varios formatos para distintas plataformas?",
    [
      "Generar una sola imagen y recortarla para cada formato.",
      "Crear un prompt completamente distinto para cada plataforma.",
      "Usar el mismo prompt base y variar solo --ar para mantener consistencia visual entre versiones.",
      "Los multiples formatos solo son necesarios en campanas pagas.",
    ],
    2,
    "La mejor estrategia es conservar la identidad visual del prompt y dejar que la proporcion adapte el encuadre a cada canal.",
  ),
  textStep(
    "Conclusion",
    "El tamano y la proporcion de la imagen no son detalles tecnicos. Son decisiones estrategicas que definen composicion, impacto y aplicacion de cada visual creado en MidJourney. 1:1 para feed, 9:16 para Stories y Reels, 16:9 para YouTube y presentaciones, 4:5 para maximizar el feed, 2:3 para retratos y Pinterest: cada proporcion tiene una funcion y un poder.\n\nDominar --ar es lo que separa a quien crea imagenes bonitas de quien crea imagenes estrategicas, pensadas para el canal correcto, en el formato correcto y con la composicion correcta.",
  ),
] as const;
export const MIDJOURNEY_MODULE_3_STEPS_FR = [
  textStep(
    "Taille de l'image - maitriser la proportion et la composition",
    "Bienvenue a nouveau. Dans cette lecon, tu vas apprendre comment la taille et la proportion de l'image transforment completement la composition, l'impact et l'usage de n'importe quel visuel cree avec MidJourney, et comment choisir le bon format selon l'objectif.\n\nBeaucoup de debutants ignorent le format et gardent le carre par defaut pour tout. C'est une erreur strategique. La proportion definit la maniere dont l'oeil parcourt l'image, la place de chaque element et l'efficacite du visuel sur la plateforme finale.",
  ),
  fillStep(
    "Completez les blancs - Creez en format large",
    "Completez le prompt pour une scene 16:9 cinematographique.",
    "/imagine ___, style ___, lumiere ___, atmosphere ___, plan general large, ___",
    [
      "un horizon de ville futuriste la nuit avec des voitures volantes",
      "concept art cyberpunk",
      "neon",
      "epique et immersive",
      "--ar 16:9",
    ],
    [
      "un horizon de ville futuriste la nuit avec des voitures volantes",
      "concept art cyberpunk",
      "neon",
      "epique et immersive",
      "--ar 16:9",
    ],
    "Le 16:9 ouvre la scene et laisse plus de place a la narration, a l'horizon et au contexte visuel.",
  ),
  fillStep(
    "Completez les blancs - Creez pour le mobile",
    "Construisez le prompt pour du 9:16 en plein ecran mobile.",
    "/imagine ___, style ___, lumiere ___, composition ___, humeur ___, en laissant de l'espace en haut et en bas pour du texte, ___",
    [
      "une jeune femme sure d'elle marchant dans un quartier de mode",
      "photographie street style",
      "naturelle urbaine",
      "corps entier vertical",
      "forte et energique",
      "--ar 9:16",
    ],
    [
      "une jeune femme sure d'elle marchant dans un quartier de mode",
      "photographie street style",
      "naturelle urbaine",
      "corps entier vertical",
      "forte et energique",
      "--ar 9:16",
    ],
    "Le 9:16 fonctionne mieux quand tu penses a la vraie experience plein ecran sur mobile, y compris l'espace pour le texte et le CTA.",
  ),
  fillStep(
    "Completez les blancs - Creez pour le feed",
    "Completez le prompt pense pour un visuel 4:5.",
    "/imagine ___, style ___, lumiere ___, couleurs ___, composition ___, ___",
    [
      "un flat lay de cafe, un livre et des feuilles d'automne sur une table rustique",
      "photographie lifestyle",
      "naturelle, douce et chaude",
      "ambre et brun chaleureux",
      "vue du dessus",
      "--ar 4:5",
    ],
    [
      "un flat lay de cafe, un livre et des feuilles d'automne sur une table rustique",
      "photographie lifestyle",
      "naturelle, douce et chaude",
      "ambre et brun chaleureux",
      "vue du dessus",
      "--ar 4:5",
    ],
    "Le 4:5 donne plus de presence verticale dans le feed sans glisser vers un format story.",
  ),
  quizStep(
    "Pourquoi le 4:5 gagne dans le feed",
    "Pourquoi le 4:5 est-il considere comme le format le plus strategique pour le feed Instagram?",
    [
      "Parce qu'Instagram exige que tous les posts soient en 4:5.",
      "Parce qu'il cree une apparence differente des autres posts.",
      "Parce qu'il occupe plus de hauteur que le 1:1 sans devenir un story, ce qui augmente la presence du post dans le feed.",
      "Parce que le 4:5 genere automatiquement une meilleure resolution.",
    ],
    2,
    "Dans le feed, plus de hauteur signifie plus de presence et plus de chances de retenir l'attention avant le scroll.",
  ),
  fillStep(
    "Completez les blancs - Creez un portrait vertical classique",
    "Completez le prompt pour du 2:3.",
    "/imagine ___, style ___, lumiere ___, fond ___, composition portrait ___, ___",
    [
      "une dirigeante puissante dans un tailleur impeccable",
      "photographie editoriale de mode",
      "dramatic studio",
      "sombre, flou et melancolique",
      "corps entier vertical",
      "--ar 2:3",
    ],
    [
      "une dirigeante puissante dans un tailleur impeccable",
      "photographie editoriale de mode",
      "dramatic studio",
      "sombre, flou et melancolique",
      "corps entier vertical",
      "--ar 2:3",
    ],
    "Le 2:3 marche tres bien pour le portrait vertical, la couverture, l'affiche et tout visuel qui a besoin de hauteur sans devenir un story.",
  ),
  fillStep(
    "Completez les blancs - Comprenez l'impact de la proportion",
    "Completez comment le cadrage change avec la meme consigne selon le format.",
    "Le prompt '/imagine un chef cuisinant dans une cuisine professionnelle' en ___ montre le chef en plan rapproche avec le visage et les mains en focus. En ___ il montre le chef en plan large avec toute la cuisine en fond. En ___ il montre un plan moyen avec un equilibre entre personnage et environnement.",
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    ["--ar 9:16", "--ar 16:9", "--ar 1:1"],
    "La meme description change de cadrage parce que MidJourney reorganise la scene pour remplir au mieux l'espace disponible.",
  ),
  quizStep(
    "Plusieurs formats, meme campagne",
    "Que faut-il faire lorsqu'une image doit exister dans plusieurs formats pour differentes plateformes?",
    [
      "Generer une seule image puis la recadrer pour chaque format.",
      "Creer un prompt totalement different pour chaque plateforme.",
      "Utiliser le meme prompt de base et ne faire varier que --ar afin de garder une coherence visuelle entre les versions.",
      "Les formats multiples ne sont necessaires que pour les campagnes payantes.",
    ],
    2,
    "La meilleure strategie consiste a conserver l'identite visuelle du prompt et a laisser la proportion adapter le cadrage selon le canal.",
  ),
  textStep(
    "Conclusion",
    "La taille et la proportion de l'image ne sont pas des details techniques. Ce sont des decisions strategiques qui definissent la composition, l'impact et l'usage de chaque visuel cree dans MidJourney. 1:1 pour le feed, 9:16 pour Stories et Reels, 16:9 pour YouTube et les presentations, 4:5 pour maximiser la presence dans le feed, 2:3 pour les portraits et Pinterest - chaque proportion a sa fonction et sa force.\n\nMaitriser --ar, c'est ce qui separe une personne qui cree de belles images d'une personne qui cree des images strategiques, pensees pour le bon canal, dans le bon format et avec la bonne composition.",
  ),
] as const;
