const textStep = (title: string, content: string, promptBox?: string) => ({
  type: "text" as const,
  title,
  content,
  ...(promptBox ? { promptBox } : {}),
});

const quizStep = (
  title: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
) => ({
  type: "quiz" as const,
  title,
  question,
  options,
  correctIndex,
  explanation,
});

const fillStep = (
  title: string,
  instruction: string,
  sentence: string,
  answers: string[],
  options: string[],
  explanation: string,
) => ({
  type: "fill_blanks" as const,
  title,
  instruction,
  sentence,
  answers,
  options,
  explanation,
});

export const MIDJOURNEY_MODULE_4_STEPS_PT = [
  textStep(
    "Ponto de vista no MidJourney - O angulo que transforma tudo",
    "Bem-vindo de volta! Nesta licao, voce vai aprender como o ponto de vista, ou seja, o angulo de camera usado no prompt, transforma completamente a narrativa, a emocao e o impacto de qualquer imagem criada no MidJourney. A mesma cena vista de angulos diferentes conta historias completamente diferentes.\n\nFotografos e diretores de cinema sabem que o angulo de camera nao e apenas uma escolha tecnica. E uma decisao narrativa. Ele define a relacao de poder entre espectador e sujeito, cria emocao e direciona o olhar para onde voce quer.",
  ),
  fillStep(
    "Preencha a lacuna - Use o Eye Level",
    "Complete o prompt com os elementos corretos do angulo ao nivel dos olhos.",
    "/imagine ___, enquadramento eye level, estilo ___, iluminacao ___, fundo ___, expressao ___, ___",
    [
      "uma jovem professora explicando algo para seus alunos",
      "fotografia documental",
      "natural suave",
      "sala de aula acolhedora",
      "engajada e apaixonada",
      "--ar 16:9",
    ],
    [
      "uma jovem professora explicando algo para seus alunos",
      "fotografia documental",
      "natural suave",
      "sala de aula acolhedora",
      "engajada e apaixonada",
      "--ar 16:9",
    ],
    "Eye Level aproxima o espectador do sujeito e cria uma sensacao de igualdade e realismo humano.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Low Angle",
    "Monte o prompt com o angulo baixo olhando para cima.",
    "/imagine ___, low angle olhando para cima, estilo ___, iluminacao ___, fundo de ceu ___, clima ___, ___",
    [
      "um super-heroi no topo de um predio",
      "arte conceitual cinematografica",
      "dramatic rim",
      "escuro e tempestuoso",
      "poderoso e epico",
      "--ar 9:16",
    ],
    [
      "um super-heroi no topo de um predio",
      "arte conceitual cinematografica",
      "dramatic rim",
      "escuro e tempestuoso",
      "poderoso e epico",
      "--ar 9:16",
    ],
    "Low Angle amplia poder e grandiosidade. Ele faz o sujeito parecer dominante e monumental dentro do quadro.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com High Angle",
    "Complete o prompt com camera acima do sujeito olhando para baixo.",
    "/imagine ___, high angle olhando para baixo, estilo ___, iluminacao ___, composicao ___, ___",
    [
      "uma mulher sentada sozinha lendo em um parque cercado por folhas de outono",
      "fotografia lifestyle",
      "quente, suave e natural",
      "vista superior com espaco negativo",
      "--ar 4:5",
    ],
    [
      "uma mulher sentada sozinha lendo em um parque cercado por folhas de outono",
      "fotografia lifestyle",
      "quente, suave e natural",
      "vista superior com espaco negativo",
      "--ar 4:5",
    ],
    "High Angle pode transmitir vulnerabilidade, contexto ou organizacao visual, dependendo do sujeito e da composicao.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Over the Shoulder",
    "Complete o prompt do enquadramento por cima do ombro.",
    "/imagine ___, over the shoulder shot, estilo ___, iluminacao ___, fundo ___ em foco, clima ___, ___",
    [
      "uma pessoa olhando para uma aurora boreal sobre um lago congelado",
      "fotografia cinematografica",
      "lua azul fria",
      "nitido e detalhado",
      "misterioso e imersivo",
      "--ar 16:9",
    ],
    [
      "uma pessoa olhando para uma aurora boreal sobre um lago congelado",
      "fotografia cinematografica",
      "lua azul fria",
      "nitido e detalhado",
      "misterioso e imersivo",
      "--ar 16:9",
    ],
    "Over the Shoulder convida o espectador a ocupar a posicao do personagem e viver a cena de dentro para fora.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Close Up",
    "Monte o prompt de plano fechado.",
    "/imagine ___, extreme close up, estilo ___, iluminacao ___, profundidade de campo ___, detalhe ___, ___",
    [
      "um par de maos marcadas pelo tempo segurando uma pequena flor silvestre",
      "fotografia documental",
      "natural suave",
      "rasa",
      "ultra alto",
      "--ar 4:5",
    ],
    [
      "um par de maos marcadas pelo tempo segurando uma pequena flor silvestre",
      "fotografia documental",
      "natural suave",
      "rasa",
      "ultra alto",
      "--ar 4:5",
    ],
    "Close Up aproxima o espectador do detalhe e da emocao que seriam invisiveis em planos mais abertos.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Wide Shot",
    "Complete o prompt de plano aberto.",
    "/imagine ___, wide establishing shot, estilo ___, iluminacao ___, atmosfera ___, escala ___, ___",
    [
      "um explorador solitario na borda do Grand Canyon ao por do sol",
      "fotografia de paisagem",
      "golden hour",
      "epica e vasta",
      "figura humana pequena diante de uma paisagem massiva",
      "--ar 16:9",
    ],
    [
      "um explorador solitario na borda do Grand Canyon ao por do sol",
      "fotografia de paisagem",
      "golden hour",
      "epica e vasta",
      "figura humana pequena diante de uma paisagem massiva",
      "--ar 16:9",
    ],
    "Wide Shot estabelece contexto, escala e atmosfera antes de qualquer detalhe mais especifico da cena.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Dutch Angle",
    "Monte o prompt com camera inclinada e clima de desequilibrio.",
    "/imagine ___, dutch angle, estilo ___, iluminacao ___, atmosfera ___, clima ___, ___",
    [
      "um detetive entrando em um predio abandonado escuro",
      "fotografia noir cinematografica",
      "dramatic chiaroscuro",
      "tensa e inquietante",
      "thriller psicologico",
      "--ar 16:9",
    ],
    [
      "um detetive entrando em um predio abandonado escuro",
      "fotografia noir cinematografica",
      "dramatic chiaroscuro",
      "tensa e inquietante",
      "thriller psicologico",
      "--ar 16:9",
    ],
    "Dutch Angle quebra equilibrio e estabilidade. Ele e excelente quando a imagem precisa insinuar que algo esta errado.",
  ),
  quizStep(
    "Quando Dutch Angle e mais eficaz",
    "Em qual projeto criativo o Dutch Angle seria mais eficaz?",
    [
      "Uma campanha de produto para uma marca infantil.",
      "Fotografia de casamento com atmosfera romantica e serena.",
      "Poster de suspense, thriller ou terror, capas de misterio e projetos com tensao psicologica intencional.",
      "Dutch Angle so funciona em preto e branco.",
    ],
    2,
    "Dutch Angle serve quando o desequilibrio emocional faz parte da mensagem visual do projeto.",
  ),
  fillStep(
    "Preencha a lacuna - Combine angulo e luz",
    "Complete o prompt combinando ponto de vista e iluminacao.",
    "/imagine ___, enquadramento ___, iluminacao ___, estilo ___, clima ___, ___",
    [
      "uma rainha guerreira em uma muralha durante uma tempestade",
      "low angle",
      "dramatic rim",
      "arte conceitual de fantasia sombria",
      "poderoso e desafiador",
      "--ar 9:16",
    ],
    [
      "uma rainha guerreira em uma muralha durante uma tempestade",
      "low angle",
      "dramatic rim",
      "arte conceitual de fantasia sombria",
      "poderoso e desafiador",
      "--ar 9:16",
    ],
    "Quando ponto de vista e luz reforcam a mesma ideia, o impacto visual deixa de ser apenas bonito e passa a ser narrativo.",
  ),
  quizStep(
    "Low Angle + Rim Lighting",
    "Por que combinar Low Angle com Rim Lighting cria um resultado especialmente impactante?",
    [
      "Porque as duas tecnicas sao opostas e se equilibram.",
      "Para deixar o prompt apenas mais longo e detalhado.",
      "Porque o Low Angle cria grandiosidade e o Rim Lighting destaca o personagem com presenca cinematografica, multiplicando o impacto.",
      "Low Angle e Rim Lighting geram conflito visual quando usados juntos.",
    ],
    2,
    "O angulo amplia poder e a luz de contorno reforca destaque. Juntos, os dois levam a cena para um nivel muito mais heroico.",
  ),
  fillStep(
    "Preencha a lacuna - Escolha o angulo certo",
    "Complete o guia rapido de pontos de vista por objetivo.",
    "Para transmitir ___ e heroismo use Low Angle. Para ___ e conexao humana use Eye Level. Para ___ e flat lay use High Angle ou Bird's Eye. Para ___ e emocao use Close Up. Para ___ e escala epica use Wide Shot. Para ___ narrativa use Over the Shoulder. Para ___ e suspense use Dutch Angle.",
    [
      "poder",
      "igualdade",
      "composicao",
      "intimidade",
      "contexto",
      "imersao",
      "tensao",
    ],
    [
      "poder",
      "igualdade",
      "composicao",
      "intimidade",
      "contexto",
      "imersao",
      "tensao",
    ],
    "Escolher o angulo certo e decidir qual relacao emocional o espectador vai ter com a cena antes mesmo de olhar para o resto.",
  ),
  textStep(
    "Conclusao",
    "O ponto de vista e a decisao mais narrativa que voce toma ao criar uma imagem no MidJourney. Eye Level para conexao humana, Low Angle para poder, High Angle para contexto, Bird's Eye para padroes e escala, Worm's Eye para grandiosidade extrema, Over the Shoulder para imersao, Close Up para emocao, Wide Shot para atmosfera e Dutch Angle para tensao.\n\nDominar o ponto de vista e dominar a narrativa. E quem controla a narrativa visual controla a emocao de quem ve.",
  ),
] as const;

export const MIDJOURNEY_MODULE_4_STEPS_EN = [
  textStep(
    "Point of view in MidJourney - The angle that changes everything",
    "Welcome back! In this lesson, you will learn how point of view, the camera angle used in the prompt, completely transforms the narrative, emotion, and impact of any image created in MidJourney. The same scene seen from different angles tells completely different stories.\n\nPhotographers and film directors know that camera angle is not only a technical choice. It is a narrative decision. It defines the power relationship between viewer and subject, creates specific emotions, and directs the eye exactly where you want it to go.",
  ),
  fillStep(
    "Fill in the blanks - Use Eye Level",
    "Complete the prompt with the correct eye-level elements.",
    "/imagine ___, eye level shot, ___ style, ___ lighting, ___ background, ___ expression, ___",
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    "Eye Level creates equality and realism by placing the viewer at the same height as the subject.",
  ),
  fillStep(
    "Fill in the blanks - Create with Low Angle",
    "Build the prompt with a low camera looking upward.",
    "/imagine ___, low angle shot looking up, ___ style, ___ lighting, ___ sky background, ___ mood, ___",
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    "Low Angle enlarges the subject and makes it feel dominant, heroic, and monumental.",
  ),
  fillStep(
    "Fill in the blanks - Create with High Angle",
    "Complete the prompt with the camera above the subject looking down.",
    "/imagine ___, high angle shot looking down, ___ style, ___ lighting, ___ composition, ___",
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    "High Angle can communicate vulnerability, context, or visual organization depending on the subject and layout.",
  ),
  fillStep(
    "Fill in the blanks - Create with Over the Shoulder",
    "Complete the prompt for an over-the-shoulder perspective.",
    "/imagine ___, over the shoulder shot, ___ style, ___ lighting, ___ in focus background, ___ mood, ___",
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    "Over the Shoulder invites the viewer into the character's place and builds immersive narrative perspective.",
  ),
  fillStep(
    "Fill in the blanks - Create with Close Up",
    "Build the close-up prompt.",
    "/imagine ___, extreme close up, ___ style, ___ lighting, ___ depth of field, ___ detail, ___",
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    "Close Up brings the viewer close to emotion, texture, and detail that would disappear in wider framing.",
  ),
  fillStep(
    "Fill in the blanks - Create with Wide Shot",
    "Complete the wide establishing prompt.",
    "/imagine ___, wide establishing shot, ___ style, ___ lighting, ___ atmosphere, ___ scale, ___",
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    "Wide Shot establishes context, scale, and atmosphere before detail.",
  ),
  fillStep(
    "Fill in the blanks - Create with Dutch Angle",
    "Build the tilted-camera prompt.",
    "/imagine ___, dutch angle, ___ style, ___ lighting, ___ atmosphere, ___ mood, ___",
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    "Dutch Angle breaks balance and stability. It works when the scene needs to suggest that something is wrong.",
  ),
  quizStep(
    "When Dutch Angle is strongest",
    "In which kind of creative project is Dutch Angle most effective?",
    ["A product campaign for a children's brand.","Wedding photography with a serene romantic mood.","Thriller, suspense, or horror posters and mystery book covers where psychological imbalance is intentional.","Dutch Angle only works in black and white."],
    2,
    "Dutch Angle is strongest when emotional imbalance is part of the message itself.",
  ),
  fillStep(
    "Fill in the blanks - Combine angle and light",
    "Complete the prompt by combining point of view and lighting.",
    "/imagine ___, ___ shot, ___ lighting, ___ style, ___ mood, ___",
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    "When point of view and lighting reinforce the same idea, the image stops being merely pretty and becomes fully narrative.",
  ),
  quizStep(
    "Low Angle + Rim Lighting",
    "Why does combining Low Angle with Rim Lighting create such an especially powerful result?",
    ["Because the two techniques are opposite and balance each other.","To make the prompt longer and more detailed.","Because Low Angle creates grandeur while Rim Lighting adds cinematic separation and presence, multiplying the impact.","Low Angle and Rim Lighting create visual conflict together."],
    2,
    "The angle enlarges the subject and the rim light isolates it with force. Together they elevate the scene dramatically.",
  ),
  fillStep(
    "Fill in the blanks - Choose the right angle",
    "Complete the quick guide of viewpoints by goal.",
    "To transmit ___ and heroism use Low Angle. For ___ and human connection use Eye Level. For ___ and flat lay use High Angle or Bird's Eye. For ___ and emotion use Close Up. For ___ and epic scale use Wide Shot. For narrative ___ use Over the Shoulder. For ___ and suspense use Dutch Angle.",
    ["power","equality","composition","intimacy","context","immersion","tension"],
    ["power","equality","composition","intimacy","context","immersion","tension"],
    "Choosing the right angle means deciding what emotional relationship the viewer will have with the scene before anything else.",
  ),
  textStep(
    "Conclusion",
    "Point of view is the most narrative decision you make when creating an image in MidJourney. Eye Level for human connection, Low Angle for power, High Angle for context, Bird's Eye for pattern and scale, Worm's Eye for extreme grandeur, Over the Shoulder for immersion, Close Up for emotion, Wide Shot for atmosphere, and Dutch Angle for tension.\n\nTo master point of view is to master visual storytelling, and whoever controls visual storytelling controls the emotion of the viewer.",
  ),
] as const;

export const MIDJOURNEY_MODULE_4_STEPS_ES = [
  textStep(
    "Punto de vista en MidJourney - El angulo que lo transforma todo",
    "Bienvenido de nuevo. En esta leccion vas a aprender como el punto de vista, el angulo de camara usado en el prompt, transforma por completo la narrativa, la emocion y el impacto de cualquier imagen creada en MidJourney. La misma escena vista desde angulos distintos cuenta historias totalmente diferentes.\n\nFotografos y directores de cine saben que el angulo de camara no es solo una decision tecnica. Es una decision narrativa. Define la relacion de poder entre el espectador y el sujeto, crea emociones especificas y dirige la mirada exactamente hacia donde quieres.",
  ),
  fillStep(
    "Completa los espacios - Usa Eye Level",
    "Completa el prompt con los elementos correctos de eye level.",
    "/imagine ___, eye level shot, estilo ___, iluminacion ___, fondo ___, expresion ___, ___",
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    "Eye Level crea igualdad y realismo al colocar al espectador a la misma altura que el sujeto.",
  ),
  fillStep(
    "Completa los espacios - Crea con Low Angle",
    "Construye el prompt con una camara baja mirando hacia arriba.",
    "/imagine ___, low angle shot looking up, estilo ___, iluminacion ___, cielo ___, mood ___, ___",
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    "Low Angle agranda al sujeto y lo hace sentir dominante, heroico y monumental.",
  ),
  fillStep(
    "Completa los espacios - Crea con High Angle",
    "Completa el prompt con la camara por encima del sujeto mirando hacia abajo.",
    "/imagine ___, high angle shot looking down, estilo ___, iluminacion ___, composicion ___, ___",
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    "High Angle puede comunicar vulnerabilidad, contexto u organizacion visual segun el sujeto y la composicion.",
  ),
  fillStep(
    "Completa los espacios - Crea con Over the Shoulder",
    "Completa el prompt para una perspectiva por encima del hombro.",
    "/imagine ___, over the shoulder shot, estilo ___, iluminacion ___, fondo ___ en foco, mood ___, ___",
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    "Over the Shoulder invita al espectador a ocupar el lugar del personaje y crea una perspectiva narrativa inmersiva.",
  ),
  fillStep(
    "Completa los espacios - Crea con Close Up",
    "Construye el prompt en plano cerrado.",
    "/imagine ___, extreme close up, estilo ___, iluminacion ___, profundidad de campo ___, detalle ___, ___",
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    "Close Up acerca al espectador a la emocion, la textura y el detalle que desaparecerian en un encuadre mas abierto.",
  ),
  fillStep(
    "Completa los espacios - Crea con Wide Shot",
    "Completa el prompt de plano general.",
    "/imagine ___, wide establishing shot, estilo ___, iluminacion ___, atmosfera ___, escala ___, ___",
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    "Wide Shot establece contexto, escala y atmosfera antes de entrar en los detalles.",
  ),
  fillStep(
    "Completa los espacios - Crea con Dutch Angle",
    "Construye el prompt con la camara inclinada.",
    "/imagine ___, dutch angle, estilo ___, iluminacion ___, atmosfera ___, mood ___, ___",
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    "Dutch Angle rompe el equilibrio y la estabilidad. Funciona cuando la escena necesita sugerir que algo esta mal.",
  ),
  quizStep(
    "Cuando Dutch Angle es mas fuerte",
    "En que tipo de proyecto creativo es mas eficaz Dutch Angle?",
    ["En una campana de producto para una marca infantil.","En fotografia de boda con atmosfera romantica y serena.","En posters de thriller, suspenso o terror y portadas de misterio donde el desequilibrio emocional es intencional.","Dutch Angle solo funciona en blanco y negro."],
    2,
    "Dutch Angle funciona mejor cuando el desequilibrio emocional forma parte del mensaje.",
  ),
  fillStep(
    "Completa los espacios - Combina angulo y luz",
    "Completa el prompt combinando punto de vista e iluminacion.",
    "/imagine ___, angulo ___, iluminacion ___, estilo ___, mood ___, ___",
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    "Cuando el punto de vista y la luz refuerzan la misma idea, la imagen deja de ser solo bonita y pasa a ser narrativa.",
  ),
  quizStep(
    "Low Angle + Rim Lighting",
    "Por que combinar Low Angle con Rim Lighting crea un resultado tan impactante?",
    ["Porque las dos tecnicas son opuestas y se equilibran.","Para hacer el prompt mas largo y detallado.","Porque Low Angle crea grandeza y Rim Lighting agrega separacion cinematografica y presencia, multiplicando el impacto.","Low Angle y Rim Lighting generan conflicto visual juntas."],
    2,
    "El angulo agranda al sujeto y la luz de contorno lo separa del fondo con fuerza. Juntas elevan la escena.",
  ),
  fillStep(
    "Completa los espacios - Elige el angulo correcto",
    "Completa la guia rapida de puntos de vista segun el objetivo.",
    "Para transmitir ___ y heroismo usa Low Angle. Para ___ y conexion humana usa Eye Level. Para ___ y flat lay usa High Angle o Bird's Eye. Para ___ y emocion usa Close Up. Para ___ y escala epica usa Wide Shot. Para inmersion narrativa usa Over the Shoulder. Para ___ y suspenso usa Dutch Angle.",
    ["poder","igualdad","composicion","intimidad","contexto","tension"],
    ["poder","igualdad","composicion","intimidad","contexto","tension"],
    "Elegir el angulo correcto es decidir que relacion emocional tendra el espectador con la escena antes de mirar cualquier otra cosa.",
  ),
  textStep(
    "Conclusion",
    "El punto de vista es la decision mas narrativa que tomas al crear una imagen en MidJourney. Eye Level para conexion humana, Low Angle para poder, High Angle para contexto, Bird's Eye para patron y escala, Worm's Eye para grandeza extrema, Over the Shoulder para inmersion, Close Up para emocion, Wide Shot para atmosfera y Dutch Angle para tension.\n\nDominar el punto de vista es dominar la narrativa visual, y quien domina la narrativa visual domina la emocion del espectador.",
  ),
] as const;

export const MIDJOURNEY_MODULE_4_STEPS_FR = [
  textStep(
    "Point de vue dans MidJourney - L'angle qui change tout",
    "Bon retour. Dans cette lecon, tu vas comprendre comment le point de vue, c'est-a-dire l'angle de camera utilise dans le prompt, transforme completement la narration, l'emotion et l'impact de n'importe quelle image creee dans MidJourney. Une meme scene vue depuis des angles differents raconte des histoires completement differentes.\n\nLes photographes et les realisateurs savent que l'angle de camera n'est pas seulement un choix technique. C'est un choix narratif. Il definit la relation de pouvoir entre le spectateur et le sujet, cree des emotions precises et guide le regard exactement ou tu le veux.",
  ),
  fillStep(
    "Complete les blancs - Utilise Eye Level",
    "Complete le prompt avec les bons elements d'eye level.",
    "/imagine ___, eye level shot, style ___, eclairage ___, arriere-plan ___, expression ___, ___",
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    "Eye Level cree l'egalite et le realisme en placant le spectateur a la meme hauteur que le sujet.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Low Angle",
    "Construit le prompt avec une camera basse qui regarde vers le haut.",
    "/imagine ___, low angle shot looking up, style ___, eclairage ___, ciel ___, mood ___, ___",
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    "Low Angle agrandit le sujet et lui donne une presence dominante, heroique et monumentale.",
  ),
  fillStep(
    "Complete les blancs - Cree avec High Angle",
    "Complete le prompt avec la camera au-dessus du sujet regardant vers le bas.",
    "/imagine ___, high angle shot looking down, style ___, eclairage ___, composition ___, ___",
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    "High Angle peut communiquer la vulnerabilite, le contexte ou l'organisation visuelle selon le sujet et la composition.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Over the Shoulder",
    "Complete le prompt pour une perspective par-dessus l'epaule.",
    "/imagine ___, over the shoulder shot, style ___, eclairage ___, arriere-plan ___ net, mood ___, ___",
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    "Over the Shoulder invite le spectateur a prendre la place du personnage et cree une perspective narrative immersive.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Close Up",
    "Construit le prompt en gros plan.",
    "/imagine ___, extreme close up, style ___, eclairage ___, profondeur de champ ___, detail ___, ___",
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    "Close Up rapproche le spectateur de l'emotion, de la texture et du detail qui disparaitraient dans un cadrage plus large.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Wide Shot",
    "Complete le prompt de plan large.",
    "/imagine ___, wide establishing shot, style ___, eclairage ___, atmosphere ___, echelle ___, ___",
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    "Wide Shot installe le contexte, l'echelle et l'atmosphere avant les details.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Dutch Angle",
    "Construit le prompt avec une camera inclinee.",
    "/imagine ___, dutch angle, style ___, eclairage ___, atmosphere ___, mood ___, ___",
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    "Dutch Angle casse l'equilibre et la stabilite. Il fonctionne quand la scene doit suggerer qu'il y a un probleme.",
  ),
  quizStep(
    "Quand Dutch Angle est le plus fort",
    "Dans quel type de projet creatif Dutch Angle est-il le plus efficace ?",
    ["Dans une campagne produit pour une marque enfantine.","Dans une photo de mariage romantique et sereine.","Dans des affiches de thriller, de suspense ou d'horreur et des couvertures de mystere ou le desequilibre emotionnel est intentionnel.","Dutch Angle ne fonctionne qu'en noir et blanc."],
    2,
    "Dutch Angle fonctionne le mieux lorsque le desequilibre emotionnel fait partie du message.",
  ),
  fillStep(
    "Complete les blancs - Combine angle et lumiere",
    "Complete le prompt en combinant point de vue et eclairage.",
    "/imagine ___, angle ___, eclairage ___, style ___, mood ___, ___",
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    "Quand le point de vue et la lumiere renforcent la meme idee, l'image cesse d'etre seulement belle et devient vraiment narrative.",
  ),
  quizStep(
    "Low Angle + Rim Lighting",
    "Pourquoi la combinaison de Low Angle et Rim Lighting cree-t-elle un resultat si impactant ?",
    ["Parce que les deux techniques sont opposees et s'equilibrent.","Pour rendre le prompt plus long et plus detaille.","Parce que Low Angle cree la grandeur et Rim Lighting ajoute une separation cinematographique et une forte presence, ce qui multiplie l'impact.","Low Angle et Rim Lighting creent un conflit visuel ensemble."],
    2,
    "L'angle agrandit le sujet et la lumiere de contour le detache du fond avec force. Ensemble, ils elevent la scene.",
  ),
  fillStep(
    "Complete les blancs - Choisis le bon angle",
    "Complete le guide rapide des points de vue selon l'objectif.",
    "Pour transmettre ___ et heroisme, utilise Low Angle. Pour ___ et connexion humaine, utilise Eye Level. Pour ___ et flat lay, utilise High Angle ou Bird's Eye. Pour ___ et emotion, utilise Close Up. Pour ___ et echelle epique, utilise Wide Shot. Pour l'immersion narrative, utilise Over the Shoulder. Pour ___ et suspense, utilise Dutch Angle.",
    ["puissance","egalite","composition","intimite","contexte","tension"],
    ["puissance","egalite","composition","intimite","contexte","tension"],
    "Choisir le bon angle, c'est decider quelle relation emotionnelle le spectateur aura avec la scene avant meme de regarder le reste.",
  ),
  textStep(
    "Conclusion",
    "Le point de vue est la decision la plus narrative que tu prends quand tu crees une image dans MidJourney. Eye Level pour la connexion humaine, Low Angle pour la puissance, High Angle pour le contexte, Bird's Eye pour les motifs et l'echelle, Worm's Eye pour une grandeur extreme, Over the Shoulder pour l'immersion, Close Up pour l'emotion, Wide Shot pour l'atmosphere et Dutch Angle pour la tension.\n\nMaitriser le point de vue, c'est maitriser la narration visuelle, et maitriser la narration visuelle, c'est maitriser l'emotion du spectateur.",
  ),
] as const;
