const textStep = (title: string, content: string, promptBox?: string) => ({
  type: "text" as const,
  title,
  content,
  ...(promptBox ? { promptBox } : {}),
});

const quizStep = (
  title: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
) => ({
  type: "quiz" as const,
  title,
  question,
  options,
  correctIndex,
  explanation,
});

const fillStep = (
  title: string,
  instruction: string,
  sentence: string,
  answers: string[],
  options: string[],
  explanation: string,
) => ({
  type: "fill_blanks" as const,
  title,
  instruction,
  sentence,
  answers,
  options,
  explanation,
});

export const MIDJOURNEY_MODULE_6_STEPS_PT = [
  textStep(
    "Visuais poderosos para marketing com MidJourney",
    "Bem-vindo de volta. Nesta licao, voce vai aprender a criar imagens com impacto profissional para marketing usando MidJourney, desde posts de redes sociais ate campanhas completas. O foco agora nao e apenas fazer uma imagem bonita. E criar visuais que ajudem a posicionar a marca, segurar atencao e aumentar percepcao de valor.\n\nNo marketing digital, a imagem quase sempre fala antes do texto. Antes de ler qualquer headline, o publico ja sentiu se aquela marca parece confiavel, premium, clara ou amadora.",
  ),
  fillStep(
    "Preencha a lacuna - Crie sua foto de produto",
    "Complete o prompt de fotografia de produto com cara de campanha profissional.",
    "/imagine ___, fundo ___, iluminacao ___, fotografia ___, detalhe ___, sensacao de luxo, ___.",
    [
      "um frasco premium de serum para pele com gotas de agua e elementos botanicos",
      "marmore branco limpo",
      "soft box",
      "comercial de produto",
      "ultra alto 8K",
      "--ar 1:1",
    ],
    [
      "um frasco premium de serum para pele com gotas de agua e elementos botanicos",
      "marmore branco limpo",
      "soft box",
      "comercial de produto",
      "ultra alto 8K",
      "--ar 1:1",
    ],
    "Boa foto de produto vende percepcao antes de vender preco. Luz, textura, fundo e clareza visual fazem esse trabalho juntos.",
  ),
  fillStep(
    "Preencha a lacuna - Crie seu post para feed",
    "Monte um visual pensado para parar o scroll no feed do Instagram.",
    "/imagine ___, estilo ___, cores ___, composicao ___, iluminacao ___, clima ___, ___.",
    [
      "uma empreendedora confiante trabalhando em um cafe moderno com notebook",
      "fotografia lifestyle",
      "quentes e vibrantes",
      "regra dos tercos",
      "golden hour",
      "empoderador e inspirador",
      "--ar 4:5",
    ],
    [
      "uma empreendedora confiante trabalhando em um cafe moderno com notebook",
      "fotografia lifestyle",
      "quentes e vibrantes",
      "regra dos tercos",
      "golden hour",
      "empoderador e inspirador",
      "--ar 4:5",
    ],
    "No feed, presenca visual importa. O 4:5 ajuda a ocupar mais espaco e dar mais tempo de leitura para a imagem.",
  ),
  fillStep(
    "Preencha a lacuna - Crie um anuncio pago",
    "Complete o prompt de criativo com energia de anuncio e impacto imediato.",
    "/imagine ___, estilo ___, iluminacao ___, ___, alto contraste, cores ___, sensacao ___, ___.",
    [
      "um jovem em forma depois do treino segurando um shake proteico com suor e determinacao",
      "fotografia esportiva dinamica",
      "dramatica",
      "efeito de motion blur no fundo",
      "fortes e energeticas",
      "poderosa e motivadora",
      "--ar 9:16",
    ],
    [
      "um jovem em forma depois do treino segurando um shake proteico com suor e determinacao",
      "fotografia esportiva dinamica",
      "dramatica",
      "efeito de motion blur no fundo",
      "fortes e energeticas",
      "poderosa e motivadora",
      "--ar 9:16",
    ],
    "Anuncio bom precisa parar o scroll em milissegundos. Expressao, contraste e movimento ajudam a fazer isso rapido.",
  ),
  fillStep(
    "Preencha a lacuna - Crie para Stories e Reels",
    "Monte um visual vertical que deixe espaco para texto e CTA.",
    "/imagine ___, estilo ___, iluminacao ___, fundo ___, composicao vertical ___ deixando ___ no topo e na base para sobreposicao de texto, ___.",
    [
      "uma jovem experimentando oculos em uma boutique e sorrindo de forma natural",
      "fotografia lifestyle espontanea",
      "natural suave",
      "interior desfocado com efeito bokeh",
      "bem distribuida",
      "espaco vazio",
      "--ar 9:16",
    ],
    [
      "uma jovem experimentando oculos em uma boutique e sorrindo de forma natural",
      "fotografia lifestyle espontanea",
      "natural suave",
      "interior desfocado com efeito bokeh",
      "bem distribuida",
      "espaco vazio",
      "--ar 9:16",
    ],
    "Visual vertical forte nao e so tela cheia. E tela cheia com espaco funcional para CTA, titulo e overlay.",
  ),
  fillStep(
    "Preencha a lacuna - Crie identidade visual",
    "Complete o prompt para gerar um visual consistente com identidade de marca.",
    "/imagine ___, estetica ___, paleta ___, estilo ___, iluminacao ___, sensacao ___, identidade visual consistente, ___.",
    [
      "flat lay de produtos naturais de skincare com elementos botanicos e texturas de linho",
      "organica e minimalista",
      "tons terrosos suaves com verde s�lvia e creme quente",
      "fotografia editorial de produto",
      "natural difusa e suave",
      "limpa, premium e confiavel",
      "--ar 1:1",
    ],
    [
      "flat lay de produtos naturais de skincare com elementos botanicos e texturas de linho",
      "organica e minimalista",
      "tons terrosos suaves com verde s�lvia e creme quente",
      "fotografia editorial de produto",
      "natural difusa e suave",
      "limpa, premium e confiavel",
      "--ar 1:1",
    ],
    "Marca forte nao depende de uma imagem isolada. Depende de repeticao coerente de atmosfera, cor, textura e posicionamento.",
  ),
  fillStep(
    "Preencha a lacuna - Crie seu visual sazonal",
    "Complete o prompt de campanha sazonal com atmosfera emocional e cara de marca.",
    "/imagine ___, atmosfera ___, iluminacao ___, cores ___, estilo ___, clima ___, ___.",
    [
      "uma caixa de presente elegante cercada por galhos de pinheiro e luzes douradas sobre uma mesa rustica",
      "natal aconchegante",
      "bokeh dourado e quente",
      "vermelho profundo e dourado",
      "fotografia lifestyle de luxo",
      "magico e celebratorio",
      "--ar 4:5",
    ],
    [
      "uma caixa de presente elegante cercada por galhos de pinheiro e luzes douradas sobre uma mesa rustica",
      "natal aconchegante",
      "bokeh dourado e quente",
      "vermelho profundo e dourado",
      "fotografia lifestyle de luxo",
      "magico e celebratorio",
      "--ar 4:5",
    ],
    "Campanha sazonal forte nao abandona a marca. Ela mistura a emocao da data com a identidade visual do negocio.",
  ),
  fillStep(
    "Preencha a lacuna - Crie sua thumbnail",
    "Monte um prompt de thumbnail com impacto, curiosidade e espaco para texto.",
    "/imagine ___, expressao ___, fundo ___, iluminacao ___, estilo ___, composicao ___ deixando ___ para o titulo, ___.",
    [
      "um homem apontando para a camera com expressao chocada e empolgada",
      "vibrante e exagerada",
      "gradiente amarelo e laranja forte",
      "estudio dramatico",
      "editorial de alto contraste",
      "horizontal",
      "espaco vazio no lado direito",
      "--ar 16:9",
    ],
    [
      "um homem apontando para a camera com expressao chocada e empolgada",
      "vibrante e exagerada",
      "gradiente amarelo e laranja forte",
      "estudio dramatico",
      "editorial de alto contraste",
      "horizontal",
      "espaco vazio no lado direito",
      "--ar 16:9",
    ],
    "Thumbnail boa nao explica tudo. Ela acende curiosidade em menos de um segundo e ainda deixa espaco para o titulo trabalhar junto.",
  ),
  fillStep(
    "Preencha a lacuna - Crie visual de depoimento",
    "Complete o prompt para um visual autentico de prova social.",
    "/imagine ___, estilo ___, iluminacao ___, fundo ___, expressao ___, sensacao ___, ___.",
    [
      "uma mulher de meia-idade sorrindo de forma genuina para a camera com postura relaxada",
      "retrato lifestyle espontaneo",
      "luz natural de janela",
      "ambiente de casa desfocado e acolhedor",
      "autentica e alegre",
      "real, confiavel e profundamente identificavel",
      "--ar 4:5",
    ],
    [
      "uma mulher de meia-idade sorrindo de forma genuina para a camera com postura relaxada",
      "retrato lifestyle espontaneo",
      "luz natural de janela",
      "ambiente de casa desfocado e acolhedor",
      "autentica e alegre",
      "real, confiavel e profundamente identificavel",
      "--ar 4:5",
    ],
    "Prova social convence mais quando parece humana de verdade. O publico percebe muito rapido quando a cena esta encenada demais.",
  ),
  fillStep(
    "Preencha a lacuna - Crie visual educativo",
    "Monte um prompt para artigo, newsletter ou blog com espaco para titulo.",
    "/imagine ___, estilo ___, iluminacao ___, tons ___, composicao ___ com ___ para titulo, ___, ___.",
    [
      "uma profissional apresentando dados em uma grande tela em uma sala de reunioes moderna",
      "fotografia editorial corporativa",
      "suave e limpa",
      "azul frio e branco",
      "horizontal",
      "uma area mais escura vazia no lado esquerdo",
      "credibilidade profissional",
      "--ar 16:9",
    ],
    [
      "uma profissional apresentando dados em uma grande tela em uma sala de reunioes moderna",
      "fotografia editorial corporativa",
      "suave e limpa",
      "azul frio e branco",
      "horizontal",
      "uma area mais escura vazia no lado esquerdo",
      "credibilidade profissional",
      "--ar 16:9",
    ],
    "Visual educativo profissional ja nasce pensando no texto. Nao e so uma imagem bonita com um titulo jogado em cima depois.",
  ),
  fillStep(
    "Preencha a lacuna - Monte sua serie visual",
    "Complete a frase com a logica certa para criar uma campanha coerente em varias pecas.",
    "Para criar uma serie coesa, mantenha ___ estes elementos em todos os prompts: ___ de cores, ___ de iluminacao, ___ fotografico e ___ de composicao. Varie apenas o ___ principal para contar uma historia visual ___ ao longo da campanha.",
    [
      "fixos",
      "paleta",
      "tipo",
      "estilo",
      "regra",
      "sujeito e acao",
      "progressiva",
    ],
    [
      "fixos",
      "paleta",
      "tipo",
      "estilo",
      "regra",
      "sujeito e acao",
      "progressiva",
    ],
    "Serie forte nao nasce de sorte. Nasce de uma base visual fixa com variacoes controladas em torno dela.",
  ),
  textStep(
    "Conclusao",
    "Com MidJourney, qualquer marca pode produzir visuais com nivel de agencia sem depender de equipe grande, estudio ou orcamento elevado. Fotos de produto, posts de feed, criativos para anuncio, thumbnails, conteudo educativo, prova social e campanhas inteiras podem nascer de prompts bem construidos e de uma estrategia visual clara.\n\nA diferenca entre uma marca que cresce e uma que estagna nao esta so no produto. Esta tambem em como ela se apresenta visualmente antes de dizer qualquer palavra.",
  ),
] as const;

export const MIDJOURNEY_MODULE_6_STEPS_EN = [
  textStep(
    "Powerful marketing visuals with MidJourney",
    "Welcome back. In this lesson, you will learn how to create professional-impact marketing visuals with MidJourney, from social posts to full campaigns. The goal is no longer just to create beautiful images. The goal is to create visuals that strengthen positioning, hold attention, and increase perceived value.\n\nIn digital marketing, the image usually speaks before the copy. Before reading a single headline, the audience has already felt whether the brand looks trustworthy, premium, clear, or amateur.",
  ),
  fillStep(
    "Fill in the blanks - Create your product photo",
    "Complete the product photography prompt with campaign-level polish.",
    "/imagine ___, ___ background, ___ lighting, ___ photography, ___ detail, luxury feel, ___.",
    [
      "a premium skincare serum bottle with water droplets and botanical elements",
      "clean white marble surface",
      "soft box",
      "commercial product",
      "ultra high 8K",
      "--ar 1:1",
    ],
    [
      "a premium skincare serum bottle with water droplets and botanical elements",
      "clean white marble surface",
      "soft box",
      "commercial product",
      "ultra high 8K",
      "--ar 1:1",
    ],
    "Strong product imagery sells perception before it sells price. Light, texture, background, and clarity all contribute to that effect.",
  ),
  fillStep(
    "Fill in the blanks - Create your feed post",
    "Build a visual designed to stop the scroll in the Instagram feed.",
    "/imagine ___, ___ style, ___ colors, ___ composition, ___ lighting, ___ mood, ___.",
    [
      "a confident woman entrepreneur working in a modern cafe with a laptop",
      "lifestyle photography",
      "warm and vibrant",
      "rule of thirds",
      "golden hour",
      "empowering and inspiring",
      "--ar 4:5",
    ],
    [
      "a confident woman entrepreneur working in a modern cafe with a laptop",
      "lifestyle photography",
      "warm and vibrant",
      "rule of thirds",
      "golden hour",
      "empowering and inspiring",
      "--ar 4:5",
    ],
    "In the feed, visual presence matters. A 4:5 frame occupies more space and buys a little more time for attention.",
  ),
  fillStep(
    "Fill in the blanks - Create a paid ad",
    "Complete the prompt for an ad creative with instant impact.",
    "/imagine ___, ___ style, ___ lighting, ___, high contrast, ___ colors, ___ feel, ___.",
    [
      "a fit young man after a workout holding a protein shake with sweat and determination",
      "dynamic sports photography",
      "dramatic",
      "motion blur effect in background",
      "bold and energetic",
      "powerful and motivating",
      "--ar 9:16",
    ],
    [
      "a fit young man after a workout holding a protein shake with sweat and determination",
      "dynamic sports photography",
      "dramatic",
      "motion blur effect in background",
      "bold and energetic",
      "powerful and motivating",
      "--ar 9:16",
    ],
    "Great ads stop the scroll in milliseconds. Expression, contrast, and motion cues help them do exactly that.",
  ),
  fillStep(
    "Fill in the blanks - Create for Stories and Reels",
    "Build a vertical visual with space for text and CTA.",
    "/imagine ___, ___ style, ___ lighting, ___ background, ___ vertical composition leaving ___ at the top and bottom for text overlay, ___.",
    [
      "a young woman trying on sunglasses in a boutique smiling naturally",
      "candid lifestyle photography",
      "soft natural",
      "blurred bokeh store interior",
      "balanced",
      "empty space",
      "--ar 9:16",
    ],
    [
      "a young woman trying on sunglasses in a boutique smiling naturally",
      "candid lifestyle photography",
      "soft natural",
      "blurred bokeh store interior",
      "balanced",
      "empty space",
      "--ar 9:16",
    ],
    "A good vertical visual is not just full screen. It is full screen with functional space for CTA, title, and overlay.",
  ),
  fillStep(
    "Fill in the blanks - Create brand identity imagery",
    "Complete the prompt for a visual that reinforces brand identity.",
    "/imagine ___, ___ aesthetic, ___ color palette, ___ style, ___ lighting, ___ feel, consistent brand identity, ___.",
    [
      "flat lay of natural skincare products with botanical elements and linen textures",
      "organic and minimalist",
      "soft earth tones with sage green and warm cream",
      "editorial product photography",
      "soft diffused natural",
      "clean premium and trustworthy",
      "--ar 1:1",
    ],
    [
      "flat lay of natural skincare products with botanical elements and linen textures",
      "organic and minimalist",
      "soft earth tones with sage green and warm cream",
      "editorial product photography",
      "soft diffused natural",
      "clean premium and trustworthy",
      "--ar 1:1",
    ],
    "Strong brands are not built by one image. They are built by repeating atmosphere, color, texture, and positioning with consistency.",
  ),
  fillStep(
    "Fill in the blanks - Create your seasonal visual",
    "Complete the prompt for a seasonal campaign visual with emotional atmosphere and brand polish.",
    "/imagine ___, ___ atmosphere, ___ lighting, ___ colors, ___ style, ___ mood, ___.",
    [
      "a beautifully wrapped gift box surrounded by pine branches and golden fairy lights on a rustic wooden table",
      "cozy Christmas",
      "warm golden bokeh",
      "deep red and gold",
      "luxury lifestyle photography",
      "magical and celebratory",
      "--ar 4:5",
    ],
    [
      "a beautifully wrapped gift box surrounded by pine branches and golden fairy lights on a rustic wooden table",
      "cozy Christmas",
      "warm golden bokeh",
      "deep red and gold",
      "luxury lifestyle photography",
      "magical and celebratory",
      "--ar 4:5",
    ],
    "Strong seasonal campaigns do not abandon the brand. They blend the emotion of the date with the visual identity of the business.",
  ),
  fillStep(
    "Fill in the blanks - Create your thumbnail",
    "Build a thumbnail prompt with impact, curiosity, and space for text.",
    "/imagine ___, ___ expression, ___ background, ___ lighting, ___ style, ___ composition leaving ___ for title text, ___.",
    [
      "a man pointing at camera with shocked and excited facial expression",
      "vibrant and exaggerated",
      "bold yellow and orange gradient",
      "dramatic studio",
      "high contrast editorial",
      "horizontal",
      "empty space on the right side",
      "--ar 16:9",
    ],
    [
      "a man pointing at camera with shocked and excited facial expression",
      "vibrant and exaggerated",
      "bold yellow and orange gradient",
      "dramatic studio",
      "high contrast editorial",
      "horizontal",
      "empty space on the right side",
      "--ar 16:9",
    ],
    "A strong thumbnail does not explain everything. It sparks curiosity in under a second and still leaves room for the title to help.",
  ),
  fillStep(
    "Fill in the blanks - Create testimonial imagery",
    "Complete the prompt for an authentic social-proof visual.",
    "/imagine ___, ___ style, ___ lighting, ___ background, ___ expression, ___ feel, ___.",
    [
      "a happy middle-aged woman smiling genuinely at camera with relaxed body language",
      "candid lifestyle portrait",
      "soft natural window",
      "warm blurred home environment",
      "authentic and joyful",
      "real trustworthy and deeply relatable",
      "--ar 4:5",
    ],
    [
      "a happy middle-aged woman smiling genuinely at camera with relaxed body language",
      "candid lifestyle portrait",
      "soft natural window",
      "warm blurred home environment",
      "authentic and joyful",
      "real trustworthy and deeply relatable",
      "--ar 4:5",
    ],
    "Social proof persuades more when it feels genuinely human. People can sense staged visuals very quickly.",
  ),
  fillStep(
    "Fill in the blanks - Create educational imagery",
    "Build a prompt for article, newsletter, or blog visuals with room for the title.",
    "/imagine ___, ___ style, ___ lighting, ___ tones, ___ composition with ___ for title text placement, ___, ___.",
    [
      "a professional woman presenting data on a large screen in a modern conference room",
      "editorial corporate photography",
      "soft and clean",
      "cool blue and white",
      "horizontal",
      "empty darker area on the left",
      "professional credibility",
      "--ar 16:9",
    ],
    [
      "a professional woman presenting data on a large screen in a modern conference room",
      "editorial corporate photography",
      "soft and clean",
      "cool blue and white",
      "horizontal",
      "empty darker area on the left",
      "professional credibility",
      "--ar 16:9",
    ],
    "Professional educational imagery is designed with text in mind from the beginning, not as an afterthought.",
  ),
  fillStep(
    "Fill in the blanks - Build your visual series",
    "Complete the sentence with the right logic for a coherent campaign across multiple pieces.",
    "To create a cohesive series, keep these elements ___ in every prompt: color ___, lighting ___, photographic ___, and composition ___. Vary only the main ___ of each image to tell a ___ visual story across the campaign.",
    [
      "fixed",
      "palette",
      "type",
      "style",
      "rule",
      "subject and action",
      "progressive",
    ],
    [
      "fixed",
      "palette",
      "type",
      "style",
      "rule",
      "subject and action",
      "progressive",
    ],
    "A strong series does not happen by luck. It comes from a stable visual spine with controlled variation around it.",
  ),
  textStep(
    "Conclusion",
    "With MidJourney, any brand can now produce agency-level visuals without a large team, studio, or expensive budget. Product photos, feed posts, ad creatives, thumbnails, educational content, social proof, and full campaigns can come from well-built prompts and clear visual strategy.\n\nThe difference between a brand that grows and one that stalls is not only the product. It is also how the brand presents itself visually before saying a single word.",
  ),
] as const;

const MIDJOURNEY_MODULE_6_STEPS_ES_BASE = [
  textStep(
    "Visuales poderosos para marketing con MidJourney",
    "Bienvenido de nuevo. En esta leccion vas a aprender a crear imagenes con impacto profesional para marketing usando MidJourney, desde publicaciones en redes hasta campanas completas. El objetivo ya no es solo crear una imagen bonita. El objetivo es crear visuales que refuercen el posicionamiento, sostengan la atencion y eleven el valor percibido.\n\nEn marketing digital, la imagen suele hablar antes que el texto. Antes de leer un titulo, el publico ya sintio si la marca parece confiable, premium, clara o amateur.",
  ),
  fillStep(
    "Completa los espacios - Crea tu foto de producto",
    "Completa el prompt de fotografia de producto con acabado de campana profesional.",
    "/imagine ___, fondo ___, iluminacion ___, fotografia ___, detalle ___, sensacion de lujo, ___.",
    [
      "un frasco premium de serum para la piel con gotas de agua y elementos botanicos",
      "superficie limpia de marmol blanco",
      "soft box",
      "comercial de producto",
      "ultra alto 8K",
      "--ar 1:1",
    ],
    [
      "un frasco premium de serum para la piel con gotas de agua y elementos botanicos",
      "superficie limpia de marmol blanco",
      "soft box",
      "comercial de producto",
      "ultra alto 8K",
      "--ar 1:1",
    ],
    "Una buena foto de producto vende percepcion antes de vender precio. Luz, textura, fondo y claridad visual trabajan juntos para eso.",
  ),
  fillStep(
    "Completa los espacios - Crea tu post para feed",
    "Construye un visual pensado para detener el scroll en el feed de Instagram.",
    "/imagine ___, estilo ___, colores ___, composicion ___, iluminacion ___, mood ___, ___.",
    [
      "una emprendedora segura trabajando en un cafe moderno con portatil",
      "fotografia lifestyle",
      "calidos y vibrantes",
      "regla de tercios",
      "golden hour",
      "empoderador e inspirador",
      "--ar 4:5",
    ],
    [
      "una emprendedora segura trabajando en un cafe moderno con portatil",
      "fotografia lifestyle",
      "calidos y vibrantes",
      "regla de tercios",
      "golden hour",
      "empoderador e inspirador",
      "--ar 4:5",
    ],
    "En el feed, la presencia visual importa. El 4:5 ocupa mas espacio y compra unos segundos extra de atencion.",
  ),
  fillStep(
    "Completa los espacios - Crea un anuncio pago",
    "Completa el prompt de anuncio con impacto inmediato.",
    "/imagine ___, estilo ___, iluminacion ___, ___, alto contraste, colores ___, sensacion ___, ___.",
    [
      "un joven atl�tico despues de entrenar sosteniendo un batido proteico con sudor y determinacion",
      "fotografia deportiva dinamica",
      "dramatica",
      "efecto de motion blur en el fondo",
      "fuertes y energeticos",
      "poderosa y motivadora",
      "--ar 9:16",
    ],
    [
      "un joven atl�tico despues de entrenar sosteniendo un batido proteico con sudor y determinacion",
      "fotografia deportiva dinamica",
      "dramatica",
      "efecto de motion blur en el fondo",
      "fuertes y energeticos",
      "poderosa y motivadora",
      "--ar 9:16",
    ],
    "Un buen anuncio detiene el scroll en milisegundos. Expresion, contraste y sensacion de movimiento ayudan a lograrlo.",
  ),
  fillStep(
    "Completa los espacios - Crea para Stories y Reels",
    "Construye un visual vertical con espacio para texto y CTA.",
    "/imagine ___, estilo ___, iluminacion ___, fondo ___, composicion vertical ___ dejando ___ arriba y abajo para texto, ___.",
    [
      "una joven probandose gafas en una boutique y sonriendo de forma natural",
      "fotografia lifestyle espontanea",
      "natural suave",
      "interior desenfocado con bokeh",
      "equilibrada",
      "espacio vacio",
      "--ar 9:16",
    ],
    [
      "una joven probandose gafas en una boutique y sonriendo de forma natural",
      "fotografia lifestyle espontanea",
      "natural suave",
      "interior desenfocado con bokeh",
      "equilibrada",
      "espacio vacio",
      "--ar 9:16",
    ],
    "Un buen visual vertical no es solo pantalla completa. Es pantalla completa con espacio funcional para CTA, titulo y overlay.",
  ),
] as const;


const MIDJOURNEY_MODULE_6_STEPS_ES_EXTRA = [
  fillStep(
    "Completa los espacios - Crea identidad visual",
    "Completa el prompt para un visual que refuerce identidad de marca.",
    "/imagine ___, estetica ___, paleta ___, estilo ___, iluminacion ___, sensacion ___, identidad visual consistente, ___.",
    [
      "flat lay de productos naturales de skincare con elementos botanicos y texturas de lino",
      "organica y minimalista",
      "tonos tierra suaves con verde salvia y crema calida",
      "fotografia editorial de producto",
      "natural difusa y suave",
      "limpia, premium y confiable",
      "--ar 1:1",
    ],
    [
      "flat lay de productos naturales de skincare con elementos botanicos y texturas de lino",
      "organica y minimalista",
      "tonos tierra suaves con verde salvia y crema calida",
      "fotografia editorial de producto",
      "natural difusa y suave",
      "limpia, premium y confiable",
      "--ar 1:1",
    ],
    "Una marca fuerte no depende de una imagen aislada. Depende de repetir atmosfera, color, textura y posicionamiento con coherencia.",
  ),
  fillStep(
    "Completa los espacios - Crea tu visual estacional",
    "Completa el prompt de campana estacional con atmosfera emocional y acabado de marca.",
    "/imagine ___, atmosfera ___, iluminacion ___, colores ___, estilo ___, mood ___, ___.",
    [
      "una caja de regalo elegante rodeada de ramas de pino y luces doradas sobre una mesa rustica",
      "Navidad acogedora",
      "bokeh dorado y calido",
      "rojo profundo y dorado",
      "fotografia lifestyle de lujo",
      "magico y celebratorio",
      "--ar 4:5",
    ],
    [
      "una caja de regalo elegante rodeada de ramas de pino y luces doradas sobre una mesa rustica",
      "Navidad acogedora",
      "bokeh dorado y calido",
      "rojo profundo y dorado",
      "fotografia lifestyle de lujo",
      "magico y celebratorio",
      "--ar 4:5",
    ],
    "Una buena campana estacional no abandona la marca. Mezcla la emocion de la fecha con la identidad visual del negocio.",
  ),
  fillStep(
    "Completa los espacios - Crea tu thumbnail",
    "Construye un prompt de thumbnail con impacto, curiosidad y espacio para texto.",
    "/imagine ___, expresion ___, fondo ___, iluminacion ___, estilo ___, composicion ___ dejando ___ para el titulo, ___.",
    [
      "un hombre apuntando a la camara con expresion sorprendida y entusiasmada",
      "vibrante y exagerada",
      "gradiente amarillo y naranja intenso",
      "estudio dramatico",
      "editorial de alto contraste",
      "horizontal",
      "espacio vacio en el lado derecho",
      "--ar 16:9",
    ],
    [
      "un hombre apuntando a la camara con expresion sorprendida y entusiasmada",
      "vibrante y exagerada",
      "gradiente amarillo y naranja intenso",
      "estudio dramatico",
      "editorial de alto contraste",
      "horizontal",
      "espacio vacio en el lado derecho",
      "--ar 16:9",
    ],
    "Una buena thumbnail no explica todo. Activa curiosidad en menos de un segundo y deja espacio para que el titulo sume.",
  ),
  fillStep(
    "Completa los espacios - Crea visual de testimonio",
    "Completa el prompt para una prueba social con autenticidad.",
    "/imagine ___, estilo ___, iluminacion ___, fondo ___, expresion ___, sensacion ___, ___.",
    [
      "una mujer de mediana edad sonriendo de forma genuina a camara con postura relajada",
      "retrato lifestyle espontaneo",
      "luz natural de ventana",
      "hogar desenfocado y calido",
      "autentica y alegre",
      "real, confiable y profundamente cercana",
      "--ar 4:5",
    ],
    [
      "una mujer de mediana edad sonriendo de forma genuina a camara con postura relajada",
      "retrato lifestyle espontaneo",
      "luz natural de ventana",
      "hogar desenfocado y calido",
      "autentica y alegre",
      "real, confiable y profundamente cercana",
      "--ar 4:5",
    ],
    "La prueba social convence mas cuando se siente humana de verdad. El publico detecta rapido cuando la escena esta demasiado armada.",
  ),
  fillStep(
    "Completa los espacios - Crea visual educativo",
    "Construye un prompt para articulo, newsletter o blog con espacio para titulo.",
    "/imagine ___, estilo ___, iluminacion ___, tonos ___, composicion ___ con ___ para el titulo, ___, ___.",
    [
      "una profesional presentando datos en una gran pantalla dentro de una sala moderna",
      "fotografia editorial corporativa",
      "suave y limpia",
      "azul frio y blanco",
      "horizontal",
      "un area mas oscura vacia a la izquierda",
      "credibilidad profesional",
      "--ar 16:9",
    ],
    [
      "una profesional presentando datos en una gran pantalla dentro de una sala moderna",
      "fotografia editorial corporativa",
      "suave y limpia",
      "azul frio y blanco",
      "horizontal",
      "un area mas oscura vacia a la izquierda",
      "credibilidad profesional",
      "--ar 16:9",
    ],
    "El visual educativo profesional nace pensando en el texto. No es una imagen bonita con un titulo pegado encima despues.",
  ),
  fillStep(
    "Completa los espacios - Construye tu serie visual",
    "Completa la frase con la logica correcta para una campana coherente en varias piezas.",
    "Para crear una serie coherente, mant�n ___ estos elementos en todos los prompts: ___ de color, ___ de iluminacion, ___ fotografico y ___ de composicion. Varia solo el ___ principal de cada imagen para contar una historia visual ___ a lo largo de la campana.",
    [
      "fijos",
      "paleta",
      "tipo",
      "estilo",
      "regla",
      "sujeto y accion",
      "progresiva",
    ],
    [
      "fijos",
      "paleta",
      "tipo",
      "estilo",
      "regla",
      "sujeto y accion",
      "progresiva",
    ],
    "Una serie fuerte no nace por suerte. Nace de una columna visual estable con variaciones controladas alrededor.",
  ),
  textStep(
    "Conclusion",
    "Con MidJourney, cualquier marca puede producir visuales con nivel de agencia sin depender de equipo grande, estudio o presupuesto alto. Fotos de producto, posts de feed, creativos para anuncios, thumbnails, contenido educativo, prueba social y campanas completas pueden surgir de prompts bien construidos y estrategia visual clara.\n\nLa diferencia entre una marca que crece y otra que se estanca no esta solo en el producto. Tambien esta en como se presenta visualmente antes de decir una sola palabra.",
  ),
] as const;

export const MIDJOURNEY_MODULE_6_STEPS_ES = [...MIDJOURNEY_MODULE_6_STEPS_ES_BASE, ...MIDJOURNEY_MODULE_6_STEPS_ES_EXTRA] as const;


export const MIDJOURNEY_MODULE_6_STEPS_FR = [
  textStep(
    "Des visuels marketing puissants avec MidJourney",
    "Bon retour. Dans cette lecon, tu vas apprendre a creer des images a impact professionnel pour le marketing avec MidJourney, depuis les posts reseaux sociaux jusqu'aux campagnes completes. Le but n'est plus seulement de produire une belle image. Le but est de creer des visuels qui renforcent le positionnement, retiennent l'attention et augmentent la valeur percue.\n\nEn marketing digital, l'image parle souvent avant le texte. Avant de lire un titre, le public a deja ressenti si la marque parait fiable, premium, claire ou amateur.",
  ),
  fillStep(
    "Complete les blancs - Cree ta photo produit",
    "Complete le prompt de photographie produit avec un rendu digne d'une campagne.",
    "/imagine ___, fond ___, eclairage ___, photographie ___, detail ___, sensation de luxe, ___.",
    [
      "un flacon premium de serum pour la peau avec des gouttes d'eau et des elements botaniques",
      "surface propre en marbre blanc",
      "soft box",
      "commerciale produit",
      "ultra haute 8K",
      "--ar 1:1",
    ],
    [
      "un flacon premium de serum pour la peau avec des gouttes d'eau et des elements botaniques",
      "surface propre en marbre blanc",
      "soft box",
      "commerciale produit",
      "ultra haute 8K",
      "--ar 1:1",
    ],
    "Une bonne photo produit vend la perception avant de vendre le prix. Lumiere, texture, fond et clarte visuelle travaillent ensemble pour cela.",
  ),
  fillStep(
    "Complete les blancs - Cree ton post feed",
    "Construit un visuel pense pour stopper le scroll dans le feed Instagram.",
    "/imagine ___, style ___, couleurs ___, composition ___, eclairage ___, mood ___, ___.",
    [
      "une entrepreneuse confiante travaillant dans un cafe moderne avec un ordinateur portable",
      "photographie lifestyle",
      "chaudes et vibrantes",
      "regle des tiers",
      "golden hour",
      "inspirant et valorisant",
      "--ar 4:5",
    ],
    [
      "une entrepreneuse confiante travaillant dans un cafe moderne avec un ordinateur portable",
      "photographie lifestyle",
      "chaudes et vibrantes",
      "regle des tiers",
      "golden hour",
      "inspirant et valorisant",
      "--ar 4:5",
    ],
    "Dans le feed, la presence visuelle compte. Le 4:5 prend plus de place et achete quelques secondes d'attention supplementaires.",
  ),
  fillStep(
    "Complete les blancs - Cree une annonce payante",
    "Complete le prompt d'un creatif d'annonce a impact immediat.",
    "/imagine ___, style ___, eclairage ___, ___, contraste eleve, couleurs ___, sensation ___, ___.",
    [
      "un jeune sportif apres l'entrainement tenant un shake proteine avec sueur et determination",
      "photographie sportive dynamique",
      "dramatique",
      "effet de motion blur en arriere-plan",
      "fortes et energiques",
      "puissante et motivante",
      "--ar 9:16",
    ],
    [
      "un jeune sportif apres l'entrainement tenant un shake proteine avec sueur et determination",
      "photographie sportive dynamique",
      "dramatique",
      "effet de motion blur en arriere-plan",
      "fortes et energiques",
      "puissante et motivante",
      "--ar 9:16",
    ],
    "Une bonne annonce stoppe le scroll en millisecondes. Expression, contraste et sensation de mouvement aident a y parvenir.",
  ),
  fillStep(
    "Complete les blancs - Cree pour Stories et Reels",
    "Construis un visuel vertical avec de l'espace pour le texte et le CTA.",
    "/imagine ___, style ___, eclairage ___, fond ___, composition verticale ___ laissant ___ en haut et en bas pour le texte, ___.",
    [
      "une jeune femme essayant des lunettes dans une boutique en souriant naturellement",
      "photographie lifestyle spontanee",
      "naturel doux",
      "interieur flou avec effet bokeh",
      "equilibree",
      "de l'espace vide",
      "--ar 9:16",
    ],
    [
      "une jeune femme essayant des lunettes dans une boutique en souriant naturellement",
      "photographie lifestyle spontanee",
      "naturel doux",
      "interieur flou avec effet bokeh",
      "equilibree",
      "de l'espace vide",
      "--ar 9:16",
    ],
    "Un bon visuel vertical n'est pas seulement plein ecran. Il est plein ecran avec un espace fonctionnel pour le CTA, le titre et l'overlay.",
  ),
  fillStep(
    "Complete les blancs - Cree l'identite visuelle",
    "Complete le prompt pour un visuel qui renforce l'identite de marque.",
    "/imagine ___, esthetique ___, palette ___, style ___, eclairage ___, sensation ___, identite visuelle coherente, ___.",
    [
      "flat lay de produits skincare naturels avec elements botaniques et textures de lin",
      "organique et minimaliste",
      "tons terre doux avec vert sauge et creme chaude",
      "photographie editoriale produit",
      "naturelle diffuse et douce",
      "propre, premium et rassurante",
      "--ar 1:1",
    ],
    [
      "flat lay de produits skincare naturels avec elements botaniques et textures de lin",
      "organique et minimaliste",
      "tons terre doux avec vert sauge et creme chaude",
      "photographie editoriale produit",
      "naturelle diffuse et douce",
      "propre, premium et rassurante",
      "--ar 1:1",
    ],
    "Une marque forte ne repose pas sur une image isolee. Elle repose sur la repetition coherente d'une atmosphere, d'une couleur, d'une texture et d'un positionnement.",
  ),
  fillStep(
    "Complete les blancs - Cree ton visuel saisonnier",
    "Complete le prompt d'une campagne saisonniere avec atmosphere emotionnelle et finition de marque.",
    "/imagine ___, atmosphere ___, eclairage ___, couleurs ___, style ___, mood ___, ___.",
    [
      "une boite cadeau elegante entouree de branches de pin et de lumieres dorees sur une table rustique",
      "Noel chaleureux",
      "bokeh dore et chaud",
      "rouge profond et or",
      "photographie lifestyle de luxe",
      "magique et celebratoire",
      "--ar 4:5",
    ],
    [
      "une boite cadeau elegante entouree de branches de pin et de lumieres dorees sur une table rustique",
      "Noel chaleureux",
      "bokeh dore et chaud",
      "rouge profond et or",
      "photographie lifestyle de luxe",
      "magique et celebratoire",
      "--ar 4:5",
    ],
    "Une campagne saisonniere forte n'abandonne pas la marque. Elle melange l'emotion de la date avec l'identite visuelle du business.",
  ),
  fillStep(
    "Complete les blancs - Cree ta thumbnail",
    "Construit un prompt de thumbnail avec impact, curiosite et espace pour le texte.",
    "/imagine ___, expression ___, fond ___, eclairage ___, style ___, composition ___ laissant ___ pour le titre, ___.",
    [
      "un homme pointant la camera avec une expression choquee et enthousiaste",
      "vibrante et exageree",
      "degrade jaune et orange puissant",
      "studio dramatique",
      "editorial a fort contraste",
      "horizontale",
      "de l'espace vide sur la droite",
      "--ar 16:9",
    ],
    [
      "un homme pointant la camera avec une expression choquee et enthousiaste",
      "vibrante et exageree",
      "degrade jaune et orange puissant",
      "studio dramatique",
      "editorial a fort contraste",
      "horizontale",
      "de l'espace vide sur la droite",
      "--ar 16:9",
    ],
    "Une bonne thumbnail n'explique pas tout. Elle active la curiosite en moins d'une seconde et laisse encore de la place au titre.",
  ),
  fillStep(
    "Complete les blancs - Cree un visuel de temoignage",
    "Complete le prompt pour une preuve sociale authentique.",
    "/imagine ___, style ___, eclairage ___, fond ___, expression ___, sensation ___, ___.",
    [
      "une femme d'age moyen souriant sincerement face camera avec une posture detendue",
      "portrait lifestyle spontane",
      "lumiere naturelle de fenetre",
      "interieur de maison flou et chaleureux",
      "authentique et joyeuse",
      "reelle, fiable et tres relatable",
      "--ar 4:5",
    ],
    [
      "une femme d'age moyen souriant sincerement face camera avec une posture detendue",
      "portrait lifestyle spontane",
      "lumiere naturelle de fenetre",
      "interieur de maison flou et chaleureux",
      "authentique et joyeuse",
      "reelle, fiable et tres relatable",
      "--ar 4:5",
    ],
    "La preuve sociale persuade davantage quand elle parait vraiment humaine. Le public sent tres vite quand le visuel est trop joue.",
  ),
  fillStep(
    "Complete les blancs - Cree un visuel educatif",
    "Construit un prompt pour article, newsletter ou blog avec de l'espace pour le titre.",
    "/imagine ___, style ___, eclairage ___, tons ___, composition ___ avec ___ pour le titre, ___, ___.",
    [
      "une professionnelle presentant des donnees sur un grand ecran dans une salle moderne",
      "photographie editoriale corporate",
      "douce et propre",
      "bleu froid et blanc",
      "horizontale",
      "une zone plus sombre vide a gauche",
      "credibilite professionnelle",
      "--ar 16:9",
    ],
    [
      "une professionnelle presentant des donnees sur un grand ecran dans une salle moderne",
      "photographie editoriale corporate",
      "douce et propre",
      "bleu froid et blanc",
      "horizontale",
      "une zone plus sombre vide a gauche",
      "credibilite professionnelle",
      "--ar 16:9",
    ],
    "Un visuel educatif professionnel nait en pensant au texte. Ce n'est pas une jolie image avec un titre colle apres coup.",
  ),
  fillStep(
    "Complete les blancs - Construis ta serie visuelle",
    "Complete la phrase avec la bonne logique pour une campagne coherente sur plusieurs pieces.",
    "Pour creer une serie coherente, garde ces elements ___ dans tous les prompts : ___ de couleurs, ___ d'eclairage, ___ photographique et ___ de composition. Ne fais varier que le ___ principal de chaque image pour raconter une histoire visuelle ___ tout au long de la campagne.",
    [
      "fixes",
      "palette",
      "type",
      "style",
      "regle",
      "sujet et action",
      "progressive",
    ],
    [
      "fixes",
      "palette",
      "type",
      "style",
      "regle",
      "sujet et action",
      "progressive",
    ],
    "Une serie forte ne nait pas par hasard. Elle nait d'une colonne visuelle stable avec des variations controlees autour.",
  ),
  textStep(
    "Conclusion",
    "Avec MidJourney, n'importe quelle marque peut produire des visuels au niveau d'une agence sans dependance a une grosse equipe, a un studio ou a un budget eleve. Photos produit, posts de feed, creatives d'annonce, thumbnails, contenu educatif, preuve sociale et campagnes completes peuvent naitre de prompts bien construits et d'une strategie visuelle claire.\n\nLa difference entre une marque qui grandit et une marque qui stagne ne tient pas seulement au produit. Elle tient aussi a la maniere dont elle se presente visuellement avant de dire un seul mot.",
  ),
] as const;
