const textStep = (title: string, content: string, promptBox?: string) => ({
  type: "text" as const,
  title,
  content,
  ...(promptBox ? { promptBox } : {}),
});

const quizStep = (
  title: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
) => ({
  type: "quiz" as const,
  title,
  question,
  options,
  correctIndex,
  explanation,
});

const fillStep = (
  title: string,
  instruction: string,
  sentence: string,
  answers: string[],
  options: string[],
  explanation: string,
) => ({
  type: "fill_blanks" as const,
  title,
  instruction,
  sentence,
  answers,
  options,
  explanation,
});

export const MIDJOURNEY_MODULE_4_STEPS_PT = [
  textStep(
    "Ponto de vista no MidJourney - O angulo que transforma tudo",
    "Bem-vindo de volta! Nesta licao, voce vai aprender como o ponto de vista, ou seja, o angulo de camera usado no prompt, transforma completamente a narrativa, a emocao e o impacto de qualquer imagem criada no MidJourney. A mesma cena vista de angulos diferentes conta historias completamente diferentes.\n\nFotografos e diretores de cinema sabem que o angulo de camera nao e apenas uma escolha tecnica. E uma decisao narrativa. Ele define a relacao de poder entre espectador e sujeito, cria emocao e direciona o olhar para onde voce quer.",
  ),
  quizStep(
    "Por que o ponto de vista importa",
    "Por que o ponto de vista influencia a narrativa de uma imagem?",
    [
      "Porque o angulo de camera define a relacao emocional entre o espectador e o sujeito, criando sensacoes de poder, vulnerabilidade, intimidade ou grandiosidade.",
      "Porque angulos diferentes geram resolucoes diferentes.",
      "Porque o ponto de vista so importa em fotos de pessoas e personagens.",
      "Porque todos os angulos transmitem a mesma emocao em sujeitos diferentes.",
    ],
    0,
    "O angulo muda a posicao emocional do observador diante da cena. Ele altera como sentimos poder, proximidade, escala e tensao.",
  ),
  fillStep(
    "Preencha a lacuna - Use o Eye Level",
    "Complete o prompt com os elementos corretos do angulo ao nivel dos olhos.",
    "/imagine ___, enquadramento eye level, estilo ___, iluminacao ___, fundo ___, expressao ___, ___",
    [
      "uma jovem professora explicando algo para seus alunos",
      "fotografia documental",
      "natural suave",
      "sala de aula acolhedora",
      "engajada e apaixonada",
      "--ar 16:9",
    ],
    [
      "uma jovem professora explicando algo para seus alunos",
      "fotografia documental",
      "natural suave",
      "sala de aula acolhedora",
      "engajada e apaixonada",
      "--ar 16:9",
    ],
    "Eye Level aproxima o espectador do sujeito e cria uma sensacao de igualdade e realismo humano.",
  ),
  quizStep(
    "Emocao do Eye Level",
    "Qual sensacao emocional o Eye Level transmite em um retrato?",
    [
      "Superioridade e poder do sujeito sobre o espectador.",
      "Vulnerabilidade e fragilidade do sujeito fotografado.",
      "Igualdade, proximidade e conexao humana, gerando identificacao imediata.",
      "Eye Level so funciona para fotos de grupos.",
    ],
    2,
    "Eye Level cria equilibrio. O espectador se relaciona com o sujeito como um igual, e isso aumenta empatia e conexao.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Low Angle",
    "Monte o prompt com o angulo baixo olhando para cima.",
    "/imagine ___, low angle olhando para cima, estilo ___, iluminacao ___, fundo de ceu ___, clima ___, ___",
    [
      "um super-heroi no topo de um predio",
      "arte conceitual cinematografica",
      "dramatic rim",
      "escuro e tempestuoso",
      "poderoso e epico",
      "--ar 9:16",
    ],
    [
      "um super-heroi no topo de um predio",
      "arte conceitual cinematografica",
      "dramatic rim",
      "escuro e tempestuoso",
      "poderoso e epico",
      "--ar 9:16",
    ],
    "Low Angle amplia poder e grandiosidade. Ele faz o sujeito parecer dominante e monumental dentro do quadro.",
  ),
  quizStep(
    "Quando usar Low Angle",
    "Em qual situacao de marketing o Low Angle seria a escolha mais estrategica?",
    [
      "Para mostrar um produto pequeno como relogio ou joia.",
      "Para criar imagens de culinaria que parecam apetitosas.",
      "Para comunicar poder, lideranca e autoridade de uma marca ou produto, como automoveis, esporte ou marcas premium.",
      "Low Angle so funciona para personagens masculinos em acao.",
    ],
    2,
    "Low Angle e muito forte quando a marca quer transmitir superioridade, aspiracao, lideranca e presenca.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com High Angle",
    "Complete o prompt com camera acima do sujeito olhando para baixo.",
    "/imagine ___, high angle olhando para baixo, estilo ___, iluminacao ___, composicao ___, ___",
    [
      "uma mulher sentada sozinha lendo em um parque cercado por folhas de outono",
      "fotografia lifestyle",
      "quente, suave e natural",
      "vista superior com espaco negativo",
      "--ar 4:5",
    ],
    [
      "uma mulher sentada sozinha lendo em um parque cercado por folhas de outono",
      "fotografia lifestyle",
      "quente, suave e natural",
      "vista superior com espaco negativo",
      "--ar 4:5",
    ],
    "High Angle pode transmitir vulnerabilidade, contexto ou organizacao visual, dependendo do sujeito e da composicao.",
  ),
  quizStep(
    "Por que High Angle e popular em flat lay",
    "Por que o High Angle e tao popular em fotografia de gastronomia e flat lay?",
    [
      "Porque cameras acima geram imagens de maior qualidade.",
      "Para esconder imperfeicoes dos produtos fotografados.",
      "Porque a visao de cima revela a composicao completa dos elementos, texturas e arranjos de forma organizada.",
      "High Angle em flat lay so funciona com fundos brancos.",
    ],
    2,
    "No flat lay, ver tudo de cima ajuda a organizar pratos, objetos e espacamentos com clareza visual.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Bird's Eye View",
    "Complete o prompt da vista de passaro.",
    "/imagine ___, bird's eye view, estilo ___, iluminacao ___, cores ___, simetria perfeita, ___",
    [
      "um cruzamento movimentado com carros coloridos e pedestres",
      "fotografia aerea",
      "natural de meio-dia",
      "vivas e saturadas",
      "--ar 1:1",
    ],
    [
      "um cruzamento movimentado com carros coloridos e pedestres",
      "fotografia aerea",
      "natural de meio-dia",
      "vivas e saturadas",
      "--ar 1:1",
    ],
    "Bird's Eye entrega leitura de padrao, escala e relacao espacial entre elementos que nenhum outro angulo mostra do mesmo jeito.",
  ),
  quizStep(
    "O que Bird's Eye revela",
    "O que o Bird's Eye View revela que nenhum outro angulo consegue mostrar?",
    [
      "A expressao facial e a emocao dos sujeitos na cena.",
      "A profundidade e a textura dos elementos em primeiro plano.",
      "Padroes geometricos, escala real dos elementos e a relacao espacial entre tudo na cena.",
      "Bird's Eye so funciona para paisagens naturais.",
    ],
    2,
    "Bird's Eye transforma ambientes comuns em composicoes fascinantes porque revela padrao, ordem e escala ao mesmo tempo.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Worm's Eye View",
    "Monte o prompt com camera quase no chao olhando para cima.",
    "/imagine ___, worm's eye view, estilo ___, ceu ___, perspectiva ___, iluminacao ___, ___",
    [
      "arvores gigantes em uma floresta enevoada",
      "fotografia de natureza",
      "dramatico e nublado",
      "extrema para cima",
      "volumetrica dourada",
      "--ar 9:16",
    ],
    [
      "arvores gigantes em uma floresta enevoada",
      "fotografia de natureza",
      "dramatico e nublado",
      "extrema para cima",
      "volumetrica dourada",
      "--ar 9:16",
    ],
    "Worm's Eye exagera a perspectiva ao maximo e cria uma sensacao de escala esmagadora, quase monumental.",
  ),
  quizStep(
    "Por que Worm's Eye impressiona mais",
    "Por que o Worm's Eye View cria uma sensacao de grandiosidade mais intensa que o Low Angle convencional?",
    [
      "Porque captura mais elementos em um unico frame.",
      "Para criar distorcoes que tornam a imagem apenas mais interessante.",
      "Porque o angulo extremamente baixo exagera a perspectiva e faz estruturas e personagens parecerem monumentais.",
      "Worm's Eye e Low Angle geram o mesmo resultado visual.",
    ],
    2,
    "Quanto mais extremo o angulo, mais a perspectiva alonga e monumentaliza o que esta no quadro.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Over the Shoulder",
    "Complete o prompt do enquadramento por cima do ombro.",
    "/imagine ___, over the shoulder shot, estilo ___, iluminacao ___, fundo ___ em foco, clima ___, ___",
    [
      "uma pessoa olhando para uma aurora boreal sobre um lago congelado",
      "fotografia cinematografica",
      "lua azul fria",
      "nitido e detalhado",
      "misterioso e imersivo",
      "--ar 16:9",
    ],
    [
      "uma pessoa olhando para uma aurora boreal sobre um lago congelado",
      "fotografia cinematografica",
      "lua azul fria",
      "nitido e detalhado",
      "misterioso e imersivo",
      "--ar 16:9",
    ],
    "Over the Shoulder convida o espectador a ocupar a posicao do personagem e viver a cena de dentro para fora.",
  ),
  quizStep(
    "Por que Over the Shoulder gera imersao",
    "Por que o Over the Shoulder e tao eficaz para criar imersao narrativa?",
    [
      "Porque mostra o rosto do personagem com mais clareza.",
      "Para economizar elementos descritivos no prompt.",
      "Porque coloca o espectador literalmente na perspectiva do personagem, transformando observacao em participacao.",
      "Over the Shoulder so funciona quando ha dois personagens.",
    ],
    2,
    "Esse enquadramento aproxima o observador da experiencia do personagem e cria narrativa vivida, nao apenas observada.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Close Up",
    "Monte o prompt de plano fechado.",
    "/imagine ___, extreme close up, estilo ___, iluminacao ___, profundidade de campo ___, detalhe ___, ___",
    [
      "um par de maos marcadas pelo tempo segurando uma pequena flor silvestre",
      "fotografia documental",
      "natural suave",
      "rasa",
      "ultra alto",
      "--ar 4:5",
    ],
    [
      "um par de maos marcadas pelo tempo segurando uma pequena flor silvestre",
      "fotografia documental",
      "natural suave",
      "rasa",
      "ultra alto",
      "--ar 4:5",
    ],
    "Close Up aproxima o espectador do detalhe e da emocao que seriam invisiveis em planos mais abertos.",
  ),
  quizStep(
    "O que Close Up entrega",
    "Qual informacao emocional um Close Up entrega que um plano aberto nao consegue transmitir?",
    [
      "O contexto e o ambiente onde a cena acontece.",
      "A relacao espacial entre os elementos da cena.",
      "A textura, a expressao e os microdetalhes que carregam a emocao real da cena.",
      "Close Up so e eficaz para objetos inanimados.",
    ],
    2,
    "Close Up mostra rugas, suor, lagrimas, textura e imperfeicao. E nisso que mora a carga humana mais forte da imagem.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Wide Shot",
    "Complete o prompt de plano aberto.",
    "/imagine ___, wide establishing shot, estilo ___, iluminacao ___, atmosfera ___, escala ___, ___",
    [
      "um explorador solitario na borda do Grand Canyon ao por do sol",
      "fotografia de paisagem",
      "golden hour",
      "epica e vasta",
      "figura humana pequena diante de uma paisagem massiva",
      "--ar 16:9",
    ],
    [
      "um explorador solitario na borda do Grand Canyon ao por do sol",
      "fotografia de paisagem",
      "golden hour",
      "epica e vasta",
      "figura humana pequena diante de uma paisagem massiva",
      "--ar 16:9",
    ],
    "Wide Shot estabelece contexto, escala e atmosfera antes de qualquer detalhe mais especifico da cena.",
  ),
  quizStep(
    "Figura pequena em Wide Shot",
    "Por que colocar uma figura humana pequena em um Wide Shot e uma tecnica narrativa poderosa?",
    [
      "Para mostrar que o personagem nao e o elemento principal da cena.",
      "Porque figuras pequenas sao mais faceis de gerar pelo MidJourney.",
      "Porque o contraste entre a escala humana e a grandiosidade do ambiente comunica solidao, coragem e imensidao de forma imediata.",
      "Figuras pequenas sempre diminuem o impacto visual da paisagem.",
    ],
    2,
    "A comparacao de escala e o que faz o espectador sentir o tamanho real do ambiente e a tensao emocional da cena.",
  ),
  fillStep(
    "Preencha a lacuna - Crie com Dutch Angle",
    "Monte o prompt com camera inclinada e clima de desequilibrio.",
    "/imagine ___, dutch angle, estilo ___, iluminacao ___, atmosfera ___, clima ___, ___",
    [
      "um detetive entrando em um predio abandonado escuro",
      "fotografia noir cinematografica",
      "dramatic chiaroscuro",
      "tensa e inquietante",
      "thriller psicologico",
      "--ar 16:9",
    ],
    [
      "um detetive entrando em um predio abandonado escuro",
      "fotografia noir cinematografica",
      "dramatic chiaroscuro",
      "tensa e inquietante",
      "thriller psicologico",
      "--ar 16:9",
    ],
    "Dutch Angle quebra equilibrio e estabilidade. Ele e excelente quando a imagem precisa insinuar que algo esta errado.",
  ),
  quizStep(
    "Quando Dutch Angle e mais eficaz",
    "Em qual projeto criativo o Dutch Angle seria mais eficaz?",
    [
      "Uma campanha de produto para uma marca infantil.",
      "Fotografia de casamento com atmosfera romantica e serena.",
      "Poster de suspense, thriller ou terror, capas de misterio e projetos com tensao psicologica intencional.",
      "Dutch Angle so funciona em preto e branco.",
    ],
    2,
    "Dutch Angle serve quando o desequilibrio emocional faz parte da mensagem visual do projeto.",
  ),
  fillStep(
    "Preencha a lacuna - Combine angulo e luz",
    "Complete o prompt combinando ponto de vista e iluminacao.",
    "/imagine ___, enquadramento ___, iluminacao ___, estilo ___, clima ___, ___",
    [
      "uma rainha guerreira em uma muralha durante uma tempestade",
      "low angle",
      "dramatic rim",
      "arte conceitual de fantasia sombria",
      "poderoso e desafiador",
      "--ar 9:16",
    ],
    [
      "uma rainha guerreira em uma muralha durante uma tempestade",
      "low angle",
      "dramatic rim",
      "arte conceitual de fantasia sombria",
      "poderoso e desafiador",
      "--ar 9:16",
    ],
    "Quando ponto de vista e luz reforcam a mesma ideia, o impacto visual deixa de ser apenas bonito e passa a ser narrativo.",
  ),
  quizStep(
    "Low Angle + Rim Lighting",
    "Por que combinar Low Angle com Rim Lighting cria um resultado especialmente impactante?",
    [
      "Porque as duas tecnicas sao opostas e se equilibram.",
      "Para deixar o prompt apenas mais longo e detalhado.",
      "Porque o Low Angle cria grandiosidade e o Rim Lighting destaca o personagem com presenca cinematografica, multiplicando o impacto.",
      "Low Angle e Rim Lighting geram conflito visual quando usados juntos.",
    ],
    2,
    "O angulo amplia poder e a luz de contorno reforca destaque. Juntos, os dois levam a cena para um nivel muito mais heroico.",
  ),
  fillStep(
    "Preencha a lacuna - Escolha o angulo certo",
    "Complete o guia rapido de pontos de vista por objetivo.",
    "Para transmitir ___ e heroismo use Low Angle. Para ___ e conexao humana use Eye Level. Para ___ e flat lay use High Angle ou Bird's Eye. Para ___ e emocao use Close Up. Para ___ e escala epica use Wide Shot. Para ___ narrativa use Over the Shoulder. Para ___ e suspense use Dutch Angle.",
    [
      "poder",
      "igualdade",
      "composicao",
      "intimidade",
      "contexto",
      "imersao",
      "tensao",
    ],
    [
      "poder",
      "igualdade",
      "composicao",
      "intimidade",
      "contexto",
      "imersao",
      "tensao",
    ],
    "Escolher o angulo certo e decidir qual relacao emocional o espectador vai ter com a cena antes mesmo de olhar para o resto.",
  ),
  quizStep(
    "Erro mais comum ao escolher angulo",
    "Qual e o erro mais comum ao escolher ponto de vista no MidJourney?",
    [
      "Usar Low Angle para personagens poderosos.",
      "Combinar ponto de vista com iluminacao no mesmo prompt.",
      "Nao especificar nenhum ponto de vista e deixar o MidJourney escolher, perdendo controle narrativo.",
      "Usar o mesmo ponto de vista em imagens do mesmo projeto.",
    ],
    2,
    "Quando voce nao especifica o angulo, aceita uma composicao generica e abre mao do potencial narrativo da imagem.",
  ),
  textStep(
    "Conclusao",
    "O ponto de vista e a decisao mais narrativa que voce toma ao criar uma imagem no MidJourney. Eye Level para conexao humana, Low Angle para poder, High Angle para contexto, Bird's Eye para padroes e escala, Worm's Eye para grandiosidade extrema, Over the Shoulder para imersao, Close Up para emocao, Wide Shot para atmosfera e Dutch Angle para tensao.\n\nDominar o ponto de vista e dominar a narrativa. E quem controla a narrativa visual controla a emocao de quem ve.",
  ),
] as const;

export const MIDJOURNEY_MODULE_4_STEPS_EN = [
  textStep(
    "Point of view in MidJourney - The angle that changes everything",
    "Welcome back! In this lesson, you will learn how point of view, the camera angle used in the prompt, completely transforms the narrative, emotion, and impact of any image created in MidJourney. The same scene seen from different angles tells completely different stories.\n\nPhotographers and film directors know that camera angle is not only a technical choice. It is a narrative decision. It defines the power relationship between viewer and subject, creates specific emotions, and directs the eye exactly where you want it to go.",
  ),
  quizStep(
    "Why point of view matters",
    "Why does point of view influence the narrative of an image?",
    [
      "Because the camera angle defines the emotional relationship between viewer and subject, creating feelings such as power, vulnerability, intimacy, or grandeur.",
      "Because different angles generate different resolutions.",
      "Because point of view only matters in photographs of people and characters.",
      "Because all angles transmit the same emotion with different subjects.",
    ],
    0,
    "Angle changes the viewer's emotional position in relation to the scene. That is why it strongly affects power, closeness, scale, and tension.",
  ),
  fillStep(
    "Fill in the blanks - Use Eye Level",
    "Complete the prompt with the correct eye-level elements.",
    "/imagine ___, eye level shot, ___ style, ___ lighting, ___ background, ___ expression, ___",
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    "Eye Level creates equality and realism by placing the viewer at the same height as the subject.",
  ),
  quizStep(
    "Emotion of Eye Level",
    "What emotional feeling does Eye Level create in a portrait?",
    ["Superiority and power over the viewer.","Vulnerability and fragility.","Equality, closeness, and human connection.","Eye Level only works for group photography."],
    2,
    "Eye Level makes the viewer relate to the subject as an equal, which increases empathy and identification.",
  ),
  fillStep(
    "Fill in the blanks - Create with Low Angle",
    "Build the prompt with a low camera looking upward.",
    "/imagine ___, low angle shot looking up, ___ style, ___ lighting, ___ sky background, ___ mood, ___",
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    "Low Angle enlarges the subject and makes it feel dominant, heroic, and monumental.",
  ),
  quizStep(
    "When to use Low Angle",
    "In which marketing situation would Low Angle be most strategic?",
    ["To show a small product like a watch or jewelry.","To create appetizing food imagery.","To communicate power, leadership, and authority for brands or products such as cars, sports gear, or premium positioning.","Low Angle only works for male action characters."],
    2,
    "Low Angle is strong when the brand wants to communicate authority, aspiration, and leadership.",
  ),
  fillStep(
    "Fill in the blanks - Create with High Angle",
    "Complete the prompt with the camera above the subject looking down.",
    "/imagine ___, high angle shot looking down, ___ style, ___ lighting, ___ composition, ___",
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    "High Angle can communicate vulnerability, context, or visual organization depending on the subject and layout.",
  ),
  quizStep(
    "Why High Angle works in flat lay",
    "Why is High Angle so popular in food photography and flat lays?",
    ["Because higher cameras generate better quality images.","To hide imperfections in products.","Because the top view reveals the full composition of plates, ingredients, textures, and spacing.","High Angle flat lays only work on white backgrounds."],
    2,
    "A top view makes all elements visible at once, which is why it works so well for organized product and food compositions.",
  ),
  fillStep(
    "Fill in the blanks - Create with Bird's Eye View",
    "Complete the prompt for a full top-down view.",
    "/imagine ___, bird's eye view, ___ style, ___ lighting, ___ colors, perfect symmetry, ___",
    ["a busy city intersection with colorful cars and pedestrians","aerial photography","midday natural","vivid and saturated","--ar 1:1"],
    ["a busy city intersection with colorful cars and pedestrians","aerial photography","midday natural","vivid and saturated","--ar 1:1"],
    "Bird's Eye View reveals pattern, scale, and spatial relationships better than almost any other angle.",
  ),
  quizStep(
    "What Bird's Eye reveals",
    "What does Bird's Eye View reveal that other angles cannot show as clearly?",
    ["Facial expression and emotional nuance.","Foreground depth and surface texture.","Geometric patterns, scale, and the spatial relationship between everything in the scene.","Bird's Eye only works for natural aerial landscapes."],
    2,
    "Bird's Eye transforms ordinary environments into striking visual systems by exposing pattern and structure.",
  ),
  fillStep(
    "Fill in the blanks - Create with Worm's Eye View",
    "Build the prompt with the camera almost on the ground looking upward.",
    "/imagine ___, worm's eye view, ___ style, ___ sky, ___ perspective, ___ lighting, ___",
    ["ancient giant redwood trees in a misty forest","nature photography","dramatic cloudy","extreme upward","volumetric golden","--ar 9:16"],
    ["ancient giant redwood trees in a misty forest","nature photography","dramatic cloudy","extreme upward","volumetric golden","--ar 9:16"],
    "Worm's Eye pushes perspective to the extreme and makes structures feel towering and overwhelming.",
  ),
  quizStep(
    "Why Worm's Eye feels bigger",
    "Why does Worm's Eye View create a stronger sense of grandeur than a regular Low Angle?",
    ["Because it captures more elements in one frame.","To create distortion that is simply more interesting.","Because the extremely low camera exaggerates perspective and makes structures and characters feel massive.","Worm's Eye and Low Angle always create the same effect."],
    2,
    "The lower and more extreme the angle, the more monumental the subject feels inside the frame.",
  ),
  fillStep(
    "Fill in the blanks - Create with Over the Shoulder",
    "Complete the prompt for an over-the-shoulder perspective.",
    "/imagine ___, over the shoulder shot, ___ style, ___ lighting, ___ in focus background, ___ mood, ___",
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    "Over the Shoulder invites the viewer into the character's place and builds immersive narrative perspective.",
  ),
  quizStep(
    "Why Over the Shoulder immerses",
    "Why is Over the Shoulder so effective for narrative immersion?",
    ["Because it shows the face more clearly.","To save descriptive elements in the prompt.","Because it puts the viewer directly into the character's perspective.","Over the Shoulder only works when there are two characters."],
    2,
    "This angle turns observation into participation by letting the viewer experience the scene from inside it.",
  ),
  fillStep(
    "Fill in the blanks - Create with Close Up",
    "Build the close-up prompt.",
    "/imagine ___, extreme close up, ___ style, ___ lighting, ___ depth of field, ___ detail, ___",
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    "Close Up brings the viewer close to emotion, texture, and detail that would disappear in wider framing.",
  ),
  quizStep(
    "What Close Up delivers",
    "What emotional information can a Close Up reveal that a wide shot cannot?",
    ["The surrounding context and environment.","The spatial relationship between scene elements.","Texture, expression, and micro-details that carry the true emotion of the scene.","Close Up only works for objects and products."],
    2,
    "Close Up reveals wrinkles, tears, skin, texture, and imperfection, which is where emotional realism often lives.",
  ),
  fillStep(
    "Fill in the blanks - Create with Wide Shot",
    "Complete the wide establishing prompt.",
    "/imagine ___, wide establishing shot, ___ style, ___ lighting, ___ atmosphere, ___ scale, ___",
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    "Wide Shot establishes context, scale, and atmosphere before detail.",
  ),
  quizStep(
    "Tiny figure in Wide Shot",
    "Why is placing a tiny human figure inside a Wide Shot such a powerful narrative technique?",
    ["To show that the character is not the main element.","Because small figures are easier for MidJourney to generate.","Because the contrast between human scale and environmental vastness instantly communicates loneliness, courage, adventure, or magnitude.","Small figures always reduce landscape impact."],
    2,
    "Scale contrast is what makes the viewer actually feel the size and emotional force of the environment.",
  ),
  fillStep(
    "Fill in the blanks - Create with Dutch Angle",
    "Build the tilted-camera prompt.",
    "/imagine ___, dutch angle, ___ style, ___ lighting, ___ atmosphere, ___ mood, ___",
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    "Dutch Angle breaks balance and stability. It works when the scene needs to suggest that something is wrong.",
  ),
  quizStep(
    "When Dutch Angle is strongest",
    "In which kind of creative project is Dutch Angle most effective?",
    ["A product campaign for a children's brand.","Wedding photography with a serene romantic mood.","Thriller, suspense, or horror posters and mystery book covers where psychological imbalance is intentional.","Dutch Angle only works in black and white."],
    2,
    "Dutch Angle is strongest when emotional imbalance is part of the message itself.",
  ),
  fillStep(
    "Fill in the blanks - Combine angle and light",
    "Complete the prompt by combining point of view and lighting.",
    "/imagine ___, ___ shot, ___ lighting, ___ style, ___ mood, ___",
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    "When point of view and lighting reinforce the same idea, the image stops being merely pretty and becomes fully narrative.",
  ),
  quizStep(
    "Low Angle + Rim Lighting",
    "Why does combining Low Angle with Rim Lighting create such an especially powerful result?",
    ["Because the two techniques are opposite and balance each other.","To make the prompt longer and more detailed.","Because Low Angle creates grandeur while Rim Lighting adds cinematic separation and presence, multiplying the impact.","Low Angle and Rim Lighting create visual conflict together."],
    2,
    "The angle enlarges the subject and the rim light isolates it with force. Together they elevate the scene dramatically.",
  ),
  fillStep(
    "Fill in the blanks - Choose the right angle",
    "Complete the quick guide of viewpoints by goal.",
    "To transmit ___ and heroism use Low Angle. For ___ and human connection use Eye Level. For ___ and flat lay use High Angle or Bird's Eye. For ___ and emotion use Close Up. For ___ and epic scale use Wide Shot. For narrative ___ use Over the Shoulder. For ___ and suspense use Dutch Angle.",
    ["power","equality","composition","intimacy","context","immersion","tension"],
    ["power","equality","composition","intimacy","context","immersion","tension"],
    "Choosing the right angle means deciding what emotional relationship the viewer will have with the scene before anything else.",
  ),
  quizStep(
    "Most common angle mistake",
    "What is the most common mistake when choosing point of view in MidJourney?",
    ["Using Low Angle for powerful characters.","Combining point of view with lighting in the same prompt.","Not specifying any viewpoint and letting MidJourney choose, losing narrative control.","Using the same viewpoint within the same project."],
    2,
    "When you do not specify the angle, you accept a generic composition and lose one of the strongest narrative levers in the image.",
  ),
  textStep(
    "Conclusion",
    "Point of view is the most narrative decision you make when creating an image in MidJourney. Eye Level for human connection, Low Angle for power, High Angle for context, Bird's Eye for pattern and scale, Worm's Eye for extreme grandeur, Over the Shoulder for immersion, Close Up for emotion, Wide Shot for atmosphere, and Dutch Angle for tension.\n\nTo master point of view is to master visual storytelling, and whoever controls visual storytelling controls the emotion of the viewer.",
  ),
] as const;

export const MIDJOURNEY_MODULE_4_STEPS_ES = [
  textStep(
    "Punto de vista en MidJourney - El angulo que lo transforma todo",
    "Bienvenido de nuevo. En esta leccion vas a aprender como el punto de vista, el angulo de camara usado en el prompt, transforma por completo la narrativa, la emocion y el impacto de cualquier imagen creada en MidJourney. La misma escena vista desde angulos distintos cuenta historias totalmente diferentes.\n\nFotografos y directores de cine saben que el angulo de camara no es solo una decision tecnica. Es una decision narrativa. Define la relacion de poder entre el espectador y el sujeto, crea emociones especificas y dirige la mirada exactamente hacia donde quieres.",
  ),
  quizStep(
    "Por que importa el punto de vista",
    "Por que el punto de vista influye en la narrativa de una imagen?",
    [
      "Porque el angulo de camara define la relacion emocional entre el espectador y el sujeto, creando sensaciones como poder, vulnerabilidad, intimidad o grandeza.",
      "Porque distintos angulos generan distintas resoluciones.",
      "Porque el punto de vista solo importa en fotos de personas y personajes.",
      "Porque todos los angulos transmiten la misma emocion con sujetos distintos.",
    ],
    0,
    "El angulo cambia la posicion emocional del espectador frente a la escena. Por eso afecta tanto la escala, la cercania, el poder y la tension.",
  ),
  fillStep(
    "Completa los espacios - Usa Eye Level",
    "Completa el prompt con los elementos correctos de eye level.",
    "/imagine ___, eye level shot, estilo ___, iluminacion ___, fondo ___, expresion ___, ___",
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    "Eye Level crea igualdad y realismo al colocar al espectador a la misma altura que el sujeto.",
  ),
  quizStep(
    "Emocion de Eye Level",
    "Que sensacion emocional transmite Eye Level en un retrato?",
    ["Superioridad y poder sobre el espectador.","Vulnerabilidad y fragilidad.","Igualdad, cercania y conexion humana.","Eye Level solo funciona en fotografias grupales."],
    2,
    "Eye Level hace que el espectador se relacione con el sujeto como con un igual, aumentando la empatia y la identificacion.",
  ),
  fillStep(
    "Completa los espacios - Crea con Low Angle",
    "Construye el prompt con una camara baja mirando hacia arriba.",
    "/imagine ___, low angle shot looking up, estilo ___, iluminacion ___, cielo ___, mood ___, ___",
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    "Low Angle agranda al sujeto y lo hace sentir dominante, heroico y monumental.",
  ),
  quizStep(
    "Cuando usar Low Angle",
    "En que situacion de marketing seria mas estrategico usar Low Angle?",
    ["Para mostrar un producto pequeno como un reloj o una joya.","Para crear imagenes de comida que den hambre.","Para comunicar poder, liderazgo y autoridad en marcas o productos como autos, equipamiento deportivo o posicionamiento premium.","Low Angle solo funciona con personajes masculinos de accion."],
    2,
    "Low Angle es fuerte cuando la marca quiere transmitir autoridad, aspiracion y liderazgo.",
  ),
  fillStep(
    "Completa los espacios - Crea con High Angle",
    "Completa el prompt con la camara por encima del sujeto mirando hacia abajo.",
    "/imagine ___, high angle shot looking down, estilo ___, iluminacion ___, composicion ___, ___",
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    "High Angle puede comunicar vulnerabilidad, contexto u organizacion visual segun el sujeto y la composicion.",
  ),
  quizStep(
    "Por que High Angle funciona en flat lay",
    "Por que High Angle es tan popular en fotografia gastronomica y flat lay?",
    ["Porque las camaras elevadas generan mejor calidad.","Para esconder imperfecciones en los productos.","Porque la vista superior revela la composicion completa de platos, ingredientes, texturas y espacios.","Los flat lay con High Angle solo funcionan sobre fondos blancos."],
    2,
    "La vista superior permite ver todos los elementos a la vez, por eso funciona tan bien en composiciones organizadas de comida y producto.",
  ),
  fillStep(
    "Completa los espacios - Crea con Bird's Eye View",
    "Completa el prompt para una vista totalmente cenital.",
    "/imagine ___, bird's eye view, estilo ___, iluminacion ___, colores ___, simetria perfecta, ___",
    ["a busy city intersection with colorful cars and pedestrians","aerial photography","midday natural","vivid and saturated","--ar 1:1"],
    ["a busy city intersection with colorful cars and pedestrians","aerial photography","midday natural","vivid and saturated","--ar 1:1"],
    "Bird's Eye View revela patron, escala y relaciones espaciales mejor que casi cualquier otro angulo.",
  ),
  quizStep(
    "Lo que revela Bird's Eye",
    "Que muestra Bird's Eye View que otros angulos no muestran con tanta claridad?",
    ["La expresion facial y el matiz emocional.","La profundidad del primer plano y la textura.","Patrones geometricos, escala y la relacion espacial entre todos los elementos de la escena.","Bird's Eye solo funciona en paisajes aereos naturales."],
    2,
    "Bird's Eye transforma espacios comunes en sistemas visuales potentes al exponer patron y estructura.",
  ),
  fillStep(
    "Completa los espacios - Crea con Worm's Eye View",
    "Construye el prompt con la camara casi a ras del suelo mirando hacia arriba.",
    "/imagine ___, worm's eye view, estilo ___, cielo ___, perspectiva ___, iluminacion ___, ___",
    ["ancient giant redwood trees in a misty forest","nature photography","dramatic cloudy","extreme upward","volumetric golden","--ar 9:16"],
    ["ancient giant redwood trees in a misty forest","nature photography","dramatic cloudy","extreme upward","volumetric golden","--ar 9:16"],
    "Worm's Eye lleva la perspectiva al extremo y hace que las estructuras parezcan inmensas y abrumadoras.",
  ),
  quizStep(
    "Por que Worm's Eye se siente mas grande",
    "Por que Worm's Eye View crea una sensacion de grandeza mas fuerte que un Low Angle convencional?",
    ["Porque capta mas elementos en un mismo encuadre.","Porque crea una distorsion simplemente mas interesante.","Porque la camara extremadamente baja exagera la perspectiva y hace que estructuras y personajes parezcan gigantes.","Worm's Eye y Low Angle generan siempre el mismo efecto."],
    2,
    "Cuanto mas bajo y extremo es el angulo, mas monumental se siente el sujeto dentro del encuadre.",
  ),
  fillStep(
    "Completa los espacios - Crea con Over the Shoulder",
    "Completa el prompt para una perspectiva por encima del hombro.",
    "/imagine ___, over the shoulder shot, estilo ___, iluminacion ___, fondo ___ en foco, mood ___, ___",
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    "Over the Shoulder invita al espectador a ocupar el lugar del personaje y crea una perspectiva narrativa inmersiva.",
  ),
  quizStep(
    "Por que Over the Shoulder sumerge",
    "Por que Over the Shoulder es tan eficaz para crear inmersion narrativa?",
    ["Porque muestra la cara con mas claridad.","Para ahorrar elementos descriptivos en el prompt.","Porque coloca al espectador directamente en la perspectiva del personaje.","Over the Shoulder solo funciona cuando hay dos personajes."],
    2,
    "Este angulo convierte la observacion en participacion al dejar que el espectador experimente la escena desde dentro.",
  ),
  fillStep(
    "Completa los espacios - Crea con Close Up",
    "Construye el prompt en plano cerrado.",
    "/imagine ___, extreme close up, estilo ___, iluminacion ___, profundidad de campo ___, detalle ___, ___",
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    "Close Up acerca al espectador a la emocion, la textura y el detalle que desaparecerian en un encuadre mas abierto.",
  ),
  quizStep(
    "Lo que entrega Close Up",
    "Que informacion emocional puede revelar un Close Up que un plano abierto no puede mostrar?",
    ["El contexto y el entorno completo.","La relacion espacial entre los elementos de la escena.","La textura, la expresion y los microdetalles que cargan la emocion real de la escena.","Close Up solo funciona con objetos y productos."],
    2,
    "Close Up revela arrugas, lagrimas, piel, textura e imperfeccion, y ahi suele vivir el realismo emocional.",
  ),
  fillStep(
    "Completa los espacios - Crea con Wide Shot",
    "Completa el prompt de plano general.",
    "/imagine ___, wide establishing shot, estilo ___, iluminacion ___, atmosfera ___, escala ___, ___",
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    "Wide Shot establece contexto, escala y atmosfera antes de entrar en los detalles.",
  ),
  quizStep(
    "Figura pequena en Wide Shot",
    "Por que colocar una figura humana pequena dentro de un Wide Shot es una tecnica narrativa tan poderosa?",
    ["Para mostrar que el personaje no es el elemento principal.","Porque las figuras pequenas son mas faciles de generar.","Porque el contraste entre la escala humana y la inmensidad del entorno comunica de inmediato soledad, valentia, aventura o magnitud.","Las figuras pequenas siempre reducen el impacto del paisaje."],
    2,
    "El contraste de escala es lo que hace que el espectador sienta de verdad el tamano y la fuerza emocional del entorno.",
  ),
  fillStep(
    "Completa los espacios - Crea con Dutch Angle",
    "Construye el prompt con la camara inclinada.",
    "/imagine ___, dutch angle, estilo ___, iluminacion ___, atmosfera ___, mood ___, ___",
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    "Dutch Angle rompe el equilibrio y la estabilidad. Funciona cuando la escena necesita sugerir que algo esta mal.",
  ),
  quizStep(
    "Cuando Dutch Angle es mas fuerte",
    "En que tipo de proyecto creativo es mas eficaz Dutch Angle?",
    ["En una campana de producto para una marca infantil.","En fotografia de boda con atmosfera romantica y serena.","En posters de thriller, suspenso o terror y portadas de misterio donde el desequilibrio emocional es intencional.","Dutch Angle solo funciona en blanco y negro."],
    2,
    "Dutch Angle funciona mejor cuando el desequilibrio emocional forma parte del mensaje.",
  ),
  fillStep(
    "Completa los espacios - Combina angulo y luz",
    "Completa el prompt combinando punto de vista e iluminacion.",
    "/imagine ___, angulo ___, iluminacion ___, estilo ___, mood ___, ___",
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    "Cuando el punto de vista y la luz refuerzan la misma idea, la imagen deja de ser solo bonita y pasa a ser narrativa.",
  ),
  quizStep(
    "Low Angle + Rim Lighting",
    "Por que combinar Low Angle con Rim Lighting crea un resultado tan impactante?",
    ["Porque las dos tecnicas son opuestas y se equilibran.","Para hacer el prompt mas largo y detallado.","Porque Low Angle crea grandeza y Rim Lighting agrega separacion cinematografica y presencia, multiplicando el impacto.","Low Angle y Rim Lighting generan conflicto visual juntas."],
    2,
    "El angulo agranda al sujeto y la luz de contorno lo separa del fondo con fuerza. Juntas elevan la escena.",
  ),
  fillStep(
    "Completa los espacios - Elige el angulo correcto",
    "Completa la guia rapida de puntos de vista segun el objetivo.",
    "Para transmitir ___ y heroismo usa Low Angle. Para ___ y conexion humana usa Eye Level. Para ___ y flat lay usa High Angle o Bird's Eye. Para ___ y emocion usa Close Up. Para ___ y escala epica usa Wide Shot. Para inmersion narrativa usa Over the Shoulder. Para ___ y suspenso usa Dutch Angle.",
    ["poder","igualdad","composicion","intimidad","contexto","tension"],
    ["poder","igualdad","composicion","intimidad","contexto","tension"],
    "Elegir el angulo correcto es decidir que relacion emocional tendra el espectador con la escena antes de mirar cualquier otra cosa.",
  ),
  quizStep(
    "Error mas comun al elegir angulo",
    "Cual es el error mas comun al elegir punto de vista en MidJourney?",
    ["Usar Low Angle para personajes poderosos.","Combinar punto de vista con iluminacion en el mismo prompt.","No especificar ningun punto de vista y dejar que MidJourney elija, perdiendo control narrativo.","Usar el mismo punto de vista dentro del mismo proyecto."],
    2,
    "Cuando no especificas el angulo, aceptas una composicion generica y pierdes una de las palancas narrativas mas fuertes de la imagen.",
  ),
  textStep(
    "Conclusion",
    "El punto de vista es la decision mas narrativa que tomas al crear una imagen en MidJourney. Eye Level para conexion humana, Low Angle para poder, High Angle para contexto, Bird's Eye para patron y escala, Worm's Eye para grandeza extrema, Over the Shoulder para inmersion, Close Up para emocion, Wide Shot para atmosfera y Dutch Angle para tension.\n\nDominar el punto de vista es dominar la narrativa visual, y quien domina la narrativa visual domina la emocion del espectador.",
  ),
] as const;

export const MIDJOURNEY_MODULE_4_STEPS_FR = [
  textStep(
    "Point de vue dans MidJourney - L'angle qui change tout",
    "Bon retour. Dans cette lecon, tu vas comprendre comment le point de vue, c'est-a-dire l'angle de camera utilise dans le prompt, transforme completement la narration, l'emotion et l'impact de n'importe quelle image creee dans MidJourney. Une meme scene vue depuis des angles differents raconte des histoires completement differentes.\n\nLes photographes et les realisateurs savent que l'angle de camera n'est pas seulement un choix technique. C'est un choix narratif. Il definit la relation de pouvoir entre le spectateur et le sujet, cree des emotions precises et guide le regard exactement ou tu le veux.",
  ),
  quizStep(
    "Pourquoi le point de vue compte",
    "Pourquoi le point de vue influence-t-il la narration d'une image ?",
    [
      "Parce que l'angle de camera definit la relation emotionnelle entre le spectateur et le sujet, en creant des sensations comme la puissance, la vulnerabilite, l'intimite ou la grandeur.",
      "Parce que differents angles produisent des resolutions differentes.",
      "Parce que le point de vue ne compte que dans les photos de personnes et de personnages.",
      "Parce que tous les angles transmettent la meme emotion avec des sujets differents.",
    ],
    0,
    "L'angle change la position emotionnelle du spectateur face a la scene. C'est pour cela qu'il influence autant l'echelle, la proximite, la puissance et la tension.",
  ),
  fillStep(
    "Complete les blancs - Utilise Eye Level",
    "Complete le prompt avec les bons elements d'eye level.",
    "/imagine ___, eye level shot, style ___, eclairage ___, arriere-plan ___, expression ___, ___",
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    ["a young teacher explaining something to students","documentary photography","soft natural","warm classroom","engaged and passionate","--ar 16:9"],
    "Eye Level cree l'egalite et le realisme en placant le spectateur a la meme hauteur que le sujet.",
  ),
  quizStep(
    "Emotion de Eye Level",
    "Quelle sensation emotionnelle Eye Level transmet-il dans un portrait ?",
    ["Superiorite et pouvoir sur le spectateur.","Vulnerabilite et fragilite.","Egalite, proximite et connexion humaine.","Eye Level fonctionne seulement pour les photos de groupe."],
    2,
    "Eye Level pousse le spectateur a se relier au sujet comme a un egal, ce qui augmente l'empathie et l'identification.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Low Angle",
    "Construit le prompt avec une camera basse qui regarde vers le haut.",
    "/imagine ___, low angle shot looking up, style ___, eclairage ___, ciel ___, mood ___, ___",
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    ["a superhero standing on top of a building","cinematic concept art","dramatic rim","stormy dark","powerful and epic","--ar 9:16"],
    "Low Angle agrandit le sujet et lui donne une presence dominante, heroique et monumentale.",
  ),
  quizStep(
    "Quand utiliser Low Angle",
    "Dans quelle situation marketing Low Angle est-il le plus strategique ?",
    ["Pour montrer un petit produit comme une montre ou un bijou.","Pour creer des images culinaires appetissantes.","Pour communiquer puissance, leadership et autorite pour des marques ou produits comme l'automobile, le sport ou le premium.","Low Angle fonctionne seulement avec des personnages masculins d'action."],
    2,
    "Low Angle est tres fort quand la marque veut transmettre autorite, aspiration et leadership.",
  ),
  fillStep(
    "Complete les blancs - Cree avec High Angle",
    "Complete le prompt avec la camera au-dessus du sujet regardant vers le bas.",
    "/imagine ___, high angle shot looking down, style ___, eclairage ___, composition ___, ___",
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    ["a woman sitting alone reading in a park surrounded by autumn leaves","lifestyle photography","warm soft natural","overhead with negative space","--ar 4:5"],
    "High Angle peut communiquer la vulnerabilite, le contexte ou l'organisation visuelle selon le sujet et la composition.",
  ),
  quizStep(
    "Pourquoi High Angle fonctionne en flat lay",
    "Pourquoi High Angle est-il si populaire en photographie culinaire et en flat lay ?",
    ["Parce que les cameras placees plus haut produisent une meilleure qualite.","Pour cacher les imperfections des produits.","Parce que la vue de dessus revele toute la composition des plats, ingredients, textures et espaces.","Les flat lays en High Angle ne fonctionnent que sur fond blanc."],
    2,
    "La vue de dessus permet de voir tous les elements en meme temps, ce qui la rend ideale pour les compositions organisees de produit et de nourriture.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Bird's Eye View",
    "Complete le prompt pour une vue totalement zenithale.",
    "/imagine ___, bird's eye view, style ___, eclairage ___, couleurs ___, symetrie parfaite, ___",
    ["a busy city intersection with colorful cars and pedestrians","aerial photography","midday natural","vivid and saturated","--ar 1:1"],
    ["a busy city intersection with colorful cars and pedestrians","aerial photography","midday natural","vivid and saturated","--ar 1:1"],
    "Bird's Eye View revele les motifs, l'echelle et les relations spatiales mieux que presque tous les autres angles.",
  ),
  quizStep(
    "Ce que revele Bird's Eye",
    "Qu'est-ce que Bird's Eye View montre plus clairement que les autres angles ?",
    ["L'expression faciale et la nuance emotionnelle.","La profondeur du premier plan et la texture de surface.","Les motifs geometriques, l'echelle et la relation spatiale entre tous les elements de la scene.","Bird's Eye ne fonctionne que pour les paysages naturels vus du ciel."],
    2,
    "Bird's Eye transforme des lieux ordinaires en systemes visuels puissants en exposant structure et motif.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Worm's Eye View",
    "Construit le prompt avec la camera presque au sol qui regarde vers le haut.",
    "/imagine ___, worm's eye view, style ___, ciel ___, perspective ___, eclairage ___, ___",
    ["ancient giant redwood trees in a misty forest","nature photography","dramatic cloudy","extreme upward","volumetric golden","--ar 9:16"],
    ["ancient giant redwood trees in a misty forest","nature photography","dramatic cloudy","extreme upward","volumetric golden","--ar 9:16"],
    "Worm's Eye pousse la perspective a l'extreme et fait paraitre les structures immenses et ecrasantes.",
  ),
  quizStep(
    "Pourquoi Worm's Eye semble plus grand",
    "Pourquoi Worm's Eye View cree-t-il une impression de grandeur plus forte qu'un Low Angle classique ?",
    ["Parce qu'il capture plus d'elements dans une seule image.","Pour creer une distortion simplement plus interessante.","Parce que la camera extremement basse exagere la perspective et fait paraitre structures et personnages gigantesques.","Worm's Eye et Low Angle produisent toujours le meme effet."],
    2,
    "Plus l'angle est bas et extreme, plus le sujet parait monumental dans le cadre.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Over the Shoulder",
    "Complete le prompt pour une perspective par-dessus l'epaule.",
    "/imagine ___, over the shoulder shot, style ___, eclairage ___, arriere-plan ___ net, mood ___, ___",
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    ["a person looking at a stunning aurora borealis over a frozen lake","cinematic photography","cold blue moonlight","sharp detailed","mysterious and immersive","--ar 16:9"],
    "Over the Shoulder invite le spectateur a prendre la place du personnage et cree une perspective narrative immersive.",
  ),
  quizStep(
    "Pourquoi Over the Shoulder immerge",
    "Pourquoi Over the Shoulder est-il si efficace pour l'immersion narrative ?",
    ["Parce qu'il montre mieux le visage.","Pour economiser des elements descriptifs dans le prompt.","Parce qu'il place le spectateur directement dans la perspective du personnage.","Over the Shoulder ne fonctionne que lorsqu'il y a deux personnages."],
    2,
    "Cet angle transforme l'observation en participation en laissant le spectateur vivre la scene de l'interieur.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Close Up",
    "Construit le prompt en gros plan.",
    "/imagine ___, extreme close up, style ___, eclairage ___, profondeur de champ ___, detail ___, ___",
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    ["a pair of weathered hands holding a small wildflower","documentary photography","soft natural","shallow","ultra high","--ar 4:5"],
    "Close Up rapproche le spectateur de l'emotion, de la texture et du detail qui disparaitraient dans un cadrage plus large.",
  ),
  quizStep(
    "Ce que Close Up apporte",
    "Quelle information emotionnelle un Close Up peut-il reveler qu'un plan large ne montre pas ?",
    ["Le contexte complet et l'environnement.","La relation spatiale entre les elements de la scene.","La texture, l'expression et les micro-details qui portent l'emotion reelle de la scene.","Close Up ne fonctionne que pour les objets et les produits."],
    2,
    "Close Up revele les rides, les larmes, la peau, la texture et les imperfections, la ou vit souvent le realisme emotionnel.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Wide Shot",
    "Complete le prompt de plan large.",
    "/imagine ___, wide establishing shot, style ___, eclairage ___, atmosphere ___, echelle ___, ___",
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    ["a lone explorer standing at the edge of the Grand Canyon at sunset","landscape photography","golden hour","epic and vast","tiny human figure against massive landscape","--ar 16:9"],
    "Wide Shot installe le contexte, l'echelle et l'atmosphere avant les details.",
  ),
  quizStep(
    "Petite figure dans Wide Shot",
    "Pourquoi placer une petite figure humaine dans un Wide Shot est-il une technique narrative si puissante ?",
    ["Pour montrer que le personnage n'est pas l'element principal.","Parce que les petites figures sont plus faciles a generer.","Parce que le contraste entre l'echelle humaine et l'immensite du decor communique immediatement solitude, courage, aventure ou grandeur.","Les petites figures reduisent toujours l'impact du paysage."],
    2,
    "Le contraste d'echelle est ce qui fait ressentir au spectateur la taille et la force emotionnelle du decor.",
  ),
  fillStep(
    "Complete les blancs - Cree avec Dutch Angle",
    "Construit le prompt avec une camera inclinee.",
    "/imagine ___, dutch angle, style ___, eclairage ___, atmosphere ___, mood ___, ___",
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    ["a detective entering a dark abandoned building","noir cinematic photography","dramatic chiaroscuro","tense and unsettling","psychological thriller","--ar 16:9"],
    "Dutch Angle casse l'equilibre et la stabilite. Il fonctionne quand la scene doit suggerer qu'il y a un probleme.",
  ),
  quizStep(
    "Quand Dutch Angle est le plus fort",
    "Dans quel type de projet creatif Dutch Angle est-il le plus efficace ?",
    ["Dans une campagne produit pour une marque enfantine.","Dans une photo de mariage romantique et sereine.","Dans des affiches de thriller, de suspense ou d'horreur et des couvertures de mystere ou le desequilibre emotionnel est intentionnel.","Dutch Angle ne fonctionne qu'en noir et blanc."],
    2,
    "Dutch Angle fonctionne le mieux lorsque le desequilibre emotionnel fait partie du message.",
  ),
  fillStep(
    "Complete les blancs - Combine angle et lumiere",
    "Complete le prompt en combinant point de vue et eclairage.",
    "/imagine ___, angle ___, eclairage ___, style ___, mood ___, ___",
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    ["a warrior queen standing on a castle wall in a storm","low angle","dramatic rim","dark fantasy concept art","powerful and defiant","--ar 9:16"],
    "Quand le point de vue et la lumiere renforcent la meme idee, l'image cesse d'etre seulement belle et devient vraiment narrative.",
  ),
  quizStep(
    "Low Angle + Rim Lighting",
    "Pourquoi la combinaison de Low Angle et Rim Lighting cree-t-elle un resultat si impactant ?",
    ["Parce que les deux techniques sont opposees et s'equilibrent.","Pour rendre le prompt plus long et plus detaille.","Parce que Low Angle cree la grandeur et Rim Lighting ajoute une separation cinematographique et une forte presence, ce qui multiplie l'impact.","Low Angle et Rim Lighting creent un conflit visuel ensemble."],
    2,
    "L'angle agrandit le sujet et la lumiere de contour le detache du fond avec force. Ensemble, ils elevent la scene.",
  ),
  fillStep(
    "Complete les blancs - Choisis le bon angle",
    "Complete le guide rapide des points de vue selon l'objectif.",
    "Pour transmettre ___ et heroisme, utilise Low Angle. Pour ___ et connexion humaine, utilise Eye Level. Pour ___ et flat lay, utilise High Angle ou Bird's Eye. Pour ___ et emotion, utilise Close Up. Pour ___ et echelle epique, utilise Wide Shot. Pour l'immersion narrative, utilise Over the Shoulder. Pour ___ et suspense, utilise Dutch Angle.",
    ["puissance","egalite","composition","intimite","contexte","tension"],
    ["puissance","egalite","composition","intimite","contexte","tension"],
    "Choisir le bon angle, c'est decider quelle relation emotionnelle le spectateur aura avec la scene avant meme de regarder le reste.",
  ),
  quizStep(
    "Erreur la plus courante sur l'angle",
    "Quelle est l'erreur la plus courante lorsqu'on choisit un point de vue dans MidJourney ?",
    ["Utiliser Low Angle pour des personnages puissants.","Combiner point de vue et eclairage dans le meme prompt.","Ne preciser aucun point de vue et laisser MidJourney choisir, ce qui fait perdre le controle narratif.","Utiliser le meme point de vue dans le meme projet."],
    2,
    "Si tu ne precises pas l'angle, tu acceptes une composition generique et tu perds l'un des leviers narratifs les plus puissants de l'image.",
  ),
  textStep(
    "Conclusion",
    "Le point de vue est la decision la plus narrative que tu prends quand tu crees une image dans MidJourney. Eye Level pour la connexion humaine, Low Angle pour la puissance, High Angle pour le contexte, Bird's Eye pour les motifs et l'echelle, Worm's Eye pour une grandeur extreme, Over the Shoulder pour l'immersion, Close Up pour l'emotion, Wide Shot pour l'atmosphere et Dutch Angle pour la tension.\n\nMaitriser le point de vue, c'est maitriser la narration visuelle, et maitriser la narration visuelle, c'est maitriser l'emotion du spectateur.",
  ),
] as const;
