const textStep = (title: string, content: string, promptBox?: string) => ({
  type: "text" as const,
  title,
  content,
  ...(promptBox ? { promptBox } : {}),
});

const quizStep = (
  title: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
) => ({
  type: "quiz" as const,
  title,
  question,
  options,
  correctIndex,
  explanation,
});

const fillStep = (
  title: string,
  instruction: string,
  sentence: string,
  answers: string[],
  options: string[],
  explanation: string,
) => ({
  type: "fill_blanks" as const,
  title,
  instruction,
  sentence,
  answers,
  options,
  explanation,
});

export const MIDJOURNEY_MODULE_6_STEPS_PT = [
  textStep(
    "Visuais poderosos para marketing com MidJourney",
    "Bem-vindo de volta. Nesta licao, voce vai aprender a criar imagens com impacto profissional para marketing usando MidJourney, desde posts de redes sociais ate campanhas completas. O foco agora nao e apenas fazer uma imagem bonita. E criar visuais que ajudem a posicionar a marca, segurar atencao e aumentar percepcao de valor.\n\nNo marketing digital, a imagem quase sempre fala antes do texto. Antes de ler qualquer headline, o publico ja sentiu se aquela marca parece confiavel, premium, clara ou amadora.",
  ),
  quizStep(
    "Por que visual de qualidade importa",
    "Por que investir em visuais de alta qualidade e estrategico para qualquer marca?",
    [
      "Porque o impacto visual e processado muito mais rapido que o texto, e a primeira impressao decide se o publico continua engajando.",
      "Porque imagens bonitas garantem automaticamente mais vendas.",
      "Porque visual de qualidade so importa para marcas de luxo.",
      "Porque o texto do anuncio sempre importa mais que a imagem.",
    ],
    0,
    "Imagem nao fecha sozinha uma venda, mas decide se a pessoa para para olhar o resto. Essa primeira leitura visual muda todo o jogo.",
  ),
  fillStep(
    "Preencha a lacuna - Crie sua foto de produto",
    "Complete o prompt de fotografia de produto com cara de campanha profissional.",
    "/imagine ___, fundo ___, iluminacao ___, fotografia ___, detalhe ___, sensacao de luxo, ___.",
    [
      "um frasco premium de serum para pele com gotas de agua e elementos botanicos",
      "marmore branco limpo",
      "soft box",
      "comercial de produto",
      "ultra alto 8K",
      "--ar 1:1",
    ],
    [
      "um frasco premium de serum para pele com gotas de agua e elementos botanicos",
      "marmore branco limpo",
      "soft box",
      "comercial de produto",
      "ultra alto 8K",
      "--ar 1:1",
    ],
    "Boa foto de produto vende percepcao antes de vender preco. Luz, textura, fundo e clareza visual fazem esse trabalho juntos.",
  ),
  quizStep(
    "Produto que converte",
    "O que torna uma fotografia de produto eficaz para conversao?",
    [
      "Mostrar o maximo de produtos possivel em uma unica imagem.",
      "Usar fundos muito coloridos para chamar atencao a qualquer custo.",
      "Destaque limpo do produto, luz que valoriza textura e detalhes, e composicao que aumenta percepcao de valor.",
      "Todo produto premium precisa ser fotografado em fundo preto.",
    ],
    2,
    "Imagem de conversao nao confunde. Ela faz o produto parecer desejavel, claro e bem posicionado logo no primeiro olhar.",
  ),
  fillStep(
    "Preencha a lacuna - Crie seu post para feed",
    "Monte um visual pensado para parar o scroll no feed do Instagram.",
    "/imagine ___, estilo ___, cores ___, composicao ___, iluminacao ___, clima ___, ___.",
    [
      "uma empreendedora confiante trabalhando em um cafe moderno com notebook",
      "fotografia lifestyle",
      "quentes e vibrantes",
      "regra dos tercos",
      "golden hour",
      "empoderador e inspirador",
      "--ar 4:5",
    ],
    [
      "uma empreendedora confiante trabalhando em um cafe moderno com notebook",
      "fotografia lifestyle",
      "quentes e vibrantes",
      "regra dos tercos",
      "golden hour",
      "empoderador e inspirador",
      "--ar 4:5",
    ],
    "No feed, presenca visual importa. O 4:5 ajuda a ocupar mais espaco e dar mais tempo de leitura para a imagem.",
  ),
  quizStep(
    "Por que 4:5 no feed",
    "Por que o formato --ar 4:5 e estrategico para posts no feed do Instagram?",
    [
      "Porque e o unico formato aceito pelo algoritmo.",
      "Porque deixa a imagem maior do que qualquer imagem quadrada automaticamente.",
      "Porque ocupa mais espaco vertical no feed e aumenta a presenca visual antes do scroll.",
      "Porque o 4:5 so funciona para fotos de pessoas.",
    ],
    2,
    "Mais espaco vertical significa mais atencao. O visual ganha alguns segundos preciosos antes da pessoa seguir rolando.",
  ),
  fillStep(
    "Preencha a lacuna - Crie um anuncio pago",
    "Complete o prompt de criativo com energia de anuncio e impacto imediato.",
    "/imagine ___, estilo ___, iluminacao ___, ___, alto contraste, cores ___, sensacao ___, ___.",
    [
      "um jovem em forma depois do treino segurando um shake proteico com suor e determinacao",
      "fotografia esportiva dinamica",
      "dramatica",
      "efeito de motion blur no fundo",
      "fortes e energeticas",
      "poderosa e motivadora",
      "--ar 9:16",
    ],
    [
      "um jovem em forma depois do treino segurando um shake proteico com suor e determinacao",
      "fotografia esportiva dinamica",
      "dramatica",
      "efeito de motion blur no fundo",
      "fortes e energeticas",
      "poderosa e motivadora",
      "--ar 9:16",
    ],
    "Anuncio bom precisa parar o scroll em milissegundos. Expressao, contraste e movimento ajudam a fazer isso rapido.",
  ),
  quizStep(
    "O elemento mais importante no anuncio",
    "Qual elemento visual e mais importante em um criativo para anuncio pago?",
    [
      "O maior numero de informacoes possivel na imagem.",
      "O logo da marca em destaque centralizado.",
      "Um elemento de impacto imediato, como expressao forte, movimento ou contraste alto, que para o scroll rapidamente.",
      "Anuncios pagos sempre funcionam melhor quando sao minimalistas.",
    ],
    2,
    "Antes da proposta de valor, vem a interrupcao da atencao. Se a imagem nao segura o olhar, o resto nem entra na jogada.",
  ),
  fillStep(
    "Preencha a lacuna - Crie para Stories e Reels",
    "Monte um visual vertical que deixe espaco para texto e CTA.",
    "/imagine ___, estilo ___, iluminacao ___, fundo ___, composicao vertical ___ deixando ___ no topo e na base para sobreposicao de texto, ___.",
    [
      "uma jovem experimentando oculos em uma boutique e sorrindo de forma natural",
      "fotografia lifestyle espontanea",
      "natural suave",
      "interior desfocado com efeito bokeh",
      "bem distribuida",
      "espaco vazio",
      "--ar 9:16",
    ],
    [
      "uma jovem experimentando oculos em uma boutique e sorrindo de forma natural",
      "fotografia lifestyle espontanea",
      "natural suave",
      "interior desfocado com efeito bokeh",
      "bem distribuida",
      "espaco vazio",
      "--ar 9:16",
    ],
    "Visual vertical forte nao e so tela cheia. E tela cheia com espaco funcional para CTA, titulo e overlay.",
  ),
  quizStep(
    "Espaco vazio em Stories",
    "Por que deixar espaco vazio no topo e na base de um visual para Stories e importante?",
    [
      "Para o MidJourney gerar mais rapido.",
      "Porque o Instagram corta automaticamente as bordas dos Stories.",
      "Porque esse espaco recebe texto, link, CTA e elementos graficos sem cobrir o foco principal da imagem.",
      "Porque espaco vazio reduz o impacto visual do conteudo.",
    ],
    2,
    "Quando a imagem ja nasce pensando no layout, o resultado parece profissional e nao remendado depois.",
  ),
  fillStep(
    "Preencha a lacuna - Crie identidade visual",
    "Complete o prompt para gerar um visual consistente com identidade de marca.",
    "/imagine ___, estetica ___, paleta ___, estilo ___, iluminacao ___, sensacao ___, identidade visual consistente, ___.",
    [
      "flat lay de produtos naturais de skincare com elementos botanicos e texturas de linho",
      "organica e minimalista",
      "tons terrosos suaves com verde sálvia e creme quente",
      "fotografia editorial de produto",
      "natural difusa e suave",
      "limpa, premium e confiavel",
      "--ar 1:1",
    ],
    [
      "flat lay de produtos naturais de skincare com elementos botanicos e texturas de linho",
      "organica e minimalista",
      "tons terrosos suaves com verde sálvia e creme quente",
      "fotografia editorial de produto",
      "natural difusa e suave",
      "limpa, premium e confiavel",
      "--ar 1:1",
    ],
    "Marca forte nao depende de uma imagem isolada. Depende de repeticao coerente de atmosfera, cor, textura e posicionamento.",
  ),
  quizStep(
    "Consistencia de marca",
    "Por que manter consistencia visual entre os posts de uma marca e estrategico?",
    [
      "Para agradar o algoritmo.",
      "Porque posts iguais sao mais faceis de produzir.",
      "Porque a consistencia visual cria reconhecimento instantaneo e constrói familiaridade ao longo do tempo.",
      "Porque so marcas grandes precisam pensar nisso.",
    ],
    2,
    "Quando o publico reconhece a marca antes de ler o nome, a comunicacao ficou forte de verdade.",
  ),
  fillStep(
    "Preencha a lacuna - Crie seu visual sazonal",
    "Complete o prompt de campanha sazonal com atmosfera emocional e cara de marca.",
    "/imagine ___, atmosfera ___, iluminacao ___, cores ___, estilo ___, clima ___, ___.",
    [
      "uma caixa de presente elegante cercada por galhos de pinheiro e luzes douradas sobre uma mesa rustica",
      "natal aconchegante",
      "bokeh dourado e quente",
      "vermelho profundo e dourado",
      "fotografia lifestyle de luxo",
      "magico e celebratorio",
      "--ar 4:5",
    ],
    [
      "uma caixa de presente elegante cercada por galhos de pinheiro e luzes douradas sobre uma mesa rustica",
      "natal aconchegante",
      "bokeh dourado e quente",
      "vermelho profundo e dourado",
      "fotografia lifestyle de luxo",
      "magico e celebratorio",
      "--ar 4:5",
    ],
    "Campanha sazonal forte nao abandona a marca. Ela mistura a emocao da data com a identidade visual do negocio.",
  ),
  quizStep(
    "Visual sazonal eficaz",
    "O que torna um visual sazonal eficaz para campanhas de marketing?",
    [
      "Mostrar o produto em promocao com o preco em destaque.",
      "Usar as cores tradicionais da data sem nenhuma personalizacao.",
      "Combinar os elementos emocionais da data com a estetica da marca, para parecer da epoca e da marca ao mesmo tempo.",
      "Visuais sazonais precisam ser totalmente diferentes da identidade normal da marca.",
    ],
    2,
    "Sazonal bom conecta contexto e identidade. Se parecer so enfeite de data, perde forca de marca.",
  ),
  fillStep(
    "Preencha a lacuna - Crie sua thumbnail",
    "Monte um prompt de thumbnail com impacto, curiosidade e espaco para texto.",
    "/imagine ___, expressao ___, fundo ___, iluminacao ___, estilo ___, composicao ___ deixando ___ para o titulo, ___.",
    [
      "um homem apontando para a camera com expressao chocada e empolgada",
      "vibrante e exagerada",
      "gradiente amarelo e laranja forte",
      "estudio dramatico",
      "editorial de alto contraste",
      "horizontal",
      "espaco vazio no lado direito",
      "--ar 16:9",
    ],
    [
      "um homem apontando para a camera com expressao chocada e empolgada",
      "vibrante e exagerada",
      "gradiente amarelo e laranja forte",
      "estudio dramatico",
      "editorial de alto contraste",
      "horizontal",
      "espaco vazio no lado direito",
      "--ar 16:9",
    ],
    "Thumbnail boa nao explica tudo. Ela acende curiosidade em menos de um segundo e ainda deixa espaco para o titulo trabalhar junto.",
  ),
  quizStep(
    "Thumbnail que aumenta CTR",
    "O que torna uma thumbnail do YouTube eficaz para aumentar o CTR?",
    [
      "O logo do canal centralizado e bem grande.",
      "Mostrar o conteudo inteiro do video dentro da imagem.",
      "Expressao exagerada ou surpresa visual combinada com espaco estrategico para texto.",
      "Thumbnails com menos elementos sempre performam melhor.",
    ],
    2,
    "CTR sobe quando a thumbnail comunica promessa, tensao e curiosidade sem sobrecarregar a leitura.",
  ),
  fillStep(
    "Preencha a lacuna - Crie visual de depoimento",
    "Complete o prompt para um visual autentico de prova social.",
    "/imagine ___, estilo ___, iluminacao ___, fundo ___, expressao ___, sensacao ___, ___.",
    [
      "uma mulher de meia-idade sorrindo de forma genuina para a camera com postura relaxada",
      "retrato lifestyle espontaneo",
      "luz natural de janela",
      "ambiente de casa desfocado e acolhedor",
      "autentica e alegre",
      "real, confiavel e profundamente identificavel",
      "--ar 4:5",
    ],
    [
      "uma mulher de meia-idade sorrindo de forma genuina para a camera com postura relaxada",
      "retrato lifestyle espontaneo",
      "luz natural de janela",
      "ambiente de casa desfocado e acolhedor",
      "autentica e alegre",
      "real, confiavel e profundamente identificavel",
      "--ar 4:5",
    ],
    "Prova social convence mais quando parece humana de verdade. O publico percebe muito rapido quando a cena esta encenada demais.",
  ),
  quizStep(
    "Autenticidade em depoimentos",
    "Por que a autenticidade visual e mais importante do que a perfeicao estetica em imagens de depoimentos?",
    [
      "Porque imagens imperfeitas custam menos para produzir.",
      "Para parecer que o depoimento nao foi patrocinado.",
      "Porque o cerebro detecta rapidamente quando a imagem parece encenada, e visuais autenticos geram mais confianca.",
      "Autenticidade so importa para marcas pessoais.",
    ],
    2,
    "Depoimento sem autenticidade parece banco de imagem. E banco de imagem dificilmente cria confianca real.",
  ),
  fillStep(
    "Preencha a lacuna - Crie visual educativo",
    "Monte um prompt para artigo, newsletter ou blog com espaco para titulo.",
    "/imagine ___, estilo ___, iluminacao ___, tons ___, composicao ___ com ___ para titulo, ___, ___.",
    [
      "uma profissional apresentando dados em uma grande tela em uma sala de reunioes moderna",
      "fotografia editorial corporativa",
      "suave e limpa",
      "azul frio e branco",
      "horizontal",
      "uma area mais escura vazia no lado esquerdo",
      "credibilidade profissional",
      "--ar 16:9",
    ],
    [
      "uma profissional apresentando dados em uma grande tela em uma sala de reunioes moderna",
      "fotografia editorial corporativa",
      "suave e limpa",
      "azul frio e branco",
      "horizontal",
      "uma area mais escura vazia no lado esquerdo",
      "credibilidade profissional",
      "--ar 16:9",
    ],
    "Visual educativo profissional ja nasce pensando no texto. Nao e so uma imagem bonita com um titulo jogado em cima depois.",
  ),
  quizStep(
    "Espaco para texto no educativo",
    "Por que criar um espaco especifico para texto no visual educativo e uma pratica profissional?",
    [
      "Para economizar tempo e nao precisar montar layout.",
      "Porque MidJourney nao consegue gerar imagens sem espacos vazios.",
      "Porque a imagem ja nasce pronta para dialogar com titulo e mensagem, criando um layout coeso.",
      "Espaco para texto so e necessario em banners de propaganda.",
    ],
    2,
    "Quando visual e texto sao pensados juntos, a comunicacao parece intencional e muito mais refinada.",
  ),
  fillStep(
    "Preencha a lacuna - Monte sua serie visual",
    "Complete a frase com a logica certa para criar uma campanha coerente em varias pecas.",
    "Para criar uma serie coesa, mantenha ___ estes elementos em todos os prompts: ___ de cores, ___ de iluminacao, ___ fotografico e ___ de composicao. Varie apenas o ___ principal para contar uma historia visual ___ ao longo da campanha.",
    [
      "fixos",
      "paleta",
      "tipo",
      "estilo",
      "regra",
      "sujeito e acao",
      "progressiva",
    ],
    [
      "fixos",
      "paleta",
      "tipo",
      "estilo",
      "regra",
      "sujeito e acao",
      "progressiva",
    ],
    "Serie forte nao nasce de sorte. Nasce de uma base visual fixa com variacoes controladas em torno dela.",
  ),
  quizStep(
    "Estrategia de campanha visual coesa",
    "Qual e a estrategia mais eficaz para criar uma campanha visual coesa no MidJourney?",
    [
      "Gerar imagens aleatorias e depois escolher as parecidas.",
      "Usar exatamente o mesmo prompt em todas as pecas.",
      "Criar um prompt base com elementos fixos da identidade visual e variar so o que muda entre os posts.",
      "So e possivel manter coesao visual com edicao externa.",
    ],
    2,
    "Coesao boa nao mata variedade. Ela cria uma espinha dorsal visual para que cada peca pareca nova, mas ainda pertenca a mesma marca.",
  ),
  fillStep(
    "Preencha a lacuna - Evite os erros",
    "Complete a frase com os erros visuais que mais destroem campanhas de marketing.",
    "Os principais erros visuais em marketing com MidJourney sao: usar prompts ___ sem personalizacao, misturar ___ incompativeis entre os posts, gerar imagens com ___ errada para o canal, ignorar o ___ emocional da iluminacao e criar visuais que ___ com o posicionamento da marca.",
    [
      "genericos",
      "estilos e paletas",
      "proporcao",
      "impacto",
      "contradizem",
    ],
    [
      "genericos",
      "estilos e paletas",
      "proporcao",
      "impacto",
      "contradizem",
    ],
    "Campanha fraca geralmente nao falha por falta de beleza. Falha por falta de coerencia estrategica.",
  ),
  quizStep(
    "Erro mais comum em marketing com IA",
    "Qual e o erro visual mais comum em campanhas de marketing de pequenas empresas no MidJourney?",
    [
      "Usar prompts longos demais com muitos elementos.",
      "Criar imagens com qualidade acima do necessario.",
      "Falta de consistencia visual entre os posts, fazendo cada peca parecer de uma marca diferente.",
      "Usar o mesmo estilo em todas as imagens da marca.",
    ],
    2,
    "Quando a marca nao parece a mesma de um post para o outro, o publico nao acumula reconhecimento, memoria nem confianca.",
  ),
  textStep(
    "Conclusao",
    "Com MidJourney, qualquer marca pode produzir visuais com nivel de agencia sem depender de equipe grande, estudio ou orcamento elevado. Fotos de produto, posts de feed, criativos para anuncio, thumbnails, conteudo educativo, prova social e campanhas inteiras podem nascer de prompts bem construidos e de uma estrategia visual clara.\n\nA diferenca entre uma marca que cresce e uma que estagna nao esta so no produto. Esta tambem em como ela se apresenta visualmente antes de dizer qualquer palavra.",
  ),
] as const;

export const MIDJOURNEY_MODULE_6_STEPS_EN = [
  textStep(
    "Powerful marketing visuals with MidJourney",
    "Welcome back. In this lesson, you will learn how to create professional-impact marketing visuals with MidJourney, from social posts to full campaigns. The goal is no longer just to create beautiful images. The goal is to create visuals that strengthen positioning, hold attention, and increase perceived value.\n\nIn digital marketing, the image usually speaks before the copy. Before reading a single headline, the audience has already felt whether the brand looks trustworthy, premium, clear, or amateur.",
  ),
  quizStep(
    "Why high-quality visuals matter",
    "Why is investing in high-quality visuals strategic for any brand?",
    [
      "Because visual impact is processed much faster than text, and the first impression often decides whether people keep engaging.",
      "Because beautiful images automatically guarantee more sales.",
      "Because quality visuals only matter for luxury brands.",
      "Because ad copy is always more important than the image.",
    ],
    0,
    "An image does not close the sale alone, but it often decides whether the audience pauses long enough to consider the rest.",
  ),
  fillStep(
    "Fill in the blanks - Create your product photo",
    "Complete the product photography prompt with campaign-level polish.",
    "/imagine ___, ___ background, ___ lighting, ___ photography, ___ detail, luxury feel, ___.",
    [
      "a premium skincare serum bottle with water droplets and botanical elements",
      "clean white marble surface",
      "soft box",
      "commercial product",
      "ultra high 8K",
      "--ar 1:1",
    ],
    [
      "a premium skincare serum bottle with water droplets and botanical elements",
      "clean white marble surface",
      "soft box",
      "commercial product",
      "ultra high 8K",
      "--ar 1:1",
    ],
    "Strong product imagery sells perception before it sells price. Light, texture, background, and clarity all contribute to that effect.",
  ),
  quizStep(
    "Product imagery that converts",
    "What makes product photography effective for conversion?",
    [
      "Showing as many products as possible in one image.",
      "Using very colorful backgrounds to force attention.",
      "Clean product focus, lighting that highlights texture and detail, and composition that increases perceived value.",
      "Premium products should always be photographed on black backgrounds.",
    ],
    2,
    "Conversion imagery should not confuse. It should make the product feel desirable, clear, and well-positioned at first glance.",
  ),
  fillStep(
    "Fill in the blanks - Create your feed post",
    "Build a visual designed to stop the scroll in the Instagram feed.",
    "/imagine ___, ___ style, ___ colors, ___ composition, ___ lighting, ___ mood, ___.",
    [
      "a confident woman entrepreneur working in a modern cafe with a laptop",
      "lifestyle photography",
      "warm and vibrant",
      "rule of thirds",
      "golden hour",
      "empowering and inspiring",
      "--ar 4:5",
    ],
    [
      "a confident woman entrepreneur working in a modern cafe with a laptop",
      "lifestyle photography",
      "warm and vibrant",
      "rule of thirds",
      "golden hour",
      "empowering and inspiring",
      "--ar 4:5",
    ],
    "In the feed, visual presence matters. A 4:5 frame occupies more space and buys a little more time for attention.",
  ),
  quizStep(
    "Why 4:5 works in feed",
    "Why is --ar 4:5 strategic for Instagram feed posts?",
    [
      "Because it is the only format accepted by the algorithm.",
      "Because it automatically makes the image larger than any square post.",
      "Because it takes more vertical space in the feed and increases visual presence before the user scrolls.",
      "Because 4:5 only works for photos of people.",
    ],
    2,
    "More vertical space means more attention. The visual gains a few extra moments before the viewer keeps scrolling.",
  ),
  fillStep(
    "Fill in the blanks - Create a paid ad",
    "Complete the prompt for an ad creative with instant impact.",
    "/imagine ___, ___ style, ___ lighting, ___, high contrast, ___ colors, ___ feel, ___.",
    [
      "a fit young man after a workout holding a protein shake with sweat and determination",
      "dynamic sports photography",
      "dramatic",
      "motion blur effect in background",
      "bold and energetic",
      "powerful and motivating",
      "--ar 9:16",
    ],
    [
      "a fit young man after a workout holding a protein shake with sweat and determination",
      "dynamic sports photography",
      "dramatic",
      "motion blur effect in background",
      "bold and energetic",
      "powerful and motivating",
      "--ar 9:16",
    ],
    "Great ads stop the scroll in milliseconds. Expression, contrast, and motion cues help them do exactly that.",
  ),
  quizStep(
    "The most important ad element",
    "What visual element matters most in a paid ad creative?",
    [
      "Packing the image with as much information as possible.",
      "A big centered logo.",
      "An immediate impact element, such as strong expression, motion, or high contrast, that stops the scroll quickly.",
      "Paid ads always work best when they are minimalist.",
    ],
    2,
    "Before value proposition comes interruption of attention. If the visual cannot hold the eye, the rest never gets a chance.",
  ),
  fillStep(
    "Fill in the blanks - Create for Stories and Reels",
    "Build a vertical visual with space for text and CTA.",
    "/imagine ___, ___ style, ___ lighting, ___ background, ___ vertical composition leaving ___ at the top and bottom for text overlay, ___.",
    [
      "a young woman trying on sunglasses in a boutique smiling naturally",
      "candid lifestyle photography",
      "soft natural",
      "blurred bokeh store interior",
      "balanced",
      "empty space",
      "--ar 9:16",
    ],
    [
      "a young woman trying on sunglasses in a boutique smiling naturally",
      "candid lifestyle photography",
      "soft natural",
      "blurred bokeh store interior",
      "balanced",
      "empty space",
      "--ar 9:16",
    ],
    "A good vertical visual is not just full screen. It is full screen with functional space for CTA, title, and overlay.",
  ),
  quizStep(
    "Empty space in Stories",
    "Why is leaving empty space at the top and bottom of a Stories visual important?",
    [
      "To make MidJourney generate faster.",
      "Because Instagram automatically crops those edges.",
      "Because those areas hold text, links, CTAs, and graphic elements without covering the visual focus.",
      "Because empty space reduces visual impact.",
    ],
    2,
    "When the image is created with layout in mind, the result feels professional instead of patched later.",
  ),
  fillStep(
    "Fill in the blanks - Create brand identity imagery",
    "Complete the prompt for a visual that reinforces brand identity.",
    "/imagine ___, ___ aesthetic, ___ color palette, ___ style, ___ lighting, ___ feel, consistent brand identity, ___.",
    [
      "flat lay of natural skincare products with botanical elements and linen textures",
      "organic and minimalist",
      "soft earth tones with sage green and warm cream",
      "editorial product photography",
      "soft diffused natural",
      "clean premium and trustworthy",
      "--ar 1:1",
    ],
    [
      "flat lay of natural skincare products with botanical elements and linen textures",
      "organic and minimalist",
      "soft earth tones with sage green and warm cream",
      "editorial product photography",
      "soft diffused natural",
      "clean premium and trustworthy",
      "--ar 1:1",
    ],
    "Strong brands are not built by one image. They are built by repeating atmosphere, color, texture, and positioning with consistency.",
  ),
  quizStep(
    "Why brand consistency matters",
    "Why is maintaining visual consistency between brand posts strategic?",
    [
      "To satisfy the algorithm.",
      "Because repeated posts are easier to produce.",
      "Because visual consistency creates instant recognition and builds familiarity over time.",
      "Because only large brands need to think about it.",
    ],
    2,
    "When the audience recognizes the brand before reading the name, the visual system is doing its job.",
  ),
  fillStep(
    "Fill in the blanks - Create your seasonal visual",
    "Complete the prompt for a seasonal campaign visual with emotional atmosphere and brand polish.",
    "/imagine ___, ___ atmosphere, ___ lighting, ___ colors, ___ style, ___ mood, ___.",
    [
      "a beautifully wrapped gift box surrounded by pine branches and golden fairy lights on a rustic wooden table",
      "cozy Christmas",
      "warm golden bokeh",
      "deep red and gold",
      "luxury lifestyle photography",
      "magical and celebratory",
      "--ar 4:5",
    ],
    [
      "a beautifully wrapped gift box surrounded by pine branches and golden fairy lights on a rustic wooden table",
      "cozy Christmas",
      "warm golden bokeh",
      "deep red and gold",
      "luxury lifestyle photography",
      "magical and celebratory",
      "--ar 4:5",
    ],
    "Strong seasonal campaigns do not abandon the brand. They blend the emotion of the date with the visual identity of the business.",
  ),
  quizStep(
    "Effective seasonal imagery",
    "What makes a seasonal visual effective for marketing campaigns?",
    [
      "Showing the promotional product and price explicitly.",
      "Using the traditional date colors without brand customization.",
      "Combining the emotional elements of the date with the brand aesthetic so it feels seasonal and unmistakably branded.",
      "Seasonal visuals should be completely different from the regular brand identity.",
    ],
    2,
    "Good seasonal work connects context and identity. If it looks like generic holiday decoration, it weakens the brand.",
  ),
  fillStep(
    "Fill in the blanks - Create your thumbnail",
    "Build a thumbnail prompt with impact, curiosity, and space for text.",
    "/imagine ___, ___ expression, ___ background, ___ lighting, ___ style, ___ composition leaving ___ for title text, ___.",
    [
      "a man pointing at camera with shocked and excited facial expression",
      "vibrant and exaggerated",
      "bold yellow and orange gradient",
      "dramatic studio",
      "high contrast editorial",
      "horizontal",
      "empty space on the right side",
      "--ar 16:9",
    ],
    [
      "a man pointing at camera with shocked and excited facial expression",
      "vibrant and exaggerated",
      "bold yellow and orange gradient",
      "dramatic studio",
      "high contrast editorial",
      "horizontal",
      "empty space on the right side",
      "--ar 16:9",
    ],
    "A strong thumbnail does not explain everything. It sparks curiosity in under a second and still leaves room for the title to help.",
  ),
  quizStep(
    "Thumbnail that lifts CTR",
    "What makes a YouTube thumbnail effective for raising CTR?",
    [
      "A large centered channel logo.",
      "Showing the entire content of the video inside the image.",
      "Exaggerated facial expression or visual surprise combined with strategic space for text.",
      "Thumbnails with fewer elements always perform better.",
    ],
    2,
    "CTR rises when the thumbnail communicates promise, tension, and curiosity without overloading the read.",
  ),
  fillStep(
    "Fill in the blanks - Create testimonial imagery",
    "Complete the prompt for an authentic social-proof visual.",
    "/imagine ___, ___ style, ___ lighting, ___ background, ___ expression, ___ feel, ___.",
    [
      "a happy middle-aged woman smiling genuinely at camera with relaxed body language",
      "candid lifestyle portrait",
      "soft natural window",
      "warm blurred home environment",
      "authentic and joyful",
      "real trustworthy and deeply relatable",
      "--ar 4:5",
    ],
    [
      "a happy middle-aged woman smiling genuinely at camera with relaxed body language",
      "candid lifestyle portrait",
      "soft natural window",
      "warm blurred home environment",
      "authentic and joyful",
      "real trustworthy and deeply relatable",
      "--ar 4:5",
    ],
    "Social proof persuades more when it feels genuinely human. People can sense staged visuals very quickly.",
  ),
  quizStep(
    "Authenticity in testimonials",
    "Why is visual authenticity more important than aesthetic perfection in testimonial imagery?",
    [
      "Because imperfect images are cheaper to produce.",
      "To make the testimonial look unsponsored.",
      "Because the brain quickly detects when an image feels staged, and authentic visuals generate more trust.",
      "Authenticity only matters for personal brands.",
    ],
    2,
    "A testimonial without authenticity feels like stock photography, and stock-photography energy rarely creates trust.",
  ),
  fillStep(
    "Fill in the blanks - Create educational imagery",
    "Build a prompt for article, newsletter, or blog visuals with room for the title.",
    "/imagine ___, ___ style, ___ lighting, ___ tones, ___ composition with ___ for title text placement, ___, ___.",
    [
      "a professional woman presenting data on a large screen in a modern conference room",
      "editorial corporate photography",
      "soft and clean",
      "cool blue and white",
      "horizontal",
      "empty darker area on the left",
      "professional credibility",
      "--ar 16:9",
    ],
    [
      "a professional woman presenting data on a large screen in a modern conference room",
      "editorial corporate photography",
      "soft and clean",
      "cool blue and white",
      "horizontal",
      "empty darker area on the left",
      "professional credibility",
      "--ar 16:9",
    ],
    "Professional educational imagery is designed with text in mind from the beginning, not as an afterthought.",
  ),
  quizStep(
    "Why text space matters",
    "Why is creating specific space for text in educational imagery a professional practice?",
    [
      "To save time and avoid layout work.",
      "Because MidJourney cannot generate images without empty areas.",
      "Because the image is born ready to support title and message, creating a cohesive layout.",
      "Space for text only matters in advertising banners.",
    ],
    2,
    "When visual and text are designed together, the communication feels intentional and much more refined.",
  ),
  fillStep(
    "Fill in the blanks - Build your visual series",
    "Complete the sentence with the right logic for a coherent campaign across multiple pieces.",
    "To create a cohesive series, keep these elements ___ in every prompt: color ___, lighting ___, photographic ___, and composition ___. Vary only the main ___ of each image to tell a ___ visual story across the campaign.",
    [
      "fixed",
      "palette",
      "type",
      "style",
      "rule",
      "subject and action",
      "progressive",
    ],
    [
      "fixed",
      "palette",
      "type",
      "style",
      "rule",
      "subject and action",
      "progressive",
    ],
    "A strong series does not happen by luck. It comes from a stable visual spine with controlled variation around it.",
  ),
  quizStep(
    "Best strategy for campaign cohesion",
    "What is the most effective strategy for creating a cohesive visual campaign in MidJourney?",
    [
      "Generate random images and choose the ones that happen to look similar.",
      "Use exactly the same prompt for every asset.",
      "Create a base prompt with fixed identity elements and vary only what changes between posts.",
      "Visual cohesion is only possible with external editing.",
    ],
    2,
    "Good cohesion does not kill variety. It creates a visual backbone so each asset feels fresh while still belonging to the same brand.",
  ),
  fillStep(
    "Fill in the blanks - Avoid the mistakes",
    "Complete the sentence with the visual mistakes that most damage marketing campaigns.",
    "The main visual mistakes in marketing with MidJourney are: using ___ prompts without customization, mixing incompatible ___ between posts, generating images with the wrong ___ for the channel, ignoring the emotional ___ of lighting, and creating visuals that ___ the brand positioning.",
    [
      "generic",
      "styles and palettes",
      "ratio",
      "impact",
      "contradict",
    ],
    [
      "generic",
      "styles and palettes",
      "ratio",
      "impact",
      "contradict",
    ],
    "Weak campaigns usually fail less from lack of beauty and more from lack of strategic coherence.",
  ),
  quizStep(
    "Most common AI-marketing mistake",
    "What is the most common visual mistake in small-business marketing campaigns made with MidJourney?",
    [
      "Using prompts that are too long and overloaded.",
      "Creating images with more quality than needed.",
      "Lack of visual consistency between posts, making each piece feel like it belongs to a different brand.",
      "Using the same style in all brand images.",
    ],
    2,
    "When the brand does not feel like the same brand from one post to the next, recognition, memory, and trust never accumulate.",
  ),
  textStep(
    "Conclusion",
    "With MidJourney, any brand can now produce agency-level visuals without a large team, studio, or expensive budget. Product photos, feed posts, ad creatives, thumbnails, educational content, social proof, and full campaigns can come from well-built prompts and clear visual strategy.\n\nThe difference between a brand that grows and one that stalls is not only the product. It is also how the brand presents itself visually before saying a single word.",
  ),
] as const;

const MIDJOURNEY_MODULE_6_STEPS_ES_BASE = [
  textStep(
    "Visuales poderosos para marketing con MidJourney",
    "Bienvenido de nuevo. En esta leccion vas a aprender a crear imagenes con impacto profesional para marketing usando MidJourney, desde publicaciones en redes hasta campanas completas. El objetivo ya no es solo crear una imagen bonita. El objetivo es crear visuales que refuercen el posicionamiento, sostengan la atencion y eleven el valor percibido.\n\nEn marketing digital, la imagen suele hablar antes que el texto. Antes de leer un titulo, el publico ya sintio si la marca parece confiable, premium, clara o amateur.",
  ),
  quizStep(
    "Por que importan los visuales de calidad",
    "Por que invertir en visuales de alta calidad es estrategico para cualquier marca?",
    [
      "Porque el impacto visual se procesa mucho mas rapido que el texto, y la primera impresion suele decidir si el publico sigue prestando atencion.",
      "Porque las imagenes bonitas garantizan automaticamente mas ventas.",
      "Porque la calidad visual solo importa para marcas de lujo.",
      "Porque el texto del anuncio siempre importa mas que la imagen.",
    ],
    0,
    "Una imagen no cierra sola la venta, pero muchas veces decide si la persona se detiene el tiempo suficiente para considerar el resto.",
  ),
  fillStep(
    "Completa los espacios - Crea tu foto de producto",
    "Completa el prompt de fotografia de producto con acabado de campana profesional.",
    "/imagine ___, fondo ___, iluminacion ___, fotografia ___, detalle ___, sensacion de lujo, ___.",
    [
      "un frasco premium de serum para la piel con gotas de agua y elementos botanicos",
      "superficie limpia de marmol blanco",
      "soft box",
      "comercial de producto",
      "ultra alto 8K",
      "--ar 1:1",
    ],
    [
      "un frasco premium de serum para la piel con gotas de agua y elementos botanicos",
      "superficie limpia de marmol blanco",
      "soft box",
      "comercial de producto",
      "ultra alto 8K",
      "--ar 1:1",
    ],
    "Una buena foto de producto vende percepcion antes de vender precio. Luz, textura, fondo y claridad visual trabajan juntos para eso.",
  ),
  quizStep(
    "Producto que convierte",
    "Que vuelve eficaz una fotografia de producto para conversion?",
    [
      "Mostrar la mayor cantidad de productos posible en una sola imagen.",
      "Usar fondos muy coloridos para llamar la atencion a cualquier costo.",
      "Enfoque limpio del producto, luz que resalta textura y detalles, y composicion que eleva el valor percibido.",
      "Todo producto premium debe fotografiarse sobre fondo negro.",
    ],
    2,
    "Una imagen de conversion no confunde. Hace que el producto se sienta deseable, claro y bien posicionado desde la primera mirada.",
  ),
  fillStep(
    "Completa los espacios - Crea tu post para feed",
    "Construye un visual pensado para detener el scroll en el feed de Instagram.",
    "/imagine ___, estilo ___, colores ___, composicion ___, iluminacion ___, mood ___, ___.",
    [
      "una emprendedora segura trabajando en un cafe moderno con portatil",
      "fotografia lifestyle",
      "calidos y vibrantes",
      "regla de tercios",
      "golden hour",
      "empoderador e inspirador",
      "--ar 4:5",
    ],
    [
      "una emprendedora segura trabajando en un cafe moderno con portatil",
      "fotografia lifestyle",
      "calidos y vibrantes",
      "regla de tercios",
      "golden hour",
      "empoderador e inspirador",
      "--ar 4:5",
    ],
    "En el feed, la presencia visual importa. El 4:5 ocupa mas espacio y compra unos segundos extra de atencion.",
  ),
  quizStep(
    "Por que funciona 4:5 en el feed",
    "Por que el formato --ar 4:5 es estrategico para publicaciones del feed de Instagram?",
    [
      "Porque es el unico formato aceptado por el algoritmo.",
      "Porque siempre hace la imagen mas grande que una cuadrada.",
      "Porque ocupa mas espacio vertical en el feed y aumenta la presencia visual antes del scroll.",
      "Porque 4:5 solo funciona con fotos de personas.",
    ],
    2,
    "Mas espacio vertical significa mas atencion. El visual gana unos momentos extra antes de que la persona siga bajando.",
  ),
  fillStep(
    "Completa los espacios - Crea un anuncio pago",
    "Completa el prompt de anuncio con impacto inmediato.",
    "/imagine ___, estilo ___, iluminacion ___, ___, alto contraste, colores ___, sensacion ___, ___.",
    [
      "un joven atlético despues de entrenar sosteniendo un batido proteico con sudor y determinacion",
      "fotografia deportiva dinamica",
      "dramatica",
      "efecto de motion blur en el fondo",
      "fuertes y energeticos",
      "poderosa y motivadora",
      "--ar 9:16",
    ],
    [
      "un joven atlético despues de entrenar sosteniendo un batido proteico con sudor y determinacion",
      "fotografia deportiva dinamica",
      "dramatica",
      "efecto de motion blur en el fondo",
      "fuertes y energeticos",
      "poderosa y motivadora",
      "--ar 9:16",
    ],
    "Un buen anuncio detiene el scroll en milisegundos. Expresion, contraste y sensacion de movimiento ayudan a lograrlo.",
  ),
  quizStep(
    "El elemento mas importante del anuncio",
    "Que elemento visual importa mas en un creativo para anuncio pago?",
    [
      "Poner la mayor cantidad posible de informacion dentro de la imagen.",
      "Un logo grande y centrado.",
      "Un elemento de impacto inmediato, como una expresion fuerte, movimiento o alto contraste, que detenga el scroll rapido.",
      "Los anuncios pagos siempre funcionan mejor si son minimalistas.",
    ],
    2,
    "Antes de la propuesta de valor viene la interrupcion de la atencion. Si el visual no sostiene la mirada, lo demas ni entra.",
  ),
  fillStep(
    "Completa los espacios - Crea para Stories y Reels",
    "Construye un visual vertical con espacio para texto y CTA.",
    "/imagine ___, estilo ___, iluminacion ___, fondo ___, composicion vertical ___ dejando ___ arriba y abajo para texto, ___.",
    [
      "una joven probandose gafas en una boutique y sonriendo de forma natural",
      "fotografia lifestyle espontanea",
      "natural suave",
      "interior desenfocado con bokeh",
      "equilibrada",
      "espacio vacio",
      "--ar 9:16",
    ],
    [
      "una joven probandose gafas en una boutique y sonriendo de forma natural",
      "fotografia lifestyle espontanea",
      "natural suave",
      "interior desenfocado con bokeh",
      "equilibrada",
      "espacio vacio",
      "--ar 9:16",
    ],
    "Un buen visual vertical no es solo pantalla completa. Es pantalla completa con espacio funcional para CTA, titulo y overlay.",
  ),
  quizStep(
    "Espacio vacio en Stories",
    "Por que es importante dejar espacio vacio arriba y abajo en un visual para Stories?",
    [
      "Para que MidJourney genere mas rapido.",
      "Porque Instagram recorta automaticamente esos bordes.",
      "Porque esas zonas reciben texto, links, CTA y elementos graficos sin tapar el foco visual.",
      "Porque el espacio vacio reduce el impacto visual.",
    ],
    2,
    "Cuando la imagen nace pensando en layout, el resultado se siente profesional y no improvisado despues.",
  ),
] as const;


const MIDJOURNEY_MODULE_6_STEPS_ES_EXTRA = [
  fillStep(
    "Completa los espacios - Crea identidad visual",
    "Completa el prompt para un visual que refuerce identidad de marca.",
    "/imagine ___, estetica ___, paleta ___, estilo ___, iluminacion ___, sensacion ___, identidad visual consistente, ___.",
    [
      "flat lay de productos naturales de skincare con elementos botanicos y texturas de lino",
      "organica y minimalista",
      "tonos tierra suaves con verde salvia y crema calida",
      "fotografia editorial de producto",
      "natural difusa y suave",
      "limpia, premium y confiable",
      "--ar 1:1",
    ],
    [
      "flat lay de productos naturales de skincare con elementos botanicos y texturas de lino",
      "organica y minimalista",
      "tonos tierra suaves con verde salvia y crema calida",
      "fotografia editorial de producto",
      "natural difusa y suave",
      "limpia, premium y confiable",
      "--ar 1:1",
    ],
    "Una marca fuerte no depende de una imagen aislada. Depende de repetir atmosfera, color, textura y posicionamiento con coherencia.",
  ),
  quizStep(
    "Por que importa la consistencia de marca",
    "Por que mantener consistencia visual entre publicaciones de una marca es estrategico?",
    [
      "Para agradar al algoritmo.",
      "Porque publicar piezas parecidas es mas facil.",
      "Porque la consistencia visual crea reconocimiento instantaneo y construye familiaridad con el tiempo.",
      "Porque solo las marcas grandes necesitan pensar en eso.",
    ],
    2,
    "Cuando el publico reconoce la marca antes de leer el nombre, el sistema visual ya esta funcionando.",
  ),
  fillStep(
    "Completa los espacios - Crea tu visual estacional",
    "Completa el prompt de campana estacional con atmosfera emocional y acabado de marca.",
    "/imagine ___, atmosfera ___, iluminacion ___, colores ___, estilo ___, mood ___, ___.",
    [
      "una caja de regalo elegante rodeada de ramas de pino y luces doradas sobre una mesa rustica",
      "Navidad acogedora",
      "bokeh dorado y calido",
      "rojo profundo y dorado",
      "fotografia lifestyle de lujo",
      "magico y celebratorio",
      "--ar 4:5",
    ],
    [
      "una caja de regalo elegante rodeada de ramas de pino y luces doradas sobre una mesa rustica",
      "Navidad acogedora",
      "bokeh dorado y calido",
      "rojo profundo y dorado",
      "fotografia lifestyle de lujo",
      "magico y celebratorio",
      "--ar 4:5",
    ],
    "Una buena campana estacional no abandona la marca. Mezcla la emocion de la fecha con la identidad visual del negocio.",
  ),
  quizStep(
    "Visual estacional eficaz",
    "Que hace eficaz a un visual estacional para campanas de marketing?",
    [
      "Mostrar el producto en promocion con precio destacado.",
      "Usar los colores tipicos de la fecha sin personalizacion.",
      "Combinar la emocion de la fecha con la estetica de la marca para que se sienta estacional y de marca al mismo tiempo.",
      "Los visuales estacionales deben ser totalmente distintos de la identidad habitual.",
    ],
    2,
    "Lo estacional funciona de verdad cuando conecta contexto e identidad, no cuando parece decoracion generica de temporada.",
  ),
  fillStep(
    "Completa los espacios - Crea tu thumbnail",
    "Construye un prompt de thumbnail con impacto, curiosidad y espacio para texto.",
    "/imagine ___, expresion ___, fondo ___, iluminacion ___, estilo ___, composicion ___ dejando ___ para el titulo, ___.",
    [
      "un hombre apuntando a la camara con expresion sorprendida y entusiasmada",
      "vibrante y exagerada",
      "gradiente amarillo y naranja intenso",
      "estudio dramatico",
      "editorial de alto contraste",
      "horizontal",
      "espacio vacio en el lado derecho",
      "--ar 16:9",
    ],
    [
      "un hombre apuntando a la camara con expresion sorprendida y entusiasmada",
      "vibrante y exagerada",
      "gradiente amarillo y naranja intenso",
      "estudio dramatico",
      "editorial de alto contraste",
      "horizontal",
      "espacio vacio en el lado derecho",
      "--ar 16:9",
    ],
    "Una buena thumbnail no explica todo. Activa curiosidad en menos de un segundo y deja espacio para que el titulo sume.",
  ),
  quizStep(
    "Thumbnail que sube el CTR",
    "Que vuelve eficaz una thumbnail de YouTube para aumentar el CTR?",
    [
      "Un logo del canal grande y centrado.",
      "Mostrar todo el contenido del video dentro de la imagen.",
      "Expresion exagerada o sorpresa visual combinada con espacio estrategico para texto.",
      "Las thumbnails con menos elementos siempre funcionan mejor.",
    ],
    2,
    "El CTR crece cuando la thumbnail comunica promesa, tension y curiosidad sin saturar la lectura.",
  ),
  fillStep(
    "Completa los espacios - Crea visual de testimonio",
    "Completa el prompt para una prueba social con autenticidad.",
    "/imagine ___, estilo ___, iluminacion ___, fondo ___, expresion ___, sensacion ___, ___.",
    [
      "una mujer de mediana edad sonriendo de forma genuina a camara con postura relajada",
      "retrato lifestyle espontaneo",
      "luz natural de ventana",
      "hogar desenfocado y calido",
      "autentica y alegre",
      "real, confiable y profundamente cercana",
      "--ar 4:5",
    ],
    [
      "una mujer de mediana edad sonriendo de forma genuina a camara con postura relajada",
      "retrato lifestyle espontaneo",
      "luz natural de ventana",
      "hogar desenfocado y calido",
      "autentica y alegre",
      "real, confiable y profundamente cercana",
      "--ar 4:5",
    ],
    "La prueba social convence mas cuando se siente humana de verdad. El publico detecta rapido cuando la escena esta demasiado armada.",
  ),
  quizStep(
    "Autenticidad en testimonios",
    "Por que la autenticidad visual es mas importante que la perfeccion estetica en imagenes de testimonios?",
    [
      "Porque las imagenes imperfectas cuestan menos.",
      "Para que parezca que el testimonio no fue patrocinado.",
      "Porque el cerebro detecta rapido cuando una imagen parece actuada, y los visuales autenticos generan mas confianza.",
      "La autenticidad solo importa en marcas personales.",
    ],
    2,
    "Un testimonio sin autenticidad se siente como banco de imagenes, y eso rara vez construye confianza real.",
  ),
  fillStep(
    "Completa los espacios - Crea visual educativo",
    "Construye un prompt para articulo, newsletter o blog con espacio para titulo.",
    "/imagine ___, estilo ___, iluminacion ___, tonos ___, composicion ___ con ___ para el titulo, ___, ___.",
    [
      "una profesional presentando datos en una gran pantalla dentro de una sala moderna",
      "fotografia editorial corporativa",
      "suave y limpia",
      "azul frio y blanco",
      "horizontal",
      "un area mas oscura vacia a la izquierda",
      "credibilidad profesional",
      "--ar 16:9",
    ],
    [
      "una profesional presentando datos en una gran pantalla dentro de una sala moderna",
      "fotografia editorial corporativa",
      "suave y limpia",
      "azul frio y blanco",
      "horizontal",
      "un area mas oscura vacia a la izquierda",
      "credibilidad profesional",
      "--ar 16:9",
    ],
    "El visual educativo profesional nace pensando en el texto. No es una imagen bonita con un titulo pegado encima despues.",
  ),
  quizStep(
    "Espacio para texto en contenido educativo",
    "Por que crear un espacio especifico para texto en un visual educativo es una practica profesional?",
    [
      "Para ahorrar tiempo y no hacer layout.",
      "Porque MidJourney no puede generar imagenes sin espacios vacios.",
      "Porque la imagen nace lista para dialogar con el titulo y el mensaje, creando un layout coherente.",
      "El espacio para texto solo importa en banners publicitarios.",
    ],
    2,
    "Cuando visual y texto se piensan juntos, la comunicacion se siente intencional y mucho mas refinada.",
  ),
  fillStep(
    "Completa los espacios - Construye tu serie visual",
    "Completa la frase con la logica correcta para una campana coherente en varias piezas.",
    "Para crear una serie coherente, mantén ___ estos elementos en todos los prompts: ___ de color, ___ de iluminacion, ___ fotografico y ___ de composicion. Varia solo el ___ principal de cada imagen para contar una historia visual ___ a lo largo de la campana.",
    [
      "fijos",
      "paleta",
      "tipo",
      "estilo",
      "regla",
      "sujeto y accion",
      "progresiva",
    ],
    [
      "fijos",
      "paleta",
      "tipo",
      "estilo",
      "regla",
      "sujeto y accion",
      "progresiva",
    ],
    "Una serie fuerte no nace por suerte. Nace de una columna visual estable con variaciones controladas alrededor.",
  ),
  quizStep(
    "Mejor estrategia para una campana coherente",
    "Cual es la estrategia mas eficaz para crear una campana visual coherente en MidJourney?",
    [
      "Generar imagenes aleatorias y elegir las que se parezcan.",
      "Usar exactamente el mismo prompt en todas las piezas.",
      "Crear un prompt base con elementos fijos de identidad visual y variar solo lo que cambia entre posts.",
      "La coherencia visual solo es posible con edicion externa.",
    ],
    2,
    "La buena coherencia no mata la variedad. Crea una columna vertebral visual para que cada pieza sea nueva, pero siga siendo de la misma marca.",
  ),
  fillStep(
    "Completa los espacios - Evita los errores",
    "Completa la frase con los errores visuales que mas destruyen una campana de marketing.",
    "Los principales errores visuales en marketing con MidJourney son: usar prompts ___ sin personalizacion, mezclar ___ incompatibles entre posts, generar imagenes con ___ incorrecta para el canal, ignorar el ___ emocional de la iluminacion y crear visuales que ___ el posicionamiento de la marca.",
    [
      "genericos",
      "estilos y paletas",
      "proporcion",
      "impacto",
      "contradicen",
    ],
    [
      "genericos",
      "estilos y paletas",
      "proporcion",
      "impacto",
      "contradicen",
    ],
    "Las campanas debiles suelen fallar menos por falta de belleza y mas por falta de coherencia estrategica.",
  ),
  quizStep(
    "Error mas comun en marketing con IA",
    "Cual es el error visual mas comun en campanas de pequenas empresas hechas con MidJourney?",
    [
      "Usar prompts demasiado largos y cargados.",
      "Crear imagenes con mas calidad de la necesaria.",
      "Falta de consistencia visual entre publicaciones, haciendo que cada pieza parezca de una marca distinta.",
      "Usar el mismo estilo en todas las imagenes de la marca.",
    ],
    2,
    "Cuando la marca no parece la misma de una pieza a otra, nunca se acumulan reconocimiento, memoria ni confianza.",
  ),
  textStep(
    "Conclusion",
    "Con MidJourney, cualquier marca puede producir visuales con nivel de agencia sin depender de equipo grande, estudio o presupuesto alto. Fotos de producto, posts de feed, creativos para anuncios, thumbnails, contenido educativo, prueba social y campanas completas pueden surgir de prompts bien construidos y estrategia visual clara.\n\nLa diferencia entre una marca que crece y otra que se estanca no esta solo en el producto. Tambien esta en como se presenta visualmente antes de decir una sola palabra.",
  ),
] as const;

export const MIDJOURNEY_MODULE_6_STEPS_ES = [...MIDJOURNEY_MODULE_6_STEPS_ES_BASE, ...MIDJOURNEY_MODULE_6_STEPS_ES_EXTRA] as const;


export const MIDJOURNEY_MODULE_6_STEPS_FR = [
  textStep(
    "Des visuels marketing puissants avec MidJourney",
    "Bon retour. Dans cette lecon, tu vas apprendre a creer des images a impact professionnel pour le marketing avec MidJourney, depuis les posts reseaux sociaux jusqu'aux campagnes completes. Le but n'est plus seulement de produire une belle image. Le but est de creer des visuels qui renforcent le positionnement, retiennent l'attention et augmentent la valeur percue.\n\nEn marketing digital, l'image parle souvent avant le texte. Avant de lire un titre, le public a deja ressenti si la marque parait fiable, premium, claire ou amateur.",
  ),
  quizStep(
    "Pourquoi des visuels de qualite comptent",
    "Pourquoi investir dans des visuels de haute qualite est-il strategique pour n'importe quelle marque ?",
    [
      "Parce que l'impact visuel est traite bien plus vite que le texte, et la premiere impression decide souvent si le public continue a s'engager.",
      "Parce que de belles images garantissent automatiquement plus de ventes.",
      "Parce que la qualite visuelle ne compte que pour les marques de luxe.",
      "Parce que le texte de l'annonce compte toujours plus que l'image.",
    ],
    0,
    "Une image ne conclut pas seule une vente, mais elle decide tres souvent si la personne s'arrete assez longtemps pour considerer le reste.",
  ),
  fillStep(
    "Complete les blancs - Cree ta photo produit",
    "Complete le prompt de photographie produit avec un rendu digne d'une campagne.",
    "/imagine ___, fond ___, eclairage ___, photographie ___, detail ___, sensation de luxe, ___.",
    [
      "un flacon premium de serum pour la peau avec des gouttes d'eau et des elements botaniques",
      "surface propre en marbre blanc",
      "soft box",
      "commerciale produit",
      "ultra haute 8K",
      "--ar 1:1",
    ],
    [
      "un flacon premium de serum pour la peau avec des gouttes d'eau et des elements botaniques",
      "surface propre en marbre blanc",
      "soft box",
      "commerciale produit",
      "ultra haute 8K",
      "--ar 1:1",
    ],
    "Une bonne photo produit vend la perception avant de vendre le prix. Lumiere, texture, fond et clarte visuelle travaillent ensemble pour cela.",
  ),
  quizStep(
    "Produit qui convertit",
    "Qu'est-ce qui rend une photographie produit efficace pour la conversion ?",
    [
      "Montrer le plus de produits possible dans une seule image.",
      "Utiliser des fonds tres colores pour attirer l'attention a tout prix.",
      "Une mise en avant propre du produit, une lumiere qui valorise texture et details, et une composition qui augmente la valeur percue.",
      "Tout produit premium doit toujours etre photographie sur fond noir.",
    ],
    2,
    "Une image de conversion ne doit pas embrouiller. Elle doit rendre le produit desirable, clair et bien positionne au premier regard.",
  ),
  fillStep(
    "Complete les blancs - Cree ton post feed",
    "Construit un visuel pense pour stopper le scroll dans le feed Instagram.",
    "/imagine ___, style ___, couleurs ___, composition ___, eclairage ___, mood ___, ___.",
    [
      "une entrepreneuse confiante travaillant dans un cafe moderne avec un ordinateur portable",
      "photographie lifestyle",
      "chaudes et vibrantes",
      "regle des tiers",
      "golden hour",
      "inspirant et valorisant",
      "--ar 4:5",
    ],
    [
      "une entrepreneuse confiante travaillant dans un cafe moderne avec un ordinateur portable",
      "photographie lifestyle",
      "chaudes et vibrantes",
      "regle des tiers",
      "golden hour",
      "inspirant et valorisant",
      "--ar 4:5",
    ],
    "Dans le feed, la presence visuelle compte. Le 4:5 prend plus de place et achete quelques secondes d'attention supplementaires.",
  ),
  quizStep(
    "Pourquoi le 4:5 marche dans le feed",
    "Pourquoi le format --ar 4:5 est-il strategique pour les posts du feed Instagram ?",
    [
      "Parce que c'est le seul format accepte par l'algorithme.",
      "Parce qu'il rend toujours l'image plus grande qu'un carre.",
      "Parce qu'il prend plus d'espace vertical dans le feed et augmente la presence visuelle avant le scroll.",
      "Parce que le 4:5 ne marche que pour des photos de personnes.",
    ],
    2,
    "Plus d'espace vertical veut dire plus d'attention. Le visuel gagne quelques instants avant que la personne ne continue a defiler.",
  ),
  fillStep(
    "Complete les blancs - Cree une annonce payante",
    "Complete le prompt d'un creatif d'annonce a impact immediat.",
    "/imagine ___, style ___, eclairage ___, ___, contraste eleve, couleurs ___, sensation ___, ___.",
    [
      "un jeune sportif apres l'entrainement tenant un shake proteine avec sueur et determination",
      "photographie sportive dynamique",
      "dramatique",
      "effet de motion blur en arriere-plan",
      "fortes et energiques",
      "puissante et motivante",
      "--ar 9:16",
    ],
    [
      "un jeune sportif apres l'entrainement tenant un shake proteine avec sueur et determination",
      "photographie sportive dynamique",
      "dramatique",
      "effet de motion blur en arriere-plan",
      "fortes et energiques",
      "puissante et motivante",
      "--ar 9:16",
    ],
    "Une bonne annonce stoppe le scroll en millisecondes. Expression, contraste et sensation de mouvement aident a y parvenir.",
  ),
  quizStep(
    "L'element le plus important de l'annonce",
    "Quel element visuel compte le plus dans un creatif publicitaire payant ?",
    [
      "Mettre le plus d'informations possible dans l'image.",
      "Un logo tres grand et centre.",
      "Un element d'impact immediat, comme une expression forte, du mouvement ou un contraste eleve, qui arrete vite le scroll.",
      "Les annonces payantes fonctionnent toujours mieux si elles sont minimalistes.",
    ],
    2,
    "Avant la proposition de valeur, il faut interrompre l'attention. Si le visuel n'attrape pas l'oeil, le reste ne joue meme pas.",
  ),
  fillStep(
    "Complete les blancs - Cree pour Stories et Reels",
    "Construis un visuel vertical avec de l'espace pour le texte et le CTA.",
    "/imagine ___, style ___, eclairage ___, fond ___, composition verticale ___ laissant ___ en haut et en bas pour le texte, ___.",
    [
      "une jeune femme essayant des lunettes dans une boutique en souriant naturellement",
      "photographie lifestyle spontanee",
      "naturel doux",
      "interieur flou avec effet bokeh",
      "equilibree",
      "de l'espace vide",
      "--ar 9:16",
    ],
    [
      "une jeune femme essayant des lunettes dans une boutique en souriant naturellement",
      "photographie lifestyle spontanee",
      "naturel doux",
      "interieur flou avec effet bokeh",
      "equilibree",
      "de l'espace vide",
      "--ar 9:16",
    ],
    "Un bon visuel vertical n'est pas seulement plein ecran. Il est plein ecran avec un espace fonctionnel pour le CTA, le titre et l'overlay.",
  ),
  quizStep(
    "Espace vide dans les Stories",
    "Pourquoi est-il important de laisser de l'espace vide en haut et en bas d'un visuel pour Stories ?",
    [
      "Pour que MidJourney genere plus vite.",
      "Parce qu'Instagram recadre automatiquement ces zones.",
      "Parce que ces zones servent a accueillir texte, liens, CTA et elements graphiques sans masquer le focus visuel.",
      "Parce que l'espace vide reduit l'impact visuel.",
    ],
    2,
    "Quand l'image nait avec le layout en tete, le resultat parait professionnel et non bricole apres coup.",
  ),
  fillStep(
    "Complete les blancs - Cree l'identite visuelle",
    "Complete le prompt pour un visuel qui renforce l'identite de marque.",
    "/imagine ___, esthetique ___, palette ___, style ___, eclairage ___, sensation ___, identite visuelle coherente, ___.",
    [
      "flat lay de produits skincare naturels avec elements botaniques et textures de lin",
      "organique et minimaliste",
      "tons terre doux avec vert sauge et creme chaude",
      "photographie editoriale produit",
      "naturelle diffuse et douce",
      "propre, premium et rassurante",
      "--ar 1:1",
    ],
    [
      "flat lay de produits skincare naturels avec elements botaniques et textures de lin",
      "organique et minimaliste",
      "tons terre doux avec vert sauge et creme chaude",
      "photographie editoriale produit",
      "naturelle diffuse et douce",
      "propre, premium et rassurante",
      "--ar 1:1",
    ],
    "Une marque forte ne repose pas sur une image isolee. Elle repose sur la repetition coherente d'une atmosphere, d'une couleur, d'une texture et d'un positionnement.",
  ),
  quizStep(
    "Pourquoi la coherence de marque compte",
    "Pourquoi maintenir une coherence visuelle entre les posts d'une marque est-il strategique ?",
    [
      "Pour plaire a l'algorithme.",
      "Parce que les posts repetitifs sont plus faciles a produire.",
      "Parce que la coherence visuelle cree une reconnaissance instantanee et construit la familiarite au fil du temps.",
      "Parce que seules les grandes marques ont besoin d'y penser.",
    ],
    2,
    "Quand le public reconnait la marque avant de lire son nom, le systeme visuel fait vraiment son travail.",
  ),
  fillStep(
    "Complete les blancs - Cree ton visuel saisonnier",
    "Complete le prompt d'une campagne saisonniere avec atmosphere emotionnelle et finition de marque.",
    "/imagine ___, atmosphere ___, eclairage ___, couleurs ___, style ___, mood ___, ___.",
    [
      "une boite cadeau elegante entouree de branches de pin et de lumieres dorees sur une table rustique",
      "Noel chaleureux",
      "bokeh dore et chaud",
      "rouge profond et or",
      "photographie lifestyle de luxe",
      "magique et celebratoire",
      "--ar 4:5",
    ],
    [
      "une boite cadeau elegante entouree de branches de pin et de lumieres dorees sur une table rustique",
      "Noel chaleureux",
      "bokeh dore et chaud",
      "rouge profond et or",
      "photographie lifestyle de luxe",
      "magique et celebratoire",
      "--ar 4:5",
    ],
    "Une campagne saisonniere forte n'abandonne pas la marque. Elle melange l'emotion de la date avec l'identite visuelle du business.",
  ),
  quizStep(
    "Visuel saisonnier efficace",
    "Qu'est-ce qui rend un visuel saisonnier efficace pour une campagne marketing ?",
    [
      "Montrer clairement le produit en promotion avec son prix.",
      "Utiliser les couleurs traditionnelles de la date sans personnalisation.",
      "Combiner l'emotion de la date avec l'esthetique de la marque pour que le visuel paraisse saisonnier et pleinement de marque.",
      "Les visuels saisonniers doivent etre totalement differents de l'identite habituelle.",
    ],
    2,
    "Le saisonnier fonctionne vraiment quand il relie contexte et identite, pas quand il ressemble a une decoration generique.",
  ),
  fillStep(
    "Complete les blancs - Cree ta thumbnail",
    "Construit un prompt de thumbnail avec impact, curiosite et espace pour le texte.",
    "/imagine ___, expression ___, fond ___, eclairage ___, style ___, composition ___ laissant ___ pour le titre, ___.",
    [
      "un homme pointant la camera avec une expression choquee et enthousiaste",
      "vibrante et exageree",
      "degrade jaune et orange puissant",
      "studio dramatique",
      "editorial a fort contraste",
      "horizontale",
      "de l'espace vide sur la droite",
      "--ar 16:9",
    ],
    [
      "un homme pointant la camera avec une expression choquee et enthousiaste",
      "vibrante et exageree",
      "degrade jaune et orange puissant",
      "studio dramatique",
      "editorial a fort contraste",
      "horizontale",
      "de l'espace vide sur la droite",
      "--ar 16:9",
    ],
    "Une bonne thumbnail n'explique pas tout. Elle active la curiosite en moins d'une seconde et laisse encore de la place au titre.",
  ),
  quizStep(
    "Thumbnail qui fait monter le CTR",
    "Qu'est-ce qui rend une thumbnail YouTube efficace pour augmenter le CTR ?",
    [
      "Un logo de chaine tres grand et centre.",
      "Montrer tout le contenu de la video dans l'image.",
      "Une expression exageree ou une surprise visuelle combinee a un espace strategique pour le texte.",
      "Les thumbnails avec moins d'elements performent toujours mieux.",
    ],
    2,
    "Le CTR monte quand la thumbnail communique promesse, tension et curiosite sans surcharger la lecture.",
  ),
  fillStep(
    "Complete les blancs - Cree un visuel de temoignage",
    "Complete le prompt pour une preuve sociale authentique.",
    "/imagine ___, style ___, eclairage ___, fond ___, expression ___, sensation ___, ___.",
    [
      "une femme d'age moyen souriant sincerement face camera avec une posture detendue",
      "portrait lifestyle spontane",
      "lumiere naturelle de fenetre",
      "interieur de maison flou et chaleureux",
      "authentique et joyeuse",
      "reelle, fiable et tres relatable",
      "--ar 4:5",
    ],
    [
      "une femme d'age moyen souriant sincerement face camera avec une posture detendue",
      "portrait lifestyle spontane",
      "lumiere naturelle de fenetre",
      "interieur de maison flou et chaleureux",
      "authentique et joyeuse",
      "reelle, fiable et tres relatable",
      "--ar 4:5",
    ],
    "La preuve sociale persuade davantage quand elle parait vraiment humaine. Le public sent tres vite quand le visuel est trop joue.",
  ),
  quizStep(
    "Authenticite dans les temoignages",
    "Pourquoi l'authenticite visuelle est-elle plus importante que la perfection esthetique dans les images de temoignages ?",
    [
      "Parce que les images imparfaites coutent moins cher a produire.",
      "Pour donner l'impression que le temoignage n'est pas sponsorise.",
      "Parce que le cerveau detecte vite quand une image semble jouee, et les visuels authentiques generent plus de confiance.",
      "L'authenticite n'importe que pour les marques personnelles.",
    ],
    2,
    "Un temoignage sans authenticite donne une impression de banque d'images, et cette impression construit rarement une vraie confiance.",
  ),
  fillStep(
    "Complete les blancs - Cree un visuel educatif",
    "Construit un prompt pour article, newsletter ou blog avec de l'espace pour le titre.",
    "/imagine ___, style ___, eclairage ___, tons ___, composition ___ avec ___ pour le titre, ___, ___.",
    [
      "une professionnelle presentant des donnees sur un grand ecran dans une salle moderne",
      "photographie editoriale corporate",
      "douce et propre",
      "bleu froid et blanc",
      "horizontale",
      "une zone plus sombre vide a gauche",
      "credibilite professionnelle",
      "--ar 16:9",
    ],
    [
      "une professionnelle presentant des donnees sur un grand ecran dans une salle moderne",
      "photographie editoriale corporate",
      "douce et propre",
      "bleu froid et blanc",
      "horizontale",
      "une zone plus sombre vide a gauche",
      "credibilite professionnelle",
      "--ar 16:9",
    ],
    "Un visuel educatif professionnel nait en pensant au texte. Ce n'est pas une jolie image avec un titre colle apres coup.",
  ),
  quizStep(
    "Pourquoi l'espace texte compte",
    "Pourquoi creer un espace specifique pour le texte dans un visuel educatif est-il une pratique professionnelle ?",
    [
      "Pour gagner du temps et eviter de faire un layout.",
      "Parce que MidJourney ne peut pas generer d'images sans zones vides.",
      "Parce que l'image nait prete a soutenir le titre et le message, en creant un layout coherent.",
      "L'espace pour le texte ne compte que dans les bannieres publicitaires.",
    ],
    2,
    "Quand le visuel et le texte sont penses ensemble, la communication parait intentionnelle et beaucoup plus raffinee.",
  ),
  fillStep(
    "Complete les blancs - Construis ta serie visuelle",
    "Complete la phrase avec la bonne logique pour une campagne coherente sur plusieurs pieces.",
    "Pour creer une serie coherente, garde ces elements ___ dans tous les prompts : ___ de couleurs, ___ d'eclairage, ___ photographique et ___ de composition. Ne fais varier que le ___ principal de chaque image pour raconter une histoire visuelle ___ tout au long de la campagne.",
    [
      "fixes",
      "palette",
      "type",
      "style",
      "regle",
      "sujet et action",
      "progressive",
    ],
    [
      "fixes",
      "palette",
      "type",
      "style",
      "regle",
      "sujet et action",
      "progressive",
    ],
    "Une serie forte ne nait pas par hasard. Elle nait d'une colonne visuelle stable avec des variations controlees autour.",
  ),
  quizStep(
    "Meilleure strategie pour une campagne coherente",
    "Quelle est la strategie la plus efficace pour creer une campagne visuelle coherente dans MidJourney ?",
    [
      "Generer des images aleatoires puis garder celles qui se ressemblent.",
      "Utiliser exactement le meme prompt pour toutes les pieces.",
      "Creer un prompt de base avec des elements fixes d'identite visuelle et ne faire varier que ce qui change entre les posts.",
      "La coherence visuelle n'est possible qu'avec une edition externe.",
    ],
    2,
    "Une bonne coherence ne tue pas la variete. Elle cree une colonne vertebrale visuelle pour que chaque piece soit nouvelle tout en restant de la meme marque.",
  ),
  fillStep(
    "Complete les blancs - Evite les erreurs",
    "Complete la phrase avec les erreurs visuelles qui detruisent le plus les campagnes marketing.",
    "Les principales erreurs visuelles en marketing avec MidJourney sont : utiliser des prompts ___ sans personnalisation, melanger des ___ incompatibles entre les posts, generer des images avec un ___ incorrect pour le canal, ignorer l'___ emotionnel de la lumiere et creer des visuels qui ___ le positionnement de la marque.",
    [
      "generiques",
      "styles et palettes",
      "ratio",
      "impact",
      "contredisent",
    ],
    [
      "generiques",
      "styles et palettes",
      "ratio",
      "impact",
      "contredisent",
    ],
    "Les campagnes faibles echouent souvent moins par manque de beaute que par manque de coherence strategique.",
  ),
  quizStep(
    "Erreur la plus courante en marketing IA",
    "Quelle est l'erreur visuelle la plus courante dans les campagnes de petites entreprises faites avec MidJourney ?",
    [
      "Utiliser des prompts beaucoup trop longs et charges.",
      "Creer des images avec plus de qualite que necessaire.",
      "Le manque de coherence visuelle entre les posts, qui fait paraitre chaque piece issue d'une autre marque.",
      "Utiliser le meme style dans toutes les images de la marque.",
    ],
    2,
    "Quand la marque ne semble pas etre la meme d'un post a l'autre, la reconnaissance, la memoire et la confiance ne s'accumulent jamais.",
  ),
  textStep(
    "Conclusion",
    "Avec MidJourney, n'importe quelle marque peut produire des visuels au niveau d'une agence sans dependance a une grosse equipe, a un studio ou a un budget eleve. Photos produit, posts de feed, creatives d'annonce, thumbnails, contenu educatif, preuve sociale et campagnes completes peuvent naitre de prompts bien construits et d'une strategie visuelle claire.\n\nLa difference entre une marque qui grandit et une marque qui stagne ne tient pas seulement au produit. Elle tient aussi a la maniere dont elle se presente visuellement avant de dire un seul mot.",
  ),
] as const;
