project_id = "dqlcxpbfemhzzetwaxsa"

[functions.auto-create-account]
verify_jwt = false

[functions.resend-magic-link]
verify_jwt = false

[functions.paddle-webhook]
verify_jwt = false

[functions.primer-webhook]
verify_jwt = false

[functions.confirm-signup-email]
verify_jwt = false

[functions.pending-signup]
verify_jwt = false

[functions.bulk-grant-access]
verify_jwt = false

[functions.send-signup-invite]
verify_jwt = false

[functions.magic-login]
verify_jwt = false

[functions.admin-revoke-access]
verify_jwt = false