name: Automatic Database Backup

on:
  schedule:
    # Roda diariamente às 03:00 h (UTC)
    - cron: '0 3 * * *'
  workflow_dispatch: # Permite rodar o workflow manualmente apertando um botão no Github

jobs:
  db-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Dump Database (Schema and Data)
        env:
          PGHOST: aws-0-sa-east-1.pooler.supabase.com
          PGPORT: 5432
          PGDATABASE: postgres
          PGUSER: ${{ secrets.SUPABASE_DB_USER }}
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          echo "Iniciando processo de dump dos dados..."
          pg_dump -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" --no-password -f database_backup.sql
          
      - name: Upload Backup as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-${{ github.run_id }}
          path: database_backup.sql
          retention-days: 30 # O Github vai reter esse backup por 30 dias automaticamente
